<div class="row">
    <div class="title-divider-home">
        <span>TIME SCAN</span>
    </div>
    <div class="timescan-home">
        <div class="hidden-xs hidden-sm col-md-7 col-lg-6">
            <img src="<?php echo $this->getViewFileUrl('images/timescan/fruit-home.jpg');?>" alt="time-scan-img" height="569" width="574">
        </div>
        <div class="col-md-4 col-lg-4">
            <div class="row text-center">
                <h2 class="slogan">
                    <span class="vert">Innovation</span>
                </h2>
            </div>
            <div class="row text-center">
                <h2>Avec TIME Scan,</h2> <h2>analysez </h2> <h2>votre silhouette</h2>
            </div>
            <div class="row text-center">
                <hr>
                <p>Analyse, expertise, programme alimentaire personnalisé et presciption de produits ciblés mis au point par nos experts TIME Nutrition</p>
            </div>
            <div class="row text-center">
                <a href="<?php echo $block->getUrl('timescan', ['_secure' => true]);?>"><img src="<?php echo $this->getViewFileUrl('images/timescan/button-scan-home.jpg');?>" alt="time-scan-img" height="52" width="186"></a>
            </div>
        </div>
        <div class="hidden-xs hidden-sm hidden-md">
            <img src="<?php echo $this->getViewFileUrl('images/timescan/meter-home.jpg');?>" alt="time-scan-img" height="569" width="109">
        </div>
    </div>
</div>

<div class="row">
    <div class="title-divider-home">
        <span>Découvertes</span>
    </div>
    <div class="col-md-12 col-lg-12">
        <div class="col-md-6 col-lg-6 part-home">
            <div class="part-home-content">
            <p class="texte-accroche">
                <strong>Découvrez</strong>
            </p>
            <h2>
                TIME<br>Nutrition
            </h2>
            <hr>
            <div class="part-home-desc">
                TIME Nutrition est une méthode physiologique qui s’appuie sur les solutions apportées par la chronobiologie
                alimentaire. TIME Nutrition s’adresse à tous et toutes, sans distinction de sexe, d’âge, de race ou de religion
                puisque la physiologie est universelle !
            </div>
            <a href="<?php echo $block->getUrl('histoire', ['_secure' => true]);?>" class="action primary">En savoir Plus</a>
            <div class="text-center">
                <button data-toggle="modal" data-target="#exampleModal" id="videomodal">
                    <img width="250" height="150" src="<?php echo $this->getViewFileUrl('images/video.jpg');?>" alt="decouvrez time nutrition">
                </button>
             </div>
            </div>
        </div>
        <div class="col-md-6 col-lg-6 part-home">
            <div class="part-home-content">
            <p class="texte-accroche">
                <strong>Découvrez</strong>
            </p>
            <h2>
                ACTIMAN Jour<br><span class="h2-mini">by TIME Nutrition</span>
            </h2>
            <hr>
            <div class="part-home-desc">
                Actiman Jour est une boisson aux fruits rouges à boire le matin au cours du petit déjeuner. Cette boisson
                aux multiples vertus et sans sucres ajoutés remplacera votre jus de fruit quotidien.
            </div>
            <a class="action primary" href="<?php echo $block->getUrl('catalog/product/view/id/14596/s/actima-by-time-nutrition-1501', ['_secure' => true]);?>">En savoir Plus</a>
            <div class="text-center">
                <img src="<?php echo $this->getViewFileUrl('images/actima_home.jpg');?>" alt="youtube lexel paris">
            </div>
            </div>
        </div>
    </div>
</div>

<div class="row">
    <div class="title-divider-home">
        <span>Restons connectés</span>
    </div>
    <div class="home-social text-center">
        <div class="home-social-block col-xs-6 col-sm-3 col-md-3">
            <a href="https://www.facebook.com/TIME.Nutrition" target="_blank">
                <img src="<?php echo $this->getViewFileUrl('images/facebook.png');?>" alt="facebook time nutrition">
                FACEBOOK<br>
                <img class="img-responsive" src="<?php echo $this->getViewFileUrl('images/facebook.jpg');?>" alt="facebook time nutrition">
            </a>
        </div>
        <div class="home-social-block col-xs-6 col-sm-3 col-md-3">
            <a href="https://www.instagram.com/time_nutrition/" target="_blank">
                <img src="<?php echo $this->getViewFileUrl('images/instagram.png');?>" alt="instagram time nutrition">
                INSTAGRAM<br>
                <img class="img-responsive" src="<?php echo $this->getViewFileUrl('images/instagram.jpeg');?>" alt="instagram time nutrition">
            </a>
        </div>
        <div class="home-social-block col-xs-6 col-sm-3 col-md-3">
            <a href="https://www.youtube.com/user/TIMENutrition" target="_blank">
                <img src="<?php echo $this->getViewFileUrl('images/youtube.png');?>" alt="youtube time nutrition">
                YOUTUBE<br>
                <img class="img-responsive" src="<?php echo $this->getViewFileUrl('images/youtube.jpg');?>" alt="youtube time nutrition">
            </a>
        </div>
        <div class="home-social-block col-xs-6 col-sm-3 col-md-3">
            <a href="https://fr.pinterest.com/timenutrition/" target="_blank">
                <img src="<?php echo $this->getViewFileUrl('images/pinterest.png');?>" alt="pinterest time nutrition">
                PINTEREST<br>
                <img class="img-responsive" src="<?php echo $this->getViewFileUrl('images/pinterest.jpg');?>" alt="pinterest time nutrition">
            </a>
        </div>
    </div>
</div>

<div class="modal" tabindex="-1" role="dialog" id="exampleModal">
    <div class="modal-dialog" role="document">
        <div class="modal-content">

            <div class="modal-body">
                <iframe width="1280" height="720" src="http://www.youtube.com/embed/urs_gPNihvw" frameborder="0" allowfullscreen></iframe>
            </div>

        </div>
    </div>
</div>

<script>
    require(['jquery','Ves_All/lib/bootstrap/js/bootstrap.min'], function ($) {
        $('#exampleModal').on('shown.bs.modal', function () {
            $('#videomodal').trigger('focus')
        })
    });
</script>


