<div class="row">
    <div class="col-md-12">
        <ul  class="nav nav-pills responsive">
            <li class="active">
                <a href="#1a" data-toggle="tab">
                    <span class="number-tab">1</span>
                    <br>
                    Nettoyer - Démaquiller
                </a>
            </li>
            <li>
                <a href="#2a" data-toggle="tab">
                    <span class="number-tab">2</span>
                    <br>
                    Exfolier - Préparer
                </a>
            </li>
            <li>
                <a href="#3a" data-toggle="tab">
                    <span class="number-tab">3</span>
                    <br>
                    Prévenir - Agir
                </a>
            </li>
            <li>
                <a href="#4a" data-toggle="tab">
                    <span class="number-tab">4</span>
                    <br>
                    Nettoyer - Démaquiller
                </a>
            </li>
        </ul>
        <div class="tab-content responsive clearfix">
            <div class="tab-pane active" id="1a">
                <h3>Le secret d'une peau parfaitement propre</h3>
                <br>
                <p>Tout au long de la journée et de la nuit, les cellules mortes, la sueur, le sébum et la pollution s’accumulent pour former une couche asphyxiante à la surface de l’épiderme.</p>
                <ul>
                    <li>La respiration cutanée est ralentie</li>
                    <li>les pores s’obstruent</li>
                    <li>la peau devient propice à l’installation de points noirs et d’imperfections</li>
                </ul>
                <br>
                <h4>Quelles solutions appliquer ?</h4>
                <br>
                <p>L’utilisation bi-quotidienne d’un démaquillant et/ou nettoyant combinée à une lotion permet de débarrasser la peau des cellules mortes et autres impuretés qui ternissent le teint.</p>
                <br>
                <ul>
                    <li>La peau s’oxygène mieux</li>
                    <li>la régénération cellulaire est favorisée</li>
                    <li>la peau est plus réceptive aux soins cosmétiques qui pénétreront plus facilement</li>
                </ul>
                <br>
                La peau est parfaitement propre et le teint est éclatant.
            </div>

            <div class="tab-pane" id="2a">
                <h3>Pour une peau douce et prête à recevoir les soins</h3>
                <br>
                <p>Même en utilisant quotidiennement un démaquillant/nettoyant associé à une lotion, en quelques jours, la couche cornée s’épaissit pour former à la surface de la peau une couche hétérogène, terne et squameuse.</p>
                <br>
                <ul>
                    <li>La peau devient imperméable aux soins cosmétiques qui ont plus de difficulté pour pénétrer en profondeur</li>
                    <li>La régénération cellulaire est ralentie</li>
                    <li>La communication derme/épiderme est perturbée</li>
                </ul>
                <br>
                <h4>Quelles solutions appliquer ?</h4>
                <br>
                <p>L’utilisation bi-hebdomadaire d’un exfoliant ou d’un gommage permet d’affiner la couche cornée. Y associer l’utilisation d’un masque permet de rétablir l’équilibre dans les différentes couches de la peau</p>
                <br>
                <ul>
                    <li>La régénération cellulaire est relancée</li>
                    <li>L’eau démaquillante Lexel convient parfaitement à tous les types de peaux, même les plus délicates</li>
                    <li>La peau est plus réceptive aux soins cosmétiques (pénétration en profondeur)</li>
                    <li>La communication derme/épiderme est rétablie et les fonctions cutanées sont rééquilibrée.</li>
                </ul>
                <br>
                La qualité de la peau est améliorée. Le teint est plus homogène et plus lumineux.
            </div>

            <div class="tab-pane" id="3a">
                <h3>Nourrir sa peau est essentiel pour conserver sa beauté</h3>
                <br>
                <p>La peau connaît des dysfonctionnements liés à l’altération de ses composants, conséquence de son vieillissement naturel intrinsèque. La peau ne subvient plus seule à ses besoins pour réparer les altérations qu’elle subit et pour se préserver.</p>
                <br>
                <ul>
                    <li>La peau dispose moins de défenses naturelles</li>
                    <li>Le vieillissement cutané s’accélère</li>
                    <li>L’eau s’évapore et la peau (épiderme + derme) se déshydrate</li>
                    <li>Les composants du derme (collagène et élastine) se détériorente</li>
                </ul>
                <br>
                <h4>Quelles solutions appliquer ?</h4>
                <br>
                <p>Les actifs des sérums vont pénétrer en profondeur (derme) et les crèmes de soins (jour, nuit, yeux) vont renforcer la barrière cutanée qui va pouvoir jouer son rôle protecteur et booster les fonctions naturelles de la peau.</p>
                <br>
                <ul>
                    <li>L’eau ne peut plus s’évaporer, l’hydratation de la peau est maintenue</li>
                    <li>La production de collagène et d’élastine est relancée</li>
                    <li>La peau est plus réceptive aux soins cosmétiques (pénétration en profondeur)</li>
                    <li>Les signes liés au vieillissement naturel de la peau sont amoindris (réparation naturelle des structures de la peau par ses propres moyens)</li>
                </ul>
                <br>
                La peau est visiblement plus jeune et plus belle.
            </div>

            <div class="tab-pane" id="4a">
                <h3>Illuminez et protégez votre visage par une dernière touche de beauté</h3>
                <br>
                <p>Les agressions quotidiennes de l’environnement (pollution ambiante, UV, stress…) ralentissent l’activité cellulaire et provoquent des dommages cutanés.</p>
                <p>La peau, continuellement agressée, ne peut plus se défendre correctement. Il faut donc lui venir en aide.</p>
                <br>
                <ul>
                    <li>Les défenses naturelles de la peau sont débordées</li>
                    <li>Le vieillissement prématuré s’accélère</li>
                </ul>
                <h4>Quelles solutions appliquer ?</h4>
                <br>
                <p>L’utilisation quotidienne d’un soin de protection permet de couvrir la peau d’un bouclier contre les agressions extérieures qui agit en prévention des signes de l’âge.</p>
                <br>
                <ul>
                    <li>Le vieillissement prématuré est retardé</li>
                    <li>L’apparition des signes de l’âge est ralentie</li>
                </ul>
                <br>
                La peau reste jeune plus longtemps. Le teint est sublimé.
            </div>
        </div>
    </div>
</div>


<script type="application/javascript" rel="script">
    require(['jquery', 'jquery.bootstrap'], function ($) {
           
        });

</script>