<div class="row">
    <div class="col-md-4">
        <p style="text-align: center;">NUMÉRO 17</p>
        <a href="{{media url="wysiwyg/lexelmag/lexel-mag-17"}}" >
            <img src="<?php echo $this->getViewFileUrl('images/lexel-mag/lexel17.jpg', array('_secure'=>true)); ?>" />
        </a>
    </div>
    <div class="col-md-4">
        <p style="text-align: center;">NUMÉRO 16</p>
            <a href="{{media url="wysiwyg/lexelmag/lexel-mag-16"}}" >
        <img src="<?php echo $this->getViewFileUrl('images/lexel-mag/lexel16.jpg', array('_secure'=>true)); ?>" />
        </a>
    </div>
    <div class="col-md-4">
        <p style="text-align: center;">NUMÉRO 15</p>
            <a href="{{media url="wysiwyg/lexelmag/lexel-mag-15"}}" >
        <img src="<?php echo $this->getViewFileUrl('images/lexel-mag/lexel15.jpg', array('_secure'=>true)); ?>" />
        </a>
    </div>
    <div class="col-md-4">
        <p style="text-align: center;">NUMÉRO 14</p>
        <a href="{{media url="wysiwyg/lexelmag/lexel-mag-14"}}" >
        <img src="<?php echo $this->getViewFileUrl('images/lexel-mag/lexel14.jpg', array('_secure'=>true)); ?>" />
        </a>
    </div>
    <div class="col-md-4">
        <p style="text-align: center;">NUMÉRO 13</p>
        <a href="{{media url="wysiwyg/lexelmag/lexel-mag-13"}}" >
        <img src="<?php echo $this->getViewFileUrl('images/lexel-mag/lexel13.jpg', array('_secure'=>true)); ?>" />
        </a>
    </div>
    <div class="col-md-4">
        <p style="text-align: center;">NUMÉRO 12</p>
        <a href="{{media url="wysiwyg/lexelmag/lexel-mag-12"}}" >
        <img src="<?php echo $this->getViewFileUrl('images/lexel-mag/lexel12.jpg', array('_secure'=>true)); ?>" />
        </a>
    </div>
</div>