<div class="row">
    <h1 class="who-title"><?php echo __('NOTRE PHILOSOPHIE'); ?></h1>
</div>
<div class="row who-content">
    <p>
        Lexel Paris s’est fixé pour ambition d’être une entreprise de référence tant pour ses clients que pour ses
        collaborateurs actuels et futurs.<br>
        Fondée sur des valeurs partagées et sur une histoire, le caractère de notre entreprise se découvre de l’intérieur.
        Lexel Paris souhaite continuer à :
    </p>
    <div class="col-md-6 col-lg-6 who">
        <img class="img-responsive" src="<?php echo $this->getViewFileUrl('images/philosophie/img-1.jpg', array('_secure'=>true)); ?>" alt="" />
    </div>
    <div class="col-md-6 col-lg-6 who who-txt text-center">
        Préserver ses valeurs humaines, en étant attentif au bien-être et la motivation de ses collaborateurs.
    </div>
    <div class="col-md-6 col-lg-6 who who-txt text-center">
        Proposer le meilleur de la recherche scientifique avec des produits innovants et à la pointe de la technologie.
    </div>
    <div class="col-md-6 col-lg-6 who">
        <img class="img-responsive" src="<?php echo $this->getViewFileUrl('images/philosophie/img-2.jpg', array('_secure'=>true)); ?>" alt="" />
    </div>
    <div class="col-md-6 col-lg-6 who">
        <img class="img-responsive" src="<?php echo $this->getViewFileUrl('images/philosophie/img-3.jpg', array('_secure'=>true)); ?>" alt="" />
    </div>
    <div class="col-md-6 col-lg-6 who who-txt text-center">
        Satisfaire les besoins des clients Lexel Paris en leur apportant un service de qualité et des instants de bien être.
    </div>
    <div class="col-md-6 col-lg-6 who who-txt text-center">
        Respecter l’environnement tout en proposant des produits de qualité. Tous nos produits sont recyclables.
        <br>
        Pensez à trier vos emballages. Pour en savoir plus sur les consignes de tri en France : https://www.consignesdetri.fr/
    </div>
    <div class="col-md-6 col-lg-6 who">
        <img class="img-responsive" src="<?php echo $this->getViewFileUrl('images/philosophie/img-4.jpg', array('_secure'=>true)); ?>" alt="" />
    </div>

</div>

<div class="row who-link ">
    <div class="col-md-6 col-lg-6 text-left">
        <a class="btn btn-who" href="<?php echo $block->getUrl('who', ['_secure' => true]);?>"><?php echo __('Qui Sommes Nous'); ?></a>
    </div>
    <div class="col-md-6 col-lg-6 text-right">
        <a class="btn btn-who" href="<?php echo $block->getUrl('charte-qualite', ['_secure' => true]);?>"><?php echo __('Charte Qualité'); ?></a>
    </div>
</div>