<div class="row">
    <div class="title-divider-home">
        <span>ON PARLE DE NOUS</span>
    </div>
    <div class="home-social-block col-xs-6 col-sm-3 col-md-3 col-lg-3">
        <a href="https://lesenviesdegeorgette.net/2017/05/09/decouverte-de-la-marque-lexel-paris/" target="blank">
            <img class="img-responsive" src="<?php echo $this->getViewFileUrl('images/blogueuse/les envies de georgette.png', array('_secure'=>true)); ?>" alt="" />
        </a>
    </div>
    <div class="home-social-block col-xs-6 col-sm-3 col-md-3 col-lg-3">
        <a href="https://10thfebruary.wordpress.com/2017/08/13/partenariat-2-la-marque-lexel-paris-%F0%9F%8C%B1/" target="blank">
            <img class="img-responsive" src="<?php echo $this->getViewFileUrl('images/blogueuse/10th february.png', array('_secure'=>true)); ?>" alt="" />
        </a>
    </div>
    <div class="home-social-block col-xs-6 col-sm-3 col-md-3 col-lg-3">
        <a href="http://beauty-full.fr/je-decouvre-la-marque-lexel-paris/2017/06/08/" target="blank">
            <img class="img-responsive" src="<?php echo $this->getViewFileUrl('images/blogueuse/beauty full.png', array('_secure'=>true)); ?>" alt="" />
        </a>
    </div>
    <div class="home-social-block col-xs-6 col-sm-3 col-md-3 col-lg-3">
        <a href="http://morganelatesteuse.com/les-produits-lexel-paris-vous-connaissez" target="blank">
            <img class="img-responsive" src="<?php echo $this->getViewFileUrl('images/blogueuse/morganne la testeuse.png', array('_secure'=>true)); ?>" alt="" />
        </a>
    </div>
    <div class="home-social-block col-xs-6 col-sm-3 col-md-3 col-lg-3">
        <a href="http://mamanbeautedecouverte.publicoton.fr/lexel-paris-soins-et-beaute-une-belle-decouverte-901036" target="blank">
            <img class="img-responsive" src="<?php echo $this->getViewFileUrl('images/blogueuse/maman beaute.png', array('_secure'=>true)); ?>" alt="" />
        </a>
    </div>
    <div class="home-social-block col-xs-6 col-sm-3 col-md-3 col-lg-3">
        <a href=" https://missbeautemodefamily.blogspot.fr/2017/05/lexel-paris.html?spref=fb" target="blank">
            <img class="img-responsive" src="<?php echo $this->getViewFileUrl('images/blogueuse/miss beaute.png', array('_secure'=>true)); ?>" alt="" /></a>
    </div>
    <div class="home-social-block col-xs-6 col-sm-3 col-md-3 col-lg-3">
        <a href="http://club.beaute-addict.com/blog-beaute/commentaire-ma-palette-esprit-boheme-by-lexel-paris-822669-0.php" target="blank">
            <img class="img-responsive" src="<?php echo $this->getViewFileUrl('images/blogueuse/gaya blog.png', array('_secure'=>true)); ?>" alt="" />
        </a>
    </div>
    <div class="home-social-block col-xs-6 col-sm-3 col-md-3 col-lg-3">
        <a href="http://initialscb.fr/2017/02/7-ans-blog-concours-lexel-paris-beaute/" target="blank">
            <img class="img-responsive" src="<?php echo $this->getViewFileUrl('images/blogueuse/initial cb.png', array('_secure'=>true)); ?>" alt="" />
        </a>
    </div>
    <div class="home-social-block col-xs-6 col-sm-3 col-md-3 col-lg-3">
        <a href="https://www.youtube.com/watch?v=gIus6CNzKts" target="blank">
            <img class="img-responsive" src="<?php echo $this->getViewFileUrl('images/blogueuse/so beautsist.png', array('_secure'=>true)); ?>" alt="" />
        </a>
    </div>
    <div class="home-social-block col-xs-6 col-sm-3 col-md-3 col-lg-3">
        <a href="https://bambinsbeauteetfutilite.com/decouverte-produits-lexel-paris/" target="blank">
            <img class="img-responsive" src="<?php echo $this->getViewFileUrl('images/blogueuse/bambins beaute.png', array('_secure'=>true)); ?>" alt="" />
        </a>
    </div>
    <div class="home-social-block col-xs-6 col-sm-3 col-md-3 col-lg-3">
        <a href="http://epicureanblondie.com/night-routine-cocooning-avec-lexel-paris/" target="blank">
            <img class="img-responsive" src="<?php echo $this->getViewFileUrl('images/blogueuse/epicurean blondie.png', array('_secure'=>true)); ?>" alt="" />
        </a>
    </div>
    <div class="home-social-block col-xs-6 col-sm-3 col-md-3 col-lg-3">
        <a href="http://bymarinazaza.fr/produits-lexel-paris/" target="blank">
            <img class="img-responsive" src="<?php echo $this->getViewFileUrl('images/blogueuse/marina zaza.png', array('_secure'=>true)); ?>" alt="" />
        </a>
    </div>
    <div class="home-social-block col-xs-6 col-sm-3 col-md-3 col-lg-3">
        <a href="https://dansleplacarddedamerenard.wordpress.com/2016/11/17/creme-gommante-lexel-ou-lautre-facon-de-se-faire-un-gommage/">
            <img class="img-responsive" src="<?php echo $this->getViewFileUrl('images/blogueuse/mme renard.png', array('_secure'=>true)); ?>" alt="" />
        </a>
    </div>
    <div class="home-social-block col-xs-6 col-sm-3 col-md-3 col-lg-3">
        <a href="http://charlottebellanger.fr/soiree-lexel-paris/" target="blank">
            <img class="img-responsive" src="<?php echo $this->getViewFileUrl('images/blogueuse/charlotte bellanger.png', array('_secure'=>true)); ?>" alt="" />
        </a>
    </div>
    <div class="home-social-block col-xs-6 col-sm-3 col-md-3 col-lg-3">
        <a href="http://www.girlysunshine.com/routine-visage-lexel-paris/" target="blank">
            <img class="img-responsive" src="<?php echo $this->getViewFileUrl('images/blogueuse/girly sunshine.png', array('_secure'=>true)); ?>" alt="" />
        </a>
    </div>
    <div class="home-social-block col-xs-6 col-sm-3 col-md-3 col-lg-3">
        <a href="https://lemondeselonclaire.com/" target="blank">
            <img class="img-responsive" src="<?php echo $this->getViewFileUrl('images/blogueuse/le monde selon claire.png', array('_secure'=>true)); ?>" alt="" />
        </a>
    </div>
    <div class="home-social-block col-xs-6 col-sm-3 col-md-3 col-lg-3">
        <a href="http://www.mademoiselle-e.fr/lexel-paris-box-beaute-concours/" target="blank"> <img class="img-responsive" src="<?php echo $this->getViewFileUrl('images/blogueuse/mademoiselle e1.png', array('_secure'=>true)); ?>" alt="" />
        </a>
    </div>
    <div class="home-social-block col-xs-6 col-sm-3 col-md-3 col-lg-3">
        <a href="http://cpluslanuit.ch/2017/03/04/ma-routine-visage-avec-lexel-paris/" target="blank">
            <img class="img-responsive" src="<?php echo $this->getViewFileUrl('images/blogueuse/mon petit quelque chose.png', array('_secure'=>true)); ?>" alt="" />
        </a>
    </div>
    <div class="home-social-block col-xs-6 col-sm-3 col-md-3 col-lg-3">
        <a href="https://penseesmenteuses.wordpress.com/2017/09/09/collaboration-avec-lentreprise-lexel-paris/" target="blank">
            <img class="img-responsive" src="<?php echo $this->getViewFileUrl('images/blogueuse/pensees_menteuses.png', array('_secure'=>true)); ?>" alt="" />
        </a>
    </div>
    <div class="home-social-block col-xs-6 col-sm-3 col-md-3 col-lg-3">
        <a href="https://laurachqt.wordpress.com/2017/09/09/lexel-paris/" target="blank">
            <img class="img-responsive" src="<?php echo $this->getViewFileUrl('images/blogueuse/laura_chqt.jpg', array('_secure'=>true)); ?>" alt="" />
        </a>
    </div>
    <div class="home-social-block col-xs-6 col-sm-3 col-md-3 col-lg-3">
        <a href="https://bleureine.wordpress.com/2017/10/29/ma-routine-par-lexel-paris/" target="blank">
            <img class="img-responsive" src="<?php echo $this->getViewFileUrl('images/blogueuse/bleureine.jpg', array('_secure'=>true)); ?>" alt="" />
        </a>
    </div>
</div>