<div class="row">
    <div class="col-md-12 col-lg 12 recettes">
        <div class="col-xs-12 col-sm-6 col-md-4 col-lg-4">
            <h2><?php echo __('Bar Grille sur compotée d\'endives');?></h2>
            <ul>
                <li><img src="<?php echo $this->getViewFileUrl('images/recettes/cutlery.png'); ?>"> <span class="gray">Pour</span> : 2 personnes</li>
                <li><img src="<?php echo $this->getViewFileUrl('images/recettes/clock.png'); ?>"> <span class="gray">Préparation</span> : 15 min.</li>
                <li><img src="<?php echo $this->getViewFileUrl('images/recettes/oven.png'); ?>"> <span class="gray">Cuisson</span> : 10 min.</li>
            </ul>
            <h3 class="recette-part">Ingrédients</h3>
            <ul class="ingredients">
                <li>500 g de filet de bar</li>
                <li>250 g d'endives</li>
                <li>2 cuil. à soupe d'huile d'olive</li>
                <li>1 cuil. à soupe d'estragon ciselé</li>
                <li>1 cuil. à soupe de cerfeuil</li>
                <li>1 cuil. à café de sel</li>
                <li>1 noix de beurre</li>
                <li>Poivre blanc du moulin</li>
                <li>1 cuil. à café de sucre</li>
                <li>Jus d'1/2 citron</li>
                <li>2 cuil. à soupe d'eau</li>
            </ul>

        </div>
        <div class="col-xs-12 col-sm-6 col-md-4 col-lg-4">
            <img src="<?php echo $this->getViewFileUrl('images/recettes/bar_compotee_endives.jpg'); ?>" alt="bar grillé sur compotée d'endives time nutrition">
        </div>
        <div class="col-xs-12 col-sm-12 col-md-4 col-lg-4">
            « Bar » vient d’un mot allemand qui veut dire pointe, en référence aux dangereuses épines dorsales de ce poisson.<br>
            Le bar commun est surnommé « loup » dans la région méditerranéenne.<br>
            Cependant, les termes de bar et de loup ne sont pas pour autant complètement synonymes : plusieurs espèces proches sont appelées ainsi.<br>
            Cela n’a guère d’importance. Il vaut mieux vérifier s’il s’agit de bar d’élevage ou sauvage !

        </div>
    </div>
</div>
<div class="row">
    <div class="col-md-12 col-lg-12 recettes">
        <h3 class="recette-part">Préparation</h3>
        <ul class="preparation">
            <li>Émincer les endives</li>
            <li>Dans une casserole faire fondre le beurre et ½ cuil. à soupe d'huile d'olive à feu moyen, ajouter les endives avec le jus d'un demi citron et 2 cuil. à soupe d'eau puis saupoudrer de sucre, saler, poivrer, couvrir et cuire environ 10 min.</li>
            <li>Si au bout des 10 min. de cuisson il reste encore du liquide, découvrir et laisser cuire jusqu'à évaporation complète.</li>
            <span>Pendant la cuisson des endives :</span>
            <li>Faire chauffer à feu vif le reste de l'huile d'olive dans une poêle anti-adhésive.</li>
            <li>Saisir les filets de bar 1 min.</li>
            <li>Les retourner côté peau contre la poêle, saler, poivrer, baisser le feu et cuire environ 3 min</li>
            <li>Répartir sur deux assiettes chaudes avec la compote d'endives.</li>
            <li>Arroser le bar d'un filet d'huile d'olive.</li>
            <li>Parsemer de quelques graines de sel.</li>
            <li>Saupoudrer d'estragon et de cerfeuil.</li>
        </ul>
    </div>
</div>
<div class="row">
    <div class="col-md-12 col-lg-12">
        <div class="astuce">
            <i class="fa fa-caret-right" aria-hidden="true"></i> ASTUCES TIME NUTRITION
            <div>
                Plus besoin de faire cuire les endives avec de la mie de pain ou du bicarbonate : on ne rencontre plus les endives amères d’autrefois, les progrès considérables effectués ces dernières années en matière de sélection de variétés et les tests de maturité réalisés avant la récolte ont permis d’éliminer en grande partie le goût amer.
            </div>
        </div>

    </div>
</div>