<div class="row">
    <div class="col-md-12 col-lg 12 recettes">
        <div class="col-xs-12 col-sm-6 col-md-4 col-lg-4">
            <h2><?php echo __('Filets de cabillaud vapeur');?></h2>
            <ul>
                <li><img src="<?php echo $this->getViewFileUrl('images/recettes/cutlery.png'); ?>"> <span class="gray">Pour</span> : 2 personnes</li>
                <li><img src="<?php echo $this->getViewFileUrl('images/recettes/clock.png'); ?>"> <span class="gray">Préparation</span> : 15 min.</li>
                <li><img src="<?php echo $this->getViewFileUrl('images/recettes/oven.png'); ?>"> <span class="gray">Cuisson vapeur</span> : 5 min.</li>
            </ul>
            <h3 class="recette-part">Ingrédients</h3>
            <ul class="ingredients">
                <li>500 g de filets de cabillaud</li>
                <li>1 sachet de court-bouillon</li>
                <li>1 dl d'eau</li>
                <li>1 dl de vin blanc</li>
                <span>Coulin express</span>
                <li>2 fonds d'artichauts</li>
                <li>1 cuil à soupe de crème</li>
                <li>Cube bouillon de volaille</li>
                <li>Sel, poivre</li>
            </ul>

        </div>
        <div class="col-xs-12 col-sm-6 col-md-4 col-lg-4">
            <img src="<?php echo $this->getViewFileUrl('images/recettes/cabillaud_vapeur.jpg'); ?>" alt="filets de cabillaud vapeur time nutrition">
        </div>
        <div class="col-xs-12 col-sm-12 col-md-4 col-lg-4">
           
        </div>
    </div>
</div>
<div class="row">
    <div class="col-md-12 col-lg-12 recettes">
        <h3 class="recette-part">Préparation</h3>
        <ul class="preparation">
            <li>Dans une casserole verser l'eau et le vin, ajouter le sachet de court-bouillon, porter à ébullition et la maintenir environ 3 min.</li>
            <li>Verser dans le cuit-vapeur.</li>
            <li>Poser les filets de cabillaud dans le panier du cuit-vapeur, couvrir et cuire environ 6 à 7 min. (jusqu'à ce qu'il soit blanc).</li>
            <span>Pendant ce temps :</span>
            <li>Mixer les fonds d'artichauts avec la crème et le bouillon de volaille.</li>
            <li>Réchauffer.</li>
            <li>Sur les assiettes chaudes, poser les filets de cabillaud et les napper de la sauce.</li>
        </ul>
    </div>
</div>
<div class="row">
    <div class="col-md-12 col-lg-12">
        <div class="astuce">
            <i class="fa fa-caret-right" aria-hidden="true"></i> ASTUCES TIME NUTRITION
            <div>
                Nous vous conseillons d’accompagner ce poisson de légumes sautés.
            </div>
        </div>

    </div>
</div>