<div class="row">
    <div class="col-md-12 col-lg 12 recettes">
        <div class="col-xs-12 col-sm-6 col-md-4 col-lg-4">
            <h2><?php echo __('DARNES DE SAUMON A L’ANCIENNE');?></h2>
            <ul>
                <li><img src="<?php echo $this->getViewFileUrl('images/recettes/cutlery.png'); ?>"> <span class="gray">Pour</span> : 2 personnes</li>
                <li><img src="<?php echo $this->getViewFileUrl('images/recettes/clock.png'); ?>"> <span class="gray">Préparation</span> : 10 min.</li>
                <li><img src="<?php echo $this->getViewFileUrl('images/recettes/oven.png'); ?>"> <span class="gray">Cuisson</span> : 4 min.</li>
            </ul>
            <h3 class="recette-part">Ingrédients</h3>
            <ul class="ingredients">
                <li>400 g de darnes de saumon</li>
                <li>Moutarde à l’ancienne</li>
                <li>Jus d'un ½ citron</li>
                <li>30 g de beurre</li>
                <li>1 cuil. à soupe d'estragon ciselé</li>
                <li>Huile d’olive</li>
                <li>Sel, poivre</li>
            </ul>

        </div>
        <div class="col-xs-12 col-sm-6 col-md-4 col-lg-4">
            <img src="<?php echo $this->getViewFileUrl('images/recettes/darnes_saumon.jpg'); ?>" alt="darnes de saumon time nutrition">
        </div>
        <div class="col-xs-12 col-sm-12 col-md-4 col-lg-4">
            Une darne est une large tranche de saumon découpée avant cuisson.
        </div>
    </div>
</div>
<div class="row">
    <div class="col-md-12 col-lg-12 recettes">
        <h3 class="recette-part">Préparation</h3>
        <ul class="preparation">
            <li>Saler légèrement les deux faces du saumon.</li>
            <li>Tartiner, l'un des côté de moutarde et le saupoudrer de poivre.</li>
            <li>Faire chauffer la cuil. d'huile d'olive, quand elle est bien chaude déposer les tranches de saumon (le côté sans moutarde contre la poêle), cuire 2 min. à feu modéré et les retourner à l'aide d'une spatule.</li>
            <li>Dès qu'elles sont rissolées les réserver au chaud.</li>
            <li>Dans la même poêle verser le jus de citron, gratter les sucs faire bouillir pendant 1 min. puis ajouter le beurre hors du feu en fouettant vigoureusement à l'aide d'un fouet.</li>
            <li>Napper le saumon puis saupoudrer le tout d'estragon ciselé.</li>
        </ul>
    </div>
</div>
<div class="row">
    <div class="col-md-12 col-lg-12">
        <div class="astuce">
            <i class="fa fa-caret-right" aria-hidden="true"></i> ASTUCES TIME NUTRITION
            <div>
                Ce plat s’accordera parfaitement avec une poêlée de légumes verts.
            </div>
        </div>

    </div>
</div>