<div class="row">
    <div class="col-md-12 col-lg 12 recettes">
        <div class="col-xs-12 col-sm-6 col-md-4 col-lg-4">
            <h2><?php echo __('Daurade à la méridionale');?></h2>
            <ul>
                <li><img src="<?php echo $this->getViewFileUrl('images/recettes/cutlery.png'); ?>"> <span class="gray">Pour</span> : 2 personnes</li>
                <li><img src="<?php echo $this->getViewFileUrl('images/recettes/clock.png'); ?>"> <span class="gray">Préparation</span> : 5 min.</li>
                <li><img src="<?php echo $this->getViewFileUrl('images/recettes/oven.png'); ?>"> <span class="gray">Cuisson</span> : 30 min.</li>
            </ul>
            <h3 class="recette-part">Ingrédients</h3>
            <ul class="ingredients">
                <li>1 daurade</li>
                <li>2 petits oignons</li>
                <li>10 tomates cerise</li>
                <li>3 filets d'anchois à l'huile</li>
                <li>2 gousses d'ail</li>
                <li>2 cuil. à soupe de concentré de tomate</li>
                <li>2 cuil. à soupe d'huile d'olive</li>
                <li>2 cuil. à soupe de câpres</li>
                <li>Persil haché</li>
                <li>Sel, poivre</li>
                <li>1 verre de vin blanc</li>
            </ul>

        </div>
        <div class="col-xs-12 col-sm-6 col-md-4 col-lg-4">
            <img src="<?php echo $this->getViewFileUrl('images/recettes/daurade_meridionale.jpg'); ?>" alt="daurade méridionale time nutrition">
        </div>
        <div class="col-xs-12 col-sm-12 col-md-4 col-lg-4">
            Le terme daurade ou dorade désigne plusieurs espèces de poissons de bonne qualité gustative.
        </div>
    </div>
</div>
<div class="row">
    <div class="col-md-12 col-lg-12 recettes">
        <h3 class="recette-part">Préparation</h3>
        <ul class="preparation">
            <li>Dans une casserole faire chauffer l'huile d'olive.</li>
            <li>Faire revenir les oignons, l'ail, les câpres, les anchois, le persil et le concentré de tomate.</li>
            <li>Mouiller avec le vin blanc.</li>
            <li>Verser le tout dans un plat à four.</li>
            <li>Poser la daurade, l'arroser d'un filet d'huile d'olive, saler et poivrer.</li>
            <li>Entourer le poisson de tomates cerises.</li>
            <li>Enfourner à 220° (therm. 7) pendant 30 min.</li>
        </ul>
    </div>
</div>
<div class="row">
    <div class="col-md-12 col-lg-12">
        <div class="astuce">
            <i class="fa fa-caret-right" aria-hidden="true"></i> ASTUCES TIME NUTRITION
            <div>
                Nous vous recommandons d’accompagner ce plat d’un duo tomates courgettes à la provençale.
            </div>
        </div>

    </div>
</div>