<div class="row">
    <div class="col-md-12 col-lg 12 recettes">
        <div class="col-xs-12 col-sm-6 col-md-4 col-lg-4">
            <h2><?php echo __('Duo de lotte et saint-jacques');?></h2>
            <ul>
                <li><img src="<?php echo $this->getViewFileUrl('images/recettes/cutlery.png'); ?>"> <span class="gray">Pour</span> : 2 personnes</li>
                <li><img src="<?php echo $this->getViewFileUrl('images/recettes/clock.png'); ?>"> <span class="gray">Préparation</span> : 10 min.</li>
                <li><img src="<?php echo $this->getViewFileUrl('images/recettes/oven.png'); ?>"> <span class="gray">Cuisson</span> : 25 min. <span class="gray">Refroidissement</span> : 30 min.</li>
            </ul>
            <h3 class="recette-part">Ingrédients</h3>
            <ul class="ingredients">
                <li>450 g de lotte</li>
                <li>6 coquilles Saint-Jacques</li>
                <li>4 grosses tomates fraiches</li>
                <li>2 tomates confites</li>
                <li>12 olives noires</li>
                <li>1 bouquet de basilic</li>
                <li>½ bouquet d'estragon</li>
                <li>½ cuil. à café de graines d'anis</li>
                <li>2 cuil. à soupe d'huile d'olive</li>
                <li>Sel, poivre</li>
                <li>Sucre en poudre</li>
            </ul>

        </div>
        <div class="col-xs-12 col-sm-6 col-md-4 col-lg-4">
            <img src="<?php echo $this->getViewFileUrl('images/recettes/duo_lotte_saint_jacques.jpg'); ?>" alt="duo de lotte et saint-jacques time nutrition">
        </div>
        <div class="col-xs-12 col-sm-12 col-md-4 col-lg-4">
            La lotte ou baudroie est un poisson marin vivant le long des côtes d'Europe ; on la trouve fréquemment sur les côtes de Provence.<br>
            Sa tête énorme la fait ressembler à un crapaud, sa peau est totalement lisse et ne possède aucune écaille.<br>
            À 20 ans elle peut atteindre 2 mètres pour un poids de 45 kg !
        </div>
    </div>
</div>
<div class="row">
    <div class="col-md-12 col-lg-12 recettes">
        <h3 class="recette-part">Préparation</h3>
        <ul class="preparation">
            <li>Couper les tomates confites en 4.</li>
            <li>Ciseler les fines herbes et les répartir en 2 parts égales.</li>
            <li>Éplucher les tomates fraiches et les concasser grossièrement.</li>
            <li>Couper les filets de lotte en tronçons de 5 à 6 cm.</li>
            <li>Dans une sauteuse anti-adhésive faire chauffer l'huile d'olive.</li>
            <li>Dès que l'huile est chaude y verser les tomates concassées, les graines d'anis, une part des fines herbes ciselées, saler, poivrer et sucrer.</li>
            <li>Porter le tout à ébullition à feu vif pendant 5 min. en remuant à l'aide d'une cuillère en bois, puis baisser à feu moyen.</li>
            <li>Déposer sur les tomates en compote les tronçons de lotte et cuire 5 min. d'un côté puis 3 min. de l'autre.</li>
            <li>Réserver alors les tronçons sur une assiette et mettre à leur place dans la poêle les noix de Saint-Jacques.</li>
            <li>Cuire 3 min. d'un côté puis ajouter le corail et cuire 2 min. de l'autre, puis réserver les noix et le corail sur une assiette.</li>
            <li>Laisser mijoter la compote de tomates.</li>
            <li>Lorsqu’elle a rendu tout son jus, la retirer et la mettre à refroidir directement dans les assiettes en la disposant sur la moitié de l’assiette.</li>
            <li>Préparer la vinaigrette et la mixer avec la seconde part des fines herbes.</li>
            <li>Placer en face de la compote les tronçons de lotte sur une ligne et sur une deuxième ligne les noix de coquille Saint-Jacques et leur corail.</li>
            <li>Intercaler six olives noires sur chaque assiette et les morceaux de tomates confites.</li>
            <li>Arroser chaque élément avec 2 cuil. à café de vinaigrette.</li>
            <li>Déguster.</li>
        </ul>
    </div>
</div>
<div class="row">
    <div class="col-md-12 col-lg-12">
        <div class="astuce">
            <i class="fa fa-caret-right" aria-hidden="true"></i> ASTUCES TIME NUTRITION
            <div>
                La baudroie est un poisson prisé pour sa chair très fine mais son foie, ses joues et sa queue sont des mets particulièrement recherchés et à ne pas dédaigner.<br>
                Si vous en trouvez sur les étals des poissonniers, n’hésitez pas.
            </div>
        </div>

    </div>
</div>