<div class="row">
    <div class="col-md-12 col-lg 12 recettes">
        <div class="col-xs-12 col-sm-6 col-md-4 col-lg-4">
            <h2><?php echo __('ESCALOPES DE DINDE AUX POMMES');?></h2>
            <ul>
                <li><img src="<?php echo $this->getViewFileUrl('images/recettes/cutlery.png'); ?>"> <span class="gray">Pour</span> : 2 personnes</li>
                <li><img src="<?php echo $this->getViewFileUrl('images/recettes/clock.png'); ?>"> <span class="gray">Préparation</span> : 6 min.</li>
                <li><img src="<?php echo $this->getViewFileUrl('images/recettes/oven.png'); ?>"> <span class="gray">Cuisson</span> : 10 min.</li>
            </ul>
            <h3 class="recette-part">Ingrédients</h3>
            <ul class="ingredients">
                <li>400 g d'escalopes de dinde</li>
                <li>½ citron pressé</li>
                <li>1 pomme</li>
                <li>1 cuil. à soupe de persil haché</li>
                <li>Beurre</li>
                <li>Sel, poivre</li>
                <li>Huile d'olive</li>
            </ul>

        </div>
        <div class="col-xs-12 col-sm-6 col-md-4 col-lg-4">
            <img src="<?php echo $this->getViewFileUrl('images/recettes/escalopes_dinde_pomme.jpg'); ?>" alt="escalopes de dinde aux pommes time nutrition">
        </div>
        <div class="col-xs-12 col-sm-12 col-md-4 col-lg-4">
            L’escalope de dinde est une tranche de filet sans peau.
        </div>
    </div>
</div>
<div class="row">
    <div class="col-md-12 col-lg-12 recettes">
        <h3 class="recette-part">Préparation</h3>
        <ul class="preparation">
            <li>Dans une poêle anti-adhésive faire chauffer 1 cuil. à soupe d'huile d'olive et une noix de beurre.</li>
            <li>Y déposer les escalopes de dinde et les saisir sur les deux faces.</li>
            <li>Baisser le feu, saler et poivrer.</li>
            <li>Éplucher la pomme et la couper en dés.</li>
            <li>Ajouter les dés de pommes autour des escalopes et les faire rissoler, puis les disposer sur les escalopes.</li>
            <li>Arroser avec jus d’½ citron.</li>
            <li>Déposer les tranches sur deux assiettes et parsemer de persil.</li>
        </ul>
    </div>
</div>
<div class="row">
    <div class="col-md-12 col-lg-12">
        <div class="astuce">
            <i class="fa fa-caret-right" aria-hidden="true"></i> ASTUCES TIME NUTRITION
            <div>
                Les escalopes de dinde sont parfois un peu sèches.<br>
                Pour y remédier et les attendrir, utilisez le jus d'un citron pressé.<br>
                Arrosez la viande des deux côtés et laissez-les macérer pendant une demi-heure.<br>
                Essuyez ensuite la viande à l’aide de papier absorbant avant de la faire cuire.<br>
                La viande doit être bien sèche pour une cuisson idéale.
            </div>
        </div>

    </div>
</div>