<div class="row">
    <div class="col-md-12 col-lg 12 recettes">
        <div class="col-xs-12 col-sm-6 col-md-4 col-lg-4">
            <h2><?php echo __('Escalope de deinde à la moutarde à l\'ancienne');?></h2>
            <ul>
                <li><img src="<?php echo $this->getViewFileUrl('images/recettes/cutlery.png'); ?>"> <span class="gray">Pour</span> : 2 personnes</li>
                <li><img src="<?php echo $this->getViewFileUrl('images/recettes/clock.png'); ?>"> <span class="gray">Préparation</span> : 15 min.</li>
                <li><img src="<?php echo $this->getViewFileUrl('images/recettes/oven.png'); ?>"> <span class="gray">Cuisson</span> : 15 min.</li>
            </ul>
            <h3 class="recette-part">Ingrédients</h3>
            <ul class="ingredients">
                <li>2 escalopes de dinde de 130 g chacune</li>
                <li>2 cuil. à soupe de moutarde à l’ancienne</li>
                <li>1 cuil. à soupe d'huile d'olive</li>
                <li>1 noisette de beurre</li>
                <li>Sel, poivre</li>
            </ul>

        </div>
        <div class="col-xs-12 col-sm-6 col-md-4 col-lg-4">
            <img src="<?php echo $this->getViewFileUrl('images/recettes/escalope_dinde_moutarde.jpg'); ?>" alt="escalopes de dinde à la moutarde à l'ancienne time nutrition">
        </div>
        <div class="col-xs-12 col-sm-12 col-md-4 col-lg-4">
            La dinde est un oiseau de basse-cour originaire d’Amérique Centrale.<br>
            Les colons espagnols la ramenèrent en Europe dès le XVIe siècle : comme ils croyaient revenir des Indes, ils la baptisèrent « poule d'Inde », puis par usage « d'Inde » et enfin « dinde ».
        </div>
    </div>
</div>
<div class="row">
    <div class="col-md-12 col-lg-12 recettes">
        <h3 class="recette-part">Préparation</h3>
        <ul class="preparation">
            <li>Tartiner de moutarde les escalopes.</li>
            <li>Dans une poêle anti-adhésive faire chauffer l'huile et le beurre. Quand ils sont chauds, saisir les escalopes côté moutardé, saler et poivrer.</li>
            <li>Tartiner l'autre côté des escalopes cuire 1 min. à feu vif les retourner pour les cuire encore 1 min., baisser le feu et cuire à feu très doux pendant 12 à 13 min.</li>
            <li>Servir aussitôt.</li>
        </ul>
    </div>
</div>
<div class="row">
    <div class="col-md-12 col-lg-12">
        <div class="astuce">
            <i class="fa fa-caret-right" aria-hidden="true"></i> ASTUCES TIME NUTRITION
            <div>
                Nous vous conseillons d’accompagner ces escalopes de carottes sautées.
            </div>
        </div>

    </div>
</div>