<div class="row">
    <div class="col-md-12 col-lg 12 recettes">
        <div class="col-xs-12 col-sm-6 col-md-4 col-lg-4">
            <h2><?php echo __('Julienne à la Provençale');?></h2>
            <ul>
                <li><img src="<?php echo $this->getViewFileUrl('images/recettes/cutlery.png'); ?>"> <span class="gray">Pour</span> : 2 personnes</li>
                <li><img src="<?php echo $this->getViewFileUrl('images/recettes/clock.png'); ?>"> <span class="gray">Préparation</span> : 15 min.</li>
                <li><img src="<?php echo $this->getViewFileUrl('images/recettes/oven.png'); ?>"> <span class="gray">Cuisson</span> : 25 min.</li>
            </ul>
            <h3 class="recette-part">Ingrédients</h3>
            <ul class="ingredients">
                <li>600 g de filet de Julienne</li>
                <li>6 petites tomates</li>
                <li>14 olives noires</li>
                <li>1 cuil. à soupe d'huile d'olive</li>
                <li>1 petit oignon</li>
                <li>½ cuil. à café de sucre en poudre</li>
                <li>4 belles branches d'estragon</li>
                <li>Sel, poivre</li>
            </ul>

        </div>
        <div class="col-xs-12 col-sm-6 col-md-4 col-lg-4">
            <img src="<?php echo $this->getViewFileUrl('images/recettes/julienne_provencale.jpg'); ?>" alt="julienne à la provençale time nutrition">
        </div>
        <div class="col-xs-12 col-sm-12 col-md-4 col-lg-4">

        </div>
    </div>
</div>
<div class="row">
    <div class="col-md-12 col-lg-12 recettes">
        <h3 class="recette-part">Préparation</h3>
        <ul class="preparation">
            <li>Éplucher les tomates, les couper en 8.</li>
            <li>Effeuiller les branches d'estragon.</li>
            <li>Émincer l'oignon.</li>
            <li>Dans une sauteuse faire chauffer l'huile d'olive et y faire revenir l'oignon émincé.</li>
            <li>Quand il est transparent ajouter les tomates, saler légèrement, poivrer largement et saupoudrer de sucre.</li>
            <li>Couvrir et laisser mijoter 15 min. à feu moyen.</li>
            <li>Ajouter les filets de poisson ainsi que les olives.</li>
            <li>Parsemer les feuilles d'estragon, couvrir et laisser cuire 6 à 10 min. suivant l'épaisseur des filets.</li>
        </ul>
    </div>
</div>
<div class="row">
    <div class="col-md-12 col-lg-12">
        <div class="astuce">
            <i class="fa fa-caret-right" aria-hidden="true"></i> ASTUCES TIME NUTRITION
            <div>
                En incorporant à ce plat des olives, il constituera un plat parfaitement équilibré pour le repas du soir.
            </div>
        </div>

    </div>
</div>