<div class="row">
    <div class="col-md-12 col-lg 12 recettes">
        <div class="col-xs-12 col-sm-6 col-md-4 col-lg-4">
            <h2><?php echo __('LANGOUSTINES AU BEURRE D\'AGRUMES');?></h2>
            <ul>
                <li><img src="<?php echo $this->getViewFileUrl('images/recettes/cutlery.png'); ?>"> <span class="gray">Pour</span> : 2 personnes</li>
                <li><img src="<?php echo $this->getViewFileUrl('images/recettes/clock.png'); ?>"> <span class="gray">Préparation</span> : 25 min.</li>
                <li><img src="<?php echo $this->getViewFileUrl('images/recettes/oven.png'); ?>"> <span class="gray">Cuisson</span> : 30 s. <span class="gray">Cuisson beurre d'agrumes</span> : 5 min environ.</li>
            </ul>
            <h3 class="recette-part">Ingrédients</h3>
            <ul class="ingredients">
                <li>6 langoustines d'environ 200 g chacune</li>
                <li>1 jaune d'œuf</li>
                <li>150 g de noisettes concassées</li>
                <li>1 cuil. à soupe de feuilles de romarin</li>
                <li>1 cuil. à café d'huile d'olive</li>
                <li>Huile de friture</li>
                <li>Sel, Poivre</li>
            </ul>

        </div>
        <div class="col-xs-12 col-sm-6 col-md-4 col-lg-4">
            <img src="<?php echo $this->getViewFileUrl('images/recettes/langoustines_agrumes.jpg'); ?>" alt="langoustines au beurre d'agrumes time nutrition">
        </div>
        <div class="col-xs-12 col-sm-12 col-md-4 col-lg-4">
            Préférez les langoustines vivantes : elles ont meilleur goût !
        </div>
    </div>
</div>
<div class="row">
    <div class="col-md-12 col-lg-12 recettes">
        <h3 class="recette-part">Préparation</h3>
        <ul class="preparation">
            <li>Décortiquer les langoustines crues et ôter le boyau noir sur le dessus de la queue.</li>
            <li>Faire chauffer la friture à 170° (therm. 6).</li>
            <li>Détacher les feuilles d'une branche de romarin frais et les ciseler très finement.</li>
            <li>Dans une assiette verser les noisettes concassées.</li>
            <li>Séparer le blanc du jaune d'un œuf et verser le jaune dans un bol avec l'huile d'olive.</li>
            <li>Enrober les langoustines avec ce mélange et les rouler dans le mélange de l'assiette.</li>
            <li>Dans une petite casserole, verser le vin blanc, ajouter l'échalote émincée et faire réduire à sec, à feu vif.</li>
            <li>Pendant ce temps, plonger les queues de langoustines 30 s. dans le bain de friture.</li>
            <li>Les égoutter sur un papier absorbant et les maintenir au chaud.</li>
            <li>Quand le vin de la casserole est évaporé mettre celle-ci hors du feu et réaliser le beurre d'agrume : incorporer les zestes et le beurre petit à petit en fouettant, saler et poivrer.</li>
            <li>Saler et poivrer les langoustines, les répartir sur deux assiettes très chaudes et napper avec le beurre d'agrumes.</li>
        </ul>
    </div>
</div>
<div class="row">
    <div class="col-md-12 col-lg-12">
        <div class="astuce">
            <i class="fa fa-caret-right" aria-hidden="true"></i> ASTUCES TIME NUTRITION
            <div>
                Nous vous recommandons d’accompagner ce plat d'une compotée de chou.
            </div>
        </div>

    </div>
</div>