<div class="row">
    <div class="col-md-12 col-lg 12 recettes">
        <div class="col-xs-12 col-sm-6 col-md-4 col-lg-4">
            <h2><?php echo __('DAUBE DE LOTTE AU SAFRAN');?></h2>
            <ul>
                <li><img src="<?php echo $this->getViewFileUrl('images/recettes/cutlery.png'); ?>"> <span class="gray">Pour</span> : 2 personnes</li>
                <li><img src="<?php echo $this->getViewFileUrl('images/recettes/clock.png'); ?>"> <span class="gray">Préparation</span> : 10 min.</li>
                <li><img src="<?php echo $this->getViewFileUrl('images/recettes/oven.png'); ?>"> <span class="gray">Cuisson</span> : 10 min.</li>
            </ul>
            <h3 class="recette-part">Ingrédients</h3>
            <ul class="ingredients">
                <li>600 g de lotte (joue et filet)</li>
                <li>2 belles tomates</li>
                <li>2 grosses cuil. à soupe de crème</li>
                <li>2 dosettes de safran</li>
                <li>1 cuil. à soupe d'huile d'olive</li>
                <li>Sel, poivre</li>
            </ul>

        </div>
        <div class="col-xs-12 col-sm-6 col-md-4 col-lg-4">
            <img src="<?php echo $this->getViewFileUrl('images/recettes/lotte_safran.jpg'); ?>" alt="daube de lotte au safran time nutrition">
        </div>
        <div class="col-xs-12 col-sm-12 col-md-4 col-lg-4">
            Le safran est une épice issue de la culture du Crocus sativus : ce sont les trois stigmates de sa fleur qui sont séchés.<br>
            Le safran fut longtemps l'épice la plus chère au monde. Il a un goût amer et un parfum proche de l'iodoforme ou du foin.
        </div>
    </div>
</div>
<div class="row">
    <div class="col-md-12 col-lg-12 recettes">
        <h3 class="recette-part">Préparation</h3>
        <ul class="preparation">
            <li>Éplucher les tomates, les couper en dés, les répartir sur deux assiettes allant au micro-ondes, saler et poivrer.</li>
            <li>Dans une poêle anti-adhésive faire chauffer l'huile d'olive. Quand l'huile est bien chaude, placer les morceaux de lotte à feu moyen. Saler, poivrer.</li>
            <li>Laisser cuire environ 5 min., puis les retourner et laisser cuire encore 3 min.</li>
            <span>Pendant que le poisson cuit :</span>
            <li>Prendre une petite casserole, y faire chauffer la crème.</li>
            <li>Ajouter le safran, saler, poivrer et porter à ébullition.</li>
            <li>Dès l'ébullition retirer du feu, couvrir et laisser infuser.</li>
            <li>Chauffer l'une après l'autre chaque assiette de tomates au micro-ondes 50 secondes.</li>
            <li>Répartir les morceaux de lotte à part égale sur chaque assiette et napper avec la crème.</li>
        </ul>
    </div>
</div>
<div class="row">
    <div class="col-md-12 col-lg-12">
        <div class="astuce">
            <i class="fa fa-caret-right" aria-hidden="true"></i> ASTUCES TIME NUTRITION
            <div>
                Nous vous recommandons d’accompagner la lotte d’une compotée d’abricots et de tomates.
            </div>
        </div>

    </div>
</div>