<div class="row">
    <div class="col-md-12 col-lg 12 recettes">
        <div class="col-xs-12 col-sm-6 col-md-4 col-lg-4">
            <h2><?php echo __('Filets de cabillaud vapeur');?></h2>
            <ul>
                <li><img src="<?php echo $this->getViewFileUrl('images/recettes/cutlery.png'); ?>"> <span class="gray">Pour</span> : 2 personnes</li>
                <li><img src="<?php echo $this->getViewFileUrl('images/recettes/clock.png'); ?>"> <span class="gray">Préparation</span> : 20 min.</li>
                <li><img src="<?php echo $this->getViewFileUrl('images/recettes/oven.png'); ?>"> <span class="gray">Cuisson</span> : 25 min.</li>
            </ul>
            <h3 class="recette-part">Ingrédients</h3>
            <ul class="ingredients">
                <li>500 g de filets de merlan</li>
                <li>60 g de beurre</li>
                <li>1 petite boîte de filets d'anchois</li>
                <li>4 cuil. à soupe d'huile d'olive</li>
                <li>175 g de champignons</li>
                <li>1 carotte/li>
                <li>1 blanc de poireau</li>
                <li>1 oignon</li>
                <li>1 branche de céleri</li>
                <li>800 g de tomates</li>
                <li>100 g d'olives vertes</li>
                <li>1 citron</li>
                <li>1 cuil. à soupe de farine</li>
                <li>1 gousse d'ail</li>
                <li>4 dl de court bouillon instantané</li>
                <li>1 dl de vin blanc</li>
                <li>Sel, poivre</li>
            </ul>

        </div>
        <div class="col-xs-12 col-sm-6 col-md-4 col-lg-4">
            <img src="<?php echo $this->getViewFileUrl('images/recettes/merlan_saveur_sud.jpg'); ?>" alt="filets de merlan aux saveur du sud time nutrition">
        </div>
        <div class="col-xs-12 col-sm-12 col-md-4 col-lg-4">
            Ce poisson était auparavant méprisé mais est aujourd'hui largement consommé.<br>
            Sa chair blanche, fine et feuilletée, pauvre en lipides, se fragilise beaucoup à la cuisson.
        </div>
    </div>
</div>
<div class="row">
    <div class="col-md-12 col-lg-12 recettes">
        <h3 class="recette-part">Préparation</h3>
        <ul class="preparation">
            <li>Éplucher les tomates, les champignons, la carotte, l'oignon, le poireau et le céleri.</li>
            <li>Presser le citron.</li>
            <li>Laver les champignons et les filets de merlan.</li>
            <li>Couper en dés les tomates et les champignons.</li>
            <li>Arroser les champignons avec la moitié du jus de citron et les filets de merlan avec l'autre moitié.</li>
            <li>Hacher très finement les autres légumes.</li>
            <li>Dans une sauteuse faire chauffer à feu vif 2 cuil. à soupe d'huile d'olive, baisser le feu et y faire fondre les légumes émincés en remuant.</li>
            <li>Saupoudrer de farine, laisser légèrement roussir toujours en remuant.</li>
            <li>Ajouter les tomates et l'ail écrasé sans son germe, le vin blanc et le court bouillon ; saler légèrement et poivrer.</li>
            <li>Laisser mijoter environ 20 min. à feu très doux et à moitié couvert.</li>
            <span>Pendant ce temps</span>
            <li>Plonger les olives dénoyautées dans une casserole d'eau bouillante pendant 3 min.</li>
            <li>Les égoutter et les ajouter à la préparation de légumes quand elle est cuite.</li>
            <li>Faire revenir les dés de champignons dans une poêle, avec 1 cuil. à soupe d'huile d'olive et 15 g de beurre jusqu'à évaporation de l'eau, saler, poivrer.</li>
            <li>Réserver au chaud.</li>
            <li>Hacher les filets d'anchois et les mélanger à 35 g de beurre pour réaliser un beurre d'anchois.</li>
            <li>Dans la poêle qui a servi aux champignons faire fondre 10 g de beurre avec 1 cuil. à soupe d'huile d'olive y faire cuire les filets de merlan 1 min. de chaque côté à feu vif.</li>
            <li>Hors du feu, incorporer le beurre d'anchois à la préparation de légumes.</li>
            <li>Sur des assiettes chaudes disposer les filets entourés de champignons et napper largement avec la préparation de légumes au beurre d'anchois.</li>
        </ul>
    </div>
</div>
<div class="row">
    <div class="col-md-12 col-lg-12">
        <div class="astuce">
            <i class="fa fa-caret-right" aria-hidden="true"></i> ASTUCES TIME NUTRITION
            <div>
                On trouve le merlan toute l’année, mais ses qualités gustatives se révèlent tout particulièrement aux mois de septembre et octobre.
            </div>
        </div>

    </div>
</div>