<div class="row">
    <div class="col-md-12 col-lg 12 recettes">
        <div class="col-xs-12 col-sm-6 col-md-4 col-lg-4">
            <h2><?php echo __('Noix de Saint-Jacques au vin blanc');?></h2>
            <ul>
                <li><img src="<?php echo $this->getViewFileUrl('images/recettes/cutlery.png'); ?>"> <span class="gray">Pour</span> : 2 personnes</li>
                <li><img src="<?php echo $this->getViewFileUrl('images/recettes/clock.png'); ?>"> <span class="gray">Préparation</span> : 15 min.</li>
                <li><img src="<?php echo $this->getViewFileUrl('images/recettes/oven.png'); ?>"> <span class="gray">Cuisson</span> : 20 min.</li>
            </ul>
            <h3 class="recette-part">Ingrédients</h3>
            <ul class="ingredients">
                <li>10 coquilles Saint Jacques</li>
                <li>1 échalote</li>
                <li>2 dl de vin blanc</li>
                <li>1 noix de beurre</li>
                <li>Sel, Poivre</li>
            </ul>

        </div>
        <div class="col-xs-12 col-sm-6 col-md-4 col-lg-4">
            <img src="<?php echo $this->getViewFileUrl('images/recettes/noix_saint_jacques.jpg'); ?>" alt="noix de saint jacques au vin blanc time nutrition">
        </div>
        <div class="col-xs-12 col-sm-12 col-md-4 col-lg-4">
            Le nom « Saint-Jacques » est un nom d'usage et un nom commercial.<br>
            Depuis 1996, l'OMC a autorisé l'usage de cette dénomination pour d'autres pectinidés que l'espèce Pecten maximus, mais aussi des genres proches, comme Chlamys, Argopecten ou Placopecten, c'est-à-dire des pétoncles ou des vanneaux, pour les ventes sous forme de noix.<br>
            Préférez Pecten maximus si possible, elle est plus délicate en goût.<br>
            Le corail est permanent dans les Saint-Jacques sauf celles d’Erquy et du Mont Saint-Michel.

        </div>
    </div>
</div>
<div class="row">
    <div class="col-md-12 col-lg-12 recettes">
        <h3 class="recette-part">Préparation</h3>
        <ul class="preparation">
            <li>Hacher finement l'échalote.</li>
            <li>Nettoyer soigneusement les noix de Saint-Jacques et leur corail sous un filet d'eau, puis les poser sur un papier absorbant.</li>
            <li>Dans une casserole mettre l'échalote hachée et le vin blanc puis faire cuire à température maximum jusqu'à évaporation du vin et laisser refroidir.</li>
            <li>Dans une poêle faire fondre la noix de beurre, y déposer les noix de Saint Jacques et les cuire à feu vif 2 min. d'un côté puis ajouter le corail, retourner les noix, cuire encore 1 min., saler, poivrer et maintenir au chaud.</li>
            <li>Déposer les coquilles et le corail sur des assiettes et napper de sauce.</li>
            <li>Déguster sans attendre.</li>
        </ul>
    </div>
</div>
<div class="row">
    <div class="col-md-12 col-lg-12">
        <div class="astuce">
            <i class="fa fa-caret-right" aria-hidden="true"></i> ASTUCES TIME NUTRITION
            <div>
                Nous vous proposons d’accompagner les noix de Saint-Jacques de topinambours.<br>
                Pour 2 personnes, prévoyez 200g de topinambours.<br>
                Éplucher les topinambours, les couper en dés de 2 cm. de côté et les plonger dans un saladier d'eau citronnée pour éviter qu'ils noircissent.<br>
                Faire bouillir une grande casserole d'eau salée y jeter les dés de topinambour.<br>
                Cuire 15 min. à partir de la reprise de l'ébullition.<br>
                Egoutter.<br>
                Dans une poêle faire chauffer la cuillère à soupe de graisse de canardet y faire légèrement rissoler les dés de topinambours.
            </div>
        </div>

    </div>
</div>