<div class="row">
    <div class="col-md-12 col-lg 12 recettes">
        <div class="col-xs-12 col-sm-6 col-md-4 col-lg-4">
            <h2><?php echo __('PAPILLOTES DE CABILLAUD');?></h2>
            <ul>
                <li><img src="<?php echo $this->getViewFileUrl('images/recettes/cutlery.png'); ?>"> <span class="gray">Pour</span> : 2 personnes</li>
                <li><img src="<?php echo $this->getViewFileUrl('images/recettes/clock.png'); ?>"> <span class="gray">Préparation</span> : 10 min.</li>
                <li><img src="<?php echo $this->getViewFileUrl('images/recettes/oven.png'); ?>"> <span class="gray">Cuisson</span> : 15 à 20 min.</li>
            </ul>
            <h3 class="recette-part">Ingrédients</h3>
            <ul class="ingredients">
                <li>600 g de filet de cabillaud</li>
                <li>1 citron confit au sel</li>
                <li>4 rondelles de citron frais</li>
                <li>1 cuil. à café de graine d'aneth</li>
                <li>4 branches de thym citron</li>
                <li>2 cuil. à soupe de vin blanc sec</li>
                <li>Poivre</li>
            </ul>

        </div>
        <div class="col-xs-12 col-sm-6 col-md-4 col-lg-4">
            <img src="<?php echo $this->getViewFileUrl('images/recettes/papillotes_cabillaud.jpg'); ?>" alt="papillotes de cabillaud time nutrition">
        </div>
        <div class="col-xs-12 col-sm-12 col-md-4 col-lg-4">
            La cuisson en papillote permet de réaliser une cuisson à la vapeur.<br>
            On peut donc cuire tous les aliments : le poisson et les fruits de mer bien entendu, mais aussi les viandes blanches et rouges, les légumes ainsi que les fruits et même les pâtes !
        </div>
    </div>
</div>
<div class="row">
    <div class="col-md-12 col-lg-12 recettes">
        <h3 class="recette-part">Préparation</h3>
        <ul class="preparation">
            <li>Couper le citron confit en 8 portions.</li>
            <li>Allumer le four à 220° (therm. 7).</li>
            <li>Découper 2 feuilles d'aluminium de 50 cm de long.</li>
            <li>Sur chacune poser 2 rondelles de citron, 1 branche de thym citron et les filets de cabillaud.</li>
            <li>Parsemer les filets de graines d'aneth, déposer dessus 4 morceaux de citron confit au sel et 1 branche de thym citron.</li>
            <li>Poivrer.</li>
            <li>Refermer en partie les papillotes et introduire dans chacune 1cuil. à soupe de vin blanc sec.</li>
            <li>Fermer complètement les papillotes.</li>
            <li>Enfourner et laisser cuire 15 à 20 minutes suivant l'épaisseur des filets de Cabillaud.</li>
        </ul>
    </div>
</div>
<div class="row">
    <div class="col-md-12 col-lg-12">
        <div class="astuce">
            <i class="fa fa-caret-right" aria-hidden="true"></i> ASTUCES TIME NUTRITION
            <div>
                Cette recette pourra être réalisée avec de nombreux poissons: panga, bar, saumon, truite, …<br>
                En fonction des aliments choisis, il faut bien sûr adapter le temps de cuisson.<br>
                Sachez toutefois qu'il vaut mieux couper finement ou émincer vos ingrédients afin que la cuisson soit la plus courte possible, c'est quand même le but recherché.
            </div>
        </div>

    </div>
</div>