<div class="row">
    <div class="col-md-12 col-lg 12 recettes">
        <div class="col-xs-12 col-sm-6 col-md-4 col-lg-4">
            <h2><?php echo __('Poelee Gambas');?></h2>
            <ul>
                <li><img src="<?php echo $this->getViewFileUrl('images/recettes/cutlery.png'); ?>"> <span class="gray">Pour</span> : 2 personnes</li>
                <li><img src="<?php echo $this->getViewFileUrl('images/recettes/clock.png'); ?>"> <span class="gray">Préparation</span> : 10 min.</li>
                <li><img src="<?php echo $this->getViewFileUrl('images/recettes/oven.png'); ?>"> <span class="gray">Cuisson</span> : 10 min.</li>
            </ul>
            <h3 class="recette-part">Ingrédients</h3>
            <ul class="ingredients">
                <li>12 à 16 gambas (selon la taille)</li>
                <li>1 gousse d'ail</li>
                <li>1 piment</li>
                <li>1 cuil. à soupe d'huile d'olive</li>
                <li>Sel</li>
            </ul>

        </div>
        <div class="col-xs-12 col-sm-6 col-md-4 col-lg-4">
            <img src="<?php echo $this->getViewFileUrl('images/recettes/poelee_gambas.jpg'); ?>" alt="Poelee Gambas time nutrition">
        </div>
        <div class="col-xs-12 col-sm-12 col-md-4 col-lg-4">
            Les grandes crevettes sont usuellement désignées sous le nom de « gambas », un terme espagnol passé en français.
        </div>
    </div>
</div>
<div class="row">
    <div class="col-md-12 col-lg-12 recettes">
        <h3 class="recette-part">Préparation</h3>
        <ul class="preparation">
            <li>Remplir une casserole d'eau, ajouter une cuillère à soupe de sel et porter à ébullition.</li>
            <li>Dès que l'eau est bouillante y plonger les gambas, puis les retirer immédiatement.</li>
            <li>Les laisser refroidir, puis enlever la tête et la carapace.</li>
            <li>Hacher ensemble l'ail et le piment.</li>
            <li>Dans une sauteuse faire chauffer l'huile d'olive.</li>
            <li>Quand elle est bien chaude y déposer les gambas épluchées et les saupoudrer avec le mélange d'ail et de piment.</li>
            <li>Faire cuire à feu vif quelques minutes jusqu'à ce que l'ail soit doré.</li>
            <li>Déguster.</li>
        </ul>
    </div>
</div>
<div class="row">
    <div class="col-md-12 col-lg-12">
        <div class="astuce">
            <i class="fa fa-caret-right" aria-hidden="true"></i> ASTUCES TIME NUTRITION
            <div>
                Vous pouvez varier les plaisirs en faisant revenir dans la sauteuse avec les gambas, tomates et pignons.
            </div>
        </div>

    </div>
</div>