<div class="row">
    <div class="col-md-12 col-lg 12 recettes">
        <div class="col-xs-12 col-sm-6 col-md-4 col-lg-4">
            <h2><?php echo __('POT AU FEU DE LA MER');?></h2>
            <ul>
                <li><img src="<?php echo $this->getViewFileUrl('images/recettes/cutlery.png'); ?>"> <span class="gray">Pour</span> : 4 personnes</li>
                <li><img src="<?php echo $this->getViewFileUrl('images/recettes/clock.png'); ?>"> <span class="gray">Préparation</span> : 20 min.</li>
                <li><img src="<?php echo $this->getViewFileUrl('images/recettes/oven.png'); ?>"> <span class="gray">Cuisson</span> : 35 min.</li>
            </ul>
            <h3 class="recette-part">Ingrédients</h3>
            <ul class="ingredients">
                <li>500 g de cabillaud</li>
                <li>300 g de turbot</li>
                <li>300 g de lotte</li>
                <li>4 noix de Saint Jacques</li>
                <li>4 langoustines</li>
                <li>200 g de carottes</li>
                <li>2 poireaux</li>
                <li>4 côtes de céleri</li>
                <li>4 petits navets</li>
                <li>1 oignon</li>
                <li>1 bouquet garni</li>
                <li>1 verre de vin blanc</li>
                <li>1 cuil. à soupe de ciboulette</li>
                <li>1 cuil. à soupe d'estragon ciselé</li>
                <li>1 cuil. à soupe de peluches de cerfeuil</li>
                <li>1 cuil. à café de gros sel</li>
                <li>Poivre</li>
            </ul>

        </div>
        <div class="col-xs-12 col-sm-6 col-md-4 col-lg-4">
            <img src="<?php echo $this->getViewFileUrl('images/recettes/pot_feu_mer.jpg'); ?>" alt="pot au feu de la mer time nutrition">
        </div>
        <div class="col-xs-12 col-sm-12 col-md-4 col-lg-4">
            Le turbot est un poisson de grande taille en forme en losange.<br>
            Il ne faut pas confondre le turbot avec la barbue : la qualité de la chair est très différente.<br>
            Depuis les années 1980 on produit du turbot d’élevage surtout en Espagne.
        </div>
    </div>
</div>
<div class="row">
    <div class="col-md-12 col-lg-12 recettes">
        <h3 class="recette-part">Préparation</h3>
        <ul class="preparation">
            <li>Éplucher l'oignon.</li>
            <li>Dans une grande casserole mettre 1 l. ½ d'eau salée, verser le vin blanc, ajouter l'oignon et le bouquet garni puis poivrer.</li>
            <li>Porter à ébullition à feu vif puis baisser le feu et maintenir à frémissements pendant 10 min.</li>
            <li>Pendant ce temps, éplucher les carottes, le céleri, les découper en tronçons, les ajouter dans le court bouillon et compter 15 min de cuisson après la reprise de petite ébullition.</li>
            <li>Pendant ce temps, laver les langoustines.</li>
            <li>Continuer la cuisson pendant 8 min à feu doux puis ajouter les noix de coquilles et leur corail cuire encore 2 min.</li>
            <li>Servir le plat dans des assiettes creuses et saupoudrer du mélange d'herbes ciselées.</li>
        </ul>
    </div>
</div>
<div class="row">
    <div class="col-md-12 col-lg-12">
        <div class="astuce">
            <i class="fa fa-caret-right" aria-hidden="true"></i> ASTUCES TIME NUTRITION
            <div>
                Préférez si possible des poissons de pleine mer et non issus d’élevages !
            </div>
        </div>

    </div>
</div>