<div class="row">
    <div class="col-md-12 col-lg 12 recettes">
        <div class="col-xs-12 col-sm-6 col-md-4 col-lg-4">
            <h2><?php echo __('POULET A LA CHINOISE');?></h2>
            <ul>
                <li><img src="<?php echo $this->getViewFileUrl('images/recettes/cutlery.png'); ?>"> <span class="gray">Pour</span> : 4 personnes</li>
                <li><img src="<?php echo $this->getViewFileUrl('images/recettes/clock.png'); ?>"> <span class="gray">Préparation</span> : 20 min.</li>
                <li><img src="<?php echo $this->getViewFileUrl('images/recettes/oven.png'); ?>"> <span class="gray">Cuisson</span> : 35 min.</li>
            </ul>
            <h3 class="recette-part">Ingrédients</h3>
            <ul class="ingredients">
                <li>1 poulet de 1 kg 500 (coupé en morceaux)</li>
                <li>1 l. de lait de coco</li>
                <li>6 gousses d'ail</li>
                <li>2 piments rouges</li>
                <li>2 piments verts</li>
                <li>2 citrons verts</li>
                <li>1 cuil. à café de gingembre râpé</li>
                <li>1 cuil. à café de graines de coriandre</li>
                <li>5 cuil. à soupe d'huile d'olive</li>
                <li>2 cuil. à soupe de persil plat</li>
            </ul>

        </div>
        <div class="col-xs-12 col-sm-6 col-md-4 col-lg-4">
            <img src="<?php echo $this->getViewFileUrl('images/recettes/poulet_chinoise.jpg'); ?>" alt="poulet à la chinoise time nutrition">
        </div>
        <div class="col-xs-12 col-sm-12 col-md-4 col-lg-4">
            Un poulet est une jeune volaille, mâle ou femelle, abattue entre quarante et quatre-vingt-dix jours après sa naissance, selon le mode de production (élevage industriel ou traditionnel).
        </div>
    </div>
</div>
<div class="row">
    <div class="col-md-12 col-lg-12 recettes">
        <h3 class="recette-part">Préparation</h3>
        <ul class="preparation">
            <li>Éplucher, les gousses d'ail et les débarrasser de leurs germes.</li>
            <li>Éplucher, le gingembre</li>
            <li>Éplucher les citrons verts et les couper en 2. Presser une moitié et réserver le jus. Couper en dés la pulpe des 3 autres moitiés et ôter les pépins.</li>
            <li>Mixer l'ail, les piments, les graines de coriandre, les 2 cuil. à soupe d'huile, le jus de citron et les feuilles de persil plat.</li>
            <li>Dans une cocotte chauffer l'huile restante y faire dorer à feu vif les morceaux de poulet sur toutes leurs faces.</li>
            <li>Ajouter la préparation mixée et les dés de citron.</li>
            <li>Mélanger pendant quelques instants, mouiller avec le lait de coco, saler, poivrer, baisser le feu et laisser mijoter pendant 25 min. en remuant de temps en temps.</li>
            <li>Lorsque la sauce est bien liée, servir dans des assiettes creuses.</li>
        </ul>
    </div>
</div>
<div class="row">
    <div class="col-md-12 col-lg-12">
        <div class="astuce">
            <i class="fa fa-caret-right" aria-hidden="true"></i> ASTUCES TIME NUTRITION
            <div>
                Pour le dîner nous vous conseillons d’accompagner ce plat de tomates confites ou de légumes sautés.<br>
                Ce plat pourra également être servi au déjeuner accompagné de nouilles chinoises.
            </div>
        </div>

    </div>
</div>