<div class="row">
    <div class="col-md-12 col-lg 12 recettes">
        <div class="col-xs-12 col-sm-6 col-md-4 col-lg-4">
            <h2><?php echo __('ROUGETS GRILLES AU COULIS DE TOMATES');?></h2>
            <ul>
                <li><img src="<?php echo $this->getViewFileUrl('images/recettes/cutlery.png'); ?>"> <span class="gray">Pour</span> : 2 personnes</li>
                <li><img src="<?php echo $this->getViewFileUrl('images/recettes/clock.png'); ?>"> <span class="gray">Préparation</span> : 10 min.</li>
                <li><img src="<?php echo $this->getViewFileUrl('images/recettes/oven.png'); ?>"> <span class="gray">Cuisson</span> : 10 min.</li>
            </ul>
            <h3 class="recette-part">Ingrédients</h3>
            <ul class="ingredients">
                <li>6 rougets</li>
                <li>Huile d'olive</li>
                <span>Sauce provençale</span>
                <li>2 grappes de tomates</li>
                <li>1 oignon</li>
                <li>2 gousses d'ail</li>
                <li>1 échalote</li>
                <li>Thym</li>
                <li>Laurier</li>
                <li>Persil</li>
                <li>Sel, poivre noir</li>
                <li>Huile d'olive</li>
            </ul>

        </div>
        <div class="col-xs-12 col-sm-6 col-md-4 col-lg-4">
            <img src="<?php echo $this->getViewFileUrl('images/recettes/rouget_coulis_tomate.jpg'); ?>" alt="rougets grillés au coulis de tomate time nutrition">
        </div>
        <div class="col-xs-12 col-sm-12 col-md-4 col-lg-4">
            Le nom de Rouget est donné en français à plusieurs dizaines d’espèces de poissons « osseux ».<br>
            Ils recherchent les petits vers et crustacés dont ils se nourrissent en fouillant le fond sableux.
        </div>
    </div>
</div>
<div class="row">
    <div class="col-md-12 col-lg-12 recettes">
        <h3 class="recette-part">Préparation</h3>
        <ul class="preparation">
            <li>Préparer le barbecue et poser le gril sur le feu pour qu'il soit très chaud</li>
            <li>Vider les rougets par une petite incision.</li>
            <li>Enduire les poissons d'huile d'olive.</li>
            <li>Les poser sur la grille très chaude, cuire 3 à 5 min. de chaque côté.</li>
            <li>Quand les rougets sont cuits, insérer du persil au niveau de l’entaille.</li>
            <span>Préparation de la sauce :</span>
            <li>Emincer l'échalote, l'oignon et l'ail.</li>
            <li>Éplucher et épépiner les tomates afin de ne récupérer que la chair.</li>
            <li>Faire revenir le mélange échalote, oignon et ail dans un peu d'huile.</li>
            <li>Dans une casserole verser ce mélange et ajouter la chair des tomates, le thym et le laurier. Laisser mijoter pendant une demi-heure. Retirer alors le thym et le laurier et ajouter le persil, le sel et le poivre.</li>
            <li>Nous vous recommandons d’accompagner ce plat de champignons et de tomates grillés à la provençale.</li>
        </ul>
    </div>
</div>
<div class="row">
    <div class="col-md-12 col-lg-12">
        <div class="astuce">
            <i class="fa fa-caret-right" aria-hidden="true"></i> ASTUCES TIME NUTRITION
            <div>
                Pour le dîner nous vous conseillons d’accompagner ce plat de tomates confites ou de légumes sautés.<br>
                Ce plat pourra également être servi au déjeuner accompagné de nouilles chinoises.
            </div>
        </div>

    </div>
</div>