<div class="row">
    <div class="col-md-12 col-lg 12 recettes">
        <div class="col-xs-12 col-sm-6 col-md-4 col-lg-4">
            <h2><?php echo __('Tajine de poisson');?></h2>
            <ul>
                <li><img src="<?php echo $this->getViewFileUrl('images/recettes/cutlery.png'); ?>"> <span class="gray">Pour</span> : 4 personnes</li>
                <li><img src="<?php echo $this->getViewFileUrl('images/recettes/clock.png'); ?>"> <span class="gray">Préparation</span> : 30 min.</li>
                <li><img src="<?php echo $this->getViewFileUrl('images/recettes/oven.png'); ?>"> <span class="gray">Marinade</span> : 50 min. <span class="gray">Cuisson</span> : 50 min.</li>
            </ul>
            <h3 class="recette-part">Ingrédients</h3>
            <ul class="ingredients">
                <li>400 g de filet de lotte</li>
                <li>400 g de dos de cabillaud</li>
                <li>400 g d'espadon</li>
                <li>2 courgettes</li>
                <li>1 aubergine</li>
                <li>4 tomates</li>
                <li>1 poivron rouge</li>
                <li>2 piments verts</li>
                <li>1 oignon</li>
                <li>3 gousses d'ail</li>
                <li>1 citron</li>
                <li>6 cuil. à soupe d'huile d'olive</li>
                <li>2 cuil. à soupe de coriandre ciselée</li>
                <li>Sel, poivre</li>
                <li>1 tajine en céramique</li>
            </ul>

        </div>
        <div class="col-xs-12 col-sm-6 col-md-4 col-lg-4">
            <img src="<?php echo $this->getViewFileUrl('images/recettes/tajine_poisson.jpg'); ?>" alt="tajine de poisson time nutrition">
        </div>
        <div class="col-xs-12 col-sm-12 col-md-4 col-lg-4">
            L'espadon peut dépasser 5 mètres et peser 500 kg.<br>
            Il possède un long « bec » (le rostre) plutôt aplati qui représente le tiers de la longueur totale.<br>
            Il se nourrit de calmars et de poissons. Etant en fin de chaîne alimentaire, il est souvent accusé de concentrer des métaux lourds (mercure...).
        </div>
    </div>
</div>
<div class="row">
    <div class="col-md-12 col-lg-12 recettes">
        <h3 class="recette-part">Préparation</h3>
        <ul class="preparation">
            <li>Couper chaque poisson en 4 morceaux, les laver, les éponger et les placer dans la tajine.</li>
            <li>Saler, saupoudrer de coriandre et arroser de 3 cuil. à soupe d'huile d'olive.</li>
            <li>Couvrir d'un film alimentaire et placer au frais 45 min.</li>
            <span>Pendant ce temps :</span>
            <li>Éplucher les poivrons et les courgettes en laissant une bande de peau sur deux.</li>
            <li>Plonger les tomates dans l'eau bouillante, les éplucher, ôter le pédoncule et les couper en morceaux.</li>
            <li>Ouvrir le poivron, le débarrasser de ses graines et le couper en lanières.</li>
            <li>Débarrasser les piments de leurs graines et les couper en tranches.</li>
            <li>Couper les courgettes et l'aubergine en tranches.</li>
            <li>Éplucher l'oignon et l'émincer.</li>
            <li>Dans une sauteuse faire chauffer l'huile d'olive restante y faire revenir sans prendre couleur l'oignon émincé.</li>
            <li>Dès qu'il est transparent ajouter l'ail pressé, les morceaux de tomates, de poivron, de piment, puis de courgettes et d'aubergines, saler et poivrer.</li>
            <li>Couvrir et cuire à feu moyen 10 min puis à feu doux 15 min.</li>
            <li>Chauffer le four à 210° (therm.7).</li>
            <li>Ôter le film alimentaire du tajine et verser les légumes sur les poissons.</li>
            <li>Disposer les rondelles de piment sur le dessus puis mouiller avec 10 cl. d'eau.</li>
            <li>Couvrir avec le couvercle du tajine et enfourner pendant 15 min.</li>
            <li>Presser le citron, arroser le contenu du tajine et cuire encore 5 min à couvert.</li>
            <li>Servir.</li>
        </ul>
    </div>
</div>
<div class="row">
    <div class="col-md-12 col-lg-12">
        <div class="astuce">
            <i class="fa fa-caret-right" aria-hidden="true"></i> ASTUCES TIME NUTRITION
            <div>
                Ce plat sera un repas parfaitement équilibré pour le dîner.<br>
                Il pourra être réalisé avec de nombreux autres poissons, à choisir selon votre convenance.
            </div>
        </div>

    </div>
</div>