<div class="row">
    <div class="col-md-12 col-lg 12 recettes">
        <div class="col-xs-12 col-sm-6 col-md-4 col-lg-4">
            <h2><?php echo __('TOURTEAU A L’ESTRAGON');?></h2>
            <ul>
                <li><img src="<?php echo $this->getViewFileUrl('images/recettes/cutlery.png'); ?>"> <span class="gray">Pour</span> : 2 personnes</li>
                <li><img src="<?php echo $this->getViewFileUrl('images/recettes/clock.png'); ?>"> <span class="gray">Préparation</span> : 10 min.</li>
                <li><img src="<?php echo $this->getViewFileUrl('images/recettes/oven.png'); ?>"> <span class="gray">Cuisson</span> : 15 min.</li>
            </ul>
            <h3 class="recette-part">Ingrédients</h3>
            <ul class="ingredients">
                <li>2 tourteaux vivants (femelles de préférence)</li>
                <li>2 sachets de cube instantané</li>
                <li>2 cuil. à soupe d'huile d'olive</li>
                <li>2 cuil. à soupe d'huile de colza</li>
                <li>1 cuil. à soupe de vinaigre de cidre</li>
                <li>1 cuil. à café de moutarde à l'estragon</li>
                <li>1 cuil. à soupe d'estragon ciselé</li>
                <li>1 cuil. à soupe de basilic ciselé</li>
                <li>Sel, poivre</li>
            </ul>

        </div>
        <div class="col-xs-12 col-sm-6 col-md-4 col-lg-4">
            <img src="<?php echo $this->getViewFileUrl('images/recettes/tourteau_estragon.jpg'); ?>" alt="tourteau à l'estragon time nutrition">
        </div>
        <div class="col-xs-12 col-sm-12 col-md-4 col-lg-4">
            Le tourteau est un crustacé comme les langoustes, homards, langoustines.<br>
            Mais il en diffère, comme tous les crabes, par son abdomen réduit, sans nageoire caudale, replié sous le corps et appliqué contre lui.<br>
            Le tourteau (appelé aussi "dormeur") est un des crabes les plus connus de l'Atlantique nord.<br>
            Il peut atteindre 30 à 35 cm de largeur et son poids dépasser 4 kilos.<br>
            Sa chair est moins estimée que celle du homard ou de la langouste, mais est néanmoins très fine et très recherchée.
        </div>
    </div>
</div>
<div class="row">
    <div class="col-md-12 col-lg-12 recettes">
        <h3 class="recette-part">Préparation</h3>
        <ul class="preparation">
            <li>Les plonger dans le court bouillon bouillant et compter 15 min. de cuisson à petits bouillons à partir de la reprise de l'ébullition.</li>
            <li>Laisser refroidir dans le court bouillon puis égoutter.</li>
            <li>Détacher la queue et séparer la carapace du reste du corps, ôter la poche abdominale derrière la bouche et les ouïes situées sur les côtés. Casser les pinces à l'aide d'un casse-noix.</li>
            <li>Mettre dans le bol du mixeur tous les éléments de la sauce et mixer pendant 1 min. Réserver dans une saucière.</li>
            <li>Servir le tourteau.</li>
        </ul>
    </div>
</div>
<div class="row">
    <div class="col-md-12 col-lg-12">
        <div class="astuce">
            <i class="fa fa-caret-right" aria-hidden="true"></i> ASTUCES TIME NUTRITION
            <div>
                Nous vous conseillons d’accompagner le tourteau d'une simple salade mélangée, arrosée avec la sauce préparée.<br>
                Petit conseil : il ne faut jamais mettre au réfrigérateur un tourteau cuit car il deviendrait sec et filandreux.
            </div>
        </div>

    </div>
</div>