<div class="row">
    <div class="col-md-12 col-lg 12 recettes">
        <div class="col-xs-12 col-sm-6 col-md-4 col-lg-4">
            <h2><?php echo __('TRUITES AUX AMANDES');?></h2>
            <ul>
                <li><img src="<?php echo $this->getViewFileUrl('images/recettes/cutlery.png'); ?>"> <span class="gray">Pour</span> : 2 personnes</li>
                <li><img src="<?php echo $this->getViewFileUrl('images/recettes/clock.png'); ?>"> <span class="gray">Préparation</span> : 10 min.</li>
                <li><img src="<?php echo $this->getViewFileUrl('images/recettes/oven.png'); ?>"> <span class="gray">Cuisson</span> : 15 min.</li>
            </ul>
            <h3 class="recette-part">Ingrédients</h3>
            <ul class="ingredients">
                <li>4 truites</li>
                <li>1 gousse d'ail</li>
                <li>1 bouquet de persil</li>
                <li>50 g d'amandes effilées</li>
                <li>10 g de beurre</li>
                <li>1 cuil. à soupe de crème fraîche</li>
                <li>Huile d'olive</li>
            </ul>

        </div>
        <div class="col-xs-12 col-sm-6 col-md-4 col-lg-4">
            <img src="<?php echo $this->getViewFileUrl('images/recettes/truite_amandes.jpg'); ?>" alt="truites aux amandes time nutrition">
        </div>
        <div class="col-xs-12 col-sm-12 col-md-4 col-lg-4">
            Le terme truite est un nom désignant plusieurs espèces de poissons carnassiers de la famille des salmonidés (saumon...).<br>
            Les truites vivent dans des eaux claires et vives, certaines atteignent une trentaine de kilogrammes.
        </div>
    </div>
</div>
<div class="row">
    <div class="col-md-12 col-lg-12 recettes">
        <h3 class="recette-part">Préparation</h3>
        <ul class="preparation">
            <li>Éplucher la gousse d'ail et la débarrasser de son germe.</li>
            <li>Plonger le persil et l'ail dans une casserole d'eau bouillante pendant 3 min., puis les égoutter et les mixer.</li>
            <li>Ajouter la crème fraîche et l'huile d'olive, saler, poivrer, verser dans un bol et maintenir au chaud dans un bain marie.</li>
            <li>Dans une poêle anti-adhésive chaude faire dorer les amandes en les remuant constamment. Débarrasser sur une assiette.</li>
            <li>Mettre 1 cuil. à soupe d'huile d'olive et le beurre dans la poêle.</li>
            <li>Saler et poivrer l'intérieur des truites et y glisser ¼ de feuille de laurier et 1 brin de thym par truite.</li>
            <li>Quand l'huile et le beurre sont chauds déposer les truites.</li>
            <li>Faire cuire 2 min. puis les retourner et ôter la peau sur le côté qui vient de cuire.</li>
            <li>Laisser cuire 3 min.</li>
            <li>Retourner à nouveau quelques secondes pour rissoler les côtés sans peau.</li>
            <li>Servir en veillant à disposer le côté peau contre l'assiette.</li>
            <li>Poivrer, saler et parsemer d'amandes.</li>
            <li>Entourer d'un filet de sauce au persil.</li>
            <li>Déguster.</li>
        </ul>
    </div>
</div>
<div class="row">
    <div class="col-md-12 col-lg-12">
        <div class="astuce">
            <i class="fa fa-caret-right" aria-hidden="true"></i> ASTUCES TIME NUTRITION
            <div>
                Nous vous conseillons d’accompagner ce poisson d’un gratin de fenouil.
            </div>
        </div>

    </div>
</div>