<?php
if(isset($_POST['create-customer']) && $_POST['create-customer'] == 1){
    $objectManager = \Magento\Framework\App\ObjectManager::getInstance();
    $hash = $objectManager->get('\Magento\Framework\Encryption\EncryptorInterface');
    $storeManager = $objectManager->get('\Magento\Store\Model\StoreManagerInterface');
    $portfoliocustomer = $objectManager->create('Ntic\PortfolioCustomer\Model\PortfolioCustomer');
    $sessionId = $objectManager->get('\Magento\Customer\Model\Session')->getCustomer()->getId();

    $customerFactory = $objectManager->get('\Magento\Customer\Model\CustomerFactory');
    $websiteId = $storeManager->getWebsite()->getWebsiteId();
    $store = $storeManager->getStore();  // Get Store ID
    $storeId = $store->getStoreId();

    $customer = $customerFactory->create();
    $customer->setWebsiteId($websiteId);
    $customer->setEmail($_POST['email']);
    $customer->setFirstname($_POST['firstname']);
    $customer->setLastname($_POST['name']);
    $customer->setPassword($_POST['password']);
    $customer->setPrefix($_POST['prefix']);
    $customer->setGender($_POST['gender']);
    $customer->setDob($_POST['dob']);
    $customer->save();

    $portfoliocustomer->setCustomerId($customer->getId());
    $portfoliocustomer->setSellerId($sessionId);
    $portfoliocustomer->save();

    $addresss = $objectManager->get('\Magento\Customer\Model\AddressFactory');
    $address = $addresss->create();
    $address->setCustomerId($customer->getId())
        ->setPrefix($_POST['prefix'])
        ->setFirstname($_POST['firstname'])
        ->setLastname($_POST['name'])
        ->setCountryId($_POST['country'])
        ->setPostcode($_POST['zipcode'])
        ->setCity($_POST['city'])
        ->setTelephone($_POST['phone'])
        ->setStreet(array('0'=>$_POST['address1'], '1'=>$_POST['address2']))
        ->setIsDefaultBilling('1')
        ->setIsDefaultShipping('1')
        ->setSaveInAddressBook('1');

    $address->save();


}
?>

<div class="row">
    <div class="col-lg-12">
        <?php //echo 'Bonjour ' .$customer->getName();?>


    </div>
</div>