<div class="row">
    <div class="col-md-12 col-lg 12 recettes">
        <div class="col-xs-12 col-sm-6 col-md-4 col-lg-4">
            <h2><?php echo __('Andouillettes gratinées');?></h2>
            <ul>
                <li><img src="<?php echo $this->getViewFileUrl('images/recettes/cutlery.png'); ?>"> <span class="gray">Pour</span> : 2 personnes</li>
                <li><img src="<?php echo $this->getViewFileUrl('images/recettes/clock.png'); ?>"> <span class="gray">Préparation</span> : 15 min.</li>
                <li><img src="<?php echo $this->getViewFileUrl('images/recettes/oven.png'); ?>"> <span class="gray">Cuisson</span> : 25 min.</li>
            </ul>
            <h3 class="recette-part">Ingrédients</h3>
            <ul class="ingredients">
                <li>2 andouillettes</li>
                <li>Moutarde</li>
                <li>Farine</li>
                <li>2 cuil. à soupe d'huile d'olive</li>
                <li>4 brins de ciboulette ciselée</li>
                <li>2 grosses pommes de terre</li>
                <li>Sel, poivre</li>
            </ul>

        </div>
        <div class="col-xs-12 col-sm-6 col-md-4 col-lg-4">
            <img src="<?php echo $this->getViewFileUrl('images/recettes/andouillettes_gratinees.jpg'); ?>" alt="andouillettes gratinees time nutrition">
        </div>
        <div class="col-xs-12 col-sm-12 col-md-4 col-lg-4">
            L’andouillette est une charcuterie française actuellement élaborée à partir d’éléments du tube digestif du porc.<br>
            Elle doit sa saveur à la matière première, scrupuleusement nettoyée, mais aussi aux aromates, épices, condiments, vins ou alcools dosés selon les recettes, ainsi qu’éventuellement à un enrobant, chapelure, gelée ou saindoux.
        </div>

    </div>
</div>
<div class="row">
    <div class="col-md-12 col-lg-12 recettes">
        <h3 class="recette-part">Préparation</h3>
        <ul class="preparation">
            <li>Cuire les pommes de terre dans une casserole d'eau salée pendant 20 à 25 min.</li>
            <li>Couper les andouillettes en tranches.</li>
            <li>Enduire chaque face de moutarde, fariner légèrement à part égale sur les 2 faces, saler et poivrer.</li>
            <li>Dans une poêle faire chauffer l'huile d'olive et y faire dorer les tranches d'andouillette 2 min. de chaque côté.</li>
            <li>Écraser les pommes de terre à la fourchette, les arroser avec l'huile d'olive et mélanger.</li>
            <li>Répartir les pommes de terre sur le fond de 2 assiettes chaudes.</li>
            <li>Déposer les tranches d'andouillette sur le lit de pommes de terre.</li>
            <li>Parsemer de ciboulette ciselée, saler et poivrer.</li>
        </ul>
    </div>
</div>
<div class="row">
    <div class="col-md-12 col-lg-12">
        <div class="astuce">
            <i class="fa fa-caret-right" aria-hidden="true"></i> ASTUCES TIME NUTRITION
            <div>
                Pour plus de goût, sélectionnez une moutarde forte de Dijon ou de Charroux, toutes riches en anti-oxydants.
            </div>
        </div>

    </div>
</div>