<div class="row">
    <div class="col-md-12 col-lg 12 recettes">
        <div class="col-xs-12 col-sm-6 col-md-4 col-lg-4">
            <h2><?php echo __('Boeuf aux Epices');?></h2>
            <ul>
                <li><img src="<?php echo $this->getViewFileUrl('images/recettes/cutlery.png'); ?>"> <span class="gray">Pour</span> : 4 personnes</li>
                <li><img src="<?php echo $this->getViewFileUrl('images/recettes/clock.png'); ?>"> <span class="gray">Préparation</span> : 20 min.</li>
                <li><img src="<?php echo $this->getViewFileUrl('images/recettes/oven.png'); ?>"> <span class="gray">Cuisson</span> : 1h15.</li>
            </ul>
            <h3 class="recette-part">Ingrédients</h3>
            <ul class="ingredients">
                <li>1 kg de paleron</li>
                <li>½ cuil. à café de cumin moulu</li>
                <li>1 cuil. à café de graines de coriandre</li>
                <li>½cuil. à café de graines de cardamome</li>
                <li>2 cuil. à café de piment en poudre</li>
                <li>1 cuil. à café de curcuma moulu</li>
                <li>2 cuil. à soupe d'huile d'olive</li>
                <li>3 oignons émincés finement</li>
                <li>3 gousses d'ail pressées sans germe</li>
                <li>3 cuil. à café de gingembre frais râpé</li>
                <li>1 bâton de cannelle</li>
                <li>8 cl. de vinaigre balsamique</li>
                <li>1 dl 25 de bouillon de bœuf</li>
                <li>1 cuil. à café de sucre</li>
                <li>Sel, poivre</li>
                <li>1 cuil. à café de graines de moutarde moulu</li>
            </ul>

        </div>
        <div class="col-xs-12 col-sm-6 col-md-4 col-lg-4">
            <img src="<?php echo $this->getViewFileUrl('images/recettes/boeuf_epices.jpg'); ?>" alt="boeuf aux épices time nutrition">
        </div>
        <div class="col-xs-12 col-sm-12 col-md-4 col-lg-4">
            La qualité du mélange d’épices (curry en poudre) est vraiment importante pour la réussite de ce plat sympa qui change des bourguignons traditionnels.<br>
            En Inde, chaque famille utilise et fabrique son propre curry. La composition du curry peut changer selon les utilisations (viandes, poissons, légumes...).
        </div>

    </div>
</div>
<div class="row">
    <div class="col-md-12 col-lg-12 recettes">
        <h3 class="recette-part">Préparation</h3>
        <ul class="preparation">
            <li>Couper la viande en cubes de 3 cm.</li>
            <li>Mixer finement le cumin, la coriandre, la cardamome, le piment, le curcuma et la moutarde.</li>
            <li>Faire chauffer l'huile d'olive dans une cocotte et y faire rissoler la viande sur toutes les faces, réserver dans un saladier.</li>
            <li>Mettre alors dans la cocotte, l'oignon émincé, le gingembre, l'ail pressé et la cannelle.</li>
            <li>Faire cuire à feu doux et faire fondre l'oignon en remuant.</li>
            <li>Quand l'oignon devient transparent ajouter les épices et la viande, bien mélanger pour enrober la viande, arroser avec le bouillon et le vinaigre, saupoudrer de sucre, saler et poivrer.</li>
            <li>Couvrir et laisser mijoter à feu doux pendant 1 h 30.</li>
            <li>Enlever le bâton de cannelle.</li>
        </ul>
    </div>
</div>
<div class="row">
    <div class="col-md-12 col-lg-12">
        <div class="astuce">
            <i class="fa fa-caret-right" aria-hidden="true"></i> ASTUCES TIME NUTRITION
            <div>
                Nous vous recommandons de servir ce plat avec du riz pilaf.
            </div>
        </div>

    </div>
</div>