<div class="row">
    <div class="col-md-12 col-lg 12 recettes">
        <div class="col-xs-12 col-sm-6 col-md-4 col-lg-4">
            <h2><?php echo __('Canard aux olives');?></h2>
            <ul>
                <li><img src="<?php echo $this->getViewFileUrl('images/recettes/cutlery.png'); ?>"> <span class="gray">Pour</span> : 2 personnes</li>
                <li><img src="<?php echo $this->getViewFileUrl('images/recettes/clock.png'); ?>"> <span class="gray">Préparation</span> : 15 min.(à préparer à l'avance)</li>
                <li><img src="<?php echo $this->getViewFileUrl('images/recettes/oven.png'); ?>"> <span class="gray">Cuisson</span> : 20 min.</li> <span class="gray">Repos</span> : 10 min.</li>
            </ul>
            <h3 class="recette-part">Ingrédients</h3>
            <ul class="ingredients">
                <li>canard Col Vert</li>
                <li>16 olives vertes</li>
                <li>½ verre d'eau</li>
                <li>Sel, poivre</li>
                <li>Beurre</li>
                <span>Pour le laquage :</span>
                <li>2 cuil. à soupe de miel d'acacia</li>
                <li>2 cuil. à soupe de grains de coriandre concassés</li>
                <li>Poivre</li>
                <li>1 gousse d'ail pressée</li>
                <li>1 cuil. à soupe de vin de xérès</li>
                <li>2 cuil. à soupe de sauce soja japonaise</li>
            </ul>

        </div>
        <div class="col-xs-12 col-sm-6 col-md-4 col-lg-4">
            <img src="<?php echo $this->getViewFileUrl('images/recettes/canard_olives.jpg'); ?>" alt="canard olives time nutrition">
        </div>
        <div class="col-xs-12 col-sm-6 col-md-4 col-lg-4">
            Avec la datte, la figue et le raisin, l’olive était le fruit le plus important de l’alimentation des anciennes civilisations du bassin
            méditerranéen, et sa culture remonterait à au moins 4 000 ans avant notre ère. C’est une excellente source de fibres alimentaires.
        </div>

    </div>
</div>
<div class="row">
    <div class="col-md-12 col-lg-12 recettes">
        <h3 class="recette-part">Préparation</h3>
        <ul class="preparation">
            <li>Préchauffer le four à 210° (therm. 7)</li>
            <li>Dans un bol préparer le laquage en mélangeant : 2 cuil. à soupe de miel d'acacia, 2 cuil. à soupe de grains de coriandre concassés, 1 gousse d'ail pressée, 1 cuil. à soupe de vin de xérès, 2 cuil. à soupe de sauce soja japonaise, poivre.</li>
            <li>Vider le canard, le saler et le poivrer à l'intérieur et à l'extérieur puis le ficeler.</li>
            <li>Badigeonner largement le canard avec le laquage et le poser au centre d'un plat à four.</li>
            <li>Disposer les olives dans le plat autour du canard.</li>
            <li>Enfourner pendant 20 min à 210° (therm. 7)</li>
            <li>Sortir du four, retirer les cuisses du canard. Découper ensuite les aiguillettes et les servir entourées d’olives et nappées de sauce.</li>
            <li>Les cuisses n'étant pas assez cuites les remettre à cuire 20 à 30 min.</li>
        </ul>
    </div>
</div>
<div class="row">
    <div class="col-md-12 col-lg-12">
        <div class="astuce">
            <i class="fa fa-caret-right" aria-hidden="true"></i> ASTUCES TIME NUTRITION
            <div>
                Nous vous conseillons d’accompagner ce plat de pommes de terre sautées ou de purée.
            </div>
        </div>

    </div>
</div>