<div class="row">
    <div class="col-md-12 col-lg 12 recettes">
        <div class="col-xs-12 col-sm-6 col-md-4 col-lg-4">
            <h2><?php echo __('Cannellonis à l\'italienne');?></h2>
            <ul>
                <li><img src="<?php echo $this->getViewFileUrl('images/recettes/cutlery.png'); ?>"> <span class="gray">Pour</span> : 2 personnes</li>
                <li><img src="<?php echo $this->getViewFileUrl('images/recettes/clock.png'); ?>"> <span class="gray">Préparation</span> : 30 min.</li>
                <li><img src="<?php echo $this->getViewFileUrl('images/recettes/oven.png'); ?>"> <span class="gray">Cuisson</span> : 40 min. environ</li>
            </ul>
            <h3 class="recette-part">Ingrédients</h3>
            <ul class="ingredients">
                <li>18 carrés de pâte sèche à cannellonis</li>
                <span>Farce :</span>
                <li>4 échalotes</li>
                <li>2 gousses d'ail</li>
                <li>3 cuil. à soupe d'huile d'olive</li>
                <li>400 g de steak haché</li>
                <li>8 cuil. à soupe de concentré de tomates</li>
                <li>3 cuil. à soupe de basilic ciselé</li>
                <li>5 dl de vin rouge</li>
                <li>Thym, laurier</li>
                <li>Sel, poivre</li>
                <li>Piment de Cayenne</li>
                <span>Sauce béchamel :</span>
                <li>3 cuil. à soupe de beurre</li>
                <li>3 cuil. à soupe de farine</li>
                <li>4,5 dl de lait</li>
                <li>Muscade</li>
                <li>Sel, poivre blanc</li>
                <span>Gratin :</span>
                <li>3 cuil. à soupe de parmesan râpé</li>
                <li>15 g de beurre</li>
            </ul>

        </div>
        <div class="col-xs-12 col-sm-6 col-md-4 col-lg-4">
            <img src="<?php echo $this->getViewFileUrl('images/recettes/cannellonis_italienne.jpg'); ?>" alt="cannellonis à l'italienne time nutrition">
        </div>
        <div class="col-xs-12 col-sm-12 col-md-4 col-lg-4">
            Pour ceux qui aiment les plats de pâtes copieux, voici une recette de cannellonis à la viande. Les cannellonis, sont des pâtes à farcir, d'origine italienne.<br>
            Elles se présentent sous forme de tubes de 7 à 10 cm de long et de 2 à 3 cm de diamètre.
        </div>

    </div>
</div>
<div class="row">
    <div class="col-md-12 col-lg-12 recettes">
        <h3 class="recette-part">Préparation</h3>
        <ul class="preparation">
            <li>Éplucher et émincer finement les échalotes.</li>
            <li>Dans une poêle faire chauffer l'huile d'olive et y faire fondre les échalotes à feu moyen.</li>
            <li>Éplucher les gousses d'ail, ôter les germes et les presser.</li>
            <li>Quand les échalotes sont transparentes ajouter la viande et l'ail et faire revenir à feu vif. Bien mélanger afin de saisir uniformément toute la viande.</li>
            <li>Arroser avec le vin et poursuivre la cuisson jusqu'à évaporation complète (3 à 4 min.)</li>
            <li>Ajouter le concentré de tomates, le thym et le laurier, saler, poivrer et cuire à feu vif environ 20 min.</li>
            <li>Arrêter la cuisson et incorporer 2 cuil. à soupe de basilic ciselé et 2 traits de piment de Cayenne.</li>
            <span>Pendant la cuisson de la viande :</span>
            <li>Faire bouillir une grande casserole d'eau, saler.</li>
            <li>Plonger les carrés de pâte. Veiller à ce qu'ils ne se collent pas les uns et les autres. Faire cuire et sortir de l'eau à l'aide d'une écumoire. Les poser à plat sur un linge propre.</li>
            <li>Déposer alors une cuil. ½ de farce au centre de chaque carré et les rouler sur eux-mêmes.</li>
            <li>Disposer les cannellonis côte à côte dans un plat à four en plaçant le raccord de pâte contre le fond du plat.</li>
            <li>Recouvrir de sauce béchamel, saupoudrer de parmesan et parsemer de petites noisettes de beurre.</li>
            <li>Faire gratiner sous le grill du four 7 à 8 min.</li>
            <li>Parsemer de basilic.</li>
            <li>Déguster.</li>
        </ul>
    </div>
</div>
<div class="row">
    <div class="col-md-12 col-lg-12">
        <div class="astuce">
            <i class="fa fa-caret-right" aria-hidden="true"></i> ASTUCES TIME NUTRITION
            <div>
                Pour encore plus de plaisir, réalisez vous-même votre pâte à cannellonis. Pour cela vous avez besoin de 250 gr de farine, 1 œuf, 1 demi-cuillerée à café de sel, de l’eau.<br>
                Commencez par mélanger la farine avec le sel dans un saladier. Cassez l'œuf dans un bol et battez-le en omelette puis ajoutez-le à la farine.<br>
                Mélangez la farine et l'œuf battu en ajoutant suffisamment d'eau pour obtenir une pâte lisse qui pourra s'étaler au rouleau.<br>
                Faites une boule avec la pâte et enveloppez-la dans un chiffon humide. Laissez-la reposer pendant une heure dans un endroit frais.
            </div>
        </div>

    </div>
</div>