<div class="row">
    <div class="col-md-12 col-lg 12 recettes">
        <div class="col-xs-12 col-sm-6 col-md-4 col-lg-4">
            <h2><?php echo __('Côte de boeuf grillée');?></h2>
            <ul>
                <li><img src="<?php echo $this->getViewFileUrl('images/recettes/cutlery.png'); ?>"> <span class="gray">Pour</span> : 3 personnes</li>
                <li><img src="<?php echo $this->getViewFileUrl('images/recettes/clock.png'); ?>"> <span class="gray">Préparation</span> : 10 min.</li>
                <li><img src="<?php echo $this->getViewFileUrl('images/recettes/oven.png'); ?>"> <span class="gray">Marinade</span> : 2h.</li> <span class="gray">Cuisson</span> : 25 min.</li>
            </ul>
            <h3 class="recette-part">Ingrédients</h3>
            <ul class="ingredients">
                <li>1 côte de bœuf de 1 kg</li>
                <li>1 cuil. à café de fleur de thym</li>
                <li>1 branche de romarin frais</li>
                <li>5 cuil. à soupe d'huile d'olive</li>
                <li>2 feuilles de laurier</li>
                <li>2 cuil. à soupe de gros sel</li>
                <li>12 tomates cerise</li>
                <li>12 petits oignons blancs</li>
                <li>1 poivron vert</li>
                <li>3 grosses pommes de terre</li>
                <li>3 noix de beurre</li>
            </ul>

        </div>
        <div class="col-xs-12 col-sm-6 col-md-4 col-lg-4">
            <img src="<?php echo $this->getViewFileUrl('images/recettes/cote_boeuf.jpg'); ?>" alt="cote de boeuf grillée time nutrition">
        </div>
        <div class="col-xs-12 col-sm-12 col-md-4 col-lg-4">
            Le bœuf est une viande très nutritive grâce à ses protéines de haute qualité et à ses micronutriments.<br>
            Il faut toutefois la choisir avec soin : s’assurer d’une provenance la plus proche possible de l’élevage en liberté (elle contiendra alors moins de gras saturé, néfaste pour la santé en trop grande quantité).
        </div>

    </div>
</div>
<div class="row">
    <div class="col-md-12 col-lg-12 recettes">
        <h3 class="recette-part">Préparation</h3>
        <ul class="preparation">
            <li>Dans un plat creux, déposer la côte de bœuf, la saupoudrer avec les feuilles de romarin ciselées, le thym et les feuilles de laurier émiettées.</li>
            <li>Arroser de 3 cuil. à soupe d'huile d'olive et laisser mariner la côte de bœuf pendant 1 h. en la retournant régulièrement.</li>
            <li>Allumer le barbecue.</li>
            <li>Laver les pommes de terre, les sécher et les envelopper de papier d'aluminium. Les déposer sur le bord de la grille.</li>
            <li>Éplucher les petits oignons et le poivron.</li>
            <li>Épépiner le poivron et découper 12 petits carrés.</li>
            <li>Quand le barbecue est prêt, quand les braises commencent à blanchir, déposer la côte au centre de la grille très chaude.</li>
            <li>Cuire 12 min environ.</li>
            <li>Retourner les pommes de terre.</li>
            <li>Pendant ce temps, préparer des brochettes de légumes en piquant : 1 oignon, 1 carré de poivron, 1 tomate, 1 oignon, 1 carré de poivron, 1 tomate, ... Et arroser d'un filet d'huile.</li>
            <li>Retourner la côte de bœuf à l'aide d'une pince, sans la piquer.</li>
            <li>Ajouter les brochettes de légumes sur le barbecue et cuire en retournant les brochettes d'un quart de tour toutes les 3 min.</li>
            <li>Poser la côte de bœuf sur un papier d'aluminium, l'enduire de gros sel et de poivre.</li>
            <li>L'enfermer dans le papier d'aluminium pendant 7 à 8 min. jusqu’à ce que le sel fonde.</li>
            <li>La découper, entailler les pommes de terre et glisser une noix de beurre à l'intérieur.</li>
            <li>Saupoudrer de fines herbes, de grains de sel et de poivre concassé.</li>
        </ul>
    </div>
</div>
<div class="row">
    <div class="col-md-12 col-lg-12">
        <div class="astuce">
            <i class="fa fa-caret-right" aria-hidden="true"></i> ASTUCES TIME NUTRITION
            <div>
                Pour un plaisir maximum, choisissez la pomme de terre hollandaise, sa chair est farineuse et sa peau épaisse.
            </div>
        </div>

    </div>
</div>