<div class="row">
    <div class="col-md-12 col-lg 12 recettes">
        <div class="col-xs-12 col-sm-6 col-md-4 col-lg-4">
            <h2><?php echo __('épaule d\'agneau aux aromates');?></h2>
            <ul>
                <li><img src="<?php echo $this->getViewFileUrl('images/recettes/cutlery.png'); ?>"> <span class="gray">Pour</span> : 6 personnes</li>
                <li><img src="<?php echo $this->getViewFileUrl('images/recettes/clock.png'); ?>"> <span class="gray">Préparation</span> : 45 min.</li>
                <li><img src="<?php echo $this->getViewFileUrl('images/recettes/oven.png'); ?>"> <span class="gray">Cuisson</span> : 60 min.</li>
            </ul>
            <h3 class="recette-part">Ingrédients</h3>
            <ul class="ingredients">
                <li>1 épaule d'agneau de 1 kg 500</li>
                <li>1 gousse d'ail</li>
                <li>2 carottes</li>
                <li>2 branches de céleri</li>
                <li>1 poireau</li>
                <li>1 oignon</li>
                <li>1 poivron rouge</li>
                <span>Pour la marinade :</span>
                <li>2 cuil. à soupe d'huile d'olive</li>
                <li>1 cuil. à café de feuilles de thym</li>
                <li>½ cuil. à café de feuilles de sauge sèches, émiettées</li>
                <li>1 cuil. à soupe de paprika</li>
                <li>5 feuilles de romarin</li>
                <li>Sel</li>
            </ul>

        </div>
        <div class="col-xs-12 col-sm-6 col-md-4 col-lg-4">
            <img src="<?php echo $this->getViewFileUrl('images/recettes/epaule_agneau_aromate.jpg'); ?>" alt="épaule d'agneau aux aromates time nutrition">
        </div>
        <div class="col-xs-12 col-sm-12 col-md-4 col-lg-4">
            L’agneau est une viande riche en protéines, en vitamines et en minéraux. Elle est nutritive.<br>
            Mais c’est une viande grasse, même si l’on retire le gras apparent. Près de la moitié de ce gras est de type monoinsaturé et polyinsaturé, c’est-à-dire bon pour la santé.
        </div>

    </div>
</div>
<div class="row">
    <div class="col-md-12 col-lg-12 recettes">
        <h3 class="recette-part">Préparation</h3>
        <ul class="preparation">
            <li>Préchauffer le four à 220° (therm. 7).</li>
            <li>Epépiner le poivron et de couper en lamelles.</li>
            <li>Dans une poêle antiadhésive, faire chauffer 1 cuil. à soupe d'huile d'olive avec 1 noisette de beurre et y déposer les lanières de poivron.</li>
            <li>Saler légèrement couvrir et cuire à feu doux pendant 60 min.</li>
            <li>Éplucher une gousse d'ail, la détailler en 6 petits éclats.</li>
            <li>Faire 6 incisions profondes dans l’épaule à l'aide d'un couteau pointu et y introduire les éclats d'ail.</li>
            <li>Dans un bol verser l'huile d'olive, y ajouter le thym, la sauge et le paprika. Mélanger et enduire l'épaule. Saler et placer l'épaule dans un plat allant au four.</li>
            <li>Verser 25 cl. d'eau très chaude dans le plat et enfourner.</li>
            <span>Pendant la cuisson :</span>
            <li>Éplucher les carottes, le céleri, le poireau et l'oignon. Les hacher finement.</li>
            <li>Après 20 min. de cuisson de l'épaule, ajouter le hachis de légumes et remettre au four pendant 30 min.</li>

        </ul>
    </div>
</div>
<div class="row">
    <div class="col-md-12 col-lg-12">
        <div class="astuce">
            <i class="fa fa-caret-right" aria-hidden="true"></i> ASTUCES TIME NUTRITION
            <div>
                Pour un plat parfaitement équilibré, servez avec une association haricots verts et flageolets.
            </div>
        </div>

    </div>
</div>