<div class="row">
    <div class="col-md-12 col-lg 12 recettes">
        <div class="col-xs-12 col-sm-6 col-md-4 col-lg-4">
            <h2><?php echo __('épaule d\'agneau croustillante à la pistache');?></h2>
            <ul>
                <li><img src="<?php echo $this->getViewFileUrl('images/recettes/cutlery.png'); ?>"> <span class="gray">Pour</span> : 4 personnes</li>
                <li><img src="<?php echo $this->getViewFileUrl('images/recettes/clock.png'); ?>"> <span class="gray">Préparation</span> : 20 min.</li>
                <li><img src="<?php echo $this->getViewFileUrl('images/recettes/oven.png'); ?>"> <span class="gray">Cuisson</span> : 1 h 10 environ</li>
            </ul>
            <h3 class="recette-part">Ingrédients</h3>
            <ul class="ingredients">
                <li>1 kg d'épaule d'agneau désossée</li>
                <li>100 g de lard frais</li>
                <li>2 cuil. à soupe d'huile d'olive</li>
                <li>1 bouquet de persil</li>
                <li>200 g de lard fumé en morceaux</li>
                <li>Sel, poivre</li>
                <span>Farce :</span>
                <li>100 g de pistaches décortiquées</li>
                <li>150 g de filet de porc</li>
                <li>2 oignons</li>
                <li>1 carotte</li>
                <li>¼ de l. de bouillon instantané</li>
            </ul>

        </div>
        <div class="col-xs-12 col-sm-6 col-md-4 col-lg-4">
            <img src="<?php echo $this->getViewFileUrl('images/recettes/epaule_agneau_pistache.jpg'); ?>" alt="épaule d'agneau croustillante à la pistache time nutrition">
        </div>
        <div class="col-xs-12 col-sm-12 col-md-4 col-lg-4">
            La pistache est riche en antioxydants et c’est une bonne source de fibres alimentaires. La chair doit être d’un beau vert frais :<br>
            c’est une indication que les pistaches n’ont pas été rôties à des températures trop élevées, ce qui nuit à leur saveur.
        </div>

    </div>
</div>
<div class="row">
    <div class="col-md-12 col-lg-12 recettes">
        <h3 class="recette-part">Préparation</h3>
        <ul class="preparation">
            <li>Préparer la farce : hacher ensemble tous les éléments de la farce au hachoir à viande et bien mélanger</li>
            <li>Remplacer l'os de l’épaule d’agneau par la farce.</li>
            <li>Rouler l’épaule et la ficeler avec soin.</li>
            <li>Dans une cocotte, faire chauffer l'huile d'olive à feu moyen.</li>
            <li>Faire fondre les oignons émincés, quand ils deviennent transparents les réserver et les remplacer par le lard fumé en morceaux. Quand ils sont rissolés les réserver avec les oignons.</li>
            <li>Faire dorer l'épaule sur toutes ses faces à feu vif.</li>
            <li>Baisser le feu, remettre les oignons et les lardons dans la cocotte ainsi que la carotte en rondelles, saler légèrement et poivrer.</li>
            <li>Mouiller avec le vin blanc et le bouillon.</li>
            <li>Couvrir et cuire à feu moyen 30 min.</li>
            <li>Puis découvrir et cuire encore 30 min.</li>
            <li>Découper en tranches et servir.</li>

        </ul>
    </div>
</div>
<div class="row">
    <div class="col-md-12 col-lg-12">
        <div class="astuce">
            <i class="fa fa-caret-right" aria-hidden="true"></i> ASTUCES TIME NUTRITION
            <div>
                Petit conseil : pensez à faire désosser l'épaule par votre boucher.<br>
                Vous pouvez accompagner les tranches d’agneau de quelques pommes de terre sautées et d’une cuillère à soupe de pistaches concassées.
            </div>
        </div>

    </div>
</div>