<div class="row">
    <div class="col-md-12 col-lg 12 recettes">
        <div class="col-xs-12 col-sm-6 col-md-4 col-lg-4">
            <h2><?php echo __('escalopes de veau napolitaines');?></h2>
            <ul>
                <li><img src="<?php echo $this->getViewFileUrl('images/recettes/cutlery.png'); ?>"> <span class="gray">Pour</span> : 2 personnes</li>
                <li><img src="<?php echo $this->getViewFileUrl('images/recettes/clock.png'); ?>"> <span class="gray">Préparation</span> : 15 min.</li>
                <li><img src="<?php echo $this->getViewFileUrl('images/recettes/oven.png'); ?>"> <span class="gray">Cuisson</span> : 35 min.</li>
            </ul>
            <h3 class="recette-part">Ingrédients</h3>
            <ul class="ingredients">
                <li>2 escalopes de minimum 200 g chacune</li>
                <li>2 cuil. à soupe d'huile d'olive</li>
                <li>1 noisette de beurre</li>
                <li>250 g de tomates</li>
                <li>½ cuil. à café de sucre en poudre</li>
                <li>1 petite botte de sauge</li>
                <li>1 échalote</li>
                <li>Sel, poivre</li>
            </ul>

        </div>
        <div class="col-xs-12 col-sm-6 col-md-4 col-lg-4">
            <img src="<?php echo $this->getViewFileUrl('images/recettes/escalopes_veau_napolitaine.jpg'); ?>" alt="escalopes de veau napolitaines time nutrition">
        </div>
        <div class="col-xs-12 col-sm-12 col-md-4 col-lg-4">
            Une escalope est une mince tranche de viande (généralement blanche - veau, porc ou volaille -) ou de poisson préparée.<br>
            Une escalope de veau peut être découpée dans le quasi, la noix, la sous-noix, la noix pâtissière ou l'épaule.
        </div>

    </div>
</div>
<div class="row">
    <div class="col-md-12 col-lg-12 recettes">
        <h3 class="recette-part">Préparation</h3>
        <ul class="preparation">
            <li>Laver les tomates et les couper en tranches.</li>
            <li>Dans une sauteuse faire chauffer 1 cuil. à soupe d'huile d'olive et faire fondre l'échalote.</li>
            <li>Dès que l'échalote est transparente ajouter les quartiers de tomates, le sucre, la botte de sauge, du sel et du poivre.</li>
            <li>Laisser mijoter à feu doux pendant 20 min. environ jusqu'à ce que le coulis de tomate soit onctueux.</li>
            <li>Mixer et passer au travers d'un chinois afin d’éliminer les pépins et les peaux. Réserver au chaud.</li>
            <li>Dans une poêle, faire chauffer le beurre et 1 cuil. d'huile d'olive à feu vif.</li>
            <li>Assaisonner les escalopes de sel et de poivre, les saisir dans la poêle, 1 min de chaque côté.</li>
            <li>Baisser le feu puis laisser cuire à feu doux encore 4 min environ, de chaque côté, suivant l'épaisseur.</li>
            <li>Napper les assiettes de coulis, déposer les escalopes en leur centre et parsemer les assiettes avec le reste de la sauge ciselée.</li>
        </ul>
    </div>
</div>
<div class="row">
    <div class="col-md-12 col-lg-12">
        <div class="astuce">
            <i class="fa fa-caret-right" aria-hidden="true"></i> ASTUCES TIME NUTRITION
            <div>
                Vous pouvez accompagner ces escalopes de tagliatelles fraîches ou de petit pois (pour encore plus de goût, réserver quelques feuilles de sauge, les ciseler et les rajouter au petit pois lors de leur réchauffage).
            </div>
        </div>

    </div>
</div>