<div class="row">
    <div class="col-md-12 col-lg 12 recettes">
        <div class="col-xs-12 col-sm-6 col-md-4 col-lg-4">
            <h2><?php echo __('Gigot d\'agneau aux herbes');?></h2>
            <ul>
                <li><img src="<?php echo $this->getViewFileUrl('images/recettes/cutlery.png'); ?>"> <span class="gray">Pour</span> : 4 personnes</li>
                <li><img src="<?php echo $this->getViewFileUrl('images/recettes/clock.png'); ?>"> <span class="gray">Préparation</span> : 40 min.</li>
                <li><img src="<?php echo $this->getViewFileUrl('images/recettes/oven.png'); ?>"> <span class="gray">Cuisson</span> : 45 min.</li>
            </ul>
            <h3 class="recette-part">Ingrédients</h3>
            <ul class="ingredients">
                <li>1 gigot d'agneau désossé</li>
                <li>4 cuil. à soupe d'huile d'olive</li>
                <li>1 oignon</li>
                <li>2 brins de thym</li>
                <li>2 feuilles de laurier</li>
                <li>Sel, poivre</li>
                <span>Croûte :</span>
                <li>80 g de champignons de Paris</li>
                <li>100 g de mie de pain</li>
                <li>2 blancs d'œufs</li>
                <li>1 cuil. à soupe de crème fraîche</li>
                <li>3 gousses d'ail</li>
                <li>3 cuil. à soupe d'estragon</li>
                <li>2 cuil. à soupe de persil</li>
                <li>1 cuil. à soupe de cerfeuil</li>
                <li>1 verre de vin blanc sec</li>
                <li>Muscade</li>
            </ul>

        </div>
        <div class="col-xs-12 col-sm-6 col-md-4 col-lg-4">
            <img src="<?php echo $this->getViewFileUrl('images/recettes/gigot_agneau_herbes.jpg'); ?>" alt="gigot d'agneau aux herbes time nutrition">
        </div>
        <div class="col-xs-12 col-sm-12 col-md-4 col-lg-4">
            Le gigot est la cuisse ou patte arrière de l'agneau.<br>
            C’est un morceau de viande très tendre.
        </div>

    </div>
</div>
<div class="row">
    <div class="col-md-12 col-lg-12 recettes">
        <h3 class="recette-part">Préparation</h3>
        <ul class="preparation">
            <li>Dans une cocotte faire chauffer l'huile d'olive y faire dorer le gigot désossé sur toute ses faces.</li>
            <li>Saler, poivrer.</li>
            <li>Préchauffer le four à 210° (therm. 7)</li>
            <li>Déposer le gigot dans un plat à four avec l'oignon émincé, le thym et le laurier.</li>
            <li>Enfourner le gigot pendant 20 min.</li>
            <span>Préparation de la croûte :</span>
            <li>Hacher les champignons.</li>
            <li>Dans un saladier, mélanger le blanc d'œuf, la crème, la mie de pain, les champignons, les fines herbes ciselées, la muscade et l'ail, saler, poivrer.</li>
            <li>Mélanger intimement le tout.</li>
            <span>Après 20 min. de cuisson :</span>
            <li>Sortir le gigot du four.</li>
            <li>Étaler à l'aide d'une spatule la croûte de fines herbes sur les faces du gigot.</li>
            <li>Remettre le gigot au four pendant 20 min. à 180° (therm. 6).</li>
            <li>Sortir le gigot du four, le sortir du plat et le couvrir d'un papier d'aluminium.</li>
            <li>Poser le plat de cuisson sur feu vif et verser 2 verres d'eau et 1 verre de vin blanc sec, pendant 5 min.</li>
            <li>Pendant ce temps, découper le gigot en tranches et les disposer sur un plat chaud.</li>
            <li>Verser la sauce dans une saucière.</li>
            <li>Servir.</li>
        </ul>
    </div>
</div>
<div class="row">
    <div class="col-md-12 col-lg-12">
        <div class="astuce">
            <i class="fa fa-caret-right" aria-hidden="true"></i> ASTUCES TIME NUTRITION
            <div>
                Choisissez un gigot d'agneau de lait de préférence et faites le désosser par votre boucher.<br>
                Ce plat s’accompagnera parfaitement avec d’un duo d’haricots blancs et verts.
            </div>
        </div>

    </div>
</div>