<div class="row">
    <div class="col-md-12 col-lg 12 recettes">
        <div class="col-xs-12 col-sm-6 col-md-4 col-lg-4">
            <h2><?php echo __('Grenadins de veau façon rossini');?></h2>
            <ul>
                <li><img src="<?php echo $this->getViewFileUrl('images/recettes/cutlery.png'); ?>"> <span class="gray">Pour</span> : 6 personnes</li>
                <li><img src="<?php echo $this->getViewFileUrl('images/recettes/clock.png'); ?>"> <span class="gray">Préparation</span> : 15 min.</li>
                <li><img src="<?php echo $this->getViewFileUrl('images/recettes/oven.png'); ?>"> <span class="gray">Cuisson</span> : 17 min.</li>
            </ul>
            <h3 class="recette-part">Ingrédients</h3>
            <ul class="ingredients">
                <li>6 grenadins de veau de 200 g chacun</li>
                <li>6 tranches de foie gras mi-cuit de 80 g chacune</li>
                <li>2 cuil. à soupe d'huile d'olive</li>
                <li>20 cl. de beurre</li>
                <li>1 dl. de madère</li>
                <li>Sel, poivre</li>
            </ul>

        </div>
        <div class="col-xs-12 col-sm-6 col-md-4 col-lg-4">
            <img src="<?php echo $this->getViewFileUrl('images/recettes/grenadins_veau_rossini.jpg'); ?>" alt="grenadins de veau façon rossini time nutrition">
        </div>
        <div class="col-xs-12 col-sm-12 col-md-4 col-lg-4">
            Le grenadin est un petit médaillon de filet de veau piqué ou non de lard. « Rossini » car inventé par le célèbre musicien.<br>
            C’est un accord exceptionnel entre viande, foie gras et madère (auquel on peut rajouter un peu de truffe !).
        </div>

    </div>
</div>
<div class="row">
    <div class="col-md-12 col-lg-12 recettes">
        <h3 class="recette-part">Préparation</h3>
        <ul class="preparation">
            <li>Dans une poêle, faire chauffer l'huile et le beurre à feu vif</li>
            <li>Saisir les grenadins 3 min. de chaque côté.</li>
            <li>Baisser le feu et cuire 5 min. de chaque côté, saler, poivrer.</li>
            <li>Déposer les grenadins sur un plat et réserver au chaud.</li>
            <li>Déglacer la poêle avec le madère à feu vif pendant 1 min.</li>
            <li>Napper le plat de grenadins avec cette sauce.</li>
            <li>Déposer une tranche de foie gras sur chaque grenadin.</li>
        </ul>
    </div>
</div>
<div class="row">
    <div class="col-md-12 col-lg-12">
        <div class="astuce">
            <i class="fa fa-caret-right" aria-hidden="true"></i> ASTUCES TIME NUTRITION
            <div>
                Pour ce qui le désire vous pouvez flamber les grenadins au Cognac à la fin de leur cuisson.<br>
                Nous vous conseillons d’accompagner les grenadins de girolles, voire de miettes de truffe !
            </div>
        </div>

    </div>
</div>