<div class="row">
    <div class="col-md-12 col-lg 12 recettes">
        <div class="col-xs-12 col-sm-6 col-md-4 col-lg-4">
            <h2><?php echo __('hachis parmentier revisité');?></h2>
            <ul>
                <li><img src="<?php echo $this->getViewFileUrl('images/recettes/cutlery.png'); ?>"> <span class="gray">Pour</span> : 2 personnes</li>
                <li><img src="<?php echo $this->getViewFileUrl('images/recettes/clock.png'); ?>"> <span class="gray">Préparation</span> : 30 min.</li>
                <li><img src="<?php echo $this->getViewFileUrl('images/recettes/oven.png'); ?>"> <span class="gray">Cuisson</span> : 1h 25 min.</li>
            </ul>
            <h3 class="recette-part">Ingrédients</h3>
            <ul class="ingredients">
                <li>400 g de noix de veau en morceau</li>
                <li>1 oignon</li>
                <li>1 poivron</li>
                <li>1 carotte</li>
                <li>6 feuilles de sauge</li>
                <li>1 gousse d'ail</li>
                <li>8 pommes de terre</li>
                <li>10 cl de jus de veau</li>
                <li>½ verre de vin blanc</li>
                <li>2 cuil. à soupe d'huile d'olive</li>
                <li>2 tomates</li>
                <li>1 verre de lait</li>
                <li>50 g de beurre</li>
                <li>chapelure</li>
            </ul>

        </div>
        <div class="col-xs-12 col-sm-6 col-md-4 col-lg-4">
            <img src="<?php echo $this->getViewFileUrl('images/recettes/hachis_parmentier.jpg'); ?>" alt="hachis parmentier revisité time nutrition">
        </div>
        <div class="col-xs-12 col-sm-12 col-md-4 col-lg-4">
            Plat familial traditionnel, le hachis Parmentier est à base de purée de pommes de terre et de viande de bœuf ou veau, hachée.<br>
            Ce gratin doit son nom au pharmacien Antoine Parmentier qui, convaincu que le tubercule pouvait combattre efficacement la disette, le fit goûter à Louis XVI. « Hachis » désigne un plat dans lequel les ingrédients sont hachés ou émincés ou broyés.
        </div>

    </div>
</div>
<div class="row">
    <div class="col-md-12 col-lg-12 recettes">
        <h3 class="recette-part">Préparation</h3>
        <ul class="preparation">
            <li>Éplucher l'oignon, la carotte, la gousse d'ail débarrassée de son germe, les pommes de terre, les tomates et le poivron.</li>
            <li>Émincer l'oignon, le poivron et les tomates.</li>
            <li>Dans une cocotte, faire chauffer l'huile d'olive à feu vif et faire dorer les morceaux de veau.</li>
            <li>Quand ils sont bien rissolés, ajouter l'oignon émincé et l'ail écrasé.</li>
            <li>Quand l'oignon devient transparent ajouter le poivron émincé, les tomates, les feuilles de sauge ciselées et la carotte en rondelles.</li>
            <li>Verser le vin et le fond de veau.</li>
            <li>Saler, poivrer, couvrir et cuire à feu moyen pendant 1 heure.</li>
            <span>30 min. avant fin de la cuisson de la viande :</span>
            <li>Dans une grande casserole d'eau placer les pommes de terre.</li>
            <li>Porter à ébullition, saler et maintenir l'ébullition pendant 20 min.</li>
            <li>Égoutter les pommes de terre, les écraser en purée, incorporer le lait et le beurre.</li>
            <li>Beurrer un plat à gratin, étendre la moitié de la purée.</li>
            <li>Quand le veau est cuit, passer le contenu de la cocotte au hachoir.</li>
            <li>Placer la viande hachée sur la couche de purée.</li>
            <li>Recouvrir du reste de la purée.</li>
            <li>Parsemer de quelques noisettes de beurre et de 2 cuil. à soupe de chapelure.</li>
            <li>Enfourner 25 min. à four à 180 (therm. 6).</li>
        </ul>
    </div>
</div>
<div class="row">
    <div class="col-md-12 col-lg-12">
        <div class="astuce">
            <i class="fa fa-caret-right" aria-hidden="true"></i> ASTUCES TIME NUTRITION
            <div>
                Comme en Écosse, vous pouvez rajouter une couche de macédoine de légumes entre la viande et les pommes de terre, et remplacer le veau par de la viande de mouton.
            </div>
        </div>

    </div>
</div>