<div class="row">
    <div class="col-md-12 col-lg 12 recettes">
        <div class="col-xs-12 col-sm-12 col-md-4 col-lg-4">
            <h2><?php echo __('Lapin à la moutarde');?></h2>
            <ul>
                <li><img src="<?php echo $this->getViewFileUrl('images/recettes/cutlery.png'); ?>"> <span class="gray">Pour</span> : 2 personnes</li>
                <li><img src="<?php echo $this->getViewFileUrl('images/recettes/clock.png'); ?>"> <span class="gray">Préparation</span> : 10 min.</li>
                <li><img src="<?php echo $this->getViewFileUrl('images/recettes/oven.png'); ?>"> <span class="gray">Cuisson</span> : 1h.</li>
            </ul>
            <h3 class="recette-part">Ingrédients</h3>
            <ul class="ingredients">
                <li>1 lapereau de 700 g coupé en morceaux</li>
                <li>1 cuil. à soupe d'huile d'olive</li>
                <li>1 noix de beurre</li>
                <li>1 oignon moyen émincé</li>
                <li>Moutarde de Dijon</li>
                <li>Laurier</li>
                <li>Thym</li>
                <li>1 verre de vin blanc</li>
                <li>½ l. de bouillon de volaille instantané</li>
                <li>30 g de farine</li>
                <li>1 jaune d'œuf</li>
                <li>4 cuil. à soupe de crème</li>
            </ul>

        </div>
        <div class="col-xs-12 col-sm-12 col-md-4 col-lg-4">
            <img src="<?php echo $this->getViewFileUrl('images/recettes/lapin_moutarde.jpg'); ?>" alt="lapin à la moutarde time nutrition">
        </div>
        <div class="col-xs-12 col-sm-12 col-md-4 col-lg-4">
            La consommation de viande de lapin est très ancienne.<br>
            Elle a failli disparaître mais s'est révélée une bonne solution pour obtenir de la viande à disposition des habitants des villes sans nécessiter de surfaces cultivables lors de la révolution industrielle.<br>
            Elle présente des caractéristiques intéressantes pour l’alimentation : riche en protéines, bien pourvue en minéraux mais pas en sodium et apporte des Oméga-3.
        </div>

    </div>
</div>
<div class="row">
    <div class="col-md-12 col-lg-12 recettes">
        <h3 class="recette-part">Préparation</h3>
        <ul class="preparation">
            <li>Enduire copieusement de moutarde les morceaux de lapin.</li>
            <li>Dans une sauteuse faire chauffer une cuillère d'huile d'olive avec une noix de beurre et faire revenir les morceaux de lapereau sans les laisser brunir.</li>
            <li>Ajouter les rondelles d'oignon.</li>
            <li>Saupoudrer de farine, remuer, mouiller avec le vin blanc et le bouillon de manière à juste recouvrir les morceaux.</li>
            <li>Ajouter le thym et le laurier, saler et poivrer.</li>
            <li>Laisser cuire à feu doux une petite heure en tournant les morceaux de temps en temps.</li>
            <li>Pendant ce temps, mélanger dans un bol la crème et le jaune d'œuf.</li>
            <li>Déposer les morceaux de lapereau dans un plat creux et maintenir au chaud.</li>
            <li>Lier la sauce avec le contenu du bol. La faire chauffer.</li>
            <li>Verser sur le lapin.</li>
        </ul>
    </div>
</div>
<div class="row">
    <div class="col-md-12 col-lg-12">
        <div class="astuce">
            <i class="fa fa-caret-right" aria-hidden="true"></i> ASTUCES TIME NUTRITION
            <div>
                Servez cette viande accompagnée de pommes de terre.<br>
                Pour plus de saveur, choisissez des pommes de terre Charlotte.
            </div>
        </div>

    </div>
</div>