<div class="row">
    <div class="col-md-12 col-lg 12 recettes">
        <div class="col-xs-12 col-sm-6 col-md-4 col-lg-4">
            <h2><?php echo __('Magret de canard aux figues');?></h2>
            <ul>
                <li><img src="<?php echo $this->getViewFileUrl('images/recettes/cutlery.png'); ?>"> <span class="gray">Pour</span> : 2 personnes</li>
                <li><img src="<?php echo $this->getViewFileUrl('images/recettes/clock.png'); ?>"> <span class="gray">Préparation</span> : 8 min.</li>
                <li><img src="<?php echo $this->getViewFileUrl('images/recettes/oven.png'); ?>"> <span class="gray">Cuisson</span> : 30 min.</li>
            </ul>
            <h3 class="recette-part">Ingrédients</h3>
            <ul class="ingredients">
                <li>1 magret</li>
                <li>2 escalopes de 100 g de foie gras cru</li>
                <li>20 cl de vin rouge</li>
                <li>4 figues</li>
                <li>Gros sel</li>
                <li>Poivre</li>
            </ul>

        </div>
        <div class="col-xs-12 col-sm-6 col-md-4 col-lg-4">
            <img src="<?php echo $this->getViewFileUrl('images/recettes/magret_canard_figues.jpg'); ?>" alt="magret de canard aux figues time nutrition">
        </div>
        <div class="col-xs-12 col-sm-12 col-md-4 col-lg-4">

        </div>

    </div>
</div>
<div class="row">
    <div class="col-md-12 col-lg-12 recettes">
        <h3 class="recette-part">Préparation</h3>
        <ul class="preparation">
            <span>Préparation des figues* :</span>
            <li>Mettre les figues à plat dans le fond d’une casserole (attention à les disposer de manière à ce qu’elles ne se chevauchent pas)</li>
            <li>Les arroser de vin rouge jusqu'à les recouvrir complètement.</li>
            <li>Porter à ébullition, couvrir et laisser frémir ¼ d'heure.</li>
            <span>Cuisson :</span>
            <li>Faire chauffer une poêle antiadhésive et y déposer le magret côté peau.</li>
            <li>Couvrir la poêle d'un couvercle anti-projection pour éviter les éclaboussures de graisse.</li>
            <li>Faire cuire 5 min.</li>
            <li>Retourner le magret et faire cuire encore 2 à 3 min.</li>
            <li>Débarrasser le magret sur une assiette chaude et le couvrir d'un papier d'aluminium.</li>
            <li>Récupérer la graisse sortie pendant la cuisson et la réserver dans un bol.</li>
            <li>Laver la poêle et la remettre à chauffer à feu vif. Pendant ce temps, découper le magret en fines tranches et les répartir sur 2 assiettes.</li>
            <li>Quand la poêle est bien chaude, saisir les 2 escalopes de foie gras 1 min. sur chaque face.</li>
            <li>Les ajouter au magret dans chaque assiette, parsemer largement de gros sel et de poivre.</li>
            <li>Ajouter les figues bien chaudes.</li>
            <li>Faire réduire très rapidement à feu vif le vin de cuisson des figues et en arroser largement les tranches de magret.</li>
            <li>Déguster !</li>
        </ul>
    </div>
</div>
<div class="row">
    <div class="col-md-12 col-lg-12">
        <div class="astuce">
            <i class="fa fa-caret-right" aria-hidden="true"></i> ASTUCES TIME NUTRITION
            <div>
                * Les figues peuvent être préparées la veille.<br>
                Ce plat s’accompagnera parfaitement de navets ou de pommes de terre en gratin.
            </div>
        </div>

    </div>
</div>