<div class="row">
    <div class="col-md-12 col-lg 12 recettes">
        <div class="col-xs-12 col-sm-12 col-md-4 col-lg-4">
            <h2><?php echo __('Pavés de rumsteck au cognac');?></h2>
            <ul>
                <li><img src="<?php echo $this->getViewFileUrl('images/recettes/cutlery.png'); ?>"> <span class="gray">Pour</span> : 2 personnes</li>
                <li><img src="<?php echo $this->getViewFileUrl('images/recettes/clock.png'); ?>"> <span class="gray">Préparation</span> : 12 min.</li>
                <li><img src="<?php echo $this->getViewFileUrl('images/recettes/oven.png'); ?>"> <span class="gray">Cuisson</span> : 18 à 20min.</li>
            </ul>
            <h3 class="recette-part">Ingrédients</h3>
            <ul class="ingredients">
                <li>2 pavés de Rumsteck de 220 g chacun</li>
                <li>80 g de lardons</li>
                <li>50 g de champignons de Paris</li>
                <li>1 cuil. à soupe d'huile d'olive</li>
                <li>1 petit verre de cognac</li>
                <li>15 cl. de vin blanc des Charente</li>
                <li>5 cl. de crème</li>
                <li>1 noisette de beurre</li>
                <li>2 cuil. à café de moutarde forte</li>
                <li>5 cl. de fond de veau</li>
                <li>Sel, poivre</li>
            </ul>

        </div>
        <div class="col-xs-12 col-sm-12 col-md-4 col-lg-4">
            <img src="<?php echo $this->getViewFileUrl('images/recettes/paves_rumsteck_cognac.jpg'); ?>" alt="pavés de rumsteck au cognac time nutrition">
        </div>
        <div class="col-xs-12 col-sm-12 col-md-4 col-lg-4">
            De l’anglais rump (croupe) et steak (tranche de grillade), le rumsteck est une partie de l’aloyau, c’est-à-dire l’arrière de l’animal, côté cuisse, de la queue au prolongement du filet et du contre-filet.<br>
            Morceau assez large qui forme le haut de la cuisse, c’est une viande à fibres courtes, goûteuse et tendre.
        </div>

    </div>
</div>
<div class="row">
    <div class="col-md-12 col-lg-12 recettes">
        <h3 class="recette-part">Préparation</h3>
        <ul class="preparation">
            <li>Éplucher les champignons, les laver rapidement dans de l'eau vinaigrée, les éponger et les émincer.</li>
            <li>Dans une poêle antiadhésive faire chauffer une noisette de beurre et une cuillère d'huile d'olive.</li>
            <li>Dès que le mélange est chaud y déposer les champignons, saler, poivrer et les faire sauter environ 7 à 8 min. jusqu'à ce qu'ils aient rendus leur eau. Les réserver.</li>
            <li>Dans une casserole faire réduire le vin blanc de moitié à feu vif.</li>
            <li>Mettre à feu moyen, ajouter le cognac, les lardons, le fond de veau et enfin la crème mélangée à la moutarde.</li>
            <li>Laisser réduire encore 10 min jusqu'à ce que la consistance soit crémeuse.</li>
            <li>Ajouter alors les champignons.</li>
            <li>Dans la poêle qui a cuit les champignons ajouter un filet d'huile d'olive.</li>
            <li>Quand elle est bien chaude y saisir les pavés 3 à 4 min suivant l'épaisseur.</li>
            <li>Les retourner, saler, poivrer et laisser cuire jusqu'à ce que le sang perle à la surface, pour un pavé saignant, un peu plus pour une viande à point.</li>
            <li>Placer sur des assiettes et napper la viande de sauce.</li>
        </ul>
    </div>
</div>
<div class="row">
    <div class="col-md-12 col-lg-12">
        <div class="astuce">
            <i class="fa fa-caret-right" aria-hidden="true"></i> ASTUCES TIME NUTRITION
            <div>
                Nous vous conseillons d’accompagner cette viande d’une purée de légumes ou bien d’un assortiment de différentes purées.
            </div>
        </div>

    </div>
</div>