<div class="row">
    <div class="col-md-12 col-lg 12 recettes">
        <div class="col-xs-12 col-sm-6 col-md-4 col-lg-4">
            <h2><?php echo __('POT AU FEU DE CARMEN');?></h2>
            <ul>
                <li><img src="<?php echo $this->getViewFileUrl('images/recettes/cutlery.png'); ?>"> <span class="gray">Pour</span> : 4 personnes</li>
                <li><img src="<?php echo $this->getViewFileUrl('images/recettes/clock.png'); ?>"> <span class="gray">Préparation</span> : 10 min.</li>
                <li><img src="<?php echo $this->getViewFileUrl('images/recettes/oven.png'); ?>"> <span class="gray">. <span class="gray">Cuisson</span> : 50 min.</li>
            </ul>
            <h3 class="recette-part">Ingrédients</h3>
            <ul class="ingredients">
                <li>200 g de viande de bœuf</li>
                <li>200 g de viande de porc</li>
                <li>4 tranches de chorizo</li>
                <li>4 tranches de jambon</li>
                <li>Cuisses et hauts de cuisse d'une poule</li>
                <li>100 g de lard</li>
                <li>1 os de porc</li>
                <li>1 L ½ d'eau</li>
                <li>200 g de pois chiches</li>
                <li>4 petites pommes de terre</li>
                <li>2 carottes/li></li>
                <li>1 courgette</li>
                <li>Sel, poivre</li>
            </ul>

        </div>
        <div class="col-xs-12 col-sm-6 col-md-4 col-lg-4">
            <img src="<?php echo $this->getViewFileUrl('images/recettes/pot_feu_carmen.jpg'); ?>" alt="pot au feu de carmen time nutrition">
        </div>
        <div class="col-xs-12 col-sm-12 col-md-4 col-lg-4">
            Le pot-au-feu est un plat de viande cuisant longuement à feu très doux dans un bouillon aromatisé par des légumes.<br>
            C’est un plat bouilli traditionnel de la cuisine française.<br>
            La recette « type » de pot-au-feu n’existe pas parce qu'il en existe de très nombreuses variantes.
        </div>
    </div>
</div>
<div class="row">
    <div class="col-md-12 col-lg-12 recettes">
        <h3 class="recette-part">Préparation</h3>
        <ul class="preparation">
            <li>Séparer cuisses et hauts de cuisse de la poule.</li>
            <li>Couper la courgette et les carottes en tranches.</li>
            <li>Éplucher les pommes de terre et les laisser entières.</li>
            <li>Dans un grand fait tout mettre à bouillir le litre ½ d'eau.</li>
            <li>Dès que l'eau bout y plonger le bœuf, le porc, la poule, le chorizo, le jambon, le lard et l'os de porc.</li>
            <li>Laisser cuire à couvert pendant 1 heure.</li>
            <span>Au bout d'1 heure de cuisson</span>
            <li>Ajouter les pois chiches.</li>
            <li>Laisser cuire 30 min.</li>
            <li>Saler légèrement.</li>
            <li>Laisser cuire encore jusqu'à ce que les pois chiches deviennent tendres.</li>
            <li>Ajouter alors les pommes de terre, les tranches de courgette et de carotte.</li>
            <li>Laisser cuire encore 25 min. jusqu'à ce que les pommes de terre soient tendres.</li>
            <li>Sortir les viandes et les légumes et les répartir dans 4 assiettes.</li>
            <li>Passer le bouillon au chinois et en mettre une petite louche dans chaque assiette.</li>
        </ul>
    </div>
</div>
<div class="row">
    <div class="col-md-12 col-lg-12">
        <div class="astuce">
            <i class="fa fa-caret-right" aria-hidden="true"></i> ASTUCES TIME NUTRITION
            <div>
                Pensez à garder le reste du bouillon, il pourra remplacer le thé ou le café du matin et accompagnera parfaitement le fromage/pain/beurre.
            </div>
        </div>

    </div>
</div>