<div class="row">
    <div class="col-md-12 col-lg 12 recettes">
        <div class="col-xs-12 col-sm-6 col-md-4 col-lg-4">
            <h2><?php echo __('Potée de Grand-Mère');?></h2>
            <ul>
                <li><img src="<?php echo $this->getViewFileUrl('images/recettes/cutlery.png'); ?>"> <span class="gray">Pour</span> : 2 personnes</li>
                <li><img src="<?php echo $this->getViewFileUrl('images/recettes/clock.png'); ?>"> <span class="gray">Préparation</span> : 25 min.</li>
                <li><img src="<?php echo $this->getViewFileUrl('images/recettes/oven.png'); ?>"> <span class="gray">Cuisson</span> : 2h 45 min.</li>
            </ul>
            <h3 class="recette-part">Ingrédients</h3>
            <ul class="ingredients">
                <li>400 g de noix de veau en morceau</li>
                <li>1 oignon</li>
                <li>1 poivron</li>
                <li>1 carotte</li>
                <li>6 feuilles de sauge</li>
                <li>1 gousse d'ail</li>
                <li>8 pommes de terre</li>
                <li>10 cl de jus de veau</li>
                <li>½ verre de vin blanc</li>
                <li>2 cuil. à soupe d'huile d'olive</li>
                <li>2 tomates</li>
                <li>1 verre de lait</li>
                <li>50 g de beurre</li>
                <li>chapelure</li>
            </ul>

        </div>
        <div class="col-xs-12 col-sm-6 col-md-4 col-lg-4">
            <img src="<?php echo $this->getViewFileUrl('images/recettes/potee_grand_mere.jpg'); ?>" alt="potée de grand mère time nutrition">
        </div>
        <div class="col-xs-12 col-sm-12 col-md-4 col-lg-4">
            Cette potée à base de jarret de porc est un plat de viande de porc à l'os très connu en Allemagne, en Angleterre et en France.
        </div>

    </div>
</div>
<div class="row">
    <div class="col-md-12 col-lg-12 recettes">
        <h3 class="recette-part">Préparation</h3>
        <ul class="preparation">
            <li>Éplucher tous les légumes.</li>
            <li>Couper les tomates en 4 et l'oignon en fines rondelles.</li>
            <li>Dans une cocotte faire chauffer l'huile d'olive à feu vif y faire revenir les jarrets, débarrasser sur une assiette.</li>
            <li>Les remplacer par les oignons et les faire fondre à feu moyen en remuant de temps en temps.</li>
            <li>Préparer le fond de volaille suivant son mode d'emploi.</li>
            <li>Quand les oignons sont transparents ajouter les tomates, les rondelles de carottes, les jarrets, les clous de girofle, les grains de piment et la gousse d'ail pressée.</li>
            <li>Saler et poivrer.</li>
            <li>Arroser avec le bouillon, enfourner 1 h 45 à 180° (therm. 6).</li>
            <li>Dans une casserole d'eau bouillante salée, faire cuire les carottes, les navets et les pommes de terre pendant 12 min.</li>
            <span>A la fin des 1h 45 de cuisson :</span>
            <li>Sortir du four et ôter les jarrets et les clous de girofle de la cocotte.</li>
            <li>Mixer le contenu de la cocotte.</li>
            <li>Remettre cette sauce avec les jarrets et les légumes précuits et enfourner à nouveau pendant 35 min à 180° (therm. 6).</li>
            <li>Servir</li>
        </ul>
    </div>
</div>
<div class="row">
    <div class="col-md-12 col-lg-12">
        <div class="astuce">
            <i class="fa fa-caret-right" aria-hidden="true"></i> ASTUCES TIME NUTRITION
            <div>
                Pour varier les plaisirs, vous pouvez également faire cuire le jarret « à l’allemande » : dans de la bière.
            </div>
        </div>

    </div>
</div>