<div class="row">
    <div class="col-md-12 col-lg 12 recettes">
        <div class="col-xs-12 col-sm-6 col-md-4 col-lg-4">
            <h2><?php echo __('Roti de veau aux morilles');?></h2>
            <ul>
                <li><img src="<?php echo $this->getViewFileUrl('images/recettes/cutlery.png'); ?>"> <span class="gray">Pour</span> : 2 personnes</li>
                <li><img src="<?php echo $this->getViewFileUrl('images/recettes/clock.png'); ?>"> <span class="gray">Préparation</span> : 25 min.</li>
                <li><img src="<?php echo $this->getViewFileUrl('images/recettes/oven.png'); ?>"> <span class="gray">Cuisson</span> : 40 min.</li>
            </ul>
            <h3 class="recette-part">Ingrédients</h3>
            <ul class="ingredients">
                <li>500 g de rôti de veau</li>
                <li>75 g de morilles séchées</li>
                <li>2 cuil. à soupe de crème épaisse</li>
                <li>2 cuil. à soupe d'huile d'olive2 cuil. à soupe d'huile d'olive</li>
                <li>1 grand verre de cidre</li>
                <li>1 cuil. à soupe d'estragon + 2 branches</li>
                <li>1 oignon</li>
                <li>Sel, poivre</li>
            </ul>

        </div>
        <div class="col-xs-12 col-sm-6 col-md-4 col-lg-4">
            <img src="<?php echo $this->getViewFileUrl('images/recettes/roti_veau_morilles.jpg'); ?>" alt="roti de veau aux morilles time nutrition">
        </div>
        <div class="col-xs-12 col-sm-12 col-md-4 col-lg-4">

        </div>

    </div>
</div>
<div class="row">
    <div class="col-md-12 col-lg-12 recettes">
        <h3 class="recette-part">Préparation</h3>
        <ul class="preparation">
            <li>Éplucher et émincer l'oignon.</li>
            <li>Réhydrater les morilles en les trempant dans un saladier d'eau très chaude pendant 20 min.</li>
            <li>Dans une cocotte faire chauffer l'huile d'olive y faire dorer le rôti de veau sur chaque face à feu vif, puis le retirer.</li>
            <li>Le remplacer par l'oignon émincé, baisser le feu, remuer à l'aide d'une cuillère en bois, dès que l'oignon est transparent remettre le rôti dans la cocotte avec 2 branches d'estragon, saler légèrement, poivrer, couvrir et cuire à feu doux 25 min.</li>
            <li>Enlever le veau de la cocotte. Verser le cidre dans la cocotte et à feu vif réduire de moitié ajouter 2 cuillères de crème, baisser le feu.</li>
            <li>Égoutter les morilles et les mettre dans la cocotte et cuire 10 min à feu doux.</li>
            <li>Ajouter l'estragon ciselé.</li>
            <li>Découper le rôti et le présenter dans un plat, entouré des morilles.</li>
            <li>Napper avec la sauce.</li>
        </ul>
    </div>
</div>
<div class="row">
    <div class="col-md-12 col-lg-12">
        <div class="astuce">
            <i class="fa fa-caret-right" aria-hidden="true"></i> ASTUCES TIME NUTRITION
            <div>
                Vous pouvez remplacer les morilles par des cèpes.<br>
                Nous vous conseillons d’accompagner cette viande d’un risotto à la crème et aux morilles ou bien de pommes de terre que vous pouvez faire cuire à la cocotte en même temps que les morilles.
            </div>
        </div>

    </div>
</div>