<div class="row">
    <div class="col-md-12 col-lg 12 recettes">
        <div class="col-xs-12 col-sm-6 col-md-4 col-lg-4">
            <h2><?php echo __('sauté de veau à l\'orange');?></h2>
            <ul>
                <li><img src="<?php echo $this->getViewFileUrl('images/recettes/cutlery.png'); ?>"> <span class="gray">Pour</span> : 4 personnes</li>
                <li><img src="<?php echo $this->getViewFileUrl('images/recettes/clock.png'); ?>"> <span class="gray">Préparation</span> : 30 min.</li>
                <li><img src="<?php echo $this->getViewFileUrl('images/recettes/oven.png'); ?>"> <span class="gray">Cuisson</span> : 2 h</li>
            </ul>
            <h3 class="recette-part">Ingrédients</h3>
            <ul class="ingredients">
                <li>1 kg 300 de morceaux de viande de veau</li>
                <li>2 carottes</li>
                <li>6 oignons moyens</li>
                <li>3 tomates</li>
                <li>2 gousses d'ail</li>
                <li>3 oranges</li>
                <li>1 dl de vin blanc sec</li>
                <li>7 cuil. à soupe d'huile d'olive</li>
                <li>2 cuil. à soupe de farine</li>
                <li>2 clous de girofle</li>
                <li>1 morceau de sucre</li>
                <li>Sel, poivre</li>
            </ul>

        </div>
        <div class="col-xs-12 col-sm-6 col-md-4 col-lg-4">
            <img src="<?php echo $this->getViewFileUrl('images/recettes/saute_veau_orange.jpg'); ?>" alt="sauté de veau à l'orange time nutrition">
        </div>
        <div class="col-xs-12 col-sm-12 col-md-4 col-lg-4">
            Grâce à ses protéines et ses nombreux micronutriments, la viande de veau est très nutritive.<br>
            C’est aussi une viande maigre, et même extra-maigre selon les coupes, qui contient davantage de bons gras que de mauvais gras.
        </div>

    </div>
</div>
<div class="row">
    <div class="col-md-12 col-lg-12 recettes">
        <h3 class="recette-part">Préparation</h3>
        <ul class="preparation">
            <li>Prélever le zeste d'une demi-orange et le hacher finement.</li>
            <li>Presser les 2 oranges.</li>
            <li>Éplucher les oignons, les carottes, les tomates et les couper en rondelles.</li>
            <li>Éplucher l'ail et le débarrasser de ses germes.</li>
            <li>Dans une sauteuse faire chauffer 3 cuil. à soupe d'huile d'olive y faire dorer sur toutes leurs faces les morceaux de veau.</li>
            <li>Les placer au fur et à mesure dans une cocotte avec 2 cuil. à soupe d'huile d'olive</li>
            <li>Saupoudrer avec la farine et remuer à feu vif afin de faire blondir la farine.</li>
            <li>Arroser alors avec le vin blanc, le jus des oranges, le zeste et suffisamment d'eau pour que le liquide affleure la viande.</li>
            <li>Ajouter les clous de girofle, saler et poivrer.</li>
            <li>Couvrir et baisser le feu pour faire mijoter doucement.</li>
            <li>Nettoyer la sauteuse, y verser 2 cuil. à soupe d'huile, chauffer et placer les rondelles de carottes et oignons.</li>
            <li>Les faire rissoler à feu moyen puis les verser dans la cocotte, où mijote le veau, ajouter les tomates et le sucre.</li>
            <li>Continuer la cuisson à feu très doux.</li>
            <li>Couper la dernière orange en tranches.</li>
            <li>Quand le veau est cuit le placer dans un plat et mettre le contenu de la cocotte autour et décorer avec les tranches d’oranges.</li>

        </ul>
    </div>
</div>
<div class="row">
    <div class="col-md-12 col-lg-12">
        <div class="astuce">
            <i class="fa fa-caret-right" aria-hidden="true"></i> ASTUCES TIME NUTRITION
            <div>
                Nous vous recommandons d’accompagner ces escalopes de pâtes ou de riz, de galettes de polenta ou de galettes de pommes de terre.<br>
                Pour tirer un maximum de jus des oranges, sortez les fruits du réfrigérateur à l’avance et roulez-les avec la main sur une surface de travail avant de les passer au presse-agrume.
            </div>
        </div>

    </div>
</div>