<div class="row">
    <div class="col-md-12 col-lg 12 recettes">
        <div class="col-xs-12 col-sm-6 col-md-4 col-lg-4">
            <h2><?php echo __('Tajine de Mouton');?></h2>
            <ul>
                <li><img src="<?php echo $this->getViewFileUrl('images/recettes/cutlery.png'); ?>"> <span class="gray">Pour</span> : 4 personnes</li>
                <li><img src="<?php echo $this->getViewFileUrl('images/recettes/clock.png'); ?>"> <span class="gray">Préparation</span> : 10 min.</li>
                <li><img src="<?php echo $this->getViewFileUrl('images/recettes/oven.png'); ?>"> <span class="gray">Cuisson</span> : 1h 40min.</li>
            </ul>
            <h3 class="recette-part">Ingrédients</h3>
            <ul class="ingredients">
                <li>1 kg 500 d'épaule de mouton découpée en morceaux</li>
                <li>1 oignon</li>
                <li>1 douzaine d'olives confites</li>
                <li>1 citron confit</li>
                <li>1 grosse cuil. à soupe de gingembre râpé</li>
                <li>½ cuil. à café de safran</li>
                <li>1 gousse d'ail</li>
                <li>5 cuil. à soupe d'huile d'olive</li>
                <li>1 cuil. à café de farine</li>
                <li>Sel, poivre</li>
            </ul>

        </div>
        <div class="col-xs-12 col-sm-6 col-md-4 col-lg-4">
            <img src="<?php echo $this->getViewFileUrl('images/recettes/tajine_mouton.jpg'); ?>" alt="Tajine de mouton time nutrition">
        </div>
        <div class="col-xs-12 col-sm-12 col-md-4 col-lg-4">
            Le tajine désigne un ustensile de cuisine traditionnel du Maghreb : plat de cuisson creux en terre cuite vernissée, surmonté d'un couvercle conique.<br>
            C’est aussi la préparation culinaire cuite dans cet ustensile, sorte de ragoût cuit à l'étouffée, qui peut être composé de viande, de volaille ou de poisson, de légumes ou de fruits.
        </div>

    </div>
</div>
<div class="row">
    <div class="col-md-12 col-lg-12 recettes">
        <h3 class="recette-part">Préparation</h3>
        <ul class="preparation">
            <li>Éplucher l'ail et l'oignon.</li>
            <li>Dans une cocotte verser l'huile d'olive, quand elle est chaude faire revenir à feu vif les morceaux de viande, saler et poivrer.</li>
            <li>Ajouter l'oignon entier, l'ail écrasé et débarrassé de son germe, le gingembre et le safran.</li>
            <li>Recouvrir d'eau.</li>
            <li>Dès que l'ébullition a reprise, baisser le feu, couvrir et laisser mijoter pendant 1 h 30.</li>
            <li>Remuer de temps en temps et rajouter de l'eau si nécessaire en cours de cuisson. Veiller à retirer l'oignon entier dès qu'il est cuit.</li>
            <span>Quand la viande est cuite (c'est à dire quand elle se détache facilement à la fourchette) :</span>
            <li>La retirer de la cocotte et la disposer dans un plat creux.</li>
            <li>L’entourer des olives et citrons confits.</li>
            <li>Passer l'oignon au mixeur avec un peu de sauce, ajouter la farine, mélanger et verser dans la cocotte.</li>
            <li>Laisser réduire jusqu'à l'obtention d'une sauce onctueuse.</li>
            <li>Hors du feu mélanger énergiquement la sauce.</li>
            <li>Napper la viande et déguster aussitôt.</li>
        </ul>
    </div>
</div>
<div class="row">
    <div class="col-md-12 col-lg-12">
        <div class="astuce">
            <i class="fa fa-caret-right" aria-hidden="true"></i> ASTUCES TIME NUTRITION
            <div>
                Pour faire de ce moment un véritable délice, accompagnez la tajine de couscous.<br>
                Et pensez à réserver le reste de sauce dans une saucière afin de pouvoir imprégner vos graines de semoules.
            </div>
        </div>

    </div>
</div>