<?php
/**
 * Copyright © 2013-2017 Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>

<form class="form contact"
      action="<?php /* @escapeNotVerified */ echo $block->getFormAction(); ?>"
      id="contact-form"
      enctype="multipart/form-data"
      method="post"
      data-hasrequired="<?php /* @escapeNotVerified */ echo __('* Required Fields') ?>"
      data-mage-init='{"validation":{}}'>

    <fieldset class="fieldset">
        <div class="field note no-label"><?php /* @escapeNotVerified */ echo __('Jot us a note and we’ll get back to you as quickly as possible.') ?></div>

        <div class="field subject required">
            <label class="label" for="subject" class=""><span><?php echo __('Subject') ?></span></label>
            <div class="control">
                <select name="subject" id="subject" title="subject" value="" required/>
                <option value="">--- Sélectionner un sujet ---</option>
                <option value="Question concernant une commande">Question concernant une commande</option>
                <option value="Question concernant un paiement">Question concernant un paiement</option>
                <option value="Question concernant le service client">Question concernant le service client</option>
                <option value="Question concernant un produit">Question concernant un produit</option>
                <option value="Demande de partenariat">Demande de partenariat</option>
                <option value="autres">Autres</option>
                </select>
            </div>
        </div>
        <div class="field name required">
            <label class="label" for="name"><span><?php /* @escapeNotVerified */ echo __('Name') ?></span></label>
            <div class="control">
                <input name="name" id="name" title="<?php /* @escapeNotVerified */ echo __('Name') ?>" value="<?php echo $block->escapeHtml($this->helper('Magento\Contact\Helper\Data')->getPostValue('name') ?: $this->helper('Magento\Contact\Helper\Data')->getUserName()) ?>" class="input-text" type="text" data-validate="{required:true}"/>
            </div>
        </div>
        <div class="field email required">
            <label class="label" for="email"><span><?php /* @escapeNotVerified */ echo __('Email') ?></span></label>
            <div class="control">
                <input name="email" id="email" title="<?php /* @escapeNotVerified */ echo __('Email') ?>" value="<?php echo $block->escapeHtml($this->helper('Magento\Contact\Helper\Data')->getPostValue('email') ?: $this->helper('Magento\Contact\Helper\Data')->getUserEmail()) ?>" class="input-text" type="email" data-validate="{required:true, 'validate-email':true}"/>
            </div>
        </div>
        <div class="field telephone">
            <label class="label" for="telephone"><span><?php /* @escapeNotVerified */ echo __('Phone Number') ?></span></label>
            <div class="control">
                <input name="telephone" id="telephone" title="<?php /* @escapeNotVerified */ echo __('Phone Number') ?>" value="<?php echo $block->escapeHtml($this->helper('Magento\Contact\Helper\Data')->getPostValue('telephone')) ?>" class="input-text" type="text" />
            </div>
        </div>
        <div class="field codeclient">
            <label class="label" for="code_client"><span><?php echo __('Code Client (si vous en possédez un)') ?></span></label>
            <div class="control">
                <input name="code_client" id="code_client" title="<?php echo __('Code Client') ?>" value="" class="input-text" type="text" />
            </div>
        </div>
        <div class="field comment required">
            <label class="label" for="comment"><span><?php /* @escapeNotVerified */ echo __('What’s on your mind?') ?></span></label>
            <div class="control">
                <textarea name="comment" id="comment" title="<?php /* @escapeNotVerified */ echo __('What’s on your mind?') ?>" class="input-text" cols="5" rows="3" data-validate="{required:true}"><?php echo $block->escapeHtml($this->helper('Magento\Contact\Helper\Data')->getPostValue('comment')) ?></textarea>
            </div>
        </div>

        <div class="field upload">
            <label class="label"><span><?php /* @escapeNotVerified */ echo __('Envoyer une pièce jointe') ?></span></label>
            <div class="control">
                <input type="file" name="upload_document" value="" />
            </div>
        </div>

        <div class="field">
            <div class="g-recaptcha" data-sitekey="6LdJZEsUAAAAAKSMRvw60vLzYNptq1yyllgZN_Wq"></div>
        </div>

        <?php echo $block->getChildHtml('form.additional.info'); ?>
    </fieldset>
    <div class="text-center">
        <div class="primary">
            <input type="hidden" name="hideit" id="hideit" value="" />
            <button type="submit" title="<?php /* @escapeNotVerified */ echo __('Submit') ?>" class="action submit primary">
                <span><?php /* @escapeNotVerified */ echo __('Submit') ?></span>
            </button>
        </div>
    </div>
</form>

<script src="https://www.google.com/recaptcha/api.js" async defer></script>
