<?php
$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
$storeManager = $objectManager->get('\Magento\Store\Model\StoreManagerInterface');
$baseUrl = $storeManager->getStore()->getBaseUrl();
?>

<div class="row">
    <div class="col-md-12 col-lg 12 recettes">
        <div class="col-lg-12">
            <h2><?php echo __('RECETTES DE DINER');?></h2>
            <ul>
                <li><a href="<?php echo $baseUrl.'bar_compotee_endives';?>">Bar Grille Sur Compotee D’endives</a></li>
                <li><a href="<?php echo $baseUrl.'cabillaud_vapeur';?>">Filets De Cabillaud Vapeur</a></li>
                <li><a href="<?php echo $baseUrl.'darnes_saumon';?>">Darnes De Saumon A L’ancienne</a></li>
                <li><a href="<?php echo $baseUrl.'daurade_meridionale';?>">Daurade A La Meridionale</a></li>
                <li><a href="<?php echo $baseUrl.'duo_lotte_saint_jacques';?>">Duo De Lotte Et Saint-Jacques</a></li>
                <li><a href="<?php echo $baseUrl.'escalope_dinde_moutarde';?>">Escalopes De Dinde A La Moutarde A L’ancienne</a></li>
                <li><a href="<?php echo $baseUrl.'escalopes_dinde_pomme';?>">Escalopes De Dinde Aux Pommes</a></li>
                <li><a href="<?php echo $baseUrl.'julienne_provencale';?>">Julienne A La Provençale</a></li>
                <li><a href="<?php echo $baseUrl.'langoustines_agrumes';?>">Langoustines Au Beurre D'agrumes</a></li>
                <li><a href="<?php echo $baseUrl.'lotte_safran';?>">Daube De Lotte Au Safran</a></li>
                <li><a href="<?php echo $baseUrl.'merlan_saveur_sud';?>">Filets De Merlan Aux Saveurs Du Sud</a></li>
                <li><a href="<?php echo $baseUrl.'noix_saint_jacques';?>">Noix De Saint-Jacques Au Vin Blanc</a></li>
                <li><a href="<?php echo $baseUrl.'papillotes_cabillaud';?>">Papillotes De Cabillaud</a></li>
                <li><a href="<?php echo $baseUrl.'poelee_gambas';?>">Poelee De Gambas</a></li>
                <li><a href="<?php echo $baseUrl.'pot_feu_mer';?>">Pot Au Feu De La Mer</a></li>
                <li><a href="<?php echo $baseUrl.'poulet_chinoise';?>">Poulet A La Chinoise</a></li>
                <li><a href="<?php echo $baseUrl.'rouget_coulis_tomate';?>">Rougets Grilles Au Coulis De Tomates</a></li>
                <li><a href="<?php echo $baseUrl.'tajine_poisson';?>">Tajine De Poisson</a></li>
                <li><a href="<?php echo $baseUrl.'tourteau_estragon';?>">Tourteau A L’estragon</a></li>
                <li><a href="<?php echo $baseUrl.'truite_amandes';?>">Truites Aux Amandes</a></li>
            </ul>
        </div>
    </div>
</div>