<?php
$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
$storeManager = $objectManager->get('\Magento\Store\Model\StoreManagerInterface');
$baseUrl = $storeManager->getStore()->getBaseUrl();
?>

<div class="row">
    <div class="col-md-12 col-lg 12 recettes">
        <div class="col-lg-12">
            <h2><?php echo __('RECETTES DE GOÛTER');?></h2>
            <ul>
                <li><a href="<?php echo $baseUrl.'ananas_coco';?>">Ananas A La Noix De Coco</a></li>
                <li><a href="<?php echo $baseUrl.'aumonieres_aux_pommes';?>">Aumonieres Aux Pommes</a></li>
                <li><a href="<?php echo $baseUrl.'chaud_froid_mandarine_chocolat';?>">Chaud-Froid Mandarines Chocolat</a></li>
                <li><a href="<?php echo $baseUrl.'chaud_froid_peche_caramel';?>">Chaud-Froid De Peches Au Caramel</a></li>
                <li><a href="<?php echo $baseUrl.'compote_pomme_poire';?>">Compote Pommes-Poires Au Caramel</a></li>
                <li><a href="<?php echo $baseUrl.'delice_ananas_caramel';?>">Delice D’ananas Au Caramel</a></li>
                <li><a href="<?php echo $baseUrl.'delices_choco_noisette';?>">Delices Choco-Noisette</a></li>
                <li><a href="<?php echo $baseUrl.'douceur_avocat';?>">Douceur D’avocat</a></li>
                <li><a href="<?php echo $baseUrl.'figues_epices';?>">Figues Tiedes Aux Epices</a></li>
                <li><a href="<?php echo $baseUrl.'fraises_caramelisees';?>">Fraises Caramelisees</a></li>
                <li><a href="<?php echo $baseUrl.'lychees_coulis_framboise';?>">Lychees Au Coulis De Framboise</a></li>
                <li><a href="<?php echo $baseUrl.'noix_cajou_caramel';?>">Noix De Cajou Au Caramel</a></li>
                <li><a href="<?php echo $baseUrl.'poires_amandes_chocolat';?>">Poires Fondantes Aux Amandes Et Au Chocolat</a></li>
                <li><a href="<?php echo $baseUrl.'pommes_four';?>">Pommes Au Four</a></li>
                <li><a href="<?php echo $baseUrl.'salade_fraicheur';?>">Salade Fraicheur</a></li>
                <li><a href="<?php echo $baseUrl.'salade_fruits_exotiques';?>">Salade De Fruits Exotiques</a></li>
                <li><a href="<?php echo $baseUrl.'sorbet_banane';?>">Sorbet Banane</a></li>
                <li><a href="<?php echo $baseUrl.'sorbet_citron_vert';?>">Sorbet Citron Vert</a></li>
                <li><a href="<?php echo $baseUrl.'sorbet_kiwi';?>">Sorbet Kiwi</a></li>
                <li><a href="<?php echo $baseUrl.'trio_raisin_pignon_noix';?>">Trio Caramelise Raisins/Pignons/Noix</a></li>
            </ul>
        </div>
    </div>
</div>