<?php
$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
$storeManager = $objectManager->get('\Magento\Store\Model\StoreManagerInterface');
$baseUrl = $storeManager->getStore()->getBaseUrl();
?>

<div class="row">
    <div class="col-md-12 col-lg 12 recettes">
        <div class="col-lg-12">
            <h2><?php echo __('RECETTES DE PETIT DEJEUNER');?></h2>
            <ul>
                <li><a href="<?php echo $baseUrl.'aumonieres_fromages';?>">Aumonieres Aux 4 Fromages</a></li>
                <li><a href="<?php echo $baseUrl.'blinis_fromage';?>">Blinis Au Fromage</a></li>
                <li><a href="<?php echo $baseUrl.'cabecou_noix';?>">Cabecou Aux Noix</a></li>
                <li><a href="<?php echo $baseUrl.'crepes_coulommiers';?>">Crepes Roulees Au Coulommiers</a></li>
                <li><a href="<?php echo $baseUrl.'delice_fondant_gorgonzola';?>">Delice Fondant De Gorgonzola</a></li>
                <li><a href="<?php echo $baseUrl.'duo_oeufs_knack';?>">Duo Œufs Au Plat Et Knack</a></li>
                <li><a href="<?php echo $baseUrl.'fondue_camembert';?>">Fondue De Camembert</a></li>
                <li><a href="<?php echo $baseUrl.'fromage_chevre_provencale';?>">Fromage De Chevre A La Provençale</a></li>
                <li><a href="<?php echo $baseUrl.'oeufs_brouilles';?>">Œufs Brouilles</a></li>
                <li><a href="<?php echo $baseUrl.'oeufs_cocottes';?>">Œufs Cocottes</a></li>
                <li><a href="<?php echo $baseUrl.'oeufs_farcis';?>">Œufs Farcis</a></li>
                <li><a href="<?php echo $baseUrl.'omelette_fromage';?>">Omelette Au Fromage</a></li>
                <li><a href="<?php echo $baseUrl.'pancakes_jambon';?>">Pancakes Au Jambon</a></li>
                <li><a href="<?php echo $baseUrl.'petit_dej_allemand';?>">Petit-Dej A La Mode Allemande</a></li>
                <li><a href="<?php echo $baseUrl.'tarte_roquefort_noix';?>">Tarte Roquefort-Noix</a></li>
                <li><a href="<?php echo $baseUrl.'tartelettes_bleu_auvergne';?>">Tartelettes Au Bleu D'auvergne</a></li>
                <li><a href="<?php echo $baseUrl.'tartine_terroir';?>">Tartine Du Terroir</a></li>
                <li><a href="<?php echo $baseUrl.'tartine_anglaise';?>">Tartines A L’anglaise</a></li>
                <li><a href="<?php echo $baseUrl.'tartelettes_craquantes';?>">Tartelettes Craquantes</a></li>
                <li><a href="<?php echo $baseUrl.'tuiles_croquantes_parmesan';?>">Tuiles Croquantes Au Parmesan</a></li>
            </ul>
        </div>
    </div>
</div>