<?php
$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
$storeManager = $objectManager->get('\Magento\Store\Model\StoreManagerInterface');
$baseUrl = $storeManager->getStore()->getBaseUrl();
?>

<div class="row">
    <div class="col-md-12 col-lg 12 recettes">
        <div class="col-lg-12">
            <h2><?php echo __('RECETTES');?></h2>
            <ul>
                <li><a href="<?php echo $baseUrl.'petit_dejeuner';?>">Recettes de petits déjeuner</a></li>
                <li><a href="<?php echo $baseUrl.'dejeuner';?>">Recettes de déjeuner</a></li>
                <li><a href="<?php echo $baseUrl.'canard_olives';?>">Recettes de goter</a></li>
                <li><a href="<?php echo $baseUrl.'cannellonis_italienne';?>">Recettes de diner</a></li>
            </ul>
        </div>
    </div>
</div>