<!--@subject {{trans "Définir votre nouveau mot de passe"}}  @-->

{{template config_path="design/email/header_template"}}

<p class="greeting">{{trans "Cher(e) %name," name=$customer.name}}</p>

<p>Nous avons le plaisir de vous annoncer que le site <a href="http://lexel-paris.com">Lexel Paris</a> fait peau neuve !</p>
<p>A cette occasion nous vous offrons 20€ de réduction pour un minimum de 30€ d'achat en utilisant le code ci-dessous :</p>
<p style="color:red;font-size:24px;">BIENVENUE</p>
<p>Afin de profiter de l'offre et par soucis de sécurité, nous vous demandons dans un premier temps de définir un nouveau mot de passe :</p>

<table class="button" width="100%" border="0" cellspacing="0" cellpadding="0">
    <tr>
        <td>
            <table class="inner-wrapper" border="0" cellspacing="0" cellpadding="0" align="center">
                <tr>
                    <td align="center">
                        <a href="{{var this.getUrl($store,'customer/account/createPassword/',[_query:[id:$customer.id,token:$customer.rp_token],_nosid:1])}}" target="_blank">{{trans "Set a New Password"}}</a>
                    </td>
                </tr>
            </table>
        </td>
    </tr>
</table>


{{template config_path="design/email/footer_template"}}