<div class="row">
    <div class="col-md-12 col-lg 12 recettes">
        <div class="col-xs-12 col-sm-6 col-md-4 col-lg-4">
            <h2><?php echo __('Ananas à la noix de coco');?></h2>
            <ul>
                <li><img src="<?php echo $this->getViewFileUrl('images/recettes/cutlery.png'); ?>"> <span class="gray">Pour</span> : 2 personne</li>
                <li><img src="<?php echo $this->getViewFileUrl('images/recettes/clock.png'); ?>"> <span class="gray">Préparation</span> : 10 min.</li>
                <li><img src="<?php echo $this->getViewFileUrl('images/recettes/oven.png'); ?>"> <span class="gray">Cuisson</span> : 1h.</li>
            </ul>
            <h3 class="recette-part">Ingrédients</h3>
            <ul class="ingredients">
                <li>½ ananas (de préférence variété Victoria)</li>
                <li>50 g de sucre glace</li>
                <li>1 cuil. à soupe de noix de coco râpée</li>
            </ul>

        </div>
        <div class="col-xs-12 col-sm-6 col-md-4 col-lg-4">
            <img src="<?php echo $this->getViewFileUrl('images/recettes/ananas_coco.jpg'); ?>" alt="ananas à la noix de coco time nutrition">
        </div>
        <div class="col-xs-12 col-sm-12 col-md-4 col-lg-4">
            La variété la plus consommée et la plus cultivée d’ananas est la Cayenne lisse.<br>
            Son origine viendrait de la Guyane et son nom rappellerait l'absence de piquant sur les feuilles du toupet.<br>
            Il est essentiellement cultivé aujourd’hui en Côté d'Ivoire.<br>
            Vient ensuite la Queen Victoria, dit aussi simplement "ananas Victoria", importé de l'Ile Maurice, du Kenya et surtout de la Réunion.<br>
            Cet ananas est beaucoup plus petit, avec des feuilles dentelées et un goût plus sucré, un peu comme un bonbon.
        </div>

    </div>
</div>
<div class="row">
    <div class="col-md-12 col-lg-12 recettes">
        <h3 class="recette-part">Préparation</h3>
        <ul class="preparation">
            <li>Éplucher un ½ ananas et ôter le cœur à l'aide d'un emporte-pièce.</li>
            <li>Découper l’ananas en tranches fines.</li>
            <li>Préchauffer le four à 120° (therm. 4).</li>
            <li>Verser le sucre glace dans une assiette et passer les tranches d’ananas dans le sucre sur les deux faces.</li>
            <li>Secouer l'excédent et déposer les tranches sucrées sur une feuille de papier sulfurisé.</li>
            <li>Enfourner pendant 1 h.</li>
            <li>Dès que les tranches sont dorées les retirer du four et les laisser refroidir.</li>
            <li>Piquer alors les tranches sur des piques en bois et les déposer sur une assiette.</li>
            <li>Parsemer de noix de coco râpée.</li>
        </ul>
    </div>
</div>
<div class="row">
    <div class="col-md-12 col-lg-12">
        <div class="astuce">
            <i class="fa fa-caret-right" aria-hidden="true"></i> ASTUCES TIME NUTRITION
            <div>
                Nous vous recommandons d’accompagner ces brochettes de 2 boules de sorbet aux agrumes (orange ou mandarine).
            </div>
        </div>

    </div>
</div>