<div class="row">
    <div class="col-md-12 col-lg 12 recettes">
        <div class="col-xs-12 col-sm-6 col-md-4 col-lg-4">
            <h2><?php echo __('Aumonières aux pommes');?></h2>
            <ul>
                <li><img src="<?php echo $this->getViewFileUrl('images/recettes/cutlery.png'); ?>"> <span class="gray">Pour</span> : 2 personne</li>
                <li><img src="<?php echo $this->getViewFileUrl('images/recettes/clock.png'); ?>"> <span class="gray">Préparation</span> : 15 min.</li>
                <li><img src="<?php echo $this->getViewFileUrl('images/recettes/oven.png'); ?>"> <span class="gray">Cuisson</span> : 15 min.</li>
            </ul>
            <h3 class="recette-part">Ingrédients</h3>
            <ul class="ingredients">
                <li>3 feuilles de brick</li>
                <li>2 pommes, variété Reinette ou Golden</li>
                <li>3 cuil. à soupe de miel</li>
                <li>1 sachet d'infusion pommes-cannelle</li>
                <li>25 cl. d'eau bouillante</li>
                <li>1 noix de beurre</li>
                <li>1 cuil. à soupe d'huile</li>
                <li>Cannelle</li>
                <li>Sucre vanillé</li>
                <li>Piques en bois ou ficelle</li>
            </ul>

        </div>
        <div class="col-xs-12 col-sm-6 col-md-4 col-lg-4">
            <img src="<?php echo $this->getViewFileUrl('images/recettes/aumonieres_pommes.jpg'); ?>" alt="aumonières au pommes time nutrition">
        </div>
        <div class="col-xs-12 col-sm-12 col-md-4 col-lg-4">

        </div>

    </div>
</div>
<div class="row">
    <div class="col-md-12 col-lg-12 recettes">
        <h3 class="recette-part">Préparation</h3>
        <ul class="preparation">
            <li>Préchauffer le four à 220° (therm. 7).</li>
            <li>Éplucher les pommes, les couper en 8.</li>
            <li>Plonger le sachet d'infusion dans l'eau bouillante avec 1 cuil. à soupe de miel et laisser infuser 5 min.</li>
            <li>Verser sur les pommes et laisser un peu refroidir.</li>
            <li>Placer ensuite dans une poêle les pommes avec l'infusion et 2 cuil. à soupe de miel.</li>
            <li>Faire caraméliser les quartiers de pomme de chaque côté à feu vif, saupoudrer de cannelle et de sucre vanillé.</li>
            <li>Dans un bol verser 1 cuil. à soupe d'huile et la noix de beurre, et mettre celui-ci 30 secondes au micro-ondes.</li>
            <li>Pendant ce temps, découper dans une feuille de brick 2 ronds de 10 cm. de diamètre.</li>
            <li>Enduire d'huile et beurre fondu à l'aide d'un pinceau, les 2 feuilles de brick restantes et les 2 ronds sur les 2 faces.</li>
            <li>Placer les ronds au centre de chaque feuille de brick.</li>
            <li>Répartir les quartiers de pommes caramélisés au centre de chaque rond.</li>
            <li>Refermer en aumônières en les maintenant à l'aide de piques en bois ou de ficelle.</li>
            <li>Placer les aumônières sur une feuille de papier sulfurisé et enfourner 10 min. à 220° (therm. 7).</li>
        </ul>
    </div>
</div>
<div class="row">
    <div class="col-md-12 col-lg-12">
        <div class="astuce">
            <i class="fa fa-caret-right" aria-hidden="true"></i> ASTUCES TIME NUTRITION
            <div>
                Surveillez la cuisson, les feuilles de brick doivent être bien dorées.
            </div>
        </div>

    </div>
</div>