<div class="row">
    <div class="col-md-12 col-lg 12 recettes">
        <div class="col-xs-12 col-sm-6 col-md-4 col-lg-4">
            <h2><?php echo __('Chaud-Froid de pêches au caramel');?></h2>
            <ul>
                <li><img src="<?php echo $this->getViewFileUrl('images/recettes/cutlery.png'); ?>"> <span class="gray">Pour</span> : 1 personne</li>
                <li><img src="<?php echo $this->getViewFileUrl('images/recettes/clock.png'); ?>"> <span class="gray">Préparation</span> : 1 min.</li>
                <li><img src="<?php echo $this->getViewFileUrl('images/recettes/oven.png'); ?>"> <span class="gray">Cuisson</span> : 1 min.</li>
            </ul>
            <h3 class="recette-part">Ingrédients</h3>
            <ul class="ingredients">
                <li>2 pêches au sirop</li>
                <li>50 g de sucre</li>
                <li>1 cuil. à soupe de vinaigre d'alcool</li>
                <li>Eau</li>
            </ul>

        </div>
        <div class="col-xs-12 col-sm-6 col-md-4 col-lg-4">
            <img src="<?php echo $this->getViewFileUrl('images/recettes/chaud_froid_peche_caramel.jpg'); ?>" alt="chaud froid de pêches au caramel time nutrition">
        </div>
        <div class="col-xs-12 col-sm-12 col-md-4 col-lg-4">
            Nous vous proposon d’ajouter à ce goûter deux boules de sorbet à la pêche.<br>
            Attention ! Ce plat est très riche en sucre et peu gêner les personnes à risque diabétique.<br>
            Pour que ce goûter soit un véritable délice, veillez à mélanger dans chaque cuillérée la pêche, le caramel et le sorbet.
        </div>

    </div>
</div>
<div class="row">
    <div class="col-md-12 col-lg-12 recettes">
        <h3 class="recette-part">Préparation</h3>
        <ul class="preparation">
            <li>Couper les pêches en deux.</li>
            <li>Les disposer dans une assiette.</li>
            <li>Passer l'assiette au micro-ondes 1 min. à puissance maxi.</li>
            <span>Préparation du nappage caramel :</span>
            <li>Dans une casserole, mettre le sucre, le vinaigre et 14 cl d'eau sur un feu doux.</li>
            <li>Peu à peu, le sirop bouillonne et se colore. Quand il devient roux et commence à fumer, verser doucement 28 cl d'eau par dessus.</li>
            <li>Prolonger l'ébullition pendant 1 min pour que le sucre fonde dans l'eau.</li>
            <li>Dès que le sucre est fondu, recouvrir les pêches avec le caramel fluide.</li>
            <li>Déguster.</li>
        </ul>
    </div>
</div>
<div class="row">
    <div class="col-md-12 col-lg-12">
        <div class="astuce">
            <i class="fa fa-caret-right" aria-hidden="true"></i> ASTUCES TIME NUTRITION
            <div>
                Ces crêpes peuvent se préparer d'avance et se garder une journée au réfrigérateur ou se congeler.
            </div>
        </div>

    </div>
</div>