<div class="row">
    <div class="col-md-12 col-lg 12 recettes">
        <div class="col-xs-12 col-sm-6 col-md-4 col-lg-4">
            <h2><?php echo __('Chaud-froid mandarines chocolat');?></h2>
            <ul>
                <li><img src="<?php echo $this->getViewFileUrl('images/recettes/cutlery.png'); ?>"> <span class="gray">Pour</span> : 1 personne</li>
                <li><img src="<?php echo $this->getViewFileUrl('images/recettes/clock.png'); ?>"> <span class="gray">Préparation</span> : 5 min.</li>
            </ul>
            <h3 class="recette-part">Ingrédients</h3>
            <ul class="ingredients">
                <li>4 mandarines fraîches</li>
                <li>30 g de chocolat noir</li>
            </ul>

        </div>
        <div class="col-xs-12 col-sm-6 col-md-4 col-lg-4">
            <img src="<?php echo $this->getViewFileUrl('images/recettes/chaud_froid_mandarine_chocolat.jpg'); ?>" alt="chaud-froid mandarine chocolat time nutrition">
        </div>
        <div class="col-xs-12 col-sm-12 col-md-4 col-lg-4">
            L'alliance subtile du chocolat et de la mandarine : un goûter de prestige facile à réaliser.<br>
            À noter, aujourd’hui, la mandarine commune est progressivement remplacée par ses hybrides dépourvus de pépins, notamment la clémentine (hybride de l’orange douce et de la mandarine).
        </div>

    </div>
</div>
<div class="row">
    <div class="col-md-12 col-lg-12 recettes">
        <h3 class="recette-part">Préparation</h3>
        <ul class="preparation">
            <li>Éplucher les mandarines fraîches.</li>
            <li>Séparer les quartiers et les déposer dans une assiette en une seule couche.</li>
            <li>Faire fondre le chocolat noir au micro-ondes puis arroser largement les quartiers de mandarines..</li>
            <li>Déguster aussitôt.</li>
        </ul>
    </div>
</div>
<div class="row">
    <div class="col-md-12 col-lg-12">
        <div class="astuce">
            <i class="fa fa-caret-right" aria-hidden="true"></i> ASTUCES TIME NUTRITION
            <div>
                Pour partager ce goûter à plusieurs vous pouvez le faire sous forme de fondue au chocolat, en piquant les mandarines sur des piques en bois et en les plongeant dans la fondue de chocolat.
            </div>
        </div>

    </div>
</div>