<div class="row">
    <div class="col-md-12 col-lg 12 recettes">
        <div class="col-xs-12 col-sm-6 col-md-4 col-lg-4">
            <h2><?php echo __('Compote Pommes-Poires au caramel');?></h2>
            <ul>
                <li><img src="<?php echo $this->getViewFileUrl('images/recettes/cutlery.png'); ?>"> <span class="gray">Pour</span> : 2 personne</li>
                <li><img src="<?php echo $this->getViewFileUrl('images/recettes/clock.png'); ?>"> <span class="gray">Préparation</span> : 5 min.</li>
                <li><img src="<?php echo $this->getViewFileUrl('images/recettes/oven.png'); ?>"> <span class="gray">Cuisson</span> : 25 min.</li>
            </ul>
            <h3 class="recette-part">Ingrédients</h3>
            <ul class="ingredients">
                <li>2 poires Comice</li>
                <li>2 pommes Reinette ou Golden</li>
                <li>100 g de sucre</li>
                <li>½ sachet de sucre vanillé</li>
                <li>1 cuil. à soupe d'eau</li>
                <li>Le jus d'un demi-citron</li>
            </ul>

        </div>
        <div class="col-xs-12 col-sm-6 col-md-4 col-lg-4">
            <img src="<?php echo $this->getViewFileUrl('images/recettes/compote_pomme_poire.jpg'); ?>" alt="compote pommes poires au caramel time nutrition">
        </div>
        <div class="col-xs-12 col-sm-12 col-md-4 col-lg-4">
            Définition du caramel : produit obtenu par la cuisson du sucre dans un peu d'eau ou de lait.<br>
            Le sucre qui se caramélise brunit à différents degrés.<br>
            Le caramel peut ainsi être doré, roux ou brun. On dit également caramel pour la confiserie faite de caramel mou.<br>
            Le caramel se vend également comme tartinade pour les rôties, comme garniture pour les desserts, etc.
        </div>

    </div>
</div>
<div class="row">
    <div class="col-md-12 col-lg-12 recettes">
        <h3 class="recette-part">Préparation</h3>
        <ul class="preparation">
            <li>Éplucher les poires et les pommes, les couper en dés et les arroser avec le jus de citron pour les empêcher de noircir.</li>
            <li>Dans une sauteuse verser le sucre humecté avec l'eau et chauffer à feu vif sans remuer.</li>
            <li>Dès que le caramel est blond (environ 3 min), incorporer les dés de fruits, baisser le feu et laisser mijoter 20 min.</li>
            <li>Répartir la compote dans deux coupes.</li>
            <li>Saupoudrer de sucre vanillé.</li>
            <li>Déguster.</li>
        </ul>
    </div>
</div>
<div class="row">
    <div class="col-md-12 col-lg-12">
        <div class="astuce">
            <i class="fa fa-caret-right" aria-hidden="true"></i> ASTUCES TIME NUTRITION
            <div>
                Pour faire de cette compote un plaisir gustatif et visuel, décorez chaque coupe de 2 feuilles de menthe.
            </div>
        </div>

    </div>
</div>