<div class="row">
    <div class="col-md-12 col-lg 12 recettes">
        <div class="col-xs-12 col-sm-6 col-md-4 col-lg-4">
            <h2><?php echo __('Délices choco-noisette');?></h2>
            <ul>
                <li><img src="<?php echo $this->getViewFileUrl('images/recettes/cutlery.png'); ?>"> <span class="gray">Pour</span> : 4 personnes</li>
                <li><img src="<?php echo $this->getViewFileUrl('images/recettes/clock.png'); ?>"> <span class="gray">Préparation</span> : 15 min.</li>
                <li><img src="<?php echo $this->getViewFileUrl('images/recettes/oven.png'); ?>"> <span class="gray">Cuisson</span> : 5 à 8 min.</li>
            </ul>
            <h3 class="recette-part">Ingrédients</h3>
            <ul class="ingredients">
                <li>120 g de chocolat noir à 70 %</li>
                <li>8 noix</li>
                <li>12 noisettes</li>
                <li>50 g d’amandes effilées</li>
            </ul>

        </div>
        <div class="col-xs-12 col-sm-6 col-md-4 col-lg-4">
            <img src="<?php echo $this->getViewFileUrl('images/recettes/delices_choco_noisette.jpg'); ?>" alt="délices choco-noisette time nutrition">
        </div>
        <div class="col-xs-12 col-sm-12 col-md-4 col-lg-4">
            La noisette se distingue des autres fruits à écale par son contenu très élevé en acides gras monoinsaturés (presque exclusivement sous forme d’acide oléique) et plutôt faible en acides gras polyinsaturés et saturés.<br>
            Pour cette raison nous lui préférons souvent l’amande ou les noix.
        </div>

    </div>
</div>
<div class="row">
    <div class="col-md-12 col-lg-12 recettes">
        <h3 class="recette-part">Préparation</h3>
        <ul class="preparation">
            <li>Décoquiller les noix et les noisettes.</li>
            <li>Concasser les noisettes.</li>
            <li>Dans une poêle antiadhésive, faire griller les noisettes concassées en remuant pour éviter qu'elles brûlent. Laisser refroidir.</li>
            <li>Casser le chocolat en petits morceaux.</li>
            <li>Les faire fondre au bain marie à feu très doux.</li>
            <li>Quand le chocolat est bien mou et les noisettes refroidies les mélanger.</li>
            <li>Sur du papier sulfurisé, à l'aide d'une cuillère à café déposer des petits tas du mélange et aplatir au maximum de manière à former des palets.</li>
            <li>Les parsemer de noix et d’amandes.</li>
            <li>Laisser refroidir dans un endroit frais puis les décoller du papier et les servir.</li>
        </ul>
    </div>
</div>
<div class="row">
    <div class="col-md-12 col-lg-12">
        <div class="astuce">
            <i class="fa fa-caret-right" aria-hidden="true"></i> ASTUCES TIME NUTRITION
            <div>
                Nous vous recommandons d’accompagner ces palets d’une boule de sorbet aux fraises ou de fraises au sucre.
            </div>
        </div>

    </div>
</div>