<div class="row">
    <div class="col-md-12 col-lg 12 recettes">
        <div class="col-xs-12 col-sm-6 col-md-4 col-lg-4">
            <h2><?php echo __('Délice d\'ananas au caramel');?></h2>
            <ul>
                <li><img src="<?php echo $this->getViewFileUrl('images/recettes/cutlery.png'); ?>"> <span class="gray">Pour</span> : 1 personne</li>
                <li><img src="<?php echo $this->getViewFileUrl('images/recettes/clock.png'); ?>"> <span class="gray">Préparation</span> : 2 min.</li>
                <li><img src="<?php echo $this->getViewFileUrl('images/recettes/oven.png'); ?>"> <span class="gray">Cuisson</span> : 10 min.</li>
            </ul>
            <h3 class="recette-part">Ingrédients</h3>
            <ul class="ingredients">
                <li>4 rondelles d'ananas en boîte + le jus de la boîte</li>
                <li>50 g de sucre</li>
                <li>1 cuil. à soupe de vinaigre d'alcool</li>
                <li>Eau</li>
            </ul>

        </div>
        <div class="col-xs-12 col-sm-6 col-md-4 col-lg-4">
            <img src="<?php echo $this->getViewFileUrl('images/recettes/delice_ananas_caramel.jpg'); ?>" alt="delice d'ananas au caramel time nutrition">
        </div>
        <div class="col-xs-12 col-sm-12 col-md-4 col-lg-4">
            Le jus d'ananas est très riche en enzymes qui aident la digestion et ont même des vertus anti-inflammatoires. <br>
            La consommation d’ananas provoque cependant une libération d’histamine dans l’organisme (comme la fraise, la tomate..).<br>
            Cela peut gêner certaines personnes et leur provoquer une intolérance alimentaire.
        </div>

    </div>
</div>
<div class="row">
    <div class="col-md-12 col-lg-12 recettes">
        <h3 class="recette-part">Préparation</h3>
        <ul class="preparation">
            <li>Mettre les rondelles d'ananas dans une assiette creuse.</li>
            <li>Dans une poêle chaude, faire réduire le jus d'ananas de moitié et l'ajouter aux fruits dans l'assiette et laisser refroidir.</li>
           <span>Pendant que les fruits refroidissent, préparer le caramel :</span>
            <li>Dans une casserole, mettre le sucre, le vinaigre et 14 cl d'eau sur un feu doux.</li>
            <li>Peu à peu, le sirop bouillonne et se colore. Quand il devient roux et commence à fumer, verser doucement 28 cl d'eau par dessus.</li>
            <li>Prolonger l'ébullition pendant 1 min pour que le sucre fonde dans l'eau.</li>
            <li>Dès que le sucre est fondu, prélever 4 cuil. à soupe de caramel et verser sur les rondelles d'ananas.</li>
        </ul>
    </div>
</div>
<div class="row">
    <div class="col-md-12 col-lg-12">
        <div class="astuce">
            <i class="fa fa-caret-right" aria-hidden="true"></i> ASTUCES TIME NUTRITION
            <div>
                S’il vous reste du caramel, laissez le refroidir et réservez-le dans un récipient bien fermé.<br>
                Vous pourrez ainsi le conserver deux à trois mois.
            </div>
        </div>

    </div>
</div>