<div class="row">
    <div class="col-md-12 col-lg 12 recettes">
        <div class="col-xs-12 col-sm-12 col-md-4 col-lg-4">
            <h2><?php echo __('Douceur d\'avocat');?></h2>
            <ul>
                <li><img src="<?php echo $this->getViewFileUrl('images/recettes/cutlery.png'); ?>"> <span class="gray">Pour</span> : 1 personne</li>
                <li><img src="<?php echo $this->getViewFileUrl('images/recettes/clock.png'); ?>"> <span class="gray">Préparation</span> : 2 min.</li>
            </ul>
            <h3 class="recette-part">Ingrédients</h3>
            <ul class="ingredients">
                <li>1 avocat</li>
                <li>2 cuil. à soupe de miel de montagne</li>
            </ul>

        </div>
        <div class="col-xs-12 col-sm-12 col-md-4 col-lg-4">
            <img src="<?php echo $this->getViewFileUrl('images/recettes/douceur_avocat.jpg'); ?>" alt="douceur d'avocat time nutrition">
        </div>
        <div class="col-xs-12 col-sm-12 col-md-4 col-lg-4">
            L’avocat est un fruit très nutritif qui contient beaucoup de matières grasses.<br>
            Il est aussi très riche en antioxydants, en fibres alimentaires et en vitamine B5 et K.
        </div>

    </div>
</div>
<div class="row">
    <div class="col-md-12 col-lg-12 recettes">
        <h3 class="recette-part">Préparation</h3>
        <ul class="preparation">
            <li>Couper l'avocat dans le sens de la longueur et enlever le noyau.</li>
            <li>Verser une cuil. à soupe de miel de montagne dans la cavité de chaque demi-avocat.</li>
            <li>Déguster</li>
        </ul>
    </div>
</div>
<div class="row">
    <div class="col-md-12 col-lg-12">
        <div class="astuce">
            <i class="fa fa-caret-right" aria-hidden="true"></i> ASTUCES TIME NUTRITION
            <div>
                Si vous voulez profiter pleinement du mélange sucré/salé, veillez à réunir dans une même cuillérée avocat et miel.<br>
                Vous pourrez trouver du vrai miel de montagne dans toutes les bonnes épiceries et dans certaines grandes surfaces.
            </div>
        </div>

    </div>
</div>