<div class="row">
    <div class="col-md-12 col-lg 12 recettes">
        <div class="col-xs-12 col-sm-6 col-md-4 col-lg-4">
            <h2><?php echo __('Figues Tièdes aux épices');?></h2>
            <ul>
                <li><img src="<?php echo $this->getViewFileUrl('images/recettes/cutlery.png'); ?>"> <span class="gray">Pour</span> : 4 personne</li>
                <li><img src="<?php echo $this->getViewFileUrl('images/recettes/clock.png'); ?>"> <span class="gray">Préparation</span> : 10 min.</li>
                <li><img src="<?php echo $this->getViewFileUrl('images/recettes/oven.png'); ?>"> <span class="gray">Cuisson</span> : 5 h. <span class="gray">Cuisson</span> : 12 min.</li>
            </ul>
            <h3 class="recette-part">Ingrédients</h3>
            <ul class="ingredients">
                <li>16 figues séchées</li>
                <li>4 cuil. à soupe d'huile d'olive</li>
                <li>1 sachet de sucre vanillé</li>
                <li>1 cuil. à café de mélange 4 épices</li>
                <li>1 sachet de thé Earl Grey</li>
                <li>Eau</li>
            </ul>

        </div>
        <div class="col-xs-12 col-sm-6 col-md-4 col-lg-4">
            <img src="<?php echo $this->getViewFileUrl('images/recettes/figues_epices.jpg'); ?>" alt="figues tiedes aux epices time nutrition">
        </div>
        <div class="col-xs-12 col-sm-12 col-md-4 col-lg-4">
            Fruit méditerranéen par excellence, la figue a une teneur élevée en minéraux.<br>
            Elle assure également un complément non négligeable en vitamines du groupe B (souvent déficitaires dans l’alimentation), ainsi qu’en substances anthocyaniques ayant des propriétés précieuses pour la santé des petits vaisseaux sanguins.
        </div>

    </div>
</div>
<div class="row">
    <div class="col-md-12 col-lg-12 recettes">
        <h3 class="recette-part">Préparation</h3>
        <ul class="preparation">
            <li>Faire frémir 75cl d'eau, éteindre le feu, plonger le sachet de thé pendant 2 min.</li>
            <li>Retirer le sachet et le remplacer par les figues.</li>
            <li>Laisser tremper les figues pendant 5 heures.</li>
            <li>Préchauffer le four à 200° (therm. 6).</li>
            <li>Huiler un plat.</li>
            <li>Égoutter les figues et les disposer sur le plat.</li>
            <li>Verser 25 cl. d'eau et 4 cuil. à soupe d'huile d'olive sur les figues, les saupoudrer avec le mélange 4 épices et le sucre vanillé.</li>
            <li>Enfourner pendant 10 min.</li>
            <li>Disposer les figues sur des petites assiettes.</li>
            <li>Faire réduire le jus de cuisson et le verser en filet autour des figues.</li>
            <li>Servir tiède.</li>
        </ul>
    </div>
</div>
<div class="row">
    <div class="col-md-12 col-lg-12">
        <div class="astuce">
            <i class="fa fa-caret-right" aria-hidden="true"></i> ASTUCES TIME NUTRITION
            <div>
                Pour consommer la figue, il est préférable de la peler au voisinage de la queue.<br>
                En effet, dans cette zone du fruit, la peau est assez épaisse.<br>
                Et surtout, il peut s’y trouver des traces du "latex" présent dans les feuilles et les rameaux de la plante.<br>
                Ce suc d’apparence laiteuse renferme des enzymes.<br>
                Son contact avec les lèvres ou la muqueuse de la bouche pourrait provoquer des irritations.
            </div>
        </div>

    </div>
</div>