<div class="row">
    <div class="col-md-12 col-lg 12 recettes">
        <div class="col-xs-12 col-sm-6 col-md-4 col-lg-4">
            <h2><?php echo __('Fraises Caramélisées');?></h2>
            <ul>
                <li><img src="<?php echo $this->getViewFileUrl('images/recettes/cutlery.png'); ?>"> <span class="gray">Pour</span> : 2 personne</li>
                <li><img src="<?php echo $this->getViewFileUrl('images/recettes/clock.png'); ?>"> <span class="gray">Préparation</span> : 15 min.</li>
                <li><img src="<?php echo $this->getViewFileUrl('images/recettes/oven.png'); ?>"> <span class="gray">Cuisson</span> : 6 à 10 min.</li>
            </ul>
            <h3 class="recette-part">Ingrédients</h3>
            <ul class="ingredients">
                <li>300 g de fraises</li>
                <li>200 g de sucre</li>
                <li>2 cuil. à soupe d'eau</li>
                <li>1 cuil. à soupe d'huile d'amande</li>
            </ul>

        </div>
        <div class="col-xs-12 col-sm-6 col-md-4 col-lg-4">
            <img src="<?php echo $this->getViewFileUrl('images/recettes/fraises_caramelisees.jpg'); ?>" alt="fraises caramelisees time nutrition">
        </div>
        <div class="col-xs-12 col-sm-12 col-md-4 col-lg-4">
            Au sens botanique du terme, les « vrais » fruits de la fraise sont en fait les akènes, ces petits grains foncés (vert à brun) et secs.<br>
            Ils sont communément appelés à tort pépins alors que ce dernier terme ne devrait désigner que leur minuscule graine centrale.<br>
            On les trouve disposés régulièrement dans des alvéoles plus ou moins profondes sur la fraise.
        </div>

    </div>
</div>
<div class="row">
    <div class="col-md-12 col-lg-12 recettes">
        <h3 class="recette-part">Préparation</h3>
        <ul class="preparation">
            <li>Laver les fraises en gardant feuilles et queues.</li>
            <li>Dans une poêle mettre le sucre et l'eau et faire caraméliser à feu moyen.</li>
            <li>Pendant ce temps enduire un plat d'huile d'amande.</li>
            <li>Dès que le caramel atteint une couleur dorée, retirer la casserole du feu.</li>
            <li>Plonger les fraises dans le caramel en les tenant par la queue pour bien les enrober et les reposer sur le plat huilé.</li>
            <li>Servir rapidement pour que le caramel reste croquant.</li>
        </ul>
    </div>
</div>
<div class="row">
    <div class="col-md-12 col-lg-12">
        <div class="astuce">
            <i class="fa fa-caret-right" aria-hidden="true"></i> ASTUCES TIME NUTRITION
            <div>
                Pour un goûter plein de fraîcheur, accompagnez les fraises caramélisées d’une boule de sorbet au citron.
            </div>
        </div>

    </div>
</div>