<div class="row">
    <div class="col-md-12 col-lg 12 recettes">
        <div class="col-xs-12 col-sm-6 col-md-4 col-lg-4">
            <h2><?php echo __('Lychees au coulis de framboise');?></h2>
            <ul>
                <li><img src="<?php echo $this->getViewFileUrl('images/recettes/cutlery.png'); ?>"> <span class="gray">Pour</span> : 2 personnes</li>
                <li><img src="<?php echo $this->getViewFileUrl('images/recettes/clock.png'); ?>"> <span class="gray">Préparation</span> : 15 min.</li>
                <li><img src="<?php echo $this->getViewFileUrl('images/recettes/oven.png'); ?>"> <span class="gray">Cuisson</span> : 10 min.</li>
            </ul>
            <h3 class="recette-part">Ingrédients</h3>
            <ul class="ingredients">
                <li>300 g de fraises</li>
                <li>200 g de sucre</li>
                <li>2 cuil. à soupe d'eau</li>
                <li>1 cuil. à soupe d'huile d'amande</li>
            </ul>

        </div>
        <div class="col-xs-12 col-sm-6 col-md-4 col-lg-4">
            <img src="<?php echo $this->getViewFileUrl('images/recettes/lychees_coulis_framboise.jpg'); ?>" alt="lychees au coulis de framboise time nutrition">
        </div>
        <div class="col-xs-12 col-sm-12 col-md-4 col-lg-4">
            Juteux, sucrés, doux et agréablement parfumés, faciles à décortiquer et à déguster en une ou deux bouchées, les lychees ou litchis sont des fruits d’origine chinoise qui sont généralement appréciés d'un grand nombre de personnes.
        </div>

    </div>
</div>
<div class="row">
    <div class="col-md-12 col-lg-12 recettes">
        <h3 class="recette-part">Préparation</h3>
        <ul class="preparation">
            <li>Dans une casserole, faire cuire, à feu doux et à couvert les framboises et le sucre (environ 10 min.).</li>
            <span>Pendant ce temps :</span>
            <li>Égoutter les lychees et les présenter dans deux coupes.</li>
            <li>Les napper de sauce aux framboises.</li>
        </ul>
    </div>
</div>
<div class="row">
    <div class="col-md-12 col-lg-12">
        <div class="astuce">
            <i class="fa fa-caret-right" aria-hidden="true"></i> ASTUCES TIME NUTRITION
            <div>
                Très fragiles, les framboises se conservent mal.<br>
                On doit les achèter quand elles sont fermes, d’une belle couleur brillante, et les consommer le jour même si possible.<br>
                On peut les remplacer par des mûres, un peu plus résistantes.
            </div>
        </div>

    </div>
</div>