<div class="row">
    <div class="col-md-12 col-lg 12 recettes">
        <div class="col-xs-12 col-sm-12 col-md-4 col-lg-4">
            <h2><?php echo __('Noix de cajou au caramel');?></h2>
            <ul>
                <li><img src="<?php echo $this->getViewFileUrl('images/recettes/cutlery.png'); ?>"> <span class="gray">Pour</span> : 2 personnes</li>
                <li><img src="<?php echo $this->getViewFileUrl('images/recettes/clock.png'); ?>"> <span class="gray">Préparation</span> : 2 min.</li>
                <li><img src="<?php echo $this->getViewFileUrl('images/recettes/oven.png'); ?>"> <span class="gray">Cuisson</span> : 5 min.</li>
            </ul>
            <h3 class="recette-part">Ingrédients</h3>
            <ul class="ingredients">
                <li>1 pot à yaourt de noix de cajou non salées</li>
                <li>12 morceaux de sucre</li>
            </ul>

        </div>
        <div class="col-xs-12 col-sm-12 col-md-4 col-lg-4">
            <img src="<?php echo $this->getViewFileUrl('images/recettes/noix_cajou_caramel.jpg'); ?>" alt="noix de cajou au caramel time nutrition">
        </div>
        <div class="col-xs-12 col-sm-12 col-md-4 col-lg-4">
            La noix de cajou est produite au Vietnam, en Inde, au Nigéria, au Brésil...<br>
            Elle arrive aujourd’hui au premier rang de la production des fruits oléagineux, ayant largement dépassé l’amande !
        </div>

    </div>
</div>
<div class="row">
    <div class="col-md-12 col-lg-12 recettes">
        <h3 class="recette-part">Préparation</h3>
        <ul class="preparation">
            <li>Dans une poêle antiadhésive chauffée à feu vif, déposer les 12 morceaux de sucre et les humecter d'eau.</li>
            <li>Pendant la cuisson, remuer la poêle pour que la caramélisation se fasse de façon homogène.</li>
            <li>Au bout de 5 min. environ, dès que le caramel est doré, déposer les noix de cajou et à l'aide d'une spatule en bois les enrober de caramel.</li>
            <li>Déposer dans un bol et déguster.</li>
        </ul>
    </div>
</div>
<div class="row">
    <div class="col-md-12 col-lg-12">
        <div class="astuce">
            <i class="fa fa-caret-right" aria-hidden="true"></i> ASTUCES TIME NUTRITION
            <div>
                Veillez à ne pas utiliser pour cette recette des noix de cajou salées.
            </div>
        </div>

    </div>
</div>