<div class="row">
    <div class="col-md-12 col-lg 12 recettes">
        <div class="col-xs-12 col-sm-6 col-md-4 col-lg-4">
            <h2><?php echo __('Poires fondantes aux amandes et au chocolat');?></h2>
            <ul>
                <li><img src="<?php echo $this->getViewFileUrl('images/recettes/cutlery.png'); ?>"> <span class="gray">Pour</span> : 2 personne</li>
                <li><img src="<?php echo $this->getViewFileUrl('images/recettes/clock.png'); ?>"> <span class="gray">Préparation</span> : 10 min.</li>
                <li><img src="<?php echo $this->getViewFileUrl('images/recettes/oven.png'); ?>"> <span class="gray">Cuisson</span> : 10 min.</li>
            </ul>
            <h3 class="recette-part">Ingrédients</h3>
            <ul class="ingredients">
                <li>3 poires (de préférence Williams)</li>
                <li>75 g de sucre</li>
                <li>10 g d'amandes effilées</li>
                <li>60 g de chocolat noir</li>
                <li>1 cl. de jus d'orange</li>
            </ul>

        </div>
        <div class="col-xs-12 col-sm-6 col-md-4 col-lg-4">
            <img src="<?php echo $this->getViewFileUrl('images/recettes/poires_amandes_chocolat.jpg'); ?>" alt="poires amandes chocolat time nutrition">
        </div>
        <div class="col-xs-12 col-sm-12 col-md-4 col-lg-4">
            Comme les pommes et les pêches, la peau des poires est riche en anti-oxydants, vitamines mais peut être aussi contaminée par les pesticides.
        </div>

    </div>
</div>
<div class="row">
    <div class="col-md-12 col-lg-12 recettes">
        <h3 class="recette-part">Préparation</h3>
        <ul class="preparation">
            <li>Eplucher les poires.</li>
            <li>Dans une sauteuse verser le jus d'orange, ajouter les poires et le sucre.</li>
            <li>Laisser cuire à feu moyen pendant 5 min puis baisser le feu et laisser mijoter encore 5 min.</li>
            <span>Pendant ce temps :</span>
            <li>Dans une poêle anti-adhésive, faire griller les amandes effilées en les remuant avec une cuillère en bois pour les empêcher de brûler.</li>
            <li>Pendant ce temps, faire fondre le chocolat au micro-ondes.</li>
            <li>Quand la compote est cuite la répartir sur deux assiettes, la parsemer d'amandes grillées et de coulis de chocolat.</li>
            <li>Déguster aussitôt.</li>
        </ul>
    </div>
</div>
<div class="row">
    <div class="col-md-12 col-lg-12">
        <div class="astuce">
            <i class="fa fa-caret-right" aria-hidden="true"></i> ASTUCES TIME NUTRITION
            <div>
                Pour encore plus de plaisir, nous vous conseillons de rajouter à cette préparation 1 cuillère de sorbet à la poire.
            </div>
        </div>

    </div>
</div>