<div class="row">
    <div class="col-md-12 col-lg 12 recettes">
        <div class="col-xs-12 col-sm-6 col-md-4 col-lg-4">
            <h2><?php echo __('Pommes au four');?></h2>
            <ul>
                <li><img src="<?php echo $this->getViewFileUrl('images/recettes/cutlery.png'); ?>"> <span class="gray">Pour</span> : 2 personnes</li>
                <li><img src="<?php echo $this->getViewFileUrl('images/recettes/clock.png'); ?>"> <span class="gray">Préparation</span> : 5 min.</li>
                <li><img src="<?php echo $this->getViewFileUrl('images/recettes/oven.png'); ?>"> <span class="gray">Cuisson</span> : 25 min.</li>
            </ul>
            <h3 class="recette-part">Ingrédients</h3>
            <ul class="ingredients">
                <li>2 pommes</li>
                <li>40 g de poudre d'amandes</li>
                <li>2 cuil. à soupe de lait de coco</li>
                <li>2 cuil. à soupe de confiture d'abricots</li>
                <li>1 cuil. à soupe de pistaches</li>
                <li>1 cuil. à soupe de cassonade</li>
                <li>1 jus de citron</li>
            </ul>

        </div>
        <div class="col-xs-12 col-sm-6 col-md-4 col-lg-4">
            <img src="<?php echo $this->getViewFileUrl('images/recettes/pommes_four.jpg'); ?>" alt="pommes au four time nutrition">
        </div>
        <div class="col-xs-12 col-sm-12 col-md-4 col-lg-4">

        </div>
    </div>
</div>
<div class="row">
    <div class="col-md-12 col-lg-12 recettes">
        <h3 class="recette-part">Préparation</h3>
        <ul class="preparation">
            <li>Laver les pommes.</li>
            <li>Enlever les trognons à l'aide d'un vide pomme.</li>
            <li>Dans un bol, mélanger la poudre d'amandes avec le lait de coco et la confiture d'abricots.</li>
            <li>Remplir chaque pomme avec le mélange amandes/confiture.</li>
            <li>Garnir un plat de papier d'aluminium et y déposer les pommes.</li>
            <li>Arroser de jus de citron.</li>
            <li>Saupoudrer de cassonade et enfourner 25 min. therm. 5 (150°).</li>
            <li>Déguster chaud.</li>
        </ul>
    </div>
</div>
<div class="row">
    <div class="col-md-12 col-lg-12">
        <div class="astuce">
            <i class="fa fa-caret-right" aria-hidden="true"></i> ASTUCES TIME NUTRITION
            <div>
                Vous pouvez décliner cette recette avec des poires.<br>
                Pour cela choisir 2 grosses poires (de préférence Comice), 2 cuil. à soupe de sucre et 25 g de beurre.<br>
                Préparation : Laver les poires, les creuser avec un vide pommes pour ôter les pépins. Déposer les poires dans un plat à four huilé.<br>
                Dans chaque poire mettre une cuillère de sucre et quelques noisettes de beurre végétal. Enfourner 30 à 35 min à 225° (therm. 7).
            </div>
        </div>

    </div>
</div>