<div class="row">
    <div class="col-md-12 col-lg 12 recettes">
        <div class="col-xs-12 col-sm-12 col-md-4 col-lg-4">
            <h2><?php echo __('Salade fraicheur');?></h2>
            <ul>
                <li><img src="<?php echo $this->getViewFileUrl('images/recettes/cutlery.png'); ?>"> <span class="gray">Pour</span> : 4 personnes</li>
                <li><img src="<?php echo $this->getViewFileUrl('images/recettes/clock.png'); ?>"> <span class="gray">Préparation</span> : 15 min.</li>
                <li><img src="<?php echo $this->getViewFileUrl('images/recettes/oven.png'); ?>"> <span class="gray">Cuisson</span> : 2 min.</li>
            </ul>
            <h3 class="recette-part">Ingrédients</h3>
            <ul class="ingredients">
                <li>75 g de sucre</li>
                <li>2 pamplemousses</li>
                <li>2 kiwis</li>
                <li>1 boîte d'ananas</li>
                <li>200 g de fraises ou cerises</li>
            </ul>

        </div>
        <div class="col-xs-12 col-sm-12 col-md-4 col-lg-4">
            <img src="<?php echo $this->getViewFileUrl('images/recettes/salade_fraicheur.jpg'); ?>" alt="salade fraicheur time nutrition">
        </div>
        <div class="col-xs-12 col-sm-12 col-md-4 col-lg-4">
            La consommation de pamplemousse ou de jus de pamplemousse peut entraîner une augmentation ou, moins fréquemment, une diminution des effets de certains médicaments.<br>
            Presque toutes les classes de médicaments sont susceptibles d’être touchées.<br>
            Demandez conseil à votre médecin ou votre pharmacien !

        </div>
    </div>
</div>
<div class="row">
    <div class="col-md-12 col-lg-12 recettes">
        <h3 class="recette-part">Préparation</h3>
        <ul class="preparation">
            <li>Egoutter les tranches d’ananas et les découper en dés.</li>
            <li>Éplucher les kiwis et les couper en rondelles.</li>
            <li>Éplucher les pamplemousses à vif au dessus d'un plat creux pour récupérer le jus. Les couper en rondelles puis en morceaux.</li>
            <li>Verser le jus récupéré dans une petite casserole avec le sucre, porter à ébullition pendant 2 à 3 min.</li>
            <li>Dans des petites coupes, disposer les morceaux de pamplemousse, d'ananas et les fraises.</li>
            <li>Arroser avec le sirop.</li>
            <li>Déguster aussitôt.</li>
        </ul>
    </div>
</div>
<div class="row">
    <div class="col-md-12 col-lg-12">
        <div class="astuce">
            <i class="fa fa-caret-right" aria-hidden="true"></i> ASTUCES TIME NUTRITION
            <div>
                Pomélo ou pamplemousse : contrairement à ce que l’on croit habituellement, le fruit que nous consommons n'est pas le pamplemousse, mais le pomélo. Le « véritable » pamplemousse est plutôt rare en Occident et est surtout cultivé dans les pays tropicaux tels que la Thaïlande, le Vietnam, le sud de la Chine, la Malaisie et l'Indonésie.<br>
                C’est un fruit de couleur verdâtre à l'écorce (peau) épaisse.<br>
                Il est plus gros que le fruit que nous connaissons et contient de 16 à 18 quartiers remplis de pépins. Il peut avoir la forme d'une poire.
            </div>
        </div>

    </div>
</div>