<div class="row">
    <div class="col-md-12 col-lg 12 recettes">
        <div class="col-xs-12 col-sm-6 col-md-4 col-lg-4">
            <h2><?php echo __('Salade de fruits exotiques');?></h2>
            <ul>
                <li><img src="<?php echo $this->getViewFileUrl('images/recettes/cutlery.png'); ?>"> <span class="gray">Pour</span> : 2 personnes</li>
                <li><img src="<?php echo $this->getViewFileUrl('images/recettes/clock.png'); ?>"> <span class="gray">Préparation</span> : 10 min.</li>
                <li><img src="<?php echo $this->getViewFileUrl('images/recettes/oven.png'); ?>"> <span class="gray">Cuisson</span> : 2 min au micro-ondes.</li>
            </ul>
            <h3 class="recette-part">Ingrédients</h3>
            <ul class="ingredients">
                <li>2 tranches d'ananas au sirop</li>
                <li>100 g de papaye au sirop</li>
                <li>1 banane</li>
                <li>50 ml. de lait de coco</li>
                <li>Le jus d'un ½ citron</li>
                <li>½ cuil. à café rase de poivre chinois aux baies de Sichuan moulues</li>
                <li>½ cuil. à café rase de cannelle en poudre</li>
                <li>½ cuil. à café rase de cumin en poudre</li>
                <li>1 cuil. à soupe de feuille de menthe ciselée</li>
            </ul>

        </div>
        <div class="col-xs-12 col-sm-6 col-md-4 col-lg-4">
            <img src="<?php echo $this->getViewFileUrl('images/recettes/salade_fruits_exotiques.jpg'); ?>" alt="salade de fruits exotiques time nutrition">
        </div>
        <div class="col-xs-12 col-sm-12 col-md-4 col-lg-4">
           
        </div>
    </div>
</div>
<div class="row">
    <div class="col-md-12 col-lg-12 recettes">
        <h3 class="recette-part">Préparation</h3>
        <ul class="preparation">
            <li>Dans un bol, mélanger le lait de coco, la menthe et les épices.</li>
            <li>Éplucher la banane et la couper en rondelles.</li>
            <li>Arroser de jus de citron.</li>
            <li>Égoutter les fruits au sirop et les couper en dés.</li>
            <li>Répartir les fruits égouttés dans 2 coupes et les napper de lait aux épices.</li>
            <li>Les enfourner 2 min au micro-ondes.</li>
            <li>Déguster.</li>
        </ul>
    </div>
</div>
<div class="row">
    <div class="col-md-12 col-lg-12">
        <div class="astuce">
            <i class="fa fa-caret-right" aria-hidden="true"></i> ASTUCES TIME NUTRITION
            <div>
                Vous pouvez agrémenter ce goûter d’une boule de sorbet de votre choix.<br>
                Nous vous conseillons également de décliner cette salade de fruits à votre guise afin de découvrir chaque jour de nouveaux fruits exotiques.
            </div>
        </div>

    </div>
</div>