<div class="row">
    <div class="col-md-12 col-lg 12 recettes">
        <div class="col-xs-12 col-sm-6 col-md-4 col-lg-4">
            <h2><?php echo __('Sorbet Banane');?></h2>
            <ul>
                <li><img src="<?php echo $this->getViewFileUrl('images/recettes/cutlery.png'); ?>"> <span class="gray">Pour</span> : 4 personnes</li>
                <li><img src="<?php echo $this->getViewFileUrl('images/recettes/clock.png'); ?>"> <span class="gray">Préparation</span> : 10 min.</li>
                <li><img src="<?php echo $this->getViewFileUrl('images/recettes/oven.png'); ?>"> <span class="gray">Réfrigération</span> : 2h.</li>
            </ul>
            <h3 class="recette-part">Ingrédients</h3>
            <ul class="ingredients">
                <li>4 bananes bien mûres</li>
                <li>2 citrons</li>
                <li>100 g de sucre semoule</li>
            </ul>

        </div>
        <div class="col-xs-12 col-sm-6 col-md-4 col-lg-4">
            <img src="<?php echo $this->getViewFileUrl('images/recettes/sorbet_banane.jpg'); ?>" alt="sorbet banane time nutrition">
        </div>
        <div class="col-xs-12 col-sm-12 col-md-4 col-lg-4">
            Les bananes constituent un élément essentiel du régime alimentaire de certains pays et constituent une nourriture de base pour des millions de personnes sous les tropiques.
        </div>
    </div>
</div>
<div class="row">
    <div class="col-md-12 col-lg-12 recettes">
        <h3 class="recette-part">Préparation</h3>
        <ul class="preparation">
            <li>Éplucher les bananes et les mixer avec le jus d'un citron.</li>
            <li>Faire tiédir le jus du second citron. Y ajouter le sucre.</li>
            <li>Quand le sucre est dissout, ajouter le sirop aux bananes.</li>
            <li>Mélanger et battre le tout.</li>
            <li>Verser dans un bac à glace et placer au congélateur pendant 2 h.</li>
        </ul>
    </div>
</div>
<div class="row">
    <div class="col-md-12 col-lg-12">
        <div class="astuce">
            <i class="fa fa-caret-right" aria-hidden="true"></i> ASTUCES TIME NUTRITION
            <div>
                Nous vous conseillons de servir ce sorbet avec un mélange de fruits rouges (groseilles, framboises et fraises des bois).<br>
                Arrosez le tout de sirop de fraise et décorer de feuilles de menthe.
            </div>
        </div>

    </div>
</div>