<div class="row">
    <div class="col-md-12 col-lg 12 recettes">
        <div class="col-xs-12 col-sm-6 col-md-4 col-lg-4">
            <h2><?php echo __('SORBET CITRON VERT');?></h2>
            <ul>
                <li><img src="<?php echo $this->getViewFileUrl('images/recettes/clock.png'); ?>"> <span class="gray">Préparation</span> : 20 min.</li>
                <li><img src="<?php echo $this->getViewFileUrl('images/recettes/oven.png'); ?>"> <span class="gray">Cuisson du sirop</span> : 10 min. <span class="gray">Prise en glace</span> : 3 h</li>
            </ul>
            <h3 class="recette-part">Ingrédients</h3>
            <ul class="ingredients">
                <li>3 citrons verts non traités</li>
                <li>5,5 dl de jus de citron</li>
                <li>2 blancs d'œufs</li>
                <li>35 g de sucre glace</li>
                <li>2,5 dl d'eau</li>
                <li>300 g de sucre</li>
            </ul>

        </div>
        <div class="col-xs-12 col-sm-6 col-md-4 col-lg-4">
            <img src="<?php echo $this->getViewFileUrl('images/recettes/sorbet_citron_vert.jpg'); ?>" alt="sorbet citron vert time nutrition">
        </div>
        <div class="col-xs-12 col-sm-12 col-md-4 col-lg-4">
            Le citron vert, aussi appelé la lime ou limette, est un agrume. Le fruit a un aspect de petit citron de 3 à 6 cm de diamètre.<br>
            Son écorce est fine et lisse, de couleur vert foncé. La chair, de même couleur, est juteuse et très acide.

        </div>
    </div>
</div>
<div class="row">
    <div class="col-md-12 col-lg-12 recettes">
        <h3 class="recette-part">Préparation</h3>
        <ul class="preparation">
            <li>Dans une casserole verser l'eau et le sucre.</li>
            <li>Faire dissoudre le sucre à feu moyen à découvert.</li>
            <li>Laisser refroidir.</li>
            <li>Prélever le zeste de trois citrons verts les râper.</li>
            <li>Presser les citrons.</li>
            <li>Verser le jus et les zestes râpés dans le sirop refroidi.</li>
            <li>Verser dans la sorbetière ou dans un moule en métal.</li>
            <li>Mettre au congélateur pendant environ 2h (si vous utilisez un moule, remuer le sorbet à la fourchette de temps en temps pour empêcher la formation de cristaux).</li>
            <span>Quand le mélange commence à prendre</span>
            <li>Fouetter les blancs en neige très ferme en incorporant le sucre glace.</li>
            <li>Les mélanger délicatement au sorbet.</li>
            <li>Le placer à nouveau au congélateur environ 1 h.</li>
            <li>Le battre avant de servir.</li>
        </ul>
    </div>
</div>
<div class="row">
    <div class="col-md-12 col-lg-12">
        <div class="astuce">
            <i class="fa fa-caret-right" aria-hidden="true"></i> ASTUCES TIME NUTRITION
            <div>
                Pour bien réussir un sorbet, tout doit être le plus froid possible : le bloc de la turbine, le mélange, les cuillères pour sortir la glace en fin de turbinage.<br>
                Mettez même vos boites au congélateur avant de les remplir, cela évitera que la glace se réchauffe avant de se re-solidifer.
            </div>
        </div>

    </div>
</div>