<div class="row">
    <div class="col-md-12 col-lg 12 recettes">
        <div class="col-xs-12 col-sm-6 col-md-4 col-lg-4">
            <h2><?php echo __('Sorbet Kiwi');?></h2>
            <ul>
                <li><img src="<?php echo $this->getViewFileUrl('images/recettes/cutlery.png'); ?>"> <span class="gray">Pour</span> : 2 personnes</li>
                <li><img src="<?php echo $this->getViewFileUrl('images/recettes/clock.png'); ?>"> <span class="gray">Préparation</span> : 10 min.</li>
                <li><img src="<?php echo $this->getViewFileUrl('images/recettes/oven.png'); ?>"> <span class="gray">Congélation</span> : 5 min.</li>
            </ul>
            <h3 class="recette-part">Ingrédients</h3>
            <ul class="ingredients">
                <li>6 kiwis</li>
                <li>le jus d' ½ orange</li>
                <li>le jus d' ½ citron</li>
                <li>1 cuil. à soupe de miel</li>
                <li>1 cuil. à soupe de sucre</li>
            </ul>

        </div>
        <div class="col-xs-12 col-sm-6 col-md-4 col-lg-4">
            <img src="<?php echo $this->getViewFileUrl('images/recettes/sorbet_kiwi.jpg'); ?>" alt="sorbet kiwi time nutrition">
        </div>
        <div class="col-xs-12 col-sm-12 col-md-4 col-lg-4">

        </div>
    </div>
</div>
<div class="row">
    <div class="col-md-12 col-lg-12 recettes">
        <h3 class="recette-part">Préparation</h3>
        <ul class="preparation">
            <li>Éplucher les kiwis.</li>
            <li>En couper 3 en tranches fines. Les garder au réfrigérateur.</li>
            <li>Mixer le reste avec le jus d'orange et de citron, le sucre et le miel pendant 20 secondes.</li>
            <li>Passer cette purée au chinois en appuyant à l'aide du dos d'une cuillère.</li>
            <li>Verser dans une sorbetière et mettre au froid pendant 30 min. minimum (selon le modèle de sorbetière).</li>
            <li>Disposer les tranches de kiwis dans deux assiettes et poser une boule de sorbet au milieu.</li>
        </ul>
    </div>
</div>
<div class="row">
    <div class="col-md-12 col-lg-12">
        <div class="astuce">
            <i class="fa fa-caret-right" aria-hidden="true"></i> ASTUCES TIME NUTRITION
            <div>
                Pour que cette composition soit un véritable chef d’œuvre, décorez l’assiette avec deux fraises et quelques feuilles de menthe.
            </div>
        </div>

    </div>
</div>