<div class="row">
    <div class="col-md-12 col-lg 12 recettes">
        <div class="col-xs-12 col-sm-6 col-md-4 col-lg-4">
            <h2><?php echo __('TRIO CARAMELISE RAISINS/PIGNONS/NOIX');?></h2>
            <ul>
                <li><img src="<?php echo $this->getViewFileUrl('images/recettes/cutlery.png'); ?>"> <span class="gray">Pour</span> : 2 personnes</li>
                <li><img src="<?php echo $this->getViewFileUrl('images/recettes/clock.png'); ?>"> <span class="gray">Préparation</span> : 5 min.</li>
                <li><img src="<?php echo $this->getViewFileUrl('images/recettes/oven.png'); ?>"> <span class="gray">Cuisson</span> : 3 min.</li>
            </ul>
            <h3 class="recette-part">Ingrédients</h3>
            <ul class="ingredients">
                <li>2 pommes</li>
                <li>40 g de poudre d'amandes</li>
                <li>2 cuil. à soupe de lait de coco</li>
                <li>2 cuil. à soupe de confiture d'abricots</li>
                <li>1 cuil. à soupe de pistaches</li>
                <li>1 cuil. à soupe de cassonade</li>
                <li>1 jus de citron</li>
            </ul>

        </div>
        <div class="col-xs-12 col-sm-6 col-md-4 col-lg-4">
            <img src="<?php echo $this->getViewFileUrl('images/recettes/trio_raisin_pignon_noix.jpg'); ?>" alt="trio caramelisé raisins pignons noix time nutrition">
        </div>
        <div class="col-xs-12 col-sm-12 col-md-4 col-lg-4">
            Les raisins secs de Corinthe (Grèce) n'ont pas de pépin sont très colorés (bleus à noirs) et offrent une saveur légèrement poivrée.<br>
            Plus gros et plus parfumés, les raisins secs de Malaga (Espagne)ont une saveur qui rappelle le Muscat. Les raisins secs de Smyrne, (Turquie, Californie des Etats-Unis, Sultana d'Australie) sont quant à eux de petits raisins noirs, sans pépin et relativement sucrés.<br>
            Éviter si possible les raisins trop sulfités.
        </div>
    </div>
</div>
<div class="row">
    <div class="col-md-12 col-lg-12 recettes">
        <h3 class="recette-part">Préparation</h3>
        <ul class="preparation">
            <li>Verser le sucre dans une casserole et mouiller avec l'eau.</li>
            <li>Porter à ébullition à feu vif, baisser le feu et cuire à feu doux jusqu'à l'obtention d'un caramel clair.</li>
            <li>Plonger les cerneaux de noix, les retirer à l'aide d'une fourchette et les déposer sur un papier sulfurisé légèrement huilé.</li>
            <li>Faire de même avec les raisins et les laisser durcir, et enfin avec les pignons.</li>
            <li>Répartir les noix, les raisins et les pignons sur deux assiettes.</li>
            <li>Déguster.</li>
        </ul>
    </div>
</div>
<div class="row">
    <div class="col-md-12 col-lg-12">
        <div class="astuce">
            <i class="fa fa-caret-right" aria-hidden="true"></i> ASTUCES TIME NUTRITION
            <div>
                Vous pouvez remplacer selon votre convenance les raisins, les pignons et les noix par des noisettes, des amandes ou autre fruit sec de votre choix.
            </div>
        </div>

    </div>
</div>