<?php
$ajax = $block->getUrl('conges/index/ajax',['secure'=> true]);
?>

<div class="container">
    <div class="row">
        <div class="col-lg-12">
            <table id="datatable">
                <thead>
                     <td>Prenom Nom</td>
                    <td>Date de demande	</td>
                    <td>Date de début</td>
                    <td>Date de fin</td>
                    <td>Statut</td>
<!--                    <td>Commentaire</td>-->
                    <td>Valider / Refuser</td>
                </thead>
                <tbody>
<!--  Ici les data sur les congès-->
                </tbody>
            </table>
        </div>
    </div>

</div>
<script type="text/javascript">
    require(
        [
            'jquery',
            'datatable'
        ], function ($) {
            $(document).ready(function () {
                var table = $('#datatable').DataTable({
                    "sAjaxSource": '<?= $ajax; ?>',
                    "fnRowCallback": function( nRow, aData, iDisplayIndex, iDisplayIndexFull ) {
                        console.log(aData)
                            if ( aData.accepted == "0" && aData.updated_at == '0000-00-00 00:00:00')
                            {
                            //  $('td', nRow).css("background-color", 'rgba(0,0,255,0.1)');
                            } else if ( aData.accepted == "1" ) {
                                $('td', nRow).css("background-color", 'rgba(0,255,0,0.2)');
                            } else {
                                $('td', nRow).css("background-color", 'rgba(255,0,0,0.2)');

                            }

                    },
                    "fnDrawCallback": function (oSettings) { // CallBack quand Datatable a terminer de charger
                        /**
                         * Fonction permettant d'accepter ou refuser au clique sue le bouton
                         */
                        $('.choice').each( function(){
                            var btn = $(this);
                            btn.on('click', function () {
                                // Les variables a envoyées au controller pour l'update de la ligne
                                var id = btn.attr('data_id');
                                var action = btn.attr('data_action');
                                $.ajax({
                                    url: '<?= $ajax ?>',
                                    method: "POST",
                                    data:{'conges_id': id, 'action':action},
                                    success: function (response) {
                                         table.ajax.reload();
                                    }
                                })

                            })
                        })
                    },
                    "aoColumns": [
                        { "mData": "name" },
                        { "mData": "created_at" },
                        { "mData": "start_at" },
                        { "mData": "end_at" },
                        {
                            "targets": 3,
                            "data": null,
                            "render": function ( data, type, row, meta ) {
                                console.log(data.manager_validation)
                                if (data.accepted == 0 && data.updated_at == '0000-00-00 00:00:00') {
                                    return '<span class="label label-info square">En attente ...</span>';
                                } else if (data.accepted == 0 && data.updated_at != '0000-00-00 00:00:00') {
                                    return '<span class="label label-danger square">Refusé</span>';
                                } else {
                                    return '<span class="label label-success square">Accepté</span>';
                                }
                            }
                        },
//                        { "mData": "comment" },
                        {
                            "targets": 5,
                            "sortable": false,
                            "data": null,
                            "render": function ( data, type, row, meta ) {
                                if ( data.updated_at == '0000-00-00 00:00:00' ) {
                                    return '<button  type="button" data_action="accept" data_id="'+data.conges_id+'"  class="choice btn btn-success">Accepter</button> <button  type="button" data_action="refuse" data_id="'+data.conges_id+'" class="choice btn btn-danger">Refuser</button>';
                                } else {
                                    return "";
                                }
                            }
                        },
                    ],
                    'language':
                        {
                            "sProcessing":     "Traitement en cours...",
                            "sSearch":         "Rechercher&nbsp;:",
                            "sLengthMenu":     "Afficher _MENU_ &eacute;l&eacute;ments",
                            "sInfo":           "Affichage de l'&eacute;l&eacute;ment _START_ &agrave; _END_ sur _TOTAL_ &eacute;l&eacute;ments",
                            "sInfoEmpty":      "Affichage de l'&eacute;l&eacute;ment 0 &agrave; 0 sur 0 &eacute;l&eacute;ment",
                            "sInfoFiltered":   "(filtr&eacute; de _MAX_ &eacute;l&eacute;ments au total)",
                            "sInfoPostFix":    "",
                            "sLoadingRecords": "Chargement en cours...",
                            "sZeroRecords":    "Aucun &eacute;l&eacute;ment &agrave; afficher",
                            "sEmptyTable":     "Aucune donn&eacute;e disponible dans le tableau",
                            "oPaginate": {
                                "sFirst":      "Premier",
                                "sPrevious":   "Pr&eacute;c&eacute;dent",
                                "sNext":       "Suivant",
                                "sLast":       "Dernier"
                            },
                            "oAria": {
                                "sSortAscending":  ": activer pour trier la colonne par ordre croissant",
                                "sSortDescending": ": activer pour trier la colonne par ordre d&eacute;croissant"
                            }
                        }
                });
                /**
                 * Fin Datatable
                 */



            });

        }
    )

</script>