<?php
    // Appel du block Gesco
    $block = $block->getLayout()->createBlock('Ntic\ArchiveGesco\Block\Gesco');
?>

<div class="row">
    <div class="order-card-wrapper panel panel-default col-md-10 col-md-offset-1">
        <div class="panel-heading">
            <div class="order-card-panel-title">
                <h3 class="panel-title">DÉTAILS DE L'ABONNEMENT / <?php echo $block->subscriptionData()['subscription']['number_contract']; ?></h3>
                <a class="customer-card-link btn btn-info" href="<?php echo $this->getUrl(); ?>archivegesco/customercard?id=<?php echo $block->indexData()['customer']['client_id']; ?>">Retour</a>
            </div>
        </div>
        <!-- INFOS COMMANDE -->
        <div class="panel-body">
            <div class="row">
                <div class="panel panel-default col-md-12">
                    <div class="panel-body">
                        <!-- ORDER -->
                        <div class="order-card-data">
                            <div class="more-data flex-between">
                                <div class="data-contract">
                                    <div class="number-contract">Numéro de l'abonnement : <span><?php echo $block->subscriptionData()['subscription']['number_contract']; ?></span></div>
                                    <div class="ref-contract">Référence de l'abonnement : <span><?php echo $block->subscriptionData()['subscription']['ref_contract']; ?></span></div>
                                </div>
                                <div class="date-contract">
                                    <div class="date-activated">Date de début de l'abonnement : <span><?php echo $block->dateFormat($block->subscriptionData()['subscription']['date_activated']); ?></span></div>
                                    <div class="date-activated">Date de fin de l'abonnement : <span><?php echo $block->dateFormat($block->subscriptionData()['subscription']['date_end_subscription']); ?></span></div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>

            <!-- INFOS ADRESSE -->
            <div class="block-order flex-between">
                <div class="block-left">
                    <div class="address-panel panel panel-default col-md-5">
                        <div class="panel-heading flex-between">
                            <h3 class="panel-title">Adresse(s) de livraison / expédition</h3>
                        </div>
                        <div class="panel-body flex-between">
                            <!-- LIVRAISON -->
                            <div class="address-shipping">
                                <h4>Adresse de livraison</h4>
                                <hr>
                                <?php
                                if(!empty($block->subscriptionData()['shipping'])) {
                                    ?>
                                    <div class="client-name">
                                        <?php echo !empty($block->subscriptionData()['shipping']['gender']) ? $block->subscriptionData()['shipping']['gender'] : ''; ?>
                                        <span><?php echo !empty($block->subscriptionData()['shipping']['lastname']) ? $block->subscriptionData()['shipping']['lastname'] : ''; ?></span>
                                        <?php echo !empty($block->subscriptionData()['shipping']['firstname']) ? $block->subscriptionData()['shipping']['firstname'] : ''; ?>
                                    </div>
                                    <div class="street">
                                        <?php echo !empty($block->subscriptionData()['shipping']['addr1']) ? 'Rue : '.$block->subscriptionData()['shipping']['addr1'] : ''; ?>
                                        <br>
                                        <?php echo !empty($block->subscriptionData()['shipping']['addr2']) ? 'Rue : '.$block->subscriptionData()['shipping']['addr2'] : ''; ?>
                                        <br>
                                        <?php echo !empty($block->subscriptionData()['shipping']['addr3']) ? 'Rue : '.$block->subscriptionData()['shipping']['addr3'] : ''; ?>
                                    </div>
                                    <div class="city">
                                        <?php echo !empty($block->subscriptionData()['shipping']['zip_code']) ? $block->subscriptionData()['shipping']['zip_code'] : ''; ?>
                                        <?php echo !empty($block->subscriptionData()['shipping']['city']) ? $block->subscriptionData()['shipping']['city'] : ''; ?>
                                    </div>
                                    <?php
                                } else {
                                    ?>
                                    <div class="customer-name">
                                        <?php echo $block->indexData()['customer']['gender']; ?>
                                        <span><?php echo $block->indexData()['customer']['lastname']; ?></span>
                                        <?php echo $block->indexData()['customer']['firstname']; ?>
                                    </div>
                                    <div class="street">
                                        <?php echo !empty($block->indexData()['customer']['addr1']) ? $block->indexData()['customer']['addr1'] : ''; ?>
                                        <br>
                                        <?php echo !empty($block->indexData()['customer']['addr2']) ? $block->indexData()['customer']['addr2'] : ''; ?>
                                        <br>
                                        <?php echo !empty($block->indexData()['customer']['addr3']) ? $block->indexData()['customer']['addr3'] : ''; ?>
                                    </div>
                                    <div class="city">
                                        <?php echo $block->indexData()['customer']['zip_code']; ?>
                                        <?php echo $block->indexData()['customer']['city']; ?>
                                    </div>
                                    <?php
                                }
                                ?>
                            </div>

                            <!-- EXPEDITION -->
                            <div class="address-delivery">
                                <h4>Informations d'expédition</h4>
                                <hr>
                                <?php
                                if(!empty($block->subscriptionData()['delivery'])) {
                                    ?>
                                    <div class="wish-date">Date souhaitée : <?php echo $block->dateFormat($block->subscriptionData()['delivery']['wish_date']); ?></div>
                                    <div class="shipping-name">Nom de livraison : <?php echo $block->subscriptionData()['delivery']['shipping_name']; ?></div>
                                    <div class="transport-mode">Mode de transport : <?php echo $block->subscriptionData()['delivery']['transport_mode']; ?></div>
                                    <?php
                                }
                                ?>
                            </div>
                        </div>
                    </div>

                    <!-- PARCEL -->
                    <?php
                        if($block->subscriptionData()['subscription']['type'] != 'A') {
                            ?>
                            <div class="block-parcel">
                                <div class="parcel-panel panel panel-primary col-md-5">
                                    <div class="panel-heading flex-between">
                                        <h3 class="panel-title">Colis</h3>
                                    </div>
                                    <div class="panel-body">
                                        <?php
                                            if(!empty($block->subscriptionData()['parcel'])) {
                                                ?>
                                                <div class="header-parcel flex-around">
                                                    <div class="row-header">
                                                        <div class="header-real-date">Date de livraison</div>
                                                        <div class="header-parcel-number">Suivi de livraison</div>
                                                        <div class="header-bill-number">Numéro de facture</div>
                                                    </div>
                                                </div>
                                                <?php
                                                foreach ($block->subscriptionData()['parcel'] as $parcel) {
                                                    ?>
                                                    <div class="row-parcel">
                                                        <div class="panel panel-default">
                                                            <div class="panel-body">
                                                                <div class="data-parcel flex-around">
                                                                    <div class="real-date"><?php echo $block->dateFormat($parcel['real_date']); ?></div>
                                                                    <div class="parcel-number">
                                                                        <?php
                                                                            if(is_numeric($parcel['parcel_number'])) {
                                                                                ?>
                                                                                <a class="btn btn-warning" href="http://www.colissimo.fr/portail_colissimo/suivre.do?colispart=<?php echo $parcel['parcel_number']; ?>" target="_blank">
                                                                                    Suivre le colis
                                                                                </a>
                                                                                <?php
                                                                            } else {
                                                                                ?>
                                                                                <?php echo utf8_encode($parcel['parcel_number']); ?>
                                                                                <?php
                                                                            }
                                                                        ?>
                                                                    </div>
                                                                    <div class="bill-number"><?php echo $parcel['bill_number']; ?></div>
                                                                </div>
                                                            </div>
                                                        </div>
                                                    </div>
                                                    <?php
                                                }
                                            } else {
                                                ?>
                                                <div class="no-parcel">Oups, Aucune livraison pour cet abonnement</div>
                                                <?php
                                            }
                                        ?>
                                    </div>
                                </div>
                            </div>
                            <?php
                        }
                    ?>
                </div>

                <!-- PRODUCTS -->
                <div class="subscription-panel panel panel-danger col-md-6">
                    <div class="panel-heading flex-between">
                        <h3 class="panel-title">Produit(s) de l'abonnement</h3>
                        <?php
                            if(empty($block->subscriptionData()['club_card'])) {
                                ?>
                                <div class="total-order">Nombre total de produit(s) : <span><?php echo count($block->subscriptionData()['subscription_products']); ?></span></div>
                                <?php
                            }
                        ?>
                    </div>
                    <div class="panel-body">
                        <?php
                            if(!empty($block->subscriptionData()['club_card'])) {
                                ?>
                                <div class="card-club-name"><?php echo $block->subscriptionData()['club_card']['card_club_name']; ?> (<?php echo $block->subscriptionData()['subscription']['number_month']; ?> mois)</div>
                                <div class="amount">Mensualité : <span><?php echo str_replace('.', ',', $block->subscriptionData()['club_card']['amount']); ?> €</span></div>
                                <?php
                            } else {
                                if(!empty($block->subscriptionData()['subscription_products'])) {
                                    foreach ($block->subscriptionData()['subscription_products'] as $product) {
                                        ?>
                                        <div class="row-product">
                                            <div class="panel panel-default">
                                                <div class="panel-body">
                                                    <div class="data-products flex-between">
                                                        <div
                                                            class="number-contract"><?php echo $product['products_name']; ?></div>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                        <?php
                                    }
                                } else {
                                    ?>
                                    <div class="no-products">Oups, aucun produit trouvé(s) pour cet abonnement</div>
                                    <?php
                                }
                            }
                        ?>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<script type="text/javascript">
    require(['jquery', 'jquery.bootstrap'], function ($) {
        $( document ).ready(function() {
            var href = $('.fiche-client a').attr("href");
            var new_href = href + "?id=<?php echo $block->indexData()['customer']['client_id'];?>";

            $('.fiche-client a').attr("href", new_href);
        });
    });
</script>