<div class="row">
    <h1 class="who-title"><?php echo __('Charte qualité'); ?></h1>
</div>
<div class="row who-content">
    <p>
        Les produits cosmétiques, que nous commercialisons depuis plus de 20 ans, font partie de la vie quotidienne de
        nos clients et leur usage est intimement lié à la santé et au bien-être.<br>
        Pour garantir une totale innocuité à nos clients, notre service Recherche & Développement a mis en place une
        démarche qualité très stricte et vigilante portant sur chacune des étapes du développement de nos produits :
    </p>
    <div class="col-md-6 col-lg-6 who">
        <img class="img-responsive" src="<?php echo $this->getViewFileUrl('images/qualite/img-1.jpg', array('_secure'=>true)); ?>" alt="" />
    </div>
    <div class="col-md-6 col-lg-6 who qualite-txt text-center">
        <strong>
            Etape 1<br>
            Sur LES INGRÉDIENTS DE FORMULATION<br>
            Sélection rigoureuse
        </strong>
        <br>
        <br>
        Nous sélectionnons rigoureusement nos ingrédients parmi des matières premières qui ont fait l’objet d’un dossier
        d’évaluation de leur sécurité ou qui ont été avalisées par des commissions scientifiques et autorités compétentes
        telles que la SCCP (Comité scientifique des produits de consommation) ou le COLIPA (Association Européenne des
        produits cosmétiques, de toilette et de la parfumerie).
    </div>
    <div class="col-md-6 col-lg-6 who qualite-txt qualite-txt-lg text-center">
        <strong>
            Etape 2<br>
            SUR LA FORMULE<br>
            Batterie de test
        </strong>
        <br>
        <br>
        Lorsque la formule cosmétique est mise au point, elle subit une batterie de tests :<br>
        Les tests de vieillissement du produit en conditions accélérées pour confirmer la parfaite stabilité de la
        formule dans le temps. Les tests de compatibilité pour mesurer la compatibilité entre la formule et l’emballage
        et garantir le bon fonctionnement du packaging tout au long de l’utilisation du produit.<br>
        Le test spécifique sur le système conservateur de la formule pour garantir l’innocuité du produit sur plusieurs mois.
        Un double test d’évaluation du potentiel irritant du produit réalisé in vitro (sur des cultures cellulaires) et
        in vivo (sur des volontaires humains) pour attester de la parfaite tolérance oculaire et cutanée du produit cosmétique.<br>
        <strong>Lexel Paris ne teste aucun de ses produits et ingrédients sur les animaux sauf si la loi l’exige.</strong>

    </div>
    <div class="col-md-6 col-lg-6 who qualite-txt-lg">
        <img class="img-responsive" src="<?php echo $this->getViewFileUrl('images/qualite/img-2.jpg', array('_secure'=>true)); ?>" alt="" />
    </div>
    <div class="col-md-6 col-lg-6 who">
        <img class="img-responsive" src="<?php echo $this->getViewFileUrl('images/qualite/img-3.jpg', array('_secure'=>true)); ?>" alt="" />
    </div>
    <div class="col-md-6 col-lg-6 who qualite-txt text-center">
        <strong>
            Etape 3<br>
            SUR LE PRODUIT FINI<br>
            Approbation par un expert toxicologue indépendant
        </strong>
        <br>
        <br>
        Une fois la batterie de tests approuvée, le produit est soumis à un examen rigoureux par un expert toxicologue
        indépendant qui va, pour chaque produit, délivrer une attestation garantissant sa parfaite sécurité.
    </div>
    <div class="col-md-6 col-lg-6 who qualite-txt text-center">
        <strong>
            Etape 4<br>
            SUR LE PRODUIT MIS SUR LE MARCHÉ <br>
            Cosmétovigilance
        </strong>
        <br>
        <br>
        Lorsque le produit est mis sur le marché, nos engagements concernant la qualité se poursuivent à travers une
        plate-forme de cosmétovigilance mise en place pour recueillir les remarques des Conseillères Beauté et des clientes.
        Ces remontées d’informations sont prises en compte de manière systématique et aboutissent à la mise en place des
        mesures correctives sur un ou plusieurs éléments du produit.
    </div>
    <div class="col-md-6 col-lg-6 who">
        <img class="img-responsive" src="<?php echo $this->getViewFileUrl('images/qualite/img-4.jpg', array('_secure'=>true)); ?>" alt="" />
    </div>

</div>
<div class="row">
    <div class="col-md-12 col-lg-12 text-justify who-content">
        Enfin, nous sommes membres actifs de l’association COSMED qui regroupe nombre de professionnels de la cosmétique
        du Grand Sud et qui travaille en étroite collaboration avec les autorités compétentes, notamment l’AFSSaPS
        (Agence Française de Sécurité Sanitaire des Produits de Santé) et le ministère de la Santé. Nous sommes également
        adhérents de la Société Française de Cosmétologie (association créée en 1951) qui rassemble plus de 1500 professionnels
        issus de différents horizons : chimistes, biologistes, dermatologues, toxicologues, parfumeurs …<br>
        Nous conjuguons au quotidien nos actions avec celles des professionnels du secteur et des autorités compétentes pour assurer à nos clients la parfaite qualité et fiabilité de nos produits.
        <br><br>
        <strong>La Santé et le Bien-être de nos clients sont et resteront notre priorité.</strong>
    </div>
</div>

<div class="row who-link ">
    <div class="col-md-6 col-lg-6 text-left">
        <a class="btn btn-who" href="<?php echo $block->getUrl('notre-philosophie', ['_secure' => true]);?>"><?php echo __('Notre Philosophie'); ?></a>
    </div>

</div>