<div class="row">
    <h1 class="who-title"><?php echo __('QUI SOMMES NOUS ?'); ?></h1>
</div>
<div class="row who-content">
   <div class="col-md-6 col-lg-6 who">
       <img class="img-responsive" src="<?php echo $this->getViewFileUrl('images/who/img-1.jpg', array('_secure'=>true)); ?>" alt="" />
   </div>
    <div class="col-md-6 col-lg-6 who who-txt text-center">
        Lexel Paris est une marque française qui depuis 1993 s'est spécalisée dans la fabrication et la commercialisation
        de produits cosmétiques Haut de Gamme.
    </div>
    <div class="col-md-6 col-lg-6 who who-txt text-center">
        S’appuyant sur des solutions veillant à préserver le « capital jeunesse » de la peau, du visage et du corps, 
        la marque propose des soins ciblés suivant les différentes étapes de la vie et des habitudes beauté qui ont pu
        se transmettre depuis de nombreuses années de mère en fille.
        <br>
        Les offres « Rituel Beauté » intergénérationnelles, lancées en 2016, en sont un concentré et un résumé parfaits.
    </div>
    <div class="col-md-6 col-lg-6 who">
        <img class="img-responsive" src="<?php echo $this->getViewFileUrl('images/who/img-2.jpg', array('_secure'=>true)); ?>" alt="" />
    </div>
    <div class="col-md-6 col-lg-6 who">
        <img class="img-responsive" src="<?php echo $this->getViewFileUrl('images/who/img-3.jpg', array('_secure'=>true)); ?>" alt="" />
    </div>
    <div class="col-md-6 col-lg-6 who who-txt text-center">
        Lexel Paris a su tisser au fil du temps un lien fort avec ses clients, à travers son réseau national de
        conseillères beauté, qui proposent de vous rencontrer à votre domicile pour un soin beauté personnalisé qui
        vous permettra de découvrir la qualité des produits de la marque.
    </div>
    <div class="col-md-6 col-lg-6 who who-txt text-center">
        La large gamme des solutions LEXEL Paris répondra à tous les besoins beauté des femmes et des hommes, même les
        plus spécifiques.
    </div>
    <div class="col-md-6 col-lg-6 who">
        <img class="img-responsive" src="<?php echo $this->getViewFileUrl('images/who/img-4.jpg', array('_secure'=>true)); ?>" alt="" />
    </div>

</div>
<div class="row text-center">
    <div class="col-md-12 col-lg-12 who-link">
    Retrouvez tous ces produits et solutions « Beauté » sur le site internet <a href="http://lexel-paris.com">www.lexel-paris.com</a> ou <br>
    dans les boutiques LEXEL Paris de Montpellier et de Nice.
    </div>
</div>
<div class="row">
    <div class="col-md-12 col-lg-12 text-right">
    <a class="btn btn-who" href="<?php echo $block->getUrl('notre-philosophie', ['_secure' => true]);?>"><?php echo __('Notre Philosophie'); ?></a>
    </div>
</div>