<style>
    input[type="text"],
    input[type="password"],
    input[type="url"], input[type="tel"], input[type="search"], input[type="number"], input[type="datetime"], input[type="email"] {
        height: 36px;
        padding: 10px 16px;
        font-size: 18px;
        line-height: 1.3333333;
        border-radius: 6px;
    }
</style>
<?php
$url = $block->getUrl('conges/conges/save');
$ajax = $block->getUrl('conges/conges/index',['secure'=> true]);

?>

<div class="container-fluid">
    <div class="row" style="border-top: 1px solid rgba(0,0,0,0.1); border-bottom: 1px solid rgba(0,0,0,0.1); margin-bottom: 25px; padding-bottom:15px; background-color: #337ab7; color: white">
        <div class="col-md-5">
            <h2 class="text-center"><i class="fa fa-question-circle-o" aria-hidden="true"> Effectuer un demande de congés</i></h2>
        </div>
        <div class="col-md-6 col-md-offset-1">
            <h2 class="text-center"><i class="fa fa-paper-plane-o" aria-hidden="true"> Récapitulatif Congès</i></h2>
        </div>
    </div>
    <div class="row" >
        <div class="col-md-5 " style="background-color: aliceblue; border-radius: 8px; border: 1px solid rgba(0,0,0,0.1)">
            <form method="POST" action="<?= $url ?>" class="form-group" >

                <div class="form-check" style="padding-top: 25px;">
                    <label class="form-check-label">
                        <input class="form-check-input" type="radio" name="type" id="typeConges1" value="Congé payé (CP)" checked>
                        Congé payé (CP)
                    </label>
                </div>
                <div class="form-check">
                    <label class="form-check-label">
                        <input class="form-check-input" type="radio" name="type" id="typeConges2" value="Congé sans solde (CSS)
"> Congé sans solde (CSS)
                    </label>

                </div>

                <div class="form-group" style="padding-top: 25px">
                    <label for="start_at">Date de début :</label>
                    <input type="date" name="start_at" id="start_at" class="form-control" required>
                    <label for="end_at">Date de fin :</label>
                    <input type="date" name="end_at" id="end_at" class="form-control" required>
                </div>
                <input type="hidden" name="demandeur_id" value="<?= $block->getUid(); ?>">

                <button style="width: 100%; font-size: 1.6em" id="declarer" class="btn btn-primary"> Déclarer</button>
            </form>
        </div>

        <div class="col-md-6 col-md-offset-1 text-center">
            <div class="col-md-12">
                <table id="dataTable">
                    <thead>
                    <tr>
                        <td>Date de demande	</td>
                        <td>Date de début</td>
                        <td>Date de fin</td>
                        <td>Statut</td>
                        <td>Commentaire</td>
                    </tr>
                    </thead>
                    <tbody>

                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>

<script type="text/javascript">
    require(
        [
            'jquery',
            'datatable'
        ], function ($) {
            $(document).ready(function () {
                $('#dataTable').DataTable({
                    "sAjaxSource": '<?= $ajax; ?>',
                    "order": [[ 0, "desc" ]],
                    "aoColumns": [
                        { "mData": "created_at" },
                        { "mData": "start_at" },
                        { "mData": "end_at" },
                        {
                            "targets": 3,
                            "data": null,
                            "render": function ( data, type, row, meta ) {
                                if (data.accepted == 0 && data.updated_at == '0000-00-00 00:00:00') {
                                    return '<span class="label label-info square">En attente</span>';
                                } else if (data.accepted == 0 && data.updated_at != '0000-00-00 00:00:00') {
                                    return '<span class="label label-danger square">Refusé</span>';
                                } else {
                                    return '<span class="label label-success square">Accepté</span>';
                                }
                            }
                        },
                        { "mData": "comment" }
                    ],
                    'language':
                        {
                            "sProcessing":     "Traitement en cours...",
                            "sSearch":         "Rechercher&nbsp;:",
                            "sLengthMenu":     "Afficher _MENU_ &eacute;l&eacute;ments",
                            "sInfo":           "Affichage de l'&eacute;l&eacute;ment _START_ &agrave; _END_ sur _TOTAL_ &eacute;l&eacute;ments",
                            "sInfoEmpty":      "Affichage de l'&eacute;l&eacute;ment 0 &agrave; 0 sur 0 &eacute;l&eacute;ment",
                            "sInfoFiltered":   "(filtr&eacute; de _MAX_ &eacute;l&eacute;ments au total)",
                            "sInfoPostFix":    "",
                            "sLoadingRecords": "Chargement en cours...",
                            "sZeroRecords":    "Aucun &eacute;l&eacute;ment &agrave; afficher",
                            "sEmptyTable":     "Aucune donn&eacute;e disponible dans le tableau",
                            "oPaginate": {
                                "sFirst":      "Premier",
                                "sPrevious":   "Pr&eacute;c&eacute;dent",
                                "sNext":       "Suivant",
                                "sLast":       "Dernier"
                            },
                            "oAria": {
                                "sSortAscending":  ": activer pour trier la colonne par ordre croissant",
                                "sSortDescending": ": activer pour trier la colonne par ordre d&eacute;croissant"
                            }
                        }
                });


                /**
                 * Bouton pour afficher ou cacher le tableau resumer des evenement qui se chevauchent avec des congès
                 */
                $("#showTable").on('click', function () {
                    $("#table-container").slideToggle();
                });
            })
        }
    )

</script>