
<div class="footer-container">
    
    <div class="footer-2">
        <div class="footer-inside row">
            <div class="text-center col-xs-4 col-md-4 col-lg-4 liens-footer">
                <div class="liens-footer-content">
                    <li><strong>LEXEL PARIS</strong></li>
                    <li>17 Rue Saint Exupéry<br>34430 Saint Jean de Védas</li>
                    <li><a href="<?php echo $block->getUrl('contact', ['_secure' => true]);?>" class="btn btn-default ">Nous contacter</a></li>
                </div>
            </div>
            <div class="text-center col-xs-4 col-md-4 col-lg-4 liens-footer">
                <div class="liens-footer-content">
                    <li><strong>A PROPOS</strong></li>
                    <li><a href="<?php echo $block->getUrl('who', ['_secure' => true]);?>">Qui sommes-nous</a></li>
                    <li><a href="<?php echo $block->getUrl('partenaires', ['_secure' => true]);?>">Partenaires</a></li>
                    <li><a href="<?php echo $block->getUrl('conseil-beaute', ['_secure' => true]);?>">Nos Conseils Beauté</a></li>
                    <li><a href="<?php echo $block->getUrl('diagnostic', ['_secure' => true]);?>">Diagnostic Beauté personnalisé</a></li>
                    <li><a href="<?php echo $block->getUrl('recruit', ['_secure' => true]);?>">Recrutement</a></li>
                </div>
            </div>
            <div class="text-center col-xs-4 col-md-4 col-lg-4 liens-footer">
                <div class="liens-footer-content">
                    <li><strong>SERVICES</strong></li>
                    <li><a href="<?php echo $block->getUrl('paiement-securise', ['_secure' => true]);?>">Paiement Sécurisé</a></li>
                    <li><a href="<?php echo $block->getUrl('modalites-livraison', ['_secure' => true]);?>">Modalités de livraison</a></li>
                    <li><a href="<?php echo $block->getUrl('retours', ['_secure' => true]);?>">Retours</a></li>
                </div>
            </div>
        </div>
    </div>
    <div class="copyright text-center">
        © Lexel Paris - 2017 |<a href="<?php echo $block->getUrl('conditions-generales-de-vente', ['_secure' => true]);?>">Conditions générales de ventes</a>|<a href="<?php echo $block->getUrl('mentions-legales', ['_secure' => true]);?>">Mentions légales</a>
    </div>
</div>

<img src="<?php /* @escapeNotVerified */ echo $block->getLogoSrc() ?>"
     alt="<?php /* @escapeNotVerified */ echo $block->getLogoAlt() ?>"
    <?php echo $block->getLogoWidth() ? 'width="' . $block->getLogoWidth() . '"' : '' ?>
    <?php echo $block->getLogoHeight() ? 'height="' . $block->getLogoHeight() . '"' : '' ?>
/>

<script>

    // ###################### MODULE FACEBOOK #####################
    window.fbAsyncInit = function() {
        FB.init({
            appId      : '1555808424540454',
            cookie     : true,
            xfbml      : true,
            version    : 'v2.11'
        });
        FB.AppEvents.logPageView();
        
    };
    (function(d, s, id){
        var js, fjs = d.getElementsByTagName(s)[0];
        if (d.getElementById(id)) {return;}
        js = d.createElement(s); js.id = id;
        js.src = "//connect.facebook.net/en_US/sdk.js";
        fjs.parentNode.insertBefore(js, fjs);
    }(document, 'script', 'facebook-jssdk'));
    // ###################### FIN MODULE FACEBOOK ###################

    require(['jquery'], function ($) {

        $('a.fa-user-o').hover(
            function(){
                $(this).removeClass("fa-user-o");
                $(this).addClass("fa-user");
            },
            function () {
                $(this).removeClass("fa-user");
                $(this).addClass("fa-user-o");
            }

        );
    });
</script>

<script type="text/javascript">
    (function() {
        window.sib = { equeue: [], client_key: "qnnqaxtqm8wjdkqjs29gt" };
        /* OPTIONAL: email for identify request*/
        // window.sib.email_id = 'example@domain.com';
        window.sendinblue = {}; for (var j = ['track', 'identify', 'trackLink', 'page'], i = 0; i < j.length; i++) { (function(k) { window.sendinblue[k] = function() { var arg = Array.prototype.slice.call(arguments); (window.sib[k] || function() { var t = {}; t[k] = arg; window.sib.equeue.push(t);})(arg[0], arg[1], arg[2]);};})(j[i]);}var n = document.createElement("script"),i = document.getElementsByTagName("script")[0]; n.type = "text/javascript", n.id = "sendinblue-js", n.async = !0, n.src = "https://sibautomation.com/sa.js?key=" + window.sib.client_key, i.parentNode.insertBefore(n, i), window.sendinblue.page();
    })();
</script>
