<?php
$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
$customerSession = $objectManager->create('Magento\Customer\Model\Session');
//var_dump($customerSession->getData());
if($customerSession->isLoggedIn()) { ?>
    <li class="customer-welcome">
        <span class="customer-name"
              role="link"
              tabindex="0"
              data-mage-init='{"dropdown":{}}'
              data-toggle="dropdown"
              data-trigger-keypress-button="true"
              data-bind="scope: 'customer'">
            <span data-bind="text: customer().fullname"></span>
            <button type="button"
                    class="action switch"
                    tabindex="-1"
                    data-action="customer-menu-toggle">
                <span><?php /* @escapeNotVerified */ echo __('Change')?></span>
            </button>
        </span>
        <script type="text/x-magento-init">
        {
            "*": {
                "Magento_Ui/js/core/app": {
                    "components": {
                        "customer": {
                            "component": "Magento_Customer/js/view/customer"
                        }
                    }
                }
            }
        }
        </script>
        <div class="customer-menu" data-target="dropdown">
            <ul class="header links menu_link">
                <li>
                    <a href="<?php echo $block->getUrl('customer/account', ['_secure' => true]);?>"><?php echo __('Account Dashboard');?></a>
                </li>
                <li>
                    <a href="<?php echo $block->getUrl('customer/account/edit', ['_secure' => true]);?>"><?php echo __('Account Information');?></a>
                </li>
                <li>
                    <a href="<?php echo $block->getUrl('customer/address', ['_secure' => true]);?>"><?php echo __('Address Book');?></a>
                </li>
                <li>
                    <a href="<?php echo $block->getUrl('sales/order/history', ['_secure' => true]);?>"><?php echo __('My Orders');?></a>
                </li>
                <li>
                    <a href="<?php echo $block->getUrl('paypal/billing_agreement', ['_secure' => true]);?>"><?php echo __('Billing Agreements');?></a>
                </li>
                <li>
                    <a href="<?php echo $block->getUrl('review/disconnect', ['_secure' => true]);?>"><?php echo __('My Product Reviews');?></a>
                </li>
                <li>
                    <a title="<?php echo __('Log Out');?>"  href="<?php echo $block->getUrl('customer/account/logout', ['_secure' => true]);?>"><?php echo __('Log Out');?></a>
                </li>
            </ul>
        </div>
    </li>
<?php }else{ ?>
    <div class="menu_link">
        <a title="<?php echo __('Login');?>" href="<?php echo $block->getUrl('customer/account/login', ['_secure' => true]);?>"><?php echo __('Login');?></a>
    </div>

<?php } ?>