<div class="row">
    <div class="col-md-12 col-lg 12 recettes">
        <div class="col-xs-12 col-sm-6 col-md-4 col-lg-4">
            <h2><?php echo __('Aumonières aux 4 fromages');?></h2>
            <ul>
                <li><img src="<?php echo $this->getViewFileUrl('images/recettes/cutlery.png'); ?>"> <span class="gray">Pour</span> : 2 personnes</li>
                <li><img src="<?php echo $this->getViewFileUrl('images/recettes/clock.png'); ?>"> <span class="gray">Préparation</span> : 20 min.</li>
                <li><img src="<?php echo $this->getViewFileUrl('images/recettes/oven.png'); ?>"> <span class="gray">Cuisson</span> : 10 min.</li>
            </ul>
            <h3 class="recette-part">Ingrédients</h3>
            <p>Pâte à crêpes de blé noir (pour 8 crêpes) :</p>
            <ul class="ingredients">
                <li>125 g de farine de Sarasin</li>
                <li>100 g d'emmental râpé</li>
                <li>2 œufs</li>
                <li>25 cl. de lait tiède</li>
                <li>2 cuil. à soupe d'huile d'olive</li>
                <li>½ sachet de levure</li>
                <li>Poivre et peu de sel</li>
                <li>80 g de comté</li>
                <li>80 g d'emmental</li>
                <li>80 g de beaufort</li>
                <li>80 g de cheddar</li>
            </ul>

        </div>
        <div class="col-xs-12 col-sm-6 col-md-4 col-lg-4">
            <img src="<?php echo $this->getViewFileUrl('images/recettes/aumonieres_fromages.jpg'); ?>" alt="aumonières aux 4 fromages time nutrition">
        </div>
        <div class="col-xs-12 col-sm-6 col-md-4 col-lg-4">
            Pour varier les plaisirs, pourquoi ne pas tenter de temps en temps un petit-déjeuner chaud ?<br>
            A préparer un jour où l’on a envie de se faire plaisir !
        </div>

    </div>
</div>
<div class="row">
    <div class="col-md-12 col-lg-12 recettes">
        <h3 class="recette-part">Préparation</h3>
        <ul class="preparation">
            <li>Dans un saladier verser la farine et la levure, le sel et le poivre.</li>
            <li>Former un puit au milieu, y casser les œufs.</li>
            <li>Mélanger avec un fouet.</li>
            <li>Ajouter le gruyère.</li>
            <li>Laisser reposer la pâte 2 à 3 heures.</li>
            <li>Faire chauffer une poêle antiadhésive avec un filet d'huile d'olive</li>
            <li>Quand elle est bien chaude verser une louche de pâte et cuire à feu vif.</li>
            <li>Débarrasser sur une assiette.</li>
            <li>Garnir le centre de chaque crêpe du mélange des 4 fromages (10 g de chaque fromage par crêpe) et poivrer.</li>
            <li>Fermer les crêpes en aumônières à l’aide d’une pique, d’une ficelle ou même d’une lamelle de cheddar.</li>
            <li>Garnir la plaque du four de papier sulfurisé y déposer les crêpes et enfourner pendant 10 min. à 180° (therm. 6).</li>
            <li>Servir 2 crêpes par personne.</li>
        </ul>
    </div>
</div>
<div class="row">
    <div class="col-md-12 col-lg-12">
        <div class="astuce">
            <i class="fa fa-caret-right" aria-hidden="true"></i> ASTUCES TIME NUTRITION
            <div>
                Ces crêpes peuvent se préparer d'avance et se garder une journée au réfrigérateur ou se congeler.
            </div>
        </div>

    </div>
</div>