<div class="row">
    <div class="col-md-12 col-lg 12 recettes">
        <div class="col-xs-12 col-sm-6 col-md-4 col-lg-4">
            <h2><?php echo __('Blinis au fromage');?></h2>
            <ul>
                 <li><img src="<?php echo $this->getViewFileUrl('images/recettes/cutlery.png'); ?>"> <span class="gray">Pour</span> : 5 personnes</li>
                 <li><img src="<?php echo $this->getViewFileUrl('images/recettes/clock.png'); ?>"> <span class="gray">Préparation</span> : 20 min.</li>
                 <li><img src="<?php echo $this->getViewFileUrl('images/recettes/oven.png'); ?>"> <span class="gray">Cuisson</span> : 10 min. <span class="gray">Repos</span> : 1 h 15</li>
            </ul>
            <h3 class="recette-part">Ingrédients</h3>
            <p>Pâte à blinis pour 15 pièces* :</p>
            <ul class="ingredients">
                <li>125 g de farine de froment</li>
                <li>125 g de farine de seigle</li>
                <li>25 cl de lait</li>
                <li>½ sachet de levure</li>
                <li>100 g de crème</li>
                <li>3 œufs</li>
                <li>2 pincées de sel</li>
                <li>3 tours de poivre de moulin</li>
                <li>350 g de gruyère</li>
            </ul>

        </div>
        <div class="col-xs-12 col-sm-6 col-md-4 col-lg-4">
            <img src="<?php echo $this->getViewFileUrl('images/recettes/blinis_fromage.jpg'); ?>" alt="blinis au fromage time nutrition">
        </div>
        <div class="col-xs-12 col-sm-12 col-md-4 col-lg-4">
            TIME Nutrition recommande la consommation de fromages au lait cru non pasteurisé, non cuits.<br>
            Mais comme il n’y a rien de pire pour la santé qu’une alimentation monotone, n’hésitez pas de temps en temps à braver nos conseils !<br>
            Ainsi nous vous proposons cette recette à base de gruyère, un excellent fromage cuit.
        </div>


    </div>
</div>
<div class="row">
    <div class="col-md-12 col-lg-12 recettes">
        <h3 class="recette-part">Préparation</h3>
        <ul class="preparation">
            <li>Placer au réfrigérateur la crème dans un saladier avec le fouet qui servira à monter la crème</li>
            <li>Dans un bol, mettre la levure, la recouvrir avec le lait et laisser à température ambiante.</li>
            <li>Dans un autre saladier, mélanger les deux farines, saler, poivrer, verser le bol de lait et les 3 jaunes d'œufs.</li>
            <li>Pétrir, laisser reposer 1 h.</li>
            <li>Fouetter la crème, l'ajouter en mélangeant la préparation.</li>
            <li>Monter les blancs en neige très ferme, les incorporer par petite quantité en soulevant la pâte.</li>
            <li>Laisser reposer au moins ¼ d'heure.</li>
            <li>Dans une poêle à blinis**, graissée au beurre fondu, bien chaude, déposer une grosse cuil. à soupe de pâte, à feu vif laisser cuire 2 min.</li>
            <li>Arroser d'un peu de beurre fondu et retourner, cuire 1 min environ.</li>
            <li>Placer les blinis sur un plat chaud.</li>
            <li>Dans une poêle antiadhésive faire fondre le fromage et le verser sur chaque blinis.</li>
        </ul>
    </div>
</div>
<div class="row">
    <div class="col-md-12 col-lg-12">
        <div class="astuce">
            <i class="fa fa-caret-right" aria-hidden="true"></i> ASTUCES TIME NUTRITION
            <div>
                *Cette pâte peut se préparer la veille.<br>
                **Si vous n'avez pas de poêle à blinis prenez une grande poêle et faite cuire trois blinis à la fois. Le blinis doit avoir une épaisseur de 6 à 8 mm.
                Vous pouvez les maintenir au chaud dans le four en les recouvrant d'un papier d'aluminium.<br>
                Vous pouvez remplacer le gruyère par du fromage qui vous fera envie : roquefort, chèvre, ….
            </div>
        </div>

    </div>
</div>