<div class="row">
    <div class="col-md-12 col-lg 12 recettes">
        <div class="col-xs-12 col-sm-6 col-md-4 col-lg-4">
            <h2><?php echo __('Cabecou aux noix');?></h2>
            <ul>
                <li><img src="<?php echo $this->getViewFileUrl('images/recettes/cutlery.png'); ?>"> <span class="gray">Pour</span> : 2 personnes</li>
                <li><img src="<?php echo $this->getViewFileUrl('images/recettes/clock.png'); ?>"> <span class="gray">Préparation</span> : 7 min.</li>
                <li><img src="<?php echo $this->getViewFileUrl('images/recettes/oven.png'); ?>"> <span class="gray">Cuisson</span> : 6 min.</li>
            </ul>
            <h3 class="recette-part">Ingrédients</h3>
            <ul class="ingredients">
                <li>5 Cabécou affinés</li>
                <li>5 tranches de pain aux noix</li>
                <li>3 noix</li>
                <li>Huile de noix</li>
            </ul>

        </div>
        <div class="col-xs-12 col-sm-6 col-md-4 col-lg-4">
            <img src="<?php echo $this->getViewFileUrl('images/recettes/cabecou_noix.jpg'); ?>" alt="cabecou noix time nutrition">
        </div>
        <div class="col-xs-12 col-sm-12 col-md-4 col-lg-4">
            Le Cabécou est un fromage généralement de lait cru de chèvre originaire des régions du Massif central.<br>
            Il s'agit d'un petit fromage rond, de 4 à 5 centimètres de diamètre sur 1,5 centimètre d'épaisseur, à molle à croûte fleurie.<br>
            Sa masse ne dépasse en général pas 40 grammes et il contient environ 45 % de matière grasse. Son goût est légèrement lactique.<br>
            Cabécou est une francisation de cábro : littéralement chèvre, orthographié cabra en occitan standard.
        </div>
        
    </div>
</div>
<div class="row">
    <div class="col-md-12 col-lg-12 recettes">
        <h3 class="recette-part">Préparation</h3>
        <ul class="preparation">
            <li>Préchauffer le four à 210° (therm. 7)</li>
            <li>Ôter la croûte des Cabécou</li>
            <li>Couper des tranches de pain rondes d'un diamètre supérieur de 2 cm à celui du fromage</li>
            <li>Déposer un peu d'huile de noix sur la tartine.</li>
            <li>Poser 1 Cabécou sur chaque tartine</li>
            <li>Enfourner pendant 6 min.</li>
            <li>Pendant ce temps, casser les noix.</li>
            <li>Lorsque le fromage devient coulant, retirer du four et poser 1 demi-noix sur chaque fromage.</li>
        </ul>
    </div>
</div>
<div class="row">
    <div class="col-md-12 col-lg-12">
        <div class="astuce">
            <i class="fa fa-caret-right" aria-hidden="true"></i> ASTUCES TIME NUTRITION
            <div>
                Choisissez les cabécous protégés par une AOC sous le nom de cabécou de Rocamadour, ou possédant un signe
                de qualité Label rouge sous le nom de cabécou d'Autan.
            </div>
        </div>

    </div>
</div>