<div class="row">
    <div class="col-md-12 col-lg 12 recettes">
        <div class="col-xs-12 col-sm-6 col-md-4 col-lg-4">
            <h2><?php echo __('Crèpes roulées au coulommiers');?></h2>
            <ul>
                <li><img src="<?php echo $this->getViewFileUrl('images/recettes/cutlery.png'); ?>"> <span class="gray">Pour</span> : 2 personnes</li>
                <li><img src="<?php echo $this->getViewFileUrl('images/recettes/clock.png'); ?>"> <span class="gray">Préparation</span> : 7 min.</li>
                <li><img src="<?php echo $this->getViewFileUrl('images/recettes/oven.png'); ?>"> <span class="gray">Cuisson</span> : 6 min.</li>
            </ul>
            <h3 class="recette-part">Ingrédients</h3>
            <ul class="ingredients">
                <li>60 g de fromage râpé</li>
                <li>3 crêpes salées</li>
                <li>100 g de coulommiers</li>
                <li>1 cuil. à soupe de crème</li>
                <li>1 noix de beurre doux</li>
                <li>Moulin de poivre</li>
            </ul>

        </div>
        <div class="col-xs-12 col-sm-6 col-md-4 col-lg-4">
            <img src="<?php echo $this->getViewFileUrl('images/recettes/crepes_coulommiers.jpg'); ?>" alt="crèpes roulées au coulommiers time nutrition">
        </div>
        <div class="col-xs-12 col-sm-12 col-md-4 col-lg-4">
            Le Coulommiers est connu depuis le Moyen Âge comme un fromage à pâte molle et à croûte fleurie fabriqué à partir de lait cru de vache.<br>
            Le procédé de fabrication de ce fromage inclut l'écrémage partiel et la maturation du lait avec des ferments lactiques.<br>
            S'ensuit un affinage en hâloir à 13-15° et 90% d'hygrométrie pendant trois semaines à un mois au cours duquel le fromage développe ses arômes et sa texture.<br>
            En même temps une croûte de légère moisissure blanche se forme. La durée d’affinage optimale d’un lait cru est de 5 semaines, 8 semaines pour un fromage à cœur.
        </div>

    </div>
</div>
<div class="row">
    <div class="col-md-12 col-lg-12 recettes">
        <h3 class="recette-part">Préparation</h3>
        <ul class="preparation">
            <li>Enlever la croûte du Coulommiers.</li>
            <li>Dans une petite casserole faire fondre à feu doux le fromage avec la crème et la noix de beurre.</li>
            <li>Dès que le mélange est onctueux, l'étaler à part égale sur les 3 crêpes.</li>
            <li>Mouliner largement le poivre.</li>
            <li>Rouler les crêpes, les parsemer avec le fromage râpé et les mettre à gratiner sur le grill du four.</li>
            <li>Déguster dès la sortie du four.</li>
        </ul>
    </div>
</div>
<div class="row">
    <div class="col-md-12 col-lg-12">
        <div class="astuce">
            <i class="fa fa-caret-right" aria-hidden="true"></i> ASTUCES TIME NUTRITION
            <div>
                Selon vos goûts et vos envies du moment, vous pouvez fourrer les crêpes avec le fromage de votre choix.
            </div>
        </div>

    </div>
</div>