<div class="row">
    <div class="col-md-12 col-lg 12 recettes">
        <div class="col-xs-12 col-sm-6 col-md-4 col-lg-4">
            <h2><?php echo __('Duo oeufs au plat et knack');?></h2>
            <ul>
                <li><img src="<?php echo $this->getViewFileUrl('images/recettes/cutlery.png'); ?>"> <span class="gray">Pour</span> : 1 personnes</li>
                <li><img src="<?php echo $this->getViewFileUrl('images/recettes/clock.png'); ?>"> <span class="gray">Préparation</span> : 2 min</li>
                <li><img src="<?php echo $this->getViewFileUrl('images/recettes/oven.png'); ?>"> <span class="gray">Cuisson</span> : 3 à 4 min</li>
            </ul>
            <h3 class="recette-part">Ingrédients</h3>
            <ul class="ingredients">
                <li>2 œufs</li>
                <li>2 knacks (saucisses de Strasbourg)</li>
                <li>1 cuil. à café d'huile d'olive</li>
            </ul>

        </div>
        <div class="col-xs-12 col-sm-6 col-md-4 col-lg-4">
            <img src="<?php echo $this->getViewFileUrl('images/recettes/duo_oeufs_knack.jpg'); ?>" alt="oeufs farcis time nutrition">
        </div>
        <div class="col-xs-12 col-sm-12 col-md-4 col-lg-4">
            La cuisson des œufs au plat mérite attention : ne pas griller le blanc et conserver au jaune toute sa « liquidité » !<br>
            La knack est une spécialité culinaire alsacienne, et plus particulièrement strasbourgeoise, dont les origines remontent au XVIe siècle.<br>
            Il s'agit d'une saucisse fumée à base de viande de porc, dont le nom dérive du verbe allemand knacken et qui décrit le bruit que fait la saucisse quand sa peau éclate sous la dent.
        </div>
    </div>
</div>
<div class="row">
    <div class="col-md-12 col-lg-12 recettes">
        <h3 class="recette-part">Préparation</h3>
        <ul class="preparation">
            <li>Mettre l'huile d'olive à chauffer dans une poêle antiadhésive.</li>
            <li>Couper les saucisses en rondelles.</li>
            <li>Dès que la poêle est chaude casser les œufs au dessus de la poêle.</li>
            <li>Ajouter sur les œufs les morceaux de saucisse et laisser cuire 3 à 4 min. suivant son goût.</li>
        </ul>
    </div>
</div>
<div class="row">
    <div class="col-md-12 col-lg-12">
        <div class="astuce">
            <i class="fa fa-caret-right" aria-hidden="true"></i> ASTUCES TIME NUTRITION
            <div>
                Vous pouvez remplacer les saucisses par du jambon, du bacon, de la poitrine, du fromage, de tomates, de champignons… tout ce qui pourra vous faire plaisir au saut du lit !
            </div>
        </div>

    </div>
</div>