<div class="row">
    <div class="col-md-12 col-lg 12 recettes">
        <div class="col-xs-12 col-sm-6 col-md-4 col-lg-4">
            <h2><?php echo __('Fondue de Camembert');?></h2>
            <ul>
                <li><img src="<?php echo $this->getViewFileUrl('images/recettes/cutlery.png'); ?>"> <span class="gray">Pour</span> : 2 personnes</li>
                <li><img src="<?php echo $this->getViewFileUrl('images/recettes/clock.png'); ?>"> <span class="gray">Préparation</span> : 50 min</li>
                <li><img src="<?php echo $this->getViewFileUrl('images/recettes/oven.png'); ?>"> <span class="gray">Cuisson</span> : 30 min</li>
            </ul>
            <h3 class="recette-part">Ingrédients</h3>
            <ul class="ingredients">
                <li>1 camembert dans une boite en bois</li>
                <li>½ baguette de pain</li>
            </ul>

        </div>
        <div class="col-xs-12 col-sm-6 col-md-4 col-lg-4">
            <img src="<?php echo $this->getViewFileUrl('images/recettes/fondue_camembert.jpg'); ?>" alt="fondue de camembert time nutrition">
        </div>
        <div class="col-xs-12 col-sm-12 col-md-4 col-lg-4">
            Le nom de Camembert provient de celui du village de l'Orne (France) où fut fabriqué le fromage qui fut présenté à Napoléon III lors de l'inauguration de la ligne de chemin de fer Paris-Granville.<br>
            Le fromage Camembert de Normandie est un fromage à pâte molle et à croûte fleurie élaboré à partir d’un lait cru, produit par des vaches de race Normande essentiellement, qui pâturent plus de 6 mois par an.<br>
            Le fromage Camembert est issu d'un caillé faiblement divisé, moulé en cinq couches successives avec un temps de repos entre chacune et égoutté spontanément.
        </div>


    </div>
</div>
<div class="row">
    <div class="col-md-12 col-lg-12 recettes">
        <h3 class="recette-part">Préparation</h3>
        <ul class="preparation">
            <li>Couper le pain en rondelles</li>
            <li>Ouvrir le papier sur le dessus du fromage et gratter la croûte du dessus.</li>
            <li>Enfourner 210° (therm. 7) pendant 30 min.</li>
            <li>Tremper les rondelles de pain dans le fromage façon fondue.</li>
        </ul>
    </div>
</div>
<div class="row">
    <div class="col-md-12 col-lg-12">
        <div class="astuce">
            <i class="fa fa-caret-right" aria-hidden="true"></i> ASTUCES TIME NUTRITION
            <div>
                Pour faire de ce petit-déj un véritable moment de dégustation vous pouvez agrémenter votre camembert de quelques tranches de magret de canard fumé.<br>
                Pour cela, disposez-les lanières de magret sur le fromage avant de le mettre au four.<br>
                Pour plus de saveur, vous pouvez aussi parsemer le camembert d’un mélange d'herbes ciselées (estragon, ciboulette ou aneth) avant de l’enfourner.
            </div>
        </div>

    </div>
</div>