<div class="row">
    <div class="col-md-12 col-lg 12 recettes">
        <div class="col-xs-12 col-sm-6 col-md-4 col-lg-4">
            <h2><?php echo __('Fromage de chèvre à la provençale');?></h2>
            <ul>
                <li><img src="<?php echo $this->getViewFileUrl('images/recettes/cutlery.png'); ?>"> <span class="gray">Pour</span> : 2 personnes</li>
                <li><img src="<?php echo $this->getViewFileUrl('images/recettes/clock.png'); ?>"> <span class="gray">Préparation</span> : 15 min. (à préparer à l'avance)</li>
                <li><img src="<?php echo $this->getViewFileUrl('images/recettes/oven.png'); ?>"> <span class="gray">Cuisson</span> : 3 à 4 min</li>
            </ul>
            <h3 class="recette-part">Ingrédients</h3>
            <ul class="ingredients">
                <li>250ml d'huile d'olive</li>
                <li>1 cuil. à café de fleur de thym</li>
                <li>1 fleur d'anis étoilée</li>
                <li>1 cuil. à café de baies roses</li>
                <li>1 branche de romarin</li>
                <li>10 grains de poivre</li>
                <li>5 fromages de chèvre demi-secs</li>
            </ul>

        </div>
        <div class="col-xs-12 col-sm-6 col-md-4 col-lg-4">
            <img src="<?php echo $this->getViewFileUrl('images/recettes/fromage_chevre_provencale.jpg'); ?>" alt="fromage de chevre provençale time nutrition">
        </div>
        <div class="col-xs-12 col-sm-12 col-md-4 col-lg-4">
            Un fromage de chèvre est un fromage obtenu en transformant exclusivement du lait de chèvre, qui ne peut pas être mélangé avec le lait d’un autre animal, même en plus faible quantité, comme du lait de vache ou de brebis.<br>
            La composition du lait de chèvre en acides gras spécifiques (acide caprique) contribue à son goût caractéristique.<br>
            Les fromages de chèvre peuvent se consommer frais, demi-sec ou affinés plus ou moins longtemps. <br>
            TIME Nutrition vous recommande ici des fromages demi-sec, suffisamment forts en goût et agréables au palais.

        </div>


    </div>
</div>
<div class="row">
    <div class="col-md-12 col-lg-12 recettes">
        <h3 class="recette-part">Préparation</h3>
        <ul class="preparation">
            <li>Dans une casserole faire chauffer l'huile d’olive.</li>
            <li>Hors du feu ajouter le thym, le romarin, l'anis étoilé, les baies roses et le poivre.</li>
            <li>Couvrir et laisser refroidir.</li>
            <li>Placer les fromages dans un bocal en verre, et les recouvrir avec l'huile et ses aromates.</li>
            <li>Quand le mélange est froid, boucher avec un bouchon de liège.</li>
            <li>Ranger le bocal dans l'obscurité.</li>
        </ul>
    </div>
</div>
<div class="row">
    <div class="col-md-12 col-lg-12">
        <div class="astuce">
            <i class="fa fa-caret-right" aria-hidden="true"></i> ASTUCES TIME NUTRITION
            <div>
                Pour plus de simplicité, vous pouvez remplacer le mélange fleur de thym, fleur d'anis étoilée, baies
                roses et romarin par des herbes de Provence.
            </div>
        </div>

    </div>
</div>