<div class="row">
    <div class="col-md-12 col-lg 12 recettes">
        <div class="col-xs-12 col-sm-6 col-md-4 col-lg-4">
            <h2><?php echo __('Oeufs Cocottes');?></h2>
            <ul>
                <li><img src="<?php echo $this->getViewFileUrl('images/recettes/cutlery.png'); ?>"> <span class="gray">Pour</span> : 2 personnes</li>
                <li><img src="<?php echo $this->getViewFileUrl('images/recettes/clock.png'); ?>"> <span class="gray">Préparation</span> : 8 min</li>
                <li><img src="<?php echo $this->getViewFileUrl('images/recettes/oven.png'); ?>"> <span class="gray">Cuisson</span> : 7 min</li>
            </ul>
            <h3 class="recette-part">Ingrédients</h3>
            <ul class="ingredients">
                <li>60 g de pain</li>
                <li>4 œufs</li>
                <li>6 cuil. à soupe de crème fraîche</li>
                <li>2 cuil. à soupe d'estragon ciselé</li>
                <li>Poivre blanc</li>
                <li>Sel</li>
                <li>4 ramequins</li>
            </ul>

        </div>
        <div class="col-xs-12 col-sm-6 col-md-4 col-lg-4">
            <img src="<?php echo $this->getViewFileUrl('images/recettes/oeufs_cocottes.jpg'); ?>" alt="oeufs cocottes time nutrition">
        </div>
        <div class="col-xs-12 col-sm-12 col-md-4 col-lg-4">
            En France, les œufs utilisés en cuisine ne sont généralement pas fécondés, et utilisés à l’état frais, soit moins de vingt-huit jours après la ponte.<br>
            Dans les traditions culinaires asiatiques, les œufs sont parfois fécondés, comme le balut, ou mis à fermenter pendant plusieurs semaines, comme l’œuf de cent ans.
        </div>


    </div>
</div>
<div class="row">
    <div class="col-md-12 col-lg-12 recettes">
        <h3 class="recette-part">Préparation</h3>
        <ul class="preparation">
            <li>Allumer le four à 240° (therm. 8).</li>
            <li>Préparer un bain marie, mettre les ramequins vides dans le bain marie et enfourner.</li>
            <li>Quand les ramequins sont bien chauds, verser ½ cuil. à soupe de crème fraîche dans chacun d'eux puis casser un œuf par ramequin.</li>
            <li>Mélanger 4 cuil. à soupe de crème fraîche avec l'estragon et le poivre blanc.</li>
            <li>Ajouter le mélange sur les 4 œufs et saler.</li>
            <li>Enfourner pendant 7 min.</li>
        </ul>
    </div>
</div>
<div class="row">
    <div class="col-md-12 col-lg-12">
        <div class="astuce">
            <i class="fa fa-caret-right" aria-hidden="true"></i> ASTUCES TIME NUTRITION
            <div>
                Alternative tout aussi délicieuse : vous pouvez remplacer le mélange crème fraîche/estragon/poivre par un mélange crème fraîche/curry/cerfeuil.<br><br>
                À noter : cette recette peut être réalisée au micro-onde !<br>
                Pour cela mettre la préparation ci-dessus dans les ramequins (sans passer par l’étape bain-marie).<br>
                Une fois les ramequins montés, percer les jaunes d’œufs avec la pointe du couteau et mettre au micro-onde à 450 watts (température douce) pendant 4 à 5 minutes.
            </div>
        </div>

    </div>
</div>