<div class="row">
    <div class="col-md-12 col-lg 12 recettes">
        <div class="col-xs-12 col-sm-6 col-md-4 col-lg-4">
            <h2><?php echo __('Oeufs Brouilles');?></h2>
            <ul>
                <li><img src="<?php echo $this->getViewFileUrl('images/recettes/cutlery.png'); ?>"> <span class="gray">Pour</span> : 1 personne</li>
                <li><img src="<?php echo $this->getViewFileUrl('images/recettes/clock.png'); ?>"> <span class="gray">Préparation</span> : 5 min</li>
                <li><img src="<?php echo $this->getViewFileUrl('images/recettes/oven.png'); ?>"> <span class="gray">Cuisson</span> : 10 min</li>
            </ul>
            <h3 class="recette-part">Ingrédients</h3>
            <ul class="ingredients">
                <li>2 œufs</li>
                <li>100 g de lardons</li>
                <li>100 g de gruyère râpé</li>
                <li>1 cuil. de crème fraîche</li>
                <li>1 noisette de beurre</li>
                <li>Graines germées ou de ciboulette</li>
                <li>Sel, poivre</li>
            </ul>

        </div>
        <div class="col-xs-12 col-sm-6 col-md-4 col-lg-4">
            <img src="<?php echo $this->getViewFileUrl('images/recettes/oeufs_brouilles.jpg'); ?>" alt="oeufs brouilles time nutrition">
        </div>
        <div class="col-xs-12 col-sm-12 col-md-4 col-lg-4">
            Auguste Escoffier, célèbre écrivain-cuisinier français, disait des œufs brouillés :<br>
            «Cette préparation est incontestablement la plus fine de celles auxquelles peuvent être soumis les œufs ; à condition, toutefois, que le degré de cuisson ne soit pas dépassé, et qu’elle reste moelleuse et crémeuse».
        </div>
    </div>
</div>
<div class="row">
    <div class="col-md-12 col-lg-12 recettes">
        <h3 class="recette-part">Préparation</h3>
        <ul class="preparation">
            <li>Faire rissoler les petits lardons dans une poêle anti-adhésive puis réserver.</li>
            <li>Dans une petite casserole faire fondre une noisette de beurre.</li>
            <li>Battre dans un bol les 2 œufs.</li>
            <li>Quand le beurre est bien chaud poser la casserole sur un bain marie, y verser les œufs battus, poivrer et tourner à l'aide d'une cuill. en bois.</li>
            <li>Quand les œufs sont "pris", ajouter la crème puis les lardons et enfin le gruyère râpé.</li>
            <li>Continuer à tourner jusqu'à ce que le gruyère soit fondu.</li>
            <li>Décorer les œufs de graines germées ou de ciboulette.</li>
            <li>Déguster aussitôt !</li>
        </ul>
    </div>
</div>
<div class="row">
    <div class="col-md-12 col-lg-12">
        <div class="astuce">
            <i class="fa fa-caret-right" aria-hidden="true"></i> ASTUCES TIME NUTRITION
            <div>
                Pour que cette recette constitue un plat complet, dégustez les œufs brouillés sur des pancakes bien dorés.
            </div>
        </div>

    </div>
</div>