<div class="row">
    <div class="col-md-12 col-lg 12 recettes">
        <div class="col-xs-12 col-sm-6 col-md-4 col-lg-4">
            <h2><?php echo __('Oeufs Farcis');?></h2>
            <ul>
                <li><img src="<?php echo $this->getViewFileUrl('images/recettes/cutlery.png'); ?>"> <span class="gray">Pour</span> : 1 personnes</li>
                <li><img src="<?php echo $this->getViewFileUrl('images/recettes/clock.png'); ?>"> <span class="gray">Préparation</span> : 10 min</li>
                <li><img src="<?php echo $this->getViewFileUrl('images/recettes/oven.png'); ?>"> <span class="gray">Cuisson</span> : 20 min</li>
            </ul>
            <h3 class="recette-part">Ingrédients</h3>
            <ul class="ingredients">
                <li>50 g de gruyère râpé</li>
                <li>2 cuil. à soupe de crème épaisse</li>
                <li>1 cuil. à café de persil ciselé</li>
                <li>1 cuil. à café d'huile de d'olive</li>
                <li>20 g de beurre</li>
                <li>2 œufs</li>
                <li>3 tranches très fines de poitrine fumée</li>
            </ul>

        </div>
        <div class="col-xs-12 col-sm-6 col-md-4 col-lg-4">
            <img src="<?php echo $this->getViewFileUrl('images/recettes/oeufs_farcis.jpg'); ?>" alt="oeufs farcis time nutrition">
        </div>
        <div class="col-xs-12 col-sm-12 col-md-4 col-lg-4">
            Bon à savoir : le caractère imprimé sur l'œuf avant les lettres FR renseigne sur le mode d’élevage des poules et donc sur la qualité du produit :<br>
            0 : œufs de poules élevées en plein air (agriculture biologique)<br>
            1 : œufs de poules élevées en plein air<br>
            2 : œufs de poules élevées au sol<br>
            3 : œufs de poules élevées en cage
        </div>


    </div>
</div>
<div class="row">
    <div class="col-md-12 col-lg-12 recettes">
        <h3 class="recette-part">Préparation</h3>
        <ul class="preparation">
            <li>Faire durcir les œufs puis les couper en deux.</li>
            <li>Retirer délicatement le jaune, le placer dans un bol avec la crème épaisse et le persil, saler puis poivrer.</li>
            <li>Farcir les blancs d'œufs avec ce mélange.</li>
            <li>Déposer les sur un plat beurré.</li>
            <li>Mettre des tranches de beurre sur les œufs, saupoudrer de gruyère râpé et enfourner 12 à 15 min. à 180° (therm. 6).</li>
            <span>Pendant ce temps :</span>
            <li>Faire rissoler les tranches de poitrine fumée dans une poêle avec 1 cuil. à café d'huile d'olive.</li>
        </ul>
    </div>
</div>
<div class="row">
    <div class="col-md-12 col-lg-12">
        <div class="astuce">
            <i class="fa fa-caret-right" aria-hidden="true"></i> ASTUCES TIME NUTRITION
            <div>
                Pour un petit déjeuner TIME Nutrition équilibré, nous vous conseillons de déguster ces œufs avec du pain au levain.<br>
                Vous pouvez même, si vous le souhaitez déposer les œufs (côté farci) sur les tranches de pain avant de les mettre au four.
                <br><br>
                Petit conseil ! Pour ne pas rater vos œufs durs voici les 4 étapes à suivre à la lettre :<br>
                - Mettre une casserole d'eau à chauffer.<br>
                - À ébullition, plonger délicatement les œufs.<br>
                - À la reprise de l'ébullition, compter 8 minutes.<br>
                - Sortir les œufs à l'aide d'une écumoire et les rafraîchir sous l'eau.
            </div>
        </div>

    </div>
</div>