<div class="row">
    <div class="col-md-12 col-lg 12 recettes">
        <div class="col-xs-12 col-sm-6 col-md-4 col-lg-4">
            <h2><?php echo __('Omelette au fromage');?></h2>
            <ul>
                <li><img src="<?php echo $this->getViewFileUrl('images/recettes/cutlery.png'); ?>"> <span class="gray">Pour</span> : 2 personnes (environ 10 pièces)</li>
                <li><img src="<?php echo $this->getViewFileUrl('images/recettes/clock.png'); ?>"> <span class="gray">Préparation</span> : 6 min</li>
                <li><img src="<?php echo $this->getViewFileUrl('images/recettes/oven.png'); ?>"> <span class="gray">Cuisson</span> : 5 min.</li>
            </ul>
            <h3 class="recette-part">Ingrédients</h3>
            <ul class="ingredients">
                <li>120 g du fromage de votre choix</li>
                <li>4 œufs</li>
                <li>½ cuil. à café de cumin</li>
                <li>2 tartines de pain de campagne (70 g chacune)</li>
                <li>20 g de beurre</li>
                <li>Sel, poivre</li>
            </ul>

        </div>
        <div class="col-xs-12 col-sm-6 col-md-4 col-lg-4">
            <img src="<?php echo $this->getViewFileUrl('images/recettes/omelette_fromage.jpg'); ?>" alt="omelette au fromage time nutrition">
        </div>
        <div class="col-xs-12 col-sm-12 col-md-4 col-lg-4">
            L'omelette est un plat à base d'œufs.<br>
            Elle est à la fois très simple et très rapide à réaliser, que ce soit au niveau de la préparation, des ingrédients ajoutés ou de la cuisson.<br>
            Les goûts en la matière sont très variables. Auguste Escoffier, célèbre écrivain-cuisinier français, définit l'omelette comme « des œufs brouillés d'un genre spécial enfermés dans une enveloppe d'œuf coagulé, et rien autre chose. »
        </div>
    </div>
</div>
<div class="row">
    <div class="col-md-12 col-lg-12 recettes">
        <h3 class="recette-part">Préparation</h3>
        <ul class="preparation">
            <li>Couper le fromage en lamelles.</li>
            <li>Battre les œufs dans un saladier, saler légèrement et poivrer.</li>
            <li>Incorporer les lamelles de fromage dans le saladier.</li>
            <li>Mettre un filet d'huile d'olive dans une poêle antiadhésive et faire chauffer à feu vif</li>
            <li>Verser le mélange œuf-fromage et ajouter le cumin.</li>
            <span>Pendant ce temps :</span>
            <li>Mettre les tranches de pain à griller.</li>
            <span>Au bout de 2 minutes :</span>
            <li>Baisser le feu et faire prendre l'omelette en remuant les parties cuites vers le centre.</li>
            <li>Dès que l'omelette est cuite, la replier en deux et la faire glisser sur un plat.</li>
            <li>Déguster avec le pain légèrement grillé et beurré.</li>
        </ul>
    </div>
</div>
<div class="row">
    <div class="col-md-12 col-lg-12">
        <div class="astuce">
            <i class="fa fa-caret-right" aria-hidden="true"></i> ASTUCES TIME NUTRITION
            <div>
                Une omelette bien cuite doit être dorée mais rester baveuse et fondante en bouche.
            </div>
        </div>

    </div>
</div>