<div class="row">
    <div class="col-md-12 col-lg 12 recettes">
        <div class="col-xs-12 col-sm-6 col-md-4 col-lg-4">
            <h2><?php echo __('Pancakes au jambon');?></h2>
            <ul>
                <li><img src="<?php echo $this->getViewFileUrl('images/recettes/cutlery.png'); ?>"> <span class="gray">Pour</span> : 2 personnes (environ 10 pièces)</li>
                <li><img src="<?php echo $this->getViewFileUrl('images/recettes/clock.png'); ?>"> <span class="gray">Préparation</span> : 5 min</li>
                <li><img src="<?php echo $this->getViewFileUrl('images/recettes/oven.png'); ?>"> <span class="gray">Cuisson</span> : 4 min par pancakes</li> <span class="gray">Repos</span> : 1h</li>
            </ul>
            <h3 class="recette-part">Ingrédients</h3>
            <ul class="ingredients">
                <li>75 g de farine de sarrasin</li>
                <li>75 g de farine de froment</li>
                <li>1 œuf</li>
                <li>5 tranches de jambon</li>
                <li>¼ de cuil. à café de sel</li>
                <li>1 cuil. à café de beurre</li>
                <li>1 cuil. à café d'huile d'olive</li>
                <li>1 dl de lait</li>
                <li>Poivre</li>
                <li>Levure</li>
            </ul>

        </div>
        <div class="col-xs-12 col-sm-6 col-md-4 col-lg-4">
            <img src="<?php echo $this->getViewFileUrl('images/recettes/pancakes_jambon.jpg'); ?>" alt="pancakes au jambon time nutrition">
        </div>
        <div class="col-xs-12 col-sm-12 col-md-4 col-lg-4">
            Le pancake est l’équivalent américain de la crêpe française.<br>
            C’est idéal pour les petits déjeuners du dimanche matin.<br>
            Très nourrissant, un pancake permet de bien démarrer la journée et d’éviter le coup de barre de 11h.<br>
            Il faut également noter que conservés au frais, les pancakes se conservent très bien.
        </div>
    </div>
</div>
<div class="row">
    <div class="col-md-12 col-lg-12 recettes">
        <h3 class="recette-part">Préparation</h3>
        <ul class="preparation">
            <li>Dans un saladier tamiser les deux farines, le sel, la levure, le beurre et mélanger.</li>
            <li>Dans un bol battre l'œuf et l'ajouter au mélange des farines</li>
            <li>Ajouter le lait et l'huile d'olive.</li>
            <li>Mixer rapidement pour que la pâte ne soit pas collante, poivrer et laisser reposer au moins 1 heure.</li>
            <span>Cuisson des Pancakes :</span>
            <li>Huiler une poêle, la faire chauffer à feu vif et y verser une petite louche de pâte</li>
            <li>Dès que les bulles d'air apparaissent à la surface retourner le pancake et laisser cuire 1 min. environ.</li>
            <li>Garnir de jambon et déguster aussitôt.</li>
        </ul>
    </div>
</div>
<div class="row">
    <div class="col-md-12 col-lg-12">
        <div class="astuce">
            <i class="fa fa-caret-right" aria-hidden="true"></i> ASTUCES TIME NUTRITION
            <div>
                Pour un petit-déjeuner TIME Nutrition équilibré, agrémentez vos pancakes avec des œufs brouillés ou des tranches de fromage.
            </div>
        </div>

    </div>
</div>