<div class="row">
    <div class="col-md-12 col-lg 12 recettes">
        <div class="col-xs-12 col-sm-6 col-md-4 col-lg-4">
            <h2><?php echo __('Petit-dej à la mode allemande');?></h2>
            <ul>
                <li><img src="<?php echo $this->getViewFileUrl('images/recettes/cutlery.png'); ?>"> <span class="gray">Pour</span> : 2 personnes</li>
                <li><img src="<?php echo $this->getViewFileUrl('images/recettes/clock.png'); ?>"> <span class="gray">Préparation</span> : 2 min</li>
                <li><img src="<?php echo $this->getViewFileUrl('images/recettes/oven.png'); ?>"> <span class="gray">Cuisson</span> : 18 min</li>
            </ul>
            <h3 class="recette-part">Ingrédients</h3>
            <ul class="ingredients">
                <li>4 œufs</li>
                <li>4 tranches de bacon</li>
                <li>25 cl. de bouillon de volaille</li>
                <li>12,5 cl. de bière ambrée</li>
                <li>150 g de pain de campagne</li>
                <li>1 cuil. à soupe de vinaigre d'alcool</li>
                <li>Sel, Poivre</li>
                <li>Muscade</li>
            </ul>

        </div>
        <div class="col-xs-12 col-sm-6 col-md-4 col-lg-4">
            <img src="<?php echo $this->getViewFileUrl('images/recettes/petit_dej_allemand.jpg'); ?>" alt="petit dej à la mode allemande time nutrition">
        </div>
        <div class="col-xs-12 col-sm-12 col-md-4 col-lg-4">
            Le bacon est toujours une viande de porc salée et généralement fumée.<br>
            On appelle bacon américain les tranches fines provenant du flanc de porc.<br>
            C'est le plus commun au Canada et le plus employé en cuisine.<br>
            Le bacon canadien qui, ironiquement, est surtout consommé aux États-Unis, provient de la longe et s'apparente plus à une tranche fine de jambon maigre.<br>
            On le sert presque exclusivement avec des oeufs au petit déjeuner. Quant à la pancetta, le bacon italien, c'est une poitrine de porc salée et poivrée qui est séchée pendant trois mois.<br>
            Elle est ensuite présentée en roulade comme un gros saucisson.
        </div>


    </div>
</div>
<div class="row">
    <div class="col-md-12 col-lg-12 recettes">
        <h3 class="recette-part">Préparation</h3>
        <ul class="preparation">
            <li>Retirer la mie du pain de campagne et conserver d’un côté la croûte et de l’autre la mie.</li>
            <li>Dans une casserole, porter à ébullition le bouillon de volaille et la bière, ajouter la mie de pain, saler et laisser cuire 15 min.</li>
            <span>Pendant ce temps</span>
            <li>Couper le bacon en lanières et la croûte du pain de campagne en dés.</li>
            <li>Dans une poêle antiadhésive faire rissoler le bacon, puis le réserver sur un papier absorbant.</li>
            <li>Dans la poêle très chaude mettre les dés de croûte de pain à rissoler dans le gras du bacon, puis les réserver sur un papier absorbant.</li>
            <li>Dans une casserole faire chauffer 1L d'eau avec 1 cuillère à soupe de vinaigre d'alcool.</li>
            <li>Dès que l'eau frémit, casser chaque œuf dans une tasse et les verser délicatement dans l'eau frémissante, laisser cuire 3 min. puis retirer les œufs à l'aide d'une écumoire et les réserver sur un papier absorbant.</li>
            <span>A là fin des 15 minutes de cuisson :</span>
            <li>Sortir la soupe du feu et la saupoudrer d'une pincée de muscade.</li>
            <li>La répartir dans deux assiettes bien chaudes</li>
            <li>Poser les deux œufs dans chaque assiette, les recouvrir à parts égales avec le bacon frit et répartir autour les croûtons grillés.</li>
        </ul>
    </div>
</div>
<div class="row">
    <div class="col-md-12 col-lg-12">
        <div class="astuce">
            <i class="fa fa-caret-right" aria-hidden="true"></i> ASTUCES TIME NUTRITION
            <div>
                Servir avec éventuellement un peu de ketchup pour faire moins allemand et plus américain !
            </div>
        </div>

    </div>
</div>