<div class="row">
    <div class="col-md-12 col-lg 12 recettes">
        <div class="col-xs-12 col-sm-6 col-md-4 col-lg-4">
            <h2><?php echo __('Tarte rouqefort-noix');?></h2>
            <ul>
                <li><img src="<?php echo $this->getViewFileUrl('images/recettes/cutlery.png'); ?>"> <span class="gray">Pour</span> : 4 personnes</li>
                <li><img src="<?php echo $this->getViewFileUrl('images/recettes/clock.png'); ?>"> <span class="gray">Préparation</span> : 10 min</li>
                <li><img src="<?php echo $this->getViewFileUrl('images/recettes/oven.png'); ?>"> <span class="gray">Cuisson</span> : 30 min</li>
            </ul>
            <h3 class="recette-part">Ingrédients</h3>
            <ul class="ingredients">
                <li>fond de tarte en pâte brisée surgelée</li>
                <li>150 g de roquefort</li>
                <li>200 g de mascarpone</li>
                <li>3 œufs</li>
                <li>4 noix concassées</li>
                <li>Poivre</li>
                <li>Noix de muscade</li>
            </ul>

        </div>
        <div class="col-xs-12 col-sm-6 col-md-4 col-lg-4">
            <img src="<?php echo $this->getViewFileUrl('images/recettes/tarte_roquefort_noix.jpg'); ?>" alt="tarte roquefort noix time nutrition">
        </div>
        <div class="col-xs-12 col-sm-12 col-md-4 col-lg-4">
            Le roquefort est une appellation fromagère française à pâte persillée élaborée exclusivement avec des laits crus de brebis.<br>
            Ce fromage qui date au moins du XIe siècle, est un symbole historique de la région des causses et vallées de l'Aveyron.<br>
            Ce fromage de réputation mondiale est devenu l'emblème de la résistance des producteurs de fromages au lait cru contre les demandes réitérées de la généralisation de la pasteurisation du lait.

        </div>


    </div>
</div>
<div class="row">
    <div class="col-md-12 col-lg-12 recettes">
        <h3 class="recette-part">Préparation</h3>
        <ul class="preparation">
            <li>Beurrer un moule à tarte.</li>
            <li>Etaler la pâte brisée dans le moule et la piquer de part en part à l'aide d'une fourchette.</li>
            <li>Dans un saladier, mélanger le mascarpone, le roquefort, les œufs battus et les noix.</li>
            <li>Déposer le mélange sur la pâte brisée.</li>
            <li>Poivrer et saupoudrer de muscade.</li>
            <li>Enfourner 30 min à 210° (therm. 7).</li>
            <li>Servir aussitôt.</li>
        </ul>
    </div>
</div>
<div class="row">
    <div class="col-md-12 col-lg-12">
        <div class="astuce">
            <i class="fa fa-caret-right" aria-hidden="true"></i> ASTUCES TIME NUTRITION
            <div>
                Selon vos goûts et vos envies du moment, vous pouvez réaliser cette recette avec le fromage de votre choix.
            </div>
        </div>

    </div>
</div>