<div class="row">
    <div class="col-md-12 col-lg 12 recettes">
        <div class="col-xs-12 col-sm-6 col-md-4 col-lg-4">
            <h2><?php echo __('Délice fondant de gorgonzola');?></h2>
            <ul>
                <li><img src="<?php echo $this->getViewFileUrl('images/recettes/cutlery.png'); ?>"> <span class="gray">Pour</span> : 2 personnes</li>
                <li><img src="<?php echo $this->getViewFileUrl('images/recettes/clock.png'); ?>"> <span class="gray">Préparation</span> : 6 min</li>
                <li><img src="<?php echo $this->getViewFileUrl('images/recettes/oven.png'); ?>"> <span class="gray">Cuisson</span> : 3 min</li>
            </ul>
            <h3 class="recette-part">Ingrédients</h3>
            <ul class="ingredients">
                <li>100 g de gorgonzola écroûté</li>
                <li>100 g de crème fraîche</li>
                <li>Baies de Sichuan (poivre chinois)</li>
                <li>Ail</li>
                <li>140 g de pain de campagne en tranches</li>
            </ul>

        </div>
        <div class="col-xs-12 col-sm-6 col-md-4 col-lg-4">
            <img src="<?php echo $this->getViewFileUrl('images/recettes/delice_fondant_gorgonzola.jpg'); ?>" alt="délice fondant de gorgonzola time nutrition">
        </div>
        <div class="col-xs-12 col-sm-12 col-md-4 col-lg-4">
            Le gorgonzola est le nom d'un fromage traditionnel à base de lait de vache, à pâte persillée, produit en Italie dans les régions de Lombardie et du Piémont.<br>
            A l'origine, la Gorgonzola doit sa singularité à l'introduction de souches de moisissures de Penicillium glaucum.<br>
            La pâte est généralement fine et douce. De couleur ivoire à l'état jeune, elle devient ensuite plus foncée d'ocre clair et prend une saveur typée en vieillissant.<br>
            Comme tous les fromages bleus, il a subi des perforations pour entretenir la vitalité des moisissures internes, aussi est-il constamment enveloppé de papier d'aluminium pour en boucher les trous et éviter l'égouttage du sérum en cours de conservation.
        </div>


    </div>
</div>
<div class="row">
    <div class="col-md-12 col-lg-12 recettes">
        <h3 class="recette-part">Préparation</h3>
        <ul class="preparation">
            <li>Faire griller les tranches de pain.</li>
            <li>Dans un bol mélanger le gorgonzola et la crème fraîche.</li>
            <li>Étaler le mélange sur le pain grillé.</li>
            <li>Parsemer de baies de Sichuan.</li>
            <li>Disposer les tartines sur une grille et les enfourner 2 à 3 min, en mode gril.</li>
            <li>Dès que les tartines sont dorées les servir aussitôt.</li>
        </ul>
    </div>
</div>
<div class="row">
    <div class="col-md-12 col-lg-12">
        <div class="astuce">
            <i class="fa fa-caret-right" aria-hidden="true"></i> ASTUCES TIME NUTRITION
            <div>
                Selon vos goûts et vos envies du moment, vous pouvez réaliser cette recette avec le fromage de votre choix (bleu, roquefort, chèvre, …).
            </div>
        </div>

    </div>
</div>