<div class="row">
    <div class="col-md-12 col-lg 12 recettes">
        <div class="col-xs-12 col-sm-6 col-md-4 col-lg-4">
            <h2><?php echo __('Tartines à l\'anglaise');?></h2>
            <ul>
                <li><img src="<?php echo $this->getViewFileUrl('images/recettes/cutlery.png'); ?>"> <span class="gray">Pour</span> : 2 personnes</li>
                <li><img src="<?php echo $this->getViewFileUrl('images/recettes/clock.png'); ?>"> <span class="gray">Préparation</span> : 2 min</li>
                <li><img src="<?php echo $this->getViewFileUrl('images/recettes/oven.png'); ?>"> <span class="gray">Cuisson</span> : 5 min</li>
            </ul>
            <h3 class="recette-part">Ingrédients</h3>
            <ul class="ingredients">
                <li>200 g de Chester</li>
                <li>40 g de beurre</li>
                <li>2 tranches de pain de campagne</li>
                <li>Moutarde Anglaise</li>
            </ul>

        </div>
        <div class="col-xs-12 col-sm-6 col-md-4 col-lg-4">
            <img src="<?php echo $this->getViewFileUrl('images/recettes/tartines_anglaises.jpg'); ?>" alt="tartines anglaises time nutrition">
        </div>
        <div class="col-xs-12 col-sm-12 col-md-4 col-lg-4">
            Le chester, fabriqué plus spécialement dans le Cheshire et quelques parties du Shropshire, est un fromage à pâte ferme, de couleur saumon clair.<br>
            C’est un fromage cru anglais, salé, à pâte ferme et de forme cylindrique, il est fabriqué à partir du lait de vache.
        </div>
    </div>
</div>
<div class="row">
    <div class="col-md-12 col-lg-12 recettes">
        <h3 class="recette-part">Préparation</h3>
        <ul class="preparation">
            <li>Faire griller les tranches de pain.</li>
            <li>Les tartiner de beurre, puis de moutarde Anglaise.</li>
            <li>Découper le Chester en petites lamelles très fines.</li>
            <li>Faire fondre, dans une casserole à feu moyen, les lamelles de fromage puis, quand la crème obtenue est bien lisse la répartir sur les tranches de pain grillé.</li>
            <li>Déguster et voyager par la même occasion !</li>
        </ul>
    </div>
</div>
<div class="row">
    <div class="col-md-12 col-lg-12">
        <div class="astuce">
            <i class="fa fa-caret-right" aria-hidden="true"></i> ASTUCES TIME NUTRITION
            <div>
                Vous trouverez la moutarde Anglaise dans les épiceries fine.<br>
                Si vous ne la trouvez pas ou que vous souhaitez aller au plus simple, vous pouvez la remplacer par de la Savora.
            </div>
        </div>

    </div>
</div>