<div class="row">
    <div class="col-md-12 col-lg 12 recettes">
        <div class="col-xs-12 col-sm-6 col-md-4 col-lg-4">
            <h2><?php echo __('Tartelettes au bleu d\'auvergne');?></h2>
            <ul>
                <li><img src="<?php echo $this->getViewFileUrl('images/recettes/cutlery.png'); ?>"> <span class="gray">Pour</span> : 2 personnes</li>
                <li><img src="<?php echo $this->getViewFileUrl('images/recettes/clock.png'); ?>"> <span class="gray">Préparation</span> : 12 min</li>
                <li><img src="<?php echo $this->getViewFileUrl('images/recettes/oven.png'); ?>"> <span class="gray">Cuisson</span> : 25 min</li>
            </ul>
            <h3 class="recette-part">Ingrédients</h3>
            <ul class="ingredients">
                <li>1 rouleau de pâte feuilletée</li>
                <li>3 œufs</li>
                <li>100 g de Bleu d'Auvergne</li>
                <li>2 dl. de crème</li>
                <li>1 cuil. à soupe de farine</li>
                <li>Sel, poivre</li>
            </ul>

        </div>
        <div class="col-xs-12 col-sm-6 col-md-4 col-lg-4">
            <img src="<?php echo $this->getViewFileUrl('images/recettes/tartelettes_bleu_auvergne.jpg'); ?>" alt="tartelettes au bleu d'auvergne time nutrition">
        </div>
        <div class="col-xs-12 col-sm-12 col-md-4 col-lg-4">
            Auguste Escoffier, célèbre écrivain-cuisinier français, disait des œufs brouillés :<br>
            «Cette préparation est incontestablement la plus fine de celles auxquelles peuvent être soumis les œufs ; à condition, toutefois, que le degré de cuisson ne soit pas dépassé, et qu’elle reste moelleuse et crémeuse».
        </div>
    </div>
</div>
<div class="row">
    <div class="col-md-12 col-lg-12 recettes">
        <h3 class="recette-part">Préparation</h3>
        <ul class="preparation">
            <li>Préchauffer le four à 210° (therm. 7).</li>
            <li>Dérouler la pâte feuilletée, découper des ronds de la taille de vos moules à tartelette.</li>
            <li>Étaler chaque rond de pâte sur le fond d’un moule recouvert d'une feuille de cuisson, puis piquer la pâte à l'aide d'une fourchette.</li>
            <li>Dans un saladier fouetter les œufs avec la farine tamisée, la crème et le Bleu d'Auvergne émietté, saler légèrement et poivrer.</li>
            <li>Verser la préparation sur les fonds de tarte.</li>
            <li>Enfourner pendant 25 min.</li>
            <li>Déguster.</li>
        </ul>
    </div>
</div>
<div class="row">
    <div class="col-md-12 col-lg-12">
        <div class="astuce">
            <i class="fa fa-caret-right" aria-hidden="true"></i> ASTUCES TIME NUTRITION
            <div>
                Pour varier le plaisir, vous pouvez décliner cette recette en remplaçant le Bleu d’Auvergne par du Gorgonzola, du Bleu de Bresse ou du Roquefort par exemple.
            </div>
        </div>

    </div>
</div>