<div class="row">
    <div class="col-md-12 col-lg 12 recettes">
        <div class="col-xs-12 col-sm-6 col-md-4 col-lg-4">
            <h2><?php echo __('Tartelettes Craquantes');?></h2>
            <ul>
                <li><img src="<?php echo $this->getViewFileUrl('images/recettes/cutlery.png'); ?>"> <span class="gray">Pour</span> : 2 personnes (environ 10 pièces)</li>
                <li><img src="<?php echo $this->getViewFileUrl('images/recettes/clock.png'); ?>"> <span class="gray">Préparation</span> : 15 min</li>
                <li><img src="<?php echo $this->getViewFileUrl('images/recettes/oven.png'); ?>"> <span class="gray">Cuisson</span> : 30 min <span class="gray">Repos</span> : 1h</li>
            </ul>
            <h3 class="recette-part">Ingrédients</h3>
            <ul class="ingredients">
                <li>1 rouleau de pâte feuilletée</li>
                <li>200 g + 4 tranches de chèvre frais</li>
                <li>1 tomate fraîche</li>
                <li>1 œuf</li>
                <li>1 cuil. à soupe de menthe</li>
                <li>1 pincée de muscade</li>
                <li>Beurre</li>
                <li>Sel, poivre</li>
            </ul>

        </div>
        <div class="col-xs-12 col-sm-6 col-md-4 col-lg-4">
            <img src="<?php echo $this->getViewFileUrl('images/recettes/tartelettes_craquantes.jpg'); ?>" alt="tartelettes craquantes time nutrition">
        </div>
        <div class="col-xs-12 col-sm-12 col-md-4 col-lg-4">
            La France compte une centaine de variétés différentes de fromages de chèvre.<br>
            Fabriqués en majorité au sud de la Loire, les fromages de chèvre ont une typicité et une saveur caractéristique selon la région d’origine, son terroir et ses traditions.
            Les fromages de chèvre peuvent être élaborés à partir :<br>
            - exclusivement de lait de chèvre: ce sont alors des "fromages de chèvre"" ou "pur chèvre"<br>
            - d’un mélange de lait de vache (ou lait de brebis) et de lait de chèvre (minimum 50%). Ils sont alors appelés "mi-chèvre".<br>
            - de lait pasteurisé, thermisé ou cru : dans ce dernier cas, la saveur caprine sera plus affirmée.
        </div>
    </div>
</div>
<div class="row">
    <div class="col-md-12 col-lg-12 recettes">
        <h3 class="recette-part">Préparation</h3>
        <ul class="preparation">
            <li>Préchauffer le four à 180° (therm. 6).</li>
            <li>Dérouler la pâte feuilletée, la découper et l’étaler sur le fond des moules à tartelettes beurrés.</li>
            <li>Piquer la pâte à l'aide d'une fourchette.</li>
            <li>Dans un saladier, mélanger le fromage de chèvre, l’œuf, la menthe ciselée, le sel et le poivre jusqu'à obtenir une pâte homogène.</li>
            <li>Verser la crème de fromage dans les moules.</li>
            <li>Déposer sur le dessus de la tarte 2 tranches de fromage de chèvre et 2 tranches de tomates, en les intercalant.</li>
            <li>Enfourner à 180° (therm. 6) pendant 30 min.</li>
        </ul>
    </div>
</div>
<div class="row">
    <div class="col-md-12 col-lg-12">
        <div class="astuce">
            <i class="fa fa-caret-right" aria-hidden="true"></i> ASTUCES TIME NUTRITION
            <div>
                Pour encore plus de plaisir nous vous proposons de réaliser votre pâte feuilletée « maison ».<br>
                Pour cela prévoyez : 100 g de farine, 1 œuf, 5 cl. d'huile d'olive et du sel.<br>
                Dans un saladier, mélanger rapidement la farine, l'œuf, l'huile d'olive et le sel. Former une boule et laisser reposer pendant 1 h.
            </div>
        </div>

    </div>
</div>