<div class="row">
    <div class="col-md-12 col-lg 12 recettes">
        <div class="col-xs-12 col-sm-6 col-md-4 col-lg-4">
            <h2><?php echo __('Tuiles croquantes au parmesan');?></h2>
            <ul>
                <li><img src="<?php echo $this->getViewFileUrl('images/recettes/cutlery.png'); ?>"> <span class="gray">Pour</span> : 6 tuiles</li>
                <li><img src="<?php echo $this->getViewFileUrl('images/recettes/clock.png'); ?>"> <span class="gray">Préparation</span> : 10 min</li>
                <li><img src="<?php echo $this->getViewFileUrl('images/recettes/oven.png'); ?>"> <span class="gray">Cuisson</span> : 12 min</li>
            </ul>
            <h3 class="recette-part">Ingrédients</h3>
            <ul class="ingredients">
                <li>100 g de parmesan râpé</li>
                <li>20 g de farine</li>
            </ul>

        </div>
        <div class="col-xs-12 col-sm-6 col-md-4 col-lg-4">
            <img src="<?php echo $this->getViewFileUrl('images/recettes/tuiles_croquantes_parmesan.jpg'); ?>" alt="tuiles croquantes au parmesan time nutrition">
        </div>
        <div class="col-xs-12 col-sm-12 col-md-4 col-lg-4">
            Le Parmesan, appelé en Italie le Parmigiano Reggiano est une variété des fromages italiens à l'aspect granuleux connus sous l'appellation générique de Grana.<br>
            C'est un fromage à base de lait de vache, à pâte pressée cuite, affiné pendant 12 mois minimum, au goût fruité et typé.
        </div>
    </div>
</div>
<div class="row">
    <div class="col-md-12 col-lg-12 recettes">
        <h3 class="recette-part">Préparation</h3>
        <ul class="preparation">
            <li>Mélanger le parmesan et la farine.</li>
            <li>Faire chauffer une poêle antiadhésive sans matière grasse.</li>
            <li>Quand la poêle est chaude, faire 6 petits tas avec le mélange.</li>
            <li>Les étaler en fine couche.</li>
            <li>Laisser fondre sans prendre couleur.</li>
            <li>Quand les tuiles deviennent des dentelles, retirer la poêle du feu.</li>
            <li>Laisser refroidir 1 min. et décoller les tuiles à l'aide d'une spatule.</li>
        </ul>
    </div>
</div>
<div class="row">
    <div class="col-md-12 col-lg-12">
        <div class="astuce">
            <i class="fa fa-caret-right" aria-hidden="true"></i> ASTUCES TIME NUTRITION
            <div>
                Pour que le petit-déjeuner soit complet, vous pouvez servir par personne :<br>
                2 œufs cocotte, 3 tuiles au parmesan et 60 g de pain.
            </div>
        </div>

    </div>
</div>