<?php
/**
 * SolideWebservices/Flexslider
 *
 * @category Magento2_Module
 * @package  Flexslider
 * @author   Solide Webservices <contact@solidewebservices.com>
 * @license  https://opensource.org/licenses/OSL-3.0 Open Software License 3.0
 * @version  2.2.4
 * @link     https://solidewebservices.com
 */
?>

<?php if ($block->hasValidGroup()) :

    $objectManager = \Magento\Framework\App\ObjectManager::getInstance();
    $customerSession = $objectManager->get('Magento\Customer\Model\Session');
    $groupCollection = $block->_getCollection();

    foreach ($groupCollection as $group) :
        $slides = $block->getSlides($group['group_id']);
        $youtubeVideos = '';
        $vimeoVideos = '';
        $classes = '';
        $content = '';
        $loaderDuration = $group['group_slide_duration'] - ($group['group_animation_duration']);
        $initialLoaderDuration = $group['group_slide_duration'] - ($group['group_animation_duration']/2);

        if ($group['group_loggedin']==0 || ($group['group_loggedin']==1 && $customerSession->isLoggedIn())) :

            if (count($slides) > 0) :

                if ($group['width']) { ?>
                    <div class="flexslider-width" style="max-width: <?php echo $block->escapeHtml($group['width']) ?>px !important;">
                <?php } ?>

                    <?php if ($group['nav_position']=='outside') { ?>
                        <div id="nav-container">
                    <?php } ?>

                            <div class="sw-flexslider-element <?php echo $block->escapeHtml($group['identifier']) ?>-container <?php echo $block->escapeHtml($group['theme']) ?>-theme <?php echo $block->escapeHtml($group['nav_show']) ?>-nav-show <?php echo $block->escapeHtml($group['nav_style']) ?>-nav-style <?php echo $block->escapeHtml($group['nav_size']) ?>-nav-size <?php echo $block->escapeHtml($group['nav_position']) ?>-nav-position <?php echo $block->escapeHtml($group['pagination_style']) ?>-pagination-style <?php echo $block->escapeHtml($group['pagination_show']) ?>-pagination-show <?php echo $block->escapeHtml($group['pagination_position']) ?>-pagination-position <?php echo $block->escapeHtml($group['loader_position']) ?>-loader-position">

                                <?php if ($group['group_type']!='carousel') { ?>
                                <div class="sw-flexslider-container loading">
                                    <div id="flexslider-<?php echo $block->escapeHtml($group['identifier']) ?>" class="sw-flexslider flexslider-<?php echo $block->escapeHtml($group['identifier']) ?>">
                                        <ul class="slides">
                                        <?php if ($group['group_type']=='overlay') { ?>
                                            <div class="overlay-nav">
                                                <?php $height = 100/count($slides); ?>
                                                <?php foreach ($slides as $slide) : ?>
                                                    <div id="slideid-<?php echo $block->escapeHtml($slide['slide_id']); ?>" class="overlay-element" style="height:<?php echo $block->escapeHtml($height); ?>%">
                                                        <h3><?php echo $block->escapeHtml($slide->getTitle())?></h3>
                                                        <div class="overlay-arrow"></div>
                                                    </div>
                                                <?php endforeach ?>
                                            </div>
                                        <?php } ?>
                                        <?php foreach ($slides as $slide) : ?>
                                            <?php if ($slide['slide_loggedin']==0 || ($slide['slide_loggedin']==1 && $customerSession->isLoggedIn())) : ?>
                                                <?php switch ($slide['slide_type']) {
                                                    case 'youtube':
                                                        $youtubeVideos = $youtubeVideos + 1;
                                                        $classes = 'video youtube-video youtube_'. $block->escapeHtml($youtubeVideos) .' slide_'. $block->escapeHtml($slide['slide_id']);
                                                        $content = '<iframe class="youtube youtube-autoplay-'. $block->escapeHtml($slide['video_autoplay']) .'" id="ytplayer'. $block->escapeHtml($youtubeVideos) .'" src="//www.youtube.com/embed/'. $block->escapeHtml($slide['video_id']) .'?enablejsapi=1&amp;origin='. $block->flexsliderHelper->base_url().'&amp;rel=0&amp;wmode=opaque&amp;playerapiid=ytplayer'. $block->escapeHtml($youtubeVideos) .'&amp;showinfo=0&amp;modestbranding=1&amp;fs=0&amp;controls=2" width="500" height="281" frameborder="0" webkitAllowFullScreen mozallowfullscreen allowFullScreen></iframe>';
                                                        break;
                                                    case 'vimeo':
                                                        $vimeoVideos = $vimeoVideos + 1;
                                                        $classes = 'video vimeo-video vimeo_'. $block->escapeHtml($vimeoVideos) .' slide_'. $block->escapeHtml($slide['slide_id']);
                                                        $content = '<iframe class="vimeo vimeo-autoplay-'. $block->escapeHtml($slide['video_autoplay']) .'" id="player_'. $block->escapeHtml($vimeoVideos) .'" src="//player.vimeo.com/video/'. $block->escapeHtml($slide['video_id']) .'?api=1&amp;player_id=player_'. $block->escapeHtml($vimeoVideos) .'" width="500" height="281" frameborder="0" webkitAllowFullScreen mozallowfullscreen allowFullScreen></iframe>';
                                                        break;
                                                    default:
                                                        $classes = 'image slide_'. $block->escapeHtml($slide['slide_id']) ;
                                                        if ($block->flexsliderImageHelper->getImageUrl($slide['image'])) {
                                                            $content = '<img src="'. $block->flexsliderImageHelper->getImageUrl($slide['image']) .'" srcset="'. $block->flexsliderImageHelper->getImageUrl($slide['image']) .' 1200w, '. $block->flexsliderImageHelper->getImageUrl($slide['image'], 'flexslider/large/') .' 1024w, '. $block->flexsliderImageHelper->getImageUrl($slide['image'], 'flexslider/medium/') .' 640w, '. $block->flexsliderImageHelper->getImageUrl($slide['image'], 'flexslider/small/') .' 320w" sizes="100vw" alt="'. /* @noEscape */ $slide['alt_text'] .'" />';
                                                        } elseif ($slide['hosted_image_url']) {
                                                            $content = '<img src="'. /* @noEscape */ $slide['hosted_image_url'] .'" alt="'. /* @noEscape */ $slide['alt_text'] .'" />';
                                                        } else {
                                                            $content = '<h2>Image appears to be missing</h2>';
                                                        }
                                                        if ($slide->getUrl()) {
                                                            $content = '<a href="'. /* @noEscape */ $slide->getUrl() .'" title="'. /* @noEscape */ $slide['alt_text'] .'" target="'. /* @noEscape */ $slide->getUrlTarget() .'">'. /* @noEscape */ $content .'</a>';
                                                        }
                                                } ?>
                                                <li class="<?php echo $block->escapeHtml($classes); ?>">
                                                <?php /* @escapeNotVerified */ echo $content; ?>
                                                <?php
                                                if ($slide->getCaptionHtml()) {
                                                    if ($slide['caption_position']=='random') {
                                                        $input = ["top", "bottom", "top-left", "top-right", "bottom-left", "bottom-right"];
                                                        $captionPosition = $input[array_rand($input)];
                                                    } else {
                                                        $captionPosition = $slide['caption_position'];
                                                    }
                                                    if ($slide['caption_animation']==0) {
                                                        $captionPosition .= '-fixed';
                                                    } else {
                                                        $captionPosition .= '-animated';
                                                    } ?>
                                                    <div class="slider-title <?php echo $block->escapeHtml($captionPosition) ?>-caption">
                                                        <div class="caption"><?php echo $block->filterContent($slide->getCaptionHtml()) ?></div>
                                                    </div>
                                                <?php } ?>
                                                <?php if ($group['loader_show']==1) { ?>
                                                    <div class="loader-gutter">
                                                        <div class="loader"></div>
                                                    </div>
                                                <?php }?>
                                                </li>
                                            <?php endif; ?>
                                        <?php endforeach; ?>
                                        </ul>
                                    </div>
                                </div>
                                <?php } ?>

                                <?php if ($group['group_type']=='carousel' || $group['group_type']=='basic-carousel') { ?>
                                <div class="sw-flexslider-container loading">
                                    <div id="carousel-<?php echo $block->escapeHtml($group['identifier']) ?>" class="sw-flexslider carousel flexslider-<?php echo $block->escapeHtml($group['identifier']) ?>">
                                        <ul class="slides">
                                        <?php foreach ($slides as $slide) : ?>
                                            <?php if ($slide['slide_loggedin']==0 || ($slide['slide_loggedin']==1 && $customerSession->isLoggedIn())) : ?>
                                                <?php switch ($slide['slide_type']) {
                                                    case 'youtube':
                                                        $classes = 'video-thumbnail slide_'. $block->escapeHtml($slide['slide_id']);
                                                        $content = '<img src="//img.youtube.com/vi/'.$slide['video_id'].'/0.jpg" alt="'. $block->escapeHtml($slide['alt_text']) .'" />';
                                                        if ($group['group_type']=='carousel') {
                                                            $content = '<a href="//www.youtube.com/watch?v='. $block->escapeHtml($slide['video_id']) .'" title="'. $block->escapeHtml($slide['alt_text']) .'" target="_blank">'. $content .'</a>';
                                                        }
                                                        break;
                                                    case 'vimeo':
                                                        $classes = 'video-thumbnail slide_'. $block->escapeHtml($slide['slide_id']);
                                                        $img = $slide['video_id'];
                                                        $vimeoArray = unserialize(file_get_contents('//vimeo.com/api/v2/video/$img.php'));
                                                        $content = '<img src="'.$vimeoArray[0]['thumbnail_large'].'" alt="'. $block->escapeHtml($slide['alt_text']) .'" />';
                                                        if ($group['group_type']=='carousel') {
                                                            $content = '<a href="//vimeo.com/'. $block->escapeHtml($slide['video_id']) .'" title="'. $block->escapeHtml($slide['alt_text']) .'" target="_blank">'.$content.'</a>';
                                                        }
                                                        break;
                                                    default:
                                                        $classes = 'image-thumbnail slide_'. $block->escapeHtml($slide['slide_id']);
                                                        if ($block->flexsliderImageHelper->getImageUrl($slide['image'], 'flexslider/thumbnails/')) {
                                                            $content = '<img src="'. $block->flexsliderImageHelper->getImageUrl($slide['image'], 'flexslider/thumbnails/') .'" alt="'. /* @noEscape */ $slide['alt_text'] .'" />';
                                                        } else if ($slide['hosted_image_thumburl']) {
                                                            $content = '<img src="'. /* @noEscape */ $slide['hosted_image_thumburl'] .'" alt="'. /* @noEscape */ $slide['alt_text'] .'" />';
                                                        } else {
                                                            $content = '<h2>Thumbnail appears to be missing</h2>';
                                                        }
                                                        if ($slide['url'] && $group['group_type']=='carousel') {
                                                            $content = '<a href="'. /* @noEscape */ $slide['url'] .'" title="'. /* @noEscape */ $slide['alt_text'] .'" target="'. /* @noEscape */ $slide['url_target'] .'">'. /* @noEscape */ $content .'</a>';
                                                        }
                                                } ?>
                                                <li class="<?php echo $block->escapeHtml($classes); ?>">
                                                    <?php /* @escapeNotVerified */ echo $content; ?>
                                                </li>
                                            <?php endif; ?>
                                        <?php endforeach ?>
                                        </ul>
                                    </div>
                                </div>
                                <?php } ?>

                            </div>
                    <?php if ($group['nav_position']=='outside') { ?>
                        </div>
                    <?php } ?>
                <?php if ($group['width']) { ?>
                    </div>
                <?php } ?>

                <script type="text/javascript">
                    require([
                        'jquery',
                        'domReady!',
                        'solidewebservices/picturefill',
                        'solidewebservices/flexslider',
                        'solidewebservices/hoverintent'
                        <?php if ($block->flexsliderHelper->getConfig('flexslider/general/enable_easing')) { ?>, 'solidewebservices/easing'<?php } ?>
                        <?php if ($youtubeVideos || $vimeoVideos) { ?>, 'solidewebservices/fitvids'<?php } ?>
                        <?php if ($vimeoVideos) { ?>, 'solidewebservices/vimeo'<?php } ?>],
                        function($) {
                        "use strict";

                    <?php if ($group['group_type']=='carousel' || $group['group_type']=='basic-carousel') { ?>
                        $('#carousel-<?php echo $block->escapeHtml($group['identifier']) ?>').flexslider({
                            namespace:              "sw-flexslider-",
                        <?php if ($group['group_type']=='carousel') { ?>
                            directionNav:           <?php if ($group['nav_show']=='no') { echo 'false'; } else { echo 'true'; } ?>,
                        <?php } ?>
                            controlNav:              <?php if ($group['pagination_show']=='no' || $group['group_type']=='basic-carousel') { echo 'false'; } else { echo 'true'; } ?>,
                            animation:              "slide",
                            itemWidth:              <?php echo $group['thumbnail_size'] ?>,
                            itemMargin:             5,
                            minItems:               <?php echo $group['carousel_minitems'] ?>,
                            maxItems:               <?php echo $group['carousel_maxitems'] ?>,
                            move:                   <?php echo $group['carousel_move'] ?>,
                        <?php if ($group['group_type']=='basic-carousel') { ?>
                            slideshow:              false,
                            animationLoop:          false,
                            asNavFor:               '#flexslider-<?php echo $block->escapeHtml($group["identifier"]) ?>',
                        <?php } else { ?>
                            slideshow:              <?php echo $group['group_autoslide'] ? 'true' : 'false' ?>,
                            animationLoop:          <?php echo $group['group_autoloop'] ? 'true' : 'false' ?>,
                        <?php } ?>
                            start: function(slider) {
                                $('.sw-flexslider-container').removeClass('loading');
                            },
                        });
                    <?php } ?>

                    <?php if ($group['group_type']!='carousel') { ?>
                        $('#flexslider-<?php echo $block->escapeHtml($group['identifier']) ?>')<?php if ($youtubeVideos || $vimeoVideos) { ?>.fitVids()<?php } ?>.flexslider({
                            namespace:              "sw-flexslider-",
                        <?php if ($block->flexsliderHelper->getConfig('flexslider/general/enable_easing')) { ?>
                            easing:                 "<?php echo $group['group_animation_easing'] ?>",
                        <?php } ?>
                            useCSS:                 false,
                            directionNav:           <?php if ($group['nav_show']=='no' || $group['group_type']=='overlay') { echo 'false'; } else { echo 'true'; } ?>,
                        <?php if ($group['group_type']!='overlay') { ?>
                            controlNav:             <?php if ($group['pagination_show']=='no' || $group['group_type']=='basic-carousel') { echo 'false'; } else { echo 'true'; } ?>,
                            <?php } ?>
                            keyboard:               true,
                            multipleKeyboard:       true,
                            slideshow:              <?php echo $group['group_autoslide'] ? 'true' : 'false' ?>,
                        <?php if ($block->getStartSlideId()) { ?>
                            startAt:                <?php $startslide = $block->getStartSlideId() - 1; echo $startslide; ?>,
                        <?php } ?>
                            animationLoop:          <?php echo $block->escapeHtml($group['group_autoloop']) ? 'true' : 'false' ?>,
                            pauseOnAction:          <?php echo $block->escapeHtml($group['group_pauseonaction']) ? 'true' : 'false' ?>,
                            pauseOnHover:           <?php echo $block->escapeHtml($group['group_pauseonhover']) ? 'true' : 'false' ?>,
                            animation:              "<?php echo $block->escapeHtml($group['group_animation']) ?>",
                            animationSpeed:         <?php echo $block->escapeHtml($group['group_animation_duration']) ?>,
                            direction:              "<?php echo $block->escapeHtml($group['group_animation_direction']) ?>",
                            reverse:                <?php echo $block->escapeHtml($group['group_animation_reverse']) ? 'true' : 'false' ?>,
                            slideshowSpeed:         <?php echo $block->escapeHtml($group['group_slide_duration']) ?>,
                            randomize:              <?php echo $block->escapeHtml($group['group_random_slides']) ? 'true' : 'false' ?>,
                            smoothHeight:           <?php echo $block->escapeHtml($group['group_smoothheight']) ? 'true' : 'false' ?>,
                            controlsContainer:      ".flex-nav-container",
                        <?php if ($group['group_type']=='basic-carousel') { ?>
                            sync:                   '#carousel-<?php echo $block->escapeHtml($group['identifier']) ?>',
                        <?php } ?>
                        <?php if ($group['group_type']=='overlay') { ?>
                            manualControls:         "#flexslider-<?php echo $block->escapeHtml($group['identifier']) ?> .overlay-nav .overlay-element",
                            controlNav:             true,
                        <?php } ?>
                        <?php if ($youtubeVideos || $vimeoVideos) { ?>
                            video:                  true,
                        <?php } ?>
                            start: function(slider){
                            <?php if ($group['loader_show']==1) { ?>
                                animateLoader_<?php echo $block->escapeHtml($group['identifier']) ?>(<?php echo $initialLoaderDuration ?>);
                            <?php } ?>
                                $('.sw-flexslider-container').removeClass('loading');
                                animateCaption_<?php echo $group['identifier'] ?>();
                                if (slider.slides.eq(0).find('iframe.youtube-autoplay-1').length) {
                                    $('#flexslider-<?php echo $block->escapeHtml($group['identifier']) ?>').flexslider("pause");
                                    setTimeout(function() {
                                        playVideo_<?php echo $block->escapeHtml($group['identifier']) ?>($('.youtube_1:not(.clone) iframe.youtube').attr('id'));
                                    }, 2000);
                                }
                                if (slider.slides.eq(0).find('iframe.vimeo-autoplay-1').length) {
                                    $('#flexslider-<?php echo $block->escapeHtml($group['identifier']) ?>').flexslider("pause");
                                    setTimeout(function() {
                                        var $selector = $(".vimeo_1:not(.clone) iframe.vimeo").attr('id');
                                        $('#'+ $selector + '').vimeo("play");
                                    },<?php echo $block->escapeHtml($group['group_animation_duration']) ?>);
                                }
                            },
                            before: function(slider) {
                                <?php if ($youtubeVideos) { ?>
                                    if (slider.slides.eq(slider.currentSlide).find('iframe.youtube').length) {
                                        var previousVideo = slider.slides.eq(slider.currentSlide).find('iframe.youtube').attr('id');
                                        pauseVideo_<?php echo $group['identifier'] ?>(previousVideo);
                                    }
                                    if (slider.slides.eq(slider.currentSlide + 1).find('iframe.youtube-autoplay-1').length) {
                                        playVideo_<?php echo $group['identifier'] ?>(slider.slides.eq(slider.currentSlide + 1).find('iframe.youtube').attr('id'));
                                    }
                                <?php } ?>
                                <?php if ($vimeoVideos) { ?>
                                    if (slider.slides.eq(slider.currentSlide).find('iframe.vimeo').length) {
                                        $('#'+ slider.slides.eq(slider.currentSlide).find('iframe.vimeo').attr('id')+ '').vimeo("pause");
                                    }
                                    if (slider.slides.eq(slider.currentSlide + 1).find('iframe.vimeo-autoplay-1').length) {
                                        $('#flexslider-<?php echo $group['identifier'] ?>').flexslider("pause");
                                        $('#'+ slider.slides.eq(slider.currentSlide + 1).find('iframe.vimeo').attr('id')+ '').vimeo("play");
                                    }
                                <?php } ?>
                                resetCaption_<?php echo $block->escapeHtml($group['identifier']) ?>();
                            },
                            after: function(slider) {
                                <?php if ($group['loader_show']==1) { ?>
                                    animateLoader_<?php echo $block->escapeHtml($group['identifier']) ?>(<?php echo $block->escapeHtml($loaderDuration) ?>);
                                <?php } ?>
                                animateCaption_<?php echo $block->escapeHtml($group['identifier']) ?>();
                            },
                        });

                        $('.sw-flexslider-prev, .sw-flexslider-next, .sw-flexslider-control-nav, .sw-flexslider-control-paging').click(function(){
                            <?php if ($group['group_pauseonaction']==1) { ?>
                                stopAnimateLoader_<?php echo $block->escapeHtml($group['identifier']) ?>(0);
                            <?php } ?>
                        });
                    <?php } ?>

                        function animateLoader_<?php echo $block->escapeHtml($group['identifier']) ?>(varDuration){
                            $('#flexslider-<?php echo $block->escapeHtml($group['identifier']) ?> .loader').width('0%').animate({width: '100%'}, {easing: 'linear', duration: varDuration, queue: false, complete: function(){$('#flexslider-<?php echo $block->escapeHtml($group['identifier']) ?> .loader').width('0%');}});
                        }
                        function stopAnimateLoader_<?php echo $block->escapeHtml($group['identifier']) ?>(timeDelay){
                            if (typeof(timeDelay) === "undefined") {
                                $('#flexslider-<?php echo $block->escapeHtml($group['identifier']) ?> .loader-gutter').fadeOut(500);
                            } else {
                                $('#flexslider-<?php echo $block->escapeHtml($group['identifier']) ?> .loader-gutter').hide();
                            }
                        }
                        function resumeAnimateLoader_<?php echo $block->escapeHtml($group['identifier']) ?>(){
                            $('#flexslider-<?php echo $block->escapeHtml($group['identifier']) ?> .loader-gutter, .loader').clearQueue();
                            animateLoader_<?php echo $block->escapeHtml($group['identifier']) ?>(<?php echo $block->escapeHtml($group['group_slide_duration']) ?>);
                            $('#flexslider-<?php echo $block->escapeHtml($group['identifier']) ?> .loader-gutter').fadeIn(200);
                        }

                        <?php if ($block->flexsliderHelper->overlayEnabled()) { ?>
                            $('.overlay-nav .overlay-element').hoverIntent({
                                over: function(){
                                    var activeSlide = 'false';
                                    if ($(this).hasClass('sw-flexslider-active')){
                                        activeSlide = 'true';
                                    }
                                    if(activeSlide == 'false'){
                                        $(this).trigger("click");
                                    }
                                },
                                out: function(){},
                                interval: 250
                            });
                        <?php } ?>

                        function animateCaption_<?php echo $group['identifier'] ?>() {
                            $("#flexslider-<?php echo $block->escapeHtml($group['identifier']) ?> .slides .sw-flexslider-active-slide .slider-title").show();
                            $("#flexslider-<?php echo $block->escapeHtml($group['identifier']) ?> .slides .top-animated-caption").delay(200).animate({top:'0'}, 800);
                            $("#flexslider-<?php echo $block->escapeHtml($group['identifier']) ?> .slides .bottom-animated-caption").delay(200).animate({bottom:'0'}, 800);
                            $("#flexslider-<?php echo $block->escapeHtml($group['identifier']) ?> .slides .top-left-animated-caption, #flexslider-<?php echo $block->escapeHtml($group['identifier']) ?> .slides .bottom-left-animated-caption").delay(200).animate({left:'0'}, 800);
                            $("#flexslider-<?php echo $block->escapeHtml($group['identifier']) ?> .slides .top-right-animated-caption, #flexslider-<?php echo $block->escapeHtml($group['identifier']) ?> .slides .bottom-right-animated-caption").delay(200).animate({right:'0'}, 800);
                        }
                        function resetCaption_<?php echo $group['identifier'] ?>() {
                            $("#flexslider-<?php echo $block->escapeHtml($group['identifier']) ?> .slides .slider-title").hide();
                            $("#flexslider-<?php echo $block->escapeHtml($group['identifier']) ?> .slides .top-animated-caption").css({top: '-100%'});
                            $("#flexslider-<?php echo $block->escapeHtml($group['identifier']) ?> .slides .bottom-animated-caption").css({bottom: '-100%'});
                            $("#flexslider-<?php echo $block->escapeHtml($group['identifier']) ?> .slides .top-left-animated-caption, #flexslider-<?php echo $block->escapeHtml($group['identifier']) ?> .slides .bottom-left-animated-caption").css({left: '-50%'});
                            $("#flexslider-<?php echo $block->escapeHtml($group['identifier']) ?> .slides .top-right-animated-caption, #flexslider-<?php echo $block->escapeHtml($group['identifier']) ?> .slides .bottom-right-animated-caption").css({right: '-50%'});
                        }

                        <?php if ($group['group_pauseonhover']==1) { ?>
                            $('#flexslider-<?php echo $block->escapeHtml($group['identifier']) ?>').hoverIntent({
                                over: function(){
                                    stopAnimateLoader_<?php echo $group['identifier'] ?>();
                                },
                                out: function(){
                                    if($(this).find('.sw-flexslider-active-slide iframe.youtube').length) {
                                        var currentVideo = $(this).find('.sw-flexslider-active-slide iframe').attr('id');
                                        if (players_<?php echo $block->escapeHtml($group['identifier']) ?>[currentVideo].getPlayerState()==1) {
                                            setTimeout(function() {
                                                $('#flexslider-<?php echo $block->escapeHtml($group['identifier']) ?>').flexslider("pause");
                                            },2000);
                                        } else {
                                            resumeAnimateLoader_<?php echo $block->escapeHtml($group['identifier']) ?>();
                                        }
                                    } else if ($(this).find('.sw-flexslider-active-slide iframe.vimeo-autoplay-1').length) {
                                        setTimeout(function() {
                                                $('#flexslider-<?php echo $block->escapeHtml($group['identifier']) ?>').flexslider("pause");
                                        },2000);
                                    } else {
                                        resumeAnimateLoader_<?php echo $block->escapeHtml($group['identifier']) ?>();
                                    }
                                },
                                interval: 250
                            });
                        <?php } ?>

                        <?php if ($youtubeVideos) { ?>
                            var YT_ready = (function() {
                                var onReady_funcs = [],
                                api_isReady = false;
                                return function(func, b_before) {
                                    if (func === true) {
                                        api_isReady = true;
                                        for (var i = 0; i < onReady_funcs.length; i++) {
                                            onReady_funcs.shift()();
                                        }
                                    }
                                    else if (typeof func == "function") {
                                        if (api_isReady) func();
                                        else onReady_funcs[b_before ? "unshift" : "push"](func);
                                    }
                                }
                            })();
                            window.onYouTubePlayerAPIReady = function() {
                                YT_ready(true);
                            }

                            var players_<?php echo $group['identifier'] ?> = {};
                            YT_ready(function() {
                                $("li.video iframe.youtube").each(function(event) {
                                    var frameID_<?php echo $block->escapeHtml($group['identifier']) ?> = $(this).attr('id');
                                    if (frameID_<?php echo $block->escapeHtml($group['identifier']) ?>) {
                                        players_<?php echo $block->escapeHtml($group['identifier']) ?>[frameID_<?php echo $block->escapeHtml($group['identifier']) ?>] = new YT.Player(frameID_<?php echo $block->escapeHtml($group['identifier']) ?>, {
                                            events: {
                                                'onStateChange': onPlayerStateChange_<?php echo $block->escapeHtml($group['identifier']) ?>
                                            }
                                        });
                                    }
                                });
                            });
                            (function(){
                                var tag = document.createElement('script');
                                tag.src = "//www.youtube.com/iframe_api";
                                var firstScriptTag = document.getElementsByTagName('script')[0];
                                firstScriptTag.parentNode.insertBefore(tag, firstScriptTag);
                            })();

                            function onPlayerStateChange_<?php echo $block->escapeHtml($group['identifier']) ?>(event) {
                                if (event.data === 0) {
                                    $('#flexslider-<?php echo $block->escapeHtml($group['identifier']) ?>').flexslider("next");
                                    $('#flexslider-<?php echo $block->escapeHtml($group['identifier']) ?>').flexslider("play");
                                    <?php if ($group['loader_show']==1) { ?>
                                        resumeAnimateLoader_<?php echo $block->escapeHtml($group['identifier']) ?>();
                                    <?php } ?>
                                } else if (event.data === 1) {
                                    $('#flexslider-<?php echo $block->escapeHtml($group['identifier']) ?>').flexslider("pause");
                                    <?php if ($group['loader_show']==1) { ?>
                                        stopAnimateLoader_<?php echo $block->escapeHtml($group['identifier']) ?>();
                                    <?php } ?>
                                } else if (event.data === 2) {
                                    $('#flexslider-<?php echo $block->escapeHtml($group['identifier']) ?>').flexslider("play");
                                    <?php if ($group['loader_show']==1 && $group['group_pauseonhover']!=1) { ?>
                                        resumeAnimateLoader_<?php echo $block->escapeHtml($group['identifier']) ?>();
                                    <?php } ?>
                                }
                            }

                            function pauseVideo_<?php echo $block->escapeHtml($group['identifier']) ?>(previousVideo) {
                                players_<?php echo $block->escapeHtml($group['identifier']) ?>[previousVideo].pauseVideo();
                            }
                            function playVideo_<?php echo $block->escapeHtml($group['identifier']) ?>(currentVideo) {
                                $('#flexslider-<?php echo $group['identifier'] ?>').flexslider("pause");
                                players_<?php echo $block->escapeHtml($group['identifier']) ?>[currentVideo].playVideo();
                            }

                        <?php } ?>

                        <?php if ($vimeoVideos) { ?>
                            $("#flexslider-<?php echo $block->escapeHtml($group['identifier']) ?> li.video #player_<?php echo $block->escapeHtml($vimeoVideos) ?>").on("play", function(){
                                $('#flexslider-<?php echo $block->escapeHtml($group['identifier']) ?>').flexslider("pause");
                                <?php if ($group['loader_show']==1) { ?>
                                    stopAnimateLoader_<?php echo $block->escapeHtml($group['identifier']) ?>();
                                <?php } ?>
                            });
                            $("#flexslider-<?php echo $block->escapeHtml($group['identifier']) ?> li.video #player_<?php echo $block->escapeHtml($vimeoVideos) ?>").on("pause", function(){
                                $('#flexslider-<?php echo $block->escapeHtml($group['identifier']) ?>').flexslider("next");
                                <?php if ($group['loader_show']==1) { ?>
                                    resumeAnimateLoader_<?php echo $block->escapeHtml($group['identifier']) ?>();
                                <?php } ?>
                            });
                            $("#flexslider-<?php echo $block->escapeHtml($group['identifier']) ?> li.video #player_<?php echo $block->escapeHtml($vimeoVideos) ?>").on("finish", function(){
                                $('#flexslider-<?php echo $block->escapeHtml($group['identifier']) ?>').flexslider("next");
                                <?php if ($group['loader_show']==1) { ?>
                                    resumeAnimateLoader_<?php echo $block->escapeHtml($group['identifier']) ?>();
                                <?php } ?>
                            });

                        <?php } ?>

                    });

                </script>

            <?php if ($block->getCode()) : ?>
                <style type="text/css">
                    .flexslider-<?php echo $block->escapeHtml($group['identifier']) ?> .sw-flexslider-direction-nav .sw-flexslider-prev:before,
                    .flexslider-<?php echo $block->escapeHtml($group['identifier']) ?> .sw-flexslider-direction-nav .sw-flexslider-next:before
                    {
                        color: <?php echo $block->escapeHtml($group['nav_color']) ?>;
                    }
                    .flexslider-<?php echo $block->escapeHtml($group['identifier']) ?> .sw-flexslider-control-paging li a
                    {
                        background-color: <?php echo $block->escapeHtml($group['pagination_color']) ?>;
                    }
                    .flexslider-<?php echo $block->escapeHtml($group['identifier']) ?> .sw-flexslider-control-paging li a:hover
                    {
                        background-color: <?php echo $block->escapeHtml($group['pagination_hover_color']) ?>;
                    }
                    .flexslider-<?php echo $block->escapeHtml($group['identifier']) ?> .sw-flexslider-control-paging li a.sw-flexslider-active
                    {
                        background-color: <?php echo $block->escapeHtml($group['pagination_active_color']) ?>;
                    }
                    .flexslider-<?php echo $block->escapeHtml($group['identifier']) ?> .loader-gutter
                    {
                        background-color: <?php echo $block->escapeHtml($group['loader_bgcolor']) ?>;
                    }
                    .flexslider-<?php echo $block->escapeHtml($group['identifier']) ?> .loader
                    {
                        background-color: <?php echo $block->escapeHtml($group['loader_color']) ?>;
                    }
                    .flexslider-<?php echo $block->escapeHtml($group['identifier']) ?> .slides .slider-title
                    {
                        background-color: <?php echo $block->escapeHtml($group['caption_bgcolor']) ?>;
                        color: <?php echo $block->escapeHtml($group['caption_textcolor']) ?>;
                    }
                <?php if ($group['theme']=='custom') {
                    echo $block->escapeHtml($group['custom_theme']);
                } ?>
                <?php if ($group['group_type']=='overlay') { ?>
                    .overlay-nav
                    {
                        <?php if ($group['overlay_position']=='right') {
                            echo 'right: 0';
                        } else {
                            echo 'left: 0';
                        } ?>;
                        background-color: <?php echo $block->escapeHtml($group['overlay_bgcolor']) ?>;
                    }
                    .overlay-nav .overlay-element h3,
                    .overlay-nav .overlay-element .overlay-arrow:before
                    {
                        color: <?php echo $block->escapeHtml($group['overlay_textcolor']) ?>;
                    }
                    .overlay-nav .overlay-element:hover,
                    .overlay-nav .sw-flexslider-active
                    {
                        background-color: <?php echo $block->escapeHtml($group['overlay_hovercolor']) ?>;
                    }
                <?php } ?>
                <?php if ($group['nav_size']=='bigger') { ?>
                    .bigger-nav-size .sw-flexslider .sw-flexslider-direction-nav .sw-flexslider-prev:before,
                    .bigger-nav-size .sw-flexslider .sw-flexslider-direction-nav .sw-flexslider-next:before
                    {
                        font-size: 34px;
                    }
                    .bigger-nav-size .sw-flexslider:hover .sw-flexslider-direction-nav .sw-flexslider-prev:before,
                    .bigger-nav-size .sw-flexslider:hover .sw-flexslider-direction-nav .sw-flexslider-next:before
                    {
                        font-size: 40px;
                    }
                <?php } ?>
                <?php if ($group['nav_size']=='biggest') { ?>
                    .biggest-nav-size .sw-flexslider .sw-flexslider-direction-nav .sw-flexslider-prev:before,
                    .biggest-nav-size .sw-flexslider .sw-flexslider-direction-nav .sw-flexslider-next:before
                    {
                        font-size: 54px;
                    }
                    .biggest-nav-size .sw-flexslider:hover .sw-flexslider-direction-nav .sw-flexslider-prev:before,
                    .biggest-nav-size .sw-flexslider:hover .sw-flexslider-direction-nav .sw-flexslider-next:before
                    {
                        font-size: 60px;
                    }
                <?php } ?>
                </style>
            <?php endif; ?>
            <?php
            endif; // end if slides > 0
        endif; // end if customer logged in for group
    endforeach; // end foreach $groupCollection
endif; // end hasValidGroup()
