 <dl class="container-selector">
        <h2 class="accordion_toggle_categorie">Généralités TIME Nutrition</h2>
        <dt class="accordion_toggle"><a href="">Qu'est-ce que TIME Nutrition ?</a></dt>
        <dd class="accordion_content">
            <p>TIME Nutrition est un concept global qui agit sur  votre santé, votre minceur, votre bien-être et votre vieillissement en  proposant un programme alimentaire et des produits complémentaires  personnalisés.</p>
            <p>TIME Nutrition est l'art et la manière de manger  tous les aliments de façon physiologique c’est-à-dire aux moments de la journée  où ils seront les plus utiles, afin de satisfaire chaque jour les besoins en  énergie de notre organisme, sans que les aliments et les graisses ne soient  pour autant stockés dans certaines parties du corps, créant ainsi des problèmes  de silhouette (rondeurs «&nbsp;malvenues&nbsp;», etc.). TIME Nutrition répartit  les aliments et les proportions en fonction du moment de la journée où ils  seront absorbés, de votre activité, de votre taille et de votre profil. </p>
            <p>TIME Nutrition prend en compte la gestion des  sucres selon leur qualité (la qualité des sucres varie selon leur  composition&nbsp;: c’est une avancée spécifique TIME Nutrition) et selon leur  pouvoir glycémique. TIME Nutrition prend en compte les dégâts occasionnés sur  votre organisme par le stress oxydatif, les glycations et l’acidification.</p>
            <p>TIME Nutrition, c’est le bon aliment, au bon  moment, dans la bonne quantité et la bonne qualité.<br/>
            </p>
        </dd>
        <dt class="accordion_toggle"><a href="">Les enfants peuvent-ils suivre le programme TIME Nutrition ?</a></dt>
        <dd class="accordion_content">
            <p>Oui, bien sûr. La croissance majore les besoins  alimentaires et en modifie les proportions qualitatives pour permettre la construction  des cellules. Le programme TIME Nutrition peut tout à fait être adapté aux  enfants. </p>
        </dd>
        <dt class="accordion_toggle"><a href="">Les personnes âgées peuvent-elles suivre le programme TIME Nutrition ?</a> </dt>
        <dd class="accordion_content">
            <p>Oui, TIME Nutrition est un programme  physiologique adapté à tous. <br />
                Le vieillissement nécessite, pour se faire dans  les meilleures conditions, la modification progressive de l'alimentation afin  de lutter contre l'accélération du catabolisme oxydatif (la destruction des  cellules). </p>
            <p>Pour cela, il faut augmenter progressivement les  apports en nutriments antioxydants, en protéines et en lipides insaturés afin  d’apporter ce qui est nécessaire à l'organisme pour qu’il puisse lutter sans  s'épuiser.</p>
        </dd>
        <dt class="accordion_toggle"><a href="">Pourquoi TIME Nutrition aura de meilleurs résultats que tous les régimes et autres méthodes existantes ?</a></dt>
        <dd class="accordion_content">
            <p>Parce-que TIME Nutrition n’est pas un régime. Un  régime est une restriction alimentaire qui va vous permettre de maigrir. Maigrir,  c'est perdre du poids sans distinction. Cela peut donc autant correspondre à la  perte de ce que vous avez emmagasiné d'utile pour votre organisme que ce que vous  avez stocké d'inutile. En maigrissant vous pouvez donc perdre plus rapidement  des muscles que de la graisse et fragiliser votre santé.</p>
            <p>TIME Nutrition est efficace et durable car ne  vous promet pas de maigrir de façon fulgurante mais de mincir. </p>
            <p>Mincir, c'est se débarrasser simplement de ce qui  est accumulé en trop. En mincissant, vous vous débarrasserez uniquement de ce  qui gênait le bon fonctionnement de votre organisme : l'excès de gras et d'eau. </p>
            <p>Mincir durablement et apprendre à manger  correctement&nbsp;: ce sont les objectifs de TIME Nutrition.</p>
        </dd>
        <dt class="accordion_toggle"><a href="">Pourquoi TIME Nutrition n’est pas une méthode yo-yo ?</a> </dt>
        <dd class="accordion_content">
            <p>TIME Nutrition n'est pas un régime yo-yo car ce  n’est pas une méthode miracle destinée à faire mincir en quelques jours. TIME  Nutrition a pour but de vous faire adopter définitivement et sans souffrance  l’alimentation exactement adaptée aux besoins de votre physiologie sans restriction  aucune.</p>
            <p>Le résultat typique de ce qu'on appelle les  régimes «&nbsp;yo-yo&nbsp;» est une oscillation périodique entre grosseur et  maigreur. Ces régimes conduisent inéluctablement à une augmentation du poids à  l’arrêt du régime. </p>
            <p>Le mécanisme est simple : le régime provoque une  restriction et donc une carence alimentaire&nbsp;; lorsqu’on l’arrête, le corps  se protège de toute nouvelle pénurie et va stocker des réserves ! </p>
            <p>En cherchant à corriger une prise de poids par  une restriction alimentaire, vous aggravez le problème au lieu de le résoudre.  Ce qui explique pourquoi plus on persiste dans la voie des régimes, plus on  grossit !</p>
        </dd>
        <dt class="accordion_toggle"><a href="">En suivant TIME Nutrition est-ce que je ne risque pas des carences ?</a></dt>
        <dd class="accordion_content">
            <p>Non. Le programme alimentaire TIME Nutrition avec  ses synchroniseurs alimentaires répond aux besoins de votre organisme car il  est personnalisé et adapté à chacun et chacune. Il répond aux besoins  physiologiques de votre morphologie, il est adapté à vos tendances alimentaires  et à votre activité, et vous évite ainsi toutes carences.</p>
        </dd>
        <dt class="accordion_toggle"><a href="">Est-ce que en suivant cette méthode, je risque d’avoir faim au cours de la journée ?</a></dt>
        <dd class="accordion_content">
            <p>Non, TIME Nutrition vous propose un programme  équilibré et physiologique. Il ne vous soumet à aucune restriction et apporte  ce qu’il vous faut à chaque repas.</p>
            <p>Si vous respectez les recommandations  alimentaires, la prise des synchroniseurs et les quantités conseillées, vous  trouverez un véritable équilibre, idéal pour votre silhouette, optimal pour  votre santé et pouvant être maintenu tout au long de votre vie. </p>
            <p>N’essayez pas de modifier les recommandations,  vous déséquilibreriez la gestion de votre appétit et de votre faim.</p>
        </dd>
        <dt class="accordion_toggle"><a href="">Y a-t-il des recommandations communes à tous les repas TIME Nutrition ?</a></dt>
        <dd class="accordion_content">
            <p>Oui en effet il y en a&nbsp;!</p>
            <ul>
                <li>Ne  modifiez pas l’ordre de vos repas, sauf si vous travaillez la nuit. Dans ce cas  une adaptation est possible.</li>
            </ul>
            <ul>
                <li>Ne  cherchez pas à diminuer les quantités indiquées pour mincir plus vite&nbsp;:  vous obtiendrez un résultat inverse&nbsp;!</li>
            </ul>
            <ul>
                <li>N’augmentez  pas les légumes verts ou les crudités&nbsp;: votre intestin n’apprécierait  pas&nbsp;!</li>
            </ul>
            <ul>
                <li>Utilisez  condiments et sauces à votre convenance sans dépasser le raisonnable (une  pincée pour les premiers, une cuillère à café pour les seconds&nbsp;!)</li>
            </ul>
        </dd>

        <h2 class="accordion_toggle_categorie">Aliments et silhouette</h2>
        <dt class="accordion_toggle"><a href="">Tous les aliments se valent-ils ?</a> </dt>
        <dd class="accordion_content">
            <p>Non. </p>
            <p>D’une part, chacun sait qu'il y a des aliments  très nourrissants et des aliments qui le sont peu. Par exemple, il faut 30 g de  lipides purs par jour pour satisfaire les besoins quotidiens de l'être humain.  Pour cela, 100 g de fromage suffiront. Pour ce même apport il faudrait 500 g de  yaourt ou 1 litre de lait par jour. </p>
            <p>D’autre part, les modes de cuisson, de  conservation ou de stérilisation modifient les aliments et les rendent plus ou  moins utilisables ou dangereux pour nos organismes. Comme on ne connaît pas  toujours ces modifications, il convient de bien être prêt, physiologiquement  parlant, pour les assimiler à moindre risque&nbsp;: c’est le rôle des  synchroniseurs de TIME Nutrition.</p>
            <p>Enfin, certains aliments apportent trop d’eau ou  de sucres par rapport à leur teneur en protéines ou en lipides. Pour reprendre  l’exemple des 100 g de fromage, c’est un aliment concentré en nutriments  essentiels (protéines et lipides entre autres) qui ne seront pas stockés si on  le prend le matin. Ces mêmes nutriments pris sous forme de 1 litre de lait,  lactose et eau (presque absents du fromage) seront en partie stockés dans les  adipocytes et feront prendre «&nbsp;du volume&nbsp;»&nbsp;!<br/>
            </p>
        </dd>
        <dt class="accordion_toggle"><a href="">Les aliments ont-ils une influence sur la forme du corps ?</a></dt>
        <dd class="accordion_content">
            <p>Oui. Par exemple :<br />
            <ul>
                <li>trop d’aliments riches en fibres donnent du  volume au bas du corps.</li>
                <li>trop d’aliments riches en féculents génèrent  une graisse abdominale.</li>
            </ul>
        </dd>
        <dt class="accordion_toggle"><a href="">Peut-on faire grossir sa poitrine par l’alimentation ?</a></dt>
        <dd class="accordion_content">
            <p>L'association de plats riches en lipides et en sucres  gonflera les seins, mais aussi, attention, la taille et les hanches ! </p>
            <p>Cette silhouette risque de s'accompagner plus  tard d'anomalies biologiques : diabète et hypercholestérolémie dits de  surcharge, c'est-à-dire seulement liés aux erreurs nutritionnelles et à l'excès  de poids. </p>
            <p>Il est possible d’agir uniquement sur la poitrine  avec des synchroniseurs bien spécifiques que TIME Nutrition proposera bientôt.<br/>
            </p>
        </dd>
        <dt class="accordion_toggle"><a href="">Faut-il manger léger pour maigrir ?</a> </dt>
        <dd class="accordion_content">
            <p>Il est inutile de manger léger pour maigrir !  C’est même dangereux pour la santé (carences). </p>
            Il faut simplement suivre les recommandations  personnalisées de TIME Nutrition et supprimer les erreurs responsables de la  prise de poids ou de volume.</dd>
        <dt class="accordion_toggle"><a href="">Pourquoi les aliments allégés sont inutiles ?</a></dt>
        <dd class="accordion_content">
            <p>L’allégement des aliments consiste souvent à  rajouter de l'eau ou par exemple des algues à la nourriture normale. Cet «&nbsp;enrichissement&nbsp;»  malencontreux le rend d’une part moins nourrissant pour un volume égal et  d’autre part favorise l’accumulation d’eau dans les cellules adipeuses et donc  la cellulite. </p>
        </dd>
        <dt class="accordion_toggle"><a href="">Est-ce que je peux consommer des yaourts ou fromages blancs allégés ?</a></dt>
        <dd class="accordion_content">
            <p>Oui, vous pouvez en consommer pendant les repas  TIME Free car ils contiennent tous  trop  de lactose, sucre indigeste, et  risquent  de faire prendre de la cellulite dans le bas du corps (hanches, cuisses) ! </p>
            <p>Attention&nbsp;! Même à 0% de matière grasse, le lactose  est présent, c’est un sucre ! Il en est de même pour les fromages blancs.<br/>
            </p>
        </dd>
        <dt class="accordion_toggle"><a href="">Comment expliquer que deux personnes qui mangent les mêmes choses n’aient pas les mêmes répercussions sur leur silhouette ?</a></dt>
        <dd class="accordion_content">
            <p>Notre corps se modifie en fonction des habitudes  alimentaires (bonnes ou mauvaises) que nous avons. Quand il y a un problème de  morphologie et/ou de poids, nos habitudes sont pratiquement toujours  responsables. Les glandes sont rarement en cause. </p>
            <p>Et même si souvent on entend « c’est de famille !  », on trouve bine plus souvent une tradition familiale d’erreurs alimentaires  qu’une anomalie génétique familiale.</p>
            <p>Veuillez noter que les diabètes, anomalies  thyroïdiennes ou hypercholestérolémies d'origine génétique sont rares : en  général poids et surpoids sont liés à des erreurs nutritionnelles. </p>
        </dd>
        <dt class="accordion_toggle"><a href="">J’ai des formes généreuses et de la cellulite au niveau des fesses, est-ce que c'est la nature qui m’a faite ainsi ?</a></dt>
        <dd class="accordion_content">
            <p>Non&nbsp;! La génétique n’est pas unique responsable  des formes. C’est aussi et surtout la manifestation d’une alimentation  déséquilibrée qui entraîne une grande accumulation d’eau ou de gras.</p>
        </dd>
        <dt class="accordion_toggle"><a href="">Faut-il faire beaucoup de sport pour avoir une silhouette musclée ?</a></dt>
        <dd class="accordion_content">
            <p>Il faut en faire un peu, c’est sûr, mais il faut  surtout apporter ce qui permet à votre corps de fabriquer du muscle et éviter  ce qui donne du ventre, des fesses ou des cuisses&nbsp;! </p>
        </dd>
        <dt class="accordion_toggle"><a href="">Est-ce que je peux consommer des laits végétaux (lait d'amande ou de soja ou de riz) ?</a></dt>
        <dd class="accordion_content">
            <p>Vous pouvez en consommer surtout pendant les  repas TIME Free. En dehors, seul le lait d’amande peut être consommé de temps  en temps au petit déjeuner ou au goûter.</p>
            <p>Le soja, qui est sans doute un aliment  intéressant pendant la ménopause, risque de réveiller un syndrome cancéreux. Le  lait de riz est trop sucré.<strong></strong></p>
        </dd>
        <dt class="accordion_toggle"><a href="">Comment respecter la recommandation du Plan National Nutrition Santé : consommer 5 fruits et légumes par jour ? </a></dt>
        <dd class="accordion_content">
            <p>TIME  Nutrition respecte cette recommandation et va même plus loin&nbsp;en vous proposant  les moments idéaux pour consommer les fruits et les légumes&nbsp;!</p>
            Prenez les fruits au goûter, privilégiez les  céréales le matin (pain), les légumes secs à midi et les légumes verts le soir. </dd>

        <h2 class="accordion_toggle_categorie">Petit-déjeuner TIME Nutrition </h2>
        <dt class="accordion_toggle"><a href="">Quel est l’heure idéale pour prendre le petit-déjeuner ?</a></dt>
        <dd class="accordion_content">
            <p>Idéalement, le petit-déjeuner doit se prendre  dans l'heure qui suit le lever. </p>
        </dd>
        <dt class="accordion_toggle"><a href="">Comment faire quand je fais une grasse matinée et que je me lève à 11h ? Faut-il tout de même prendre un petit déjeuner ?</a></dt>
        <dd class="accordion_content">
            <p>Oui, mais si vous remangez 1 ou 2 heures plus  tard, prenez le léger. Partagez par exemple la quantité de fromage en  deux&nbsp;: moitié à 11h et le reste au repas du déjeuner. </p>
        </dd>
        <dt class="accordion_toggle"><a href="">Comment faire si je me lève à 5h du matin ?</a></dt>
        <dd class="accordion_content">
            <p>Si c’est régulier, pas de problème, votre  physiologie est habituée&nbsp;: suivez votre programme TIME Nutrition selon son  déroulement normal.</p>
            <p>Si c’est exceptionnel, mangez une banane ou des  figues quand vous vous levez et prenez votre petit déjeuner complet à l’heure  normale, selon votre habitude.</p>
        </dd>
        <dt class="accordion_toggle"><a href="">Comment faire en cas de matinée longue (plus de 6 heures) ?</a></dt>
        <dd class="accordion_content">
            <p>Prenez un peu plus de fromage et un SLIM Gum une ou  deux une heure avant le repas du midi.</p>
        </dd>
        <dt class="accordion_toggle"><a href="">Comment se passe le petit-déjeuner ?</a></dt>
        <dd class="accordion_content">
            <p>Le petit déjeuner constitue la base  nutritionnelle de la journée&nbsp;!</p>
            <p>Le petit déjeuner, c’est l’heure des  synchroniseurs alimentaires du matin, du fromage, du pain, du beurre auxquels  on pourra dans certains cas ajouter des œufs et de la charcuterie.</p>
        </dd>
        <dt class="accordion_toggle"><a href="">Peut-on se recoucher après le petit-déjeuner ?</a></dt>
        <dd class="accordion_content">
            <p>Il vaut mieux éviter sinon vous ferez comme les  sumos japonais&nbsp;! Dormir après un repas entraîne toujours une prise de  poids.</p>
        </dd>
        <dt class="accordion_toggle"><a href="">Je n’ai pas l’habitude de prendre un petit-déjeuner, c’est impossible pour moi de manger le matin, je n’en ai pas envie. Comment faire ?</a></dt>
        <dd class="accordion_content">
            <p>Il est impératif pour votre organisme, pour votre  silhouette et pour votre santé à long terme de manger le matin. </p>
            <p>En ne mangeant pas le matin vous êtes à  contretemps de vos cycles physiologiques et vous aurez faim à midi, et plus  encore le soir. Vous prenez ainsi le chemin des problèmes métaboliques&nbsp;:  surpoids, diabète, cholestérol...<br />
                <br />
                Si vous n’avez pas faim le matin il y a forcément  une raison&nbsp;! Peut-être avez-vous trop mangé le soir, ou trop tard, ou les  deux&nbsp;? Si c’est le cas, corrigez en mangeant plus léger le soir.</p>
        </dd>
        <dt class="accordion_toggle"><a href="">Quels fromages manger le matin ?</a></dt>
        <dd class="accordion_content">
            <p>Tous les fromages sont bons et sont utiles. Il  faut les choisir en fonction de vos goûts et de vos envies. </p>
            <p>Préférez ceux non pasteurisés, au lait cru et  entier pour éviter toutes les actions dues à la chaleur  (pasteurisation, stérilisation, UHT...) qui détruisent le tryptophane contenu  dans le fromage et transforment ses constituants en produits glyqués toxiques.</p>
        </dd>
        <dt class="accordion_toggle"><a href="">Comment faire si je n’aime pas le fromage ?</a></dt>
        <dd class="accordion_content">
            <p>Si vous n’aimez pas le fromage, vous pouvez le remplacez  par des œufs, des charcuteries, des graines (gruau amande - purée de sésame),  ou du poisson gras, en alternance.</p>
            <p>Essayez quand même de vous réadapter  progressivement au fromage qui reste l’aliment idéal pour le matin en  complément du pain et du beurre.</p>
        </dd>
        <dt class="accordion_toggle"><a href="">Puis-je reporter la consommation de fromage du petit-déjeuner au midi ?</a></dt>
        <dd class="accordion_content">
            <p>Non, à midi la prise de fromage doit être  exceptionnelle pour éviter un apport trop important de lipides à un moment  inadapté (risque de prise de poids et d’augmentation du cholestérol&nbsp;!).</p>
        </dd>
        <dt class="accordion_toggle"><a href="">Pourquoi prendre du fromage le matin et pas le soir ? </a></dt>
        <dd class="accordion_content">
            <p>Le fromage combine l’intérêt de cumuler graisses,  protéines, calcium et très peu de sucres.<br />
                C’est l’aliment idéal pour répondre aux besoins  du matin. Le soir, il apporte trop de graisses et le calcium est mal assimilé.</p>
        </dd>
        <dt class="accordion_toggle"><a href="">Pourquoi ne doit-on pas prendre de lait (lait pur, yaourts, fromage blanc, petits suisses) le matin au petit-déjeuner alors que le fromage est recommandé ? </a></dt>
        <dd class="accordion_content">
            <p>Parce que même si tous ces aliments sont des  laitages, le fromage est le seul à ne pas contenir de lactose. </p>
            <p>Le lactose est un sucre du lait constitué de  galactose et de glucose, c’est un excellent facteur de croissance capable de  faire rapidement prendre du poids ! Il vaut donc mieux éviter ces aliments qui  en sont riches, d’autant plus qu’ils ne contiennent pas assez de protéines et  d’acides gras pour être nourrissants et que le peu qu’ils en contiennent peut  s’avérer difficilement assimilable à cause des procédés de fabrication.</p>
            <p>Le fromage ne contient pas de lactose car la  fermentation qui conduit au fromage final digère le lactose du lait. Du coup on  ne risque pas la prise de poids liée à ce sucre et on évite  les ballonnements provoqués par sa fréquente  intolérance. </p>
            <p>Le fromage a donc tous les avantages&nbsp;: il ne  contient pas de lactose, il renferme une forte proportion de protéines riches  en acides aminés et apporte tous les acides gras saturés et insaturés qui permettent  la régulation de la synthèse des triglycérides.</p>
        </dd>
        <dt class="accordion_toggle"><a href="">Quel pain prendre au petit-déjeuner ?</a></dt>
        <dd class="accordion_content">
            <p>Le pain est la source de sucre la plus facile et  la plus complète pour le petit déjeuner. Il combine les sucres et les protéines  végétales des céréales et il contribue à une bonne satiété. </p>
            <p>Vous pouvez choisir parmi tous les pains qui vous  sont proposés, avec une restriction pour les pains industriels (souvent sous  sachet prétranchés) et la baguette industrielle ou précuite: ils sont trop  raffinés et donc leurs sucres sont encore plus « rapides » et risqués pour  votre ligne.</p>
            <p>Parmi les pains, préférez donc les bons pains au  levain confectionnés selon la tradition par votre artisan boulanger et ne vous  focalisez pas sur le « complet » qui peut ne pas être supporté par les  intestins fragiles.<br />
                Si possible, évitez de le griller : la cuisson  rapide augmente la valeur glycémique des sucres jusqu’à leur donner un « profil  » de sucre rapide. Et évitez par conséquent aussi les biscottes qui n’apportent  pas grand-chose, sinon trop de sucres vite assimilés et des fringales en  retour.</p>
        </dd>
        <dt class="accordion_toggle"><a href="">Comment faire si je n’aime pas le pain ? </a></dt>
        <dd class="accordion_content">
            <p>Si vous n’aimez pas le pain, vous pouvez le  remplacer par des pâtes pâtissières salées et non sucrées, brisées ou  feuilletées. Ou encore par de vraies céréales entières. </p>
            <p>Evitez surtout les céréales classiques  (corn-flakes industriels, céréales prêtes à consommer ou céréales extrudées)  arrosées de lait qui cumulent les inconvénients du lait et du sucre (trop de  lactose et trop de sucres rapides). </p>
        </dd>
        <dt class="accordion_toggle"><a href="">Comment faire si je n’aime pas le beurre?</a></dt>
        <dd class="accordion_content">
            <p>Si vous n’aimez pas du tout le beurre, prenez un  peu d’huile d’olive ou augmentez un peu votre part de fromage. </p>
            <p>Il faudra éventuellement ajuster vos apports en  vitamine A avec un complément alimentaire adapté. Mais le beurre reste un  aliment à privilégier le matin. </p>
        </dd>
        <dt class="accordion_toggle"><a href="">Quel beurre utiliser au petit-déjeuner ?</a></dt>
        <dd class="accordion_content">
            <p>Préférez un bon beurre de baratte complet et  doux.<br />
                Evitez les beurres salés qui apportent un peu  trop de sel&nbsp;! Réservez-les aux repas TIME Free. <br />
                Evitez absolument les margarines qui n’ont pas la  valeur nutritionnelle du beurre.</p>
        </dd>
        <dt class="accordion_toggle"><a href="">J’ai de la tension. Est-ce que je peu prendre du beurre le matin ?</a></dt>
        <dd class="accordion_content">
            <p>Oui, mais attention, pas de beurre demi-sel ou  salé ! A cause du sel&nbsp;!</p>
        </dd>
        <dt class="accordion_toggle"><a href="">Est-ce je peux remplacer le beurre par des beurres allégés ?</a> </dt>
        <dd class="accordion_content">
            <p>Non, dans les produits allégés, presque tous les  acides gras ont été supprimés et ont été remplacés par d’autres substances, en  particulier des dérivés sucrés. </p>
            <p>Ce n’est pas très bon pour l’organisme car si on  supprime les acides gras de l’alimentation, on oblige l’organisme à en  fabriquer. Et le comble c’est qu’en apportant des dérivés sucrés, on favorise  encore plus cette fabrication !</p>
        </dd>
        <dt class="accordion_toggle"><a href="">Que boire le matin au petit-déjeuner ?</a></dt>
        <dd class="accordion_content">
            <p>Le petit déjeuner sera accompagné de thé, de  café, d'eau plate ou pétillante, d'infusion, de tisane selon votre choix  personnel. Ces boissons se prendront sans sucre ni lait. Evitez les jus de  fruits surtout si vous n’avez pas encore atteint votre silhouette idéale.</p>
        </dd>
        <dt class="accordion_toggle"><a href="">Puis-je mettre une sucrette (édulcorant) dans mon café le matin ?</a> </dt>
        <dd class="accordion_content">
            <p>Oui, mais non&nbsp;! Il vaut mieux vous débarrasser  de toute dépendance au sucre. Faites un café moins fort et plus parfumé. </p>
        </dd>
        <dt class="accordion_toggle"><a href="">Puis-je sucrer mon thé ?</a></dt>
        <dd class="accordion_content">
            <p>Non, il vaut mieux éviter. Pour ne pas avoir  envie de le sucrer et ne pas être obligé de boire un thé amer, ne le laissez  pas trop infuser.</p>
        </dd>
        <dt class="accordion_toggle"><a href="">Si je ne prends pas de fruits ou de jus de fruits le matin, est-ce que je ne risque pas de manquer de vitamine C ?</a></dt>
        <dd class="accordion_content">
            <p>Non. La vitamine C est présente dans les autres  aliments en quantité suffisante pour éviter toute carence&nbsp;!</p>
        </dd>

        <h2 class="accordion_toggle_categorie">Déjeuner TIME Nutrition</h2>
        <dt class="accordion_toggle"><a href="">A quelle heure faut-il prendre le déjeuner ?</a> </dt>
        <dd class="accordion_content">
            <p>Idéalement, il faut prendre le déjeuner environ 4  à 5 heures après le petit-déjeuner, suivant en cela notre rythme physiologique  du cortisol.</p>
        </dd>
        <dt class="accordion_toggle"><a href="">Que faut-il manger le midi ?</a></dt>
        <dd class="accordion_content">
            <p>- Des protéines (de préférence viande bovine).<br />
                - Des sucres lents : ceux des pâtes (cuites « al  dente » si possible), des légumes secs, des farineux, du riz (complet si  possible). <br />
                - Pas de pain.<br />
                - Des légumes verts en petite quantité.<br />
                - Pas de yaourt, ni de fruits, ni de dessert.</p>
        </dd>
        <dt class="accordion_toggle"><a href="">Pourquoi un déjeuner classique ne convient-il pas ?</a> </dt>
        <dd class="accordion_content">
            <p>Parce que entrée + plat + fromage +  dessert&nbsp;= trop de gras et de sucres&nbsp;!</p>
        </dd>
        <dt class="accordion_toggle"><a href="">Je n’aime pas la viande, comment faire ?</a></dt>
        <dd class="accordion_content">
            <p>On peut remplacer la viande par des mélanges de  légumes secs et de céréales (style riz-lentilles). Cependant il faut éviter de  prendre trop de sucres lents et compléter par une boisson TIME Protein qui vous  permettra un apport en protéines suffisant.</p>
        </dd>
        <dt class="accordion_toggle"><a href="">Quelle viande choisir pour le déjeuner ?</a></dt>
        <dd class="accordion_content">
            <p>Il faut privilégier les viandes bovines. Une  viande rouge, « lourde » (protéines à poids moléculaire élevé), convient mieux. </p>
            <p>Vous pouvez consommer éventuellement, de temps en  temps, d’autres viandes, voire uniquement des aliments végétaux riches en  protéines.</p>
            <p>Vous avez le choix, aucune viande ne vous est  interdite. À condition de varier : pas question par exemple de manger tous les  jours une entrecôte qui est parmi les viandes les plus grasses, mais si vous  alternez viandes blanches, volailles et viandes rouges à midi, pas de problème.</p>
            <p>Matin, midi ou soir, attention cependant à la  qualité, car les viandes issues d’élevages industriels où les animaux sont «  engraissés » artificiellement sont beaucoup plus grasses que les viandes «  fermières ». La plupart des viandes que l’on achète conditionnées en grandes  surfaces sont des viandes provenant d’élevages industriels. Quand ce n’est pas  le cas, c’est presque toujours précisé sur l’emballage. L’idéal serait  d’acheter vos viandes chez un artisan boucher qui mettra un point d’honneur à  vous faire découvrir les saveurs de la bonne viande qu’il achète à des  fournisseurs dont il connaît les méthodes d’élevage.</p>
        </dd>
        <dt class="accordion_toggle"><a href="">Comment dois-je mesurer la quantité de viande nécessaire au déjeuner ?</a></dt>
        <dd class="accordion_content">
            <p>Il vous faut suivre les indications portées sur  le programme personnalisé TIME Nutrition&nbsp;: la viande se pèse crue.</p>
        </dd>
        <dt class="accordion_toggle"><a href="">Est-ce que je peux manger tous les jours du poisson à midi ?</a></dt>
        <dd class="accordion_content">
            <p>Le poisson possède des chaînes de protéines plus  courtes que celles de la viande et donc s'assimile beaucoup plus rapidement.  Cela explique pourquoi il n’est pas conseillé d'en manger tous les jours à  midi. Vous risqueriez d'avoir faim très rapidement dans l'après-midi. Pour  calmer cette faim précoce, vous pouvez prendre un SLIM Gum.</p>
        </dd>
        <dt class="accordion_toggle"><a href="">Je digère mal les œufs, comment faire ?</a></dt>
        <dd class="accordion_content">
            <p>Si vous les digérez mal mais que vous souhaitez  tout de même en manger, essayez de les assaisonner avec un filet de vinaigre  qui facilitera la digestion des protéines. </p>
        </dd>
        <dt class="accordion_toggle"><a href="">Qu’est ce qu’un « féculent » ?</a></dt>
        <dd class="accordion_content">
            <p>Un féculent est un aliment susceptible de  produire de la farine ou fait avec de la farine : les pommes de terre, le riz,  les pâtes, les semoules, les légumes secs (lentilles, flageolets, cocos,  haricots rouges, pois cassés, pois chiches...) et les légumes frais (petits  pois, fèves fraîches...).</p>
        </dd>
        <dt class="accordion_toggle"><a href="">Comment cuisiner les féculents ?</a></dt>
        <dd class="accordion_content">
            <p>Classiquement et traditionnellement en accompagnement  de toutes les viandes, par exemple : les marrons avec la dinde, les lentilles  vertes du Puy avec la queue de bœuf, les frites avec les steaks, les pommes de  terre avec le confit de canard, les haricots avec le gigot... </p>
        </dd>
        <dt class="accordion_toggle"><a href="">Les féculents se mesurent-ils avant ou après la cuisson ?</a></dt>
        <dd class="accordion_content">
            <p>Les féculents ne se pèsent pas et ils se mesurent  cuits, après cuisson, une fois égouttés.</p>
        </dd>
        <dt class="accordion_toggle"><a href="">Peut-on manger un sandwich au déjeuner ?</a></dt>
        <dd class="accordion_content">
            <p>Oui et selon la taille du sandwich il vous faudra  compléter par une ou deux boissons TIME Protein qui vous permettront un apport  en protéines suffisant.</p>
        </dd>
        <dt class="accordion_toggle"><a href="">L'été il fait trop chaud, je n’ai pas envie de viande ! Comment faire ?</a></dt>
        <dd class="accordion_content">
            <p>Prenez alors une salade composée plus, selon la  richesse en viande ou poisson de la salade, une ou deux boissons TIME Protein  qui vous permettront un apport en protéines suffisant.</p>
        </dd>
        <dt class="accordion_toggle"><a href="">Est-ce que manger des salades et des crudités en quantité à midi va m’aider à retrouver la ligne plus rapidement ?</a></dt>
        <dd class="accordion_content">
            <p>Non, car vous n’aurez pas assez de nutriments  pour la gestion de votre appétit et de votre satiété. </p>
            <p>Vous risquez de maigrir, de vous carencer et...  de reprendre du poids en craquant&nbsp;! C’est le principe des régimes  yo-yo&nbsp;! </p>
        </dd>
        <dt class="accordion_toggle"><a href="">Peut-on accompagner son repas d’une entrée ? d’un dessert ?</a> </dt>
        <dd class="accordion_content">
            <p>Le plat principal pourra éventuellement être  divisé entre une entrée et un plat, mais évitez les desserts&nbsp;!</p>
        </dd>
        <dt class="accordion_toggle"><a href="">Ne pas manger de dessert est très frustrant pour moi ! J’avais l’habitude de terminer mon repas avec un fruit et quelquefois 2 carrés de chocolat noir avec mon café. Comment faire ?</a></dt>
        <dd class="accordion_content">
            <p>Si vous  ne pouvez vraiment pas vous passer de la touche sucrée de la fin du repas, nous  vous conseillons de terminer votre déjeuner par un SLIM Gum. Ainsi vous ferez  une bonne action (prise de tryptophane qui contrôle la satiété) tout en vous  faisant plaisir&nbsp;!</p>
        </dd>
        <dt class="accordion_toggle"><a href="">Comment faire si j’exerce un travail physique au quotidien ?</a></dt>
        <dd class="accordion_content">
            <p>Si vous exercez un travail physique, cela est  pris en compte dans votre programme alimentaire personnalisé TIME Nutrition.  Vous avez dû l’indiquer dans le questionnaire initial.</p>
        </dd>
        <dt class="accordion_toggle"><a href="">Comment suivre TIME Nutrition quand on est souvent amené à déjeuner au restaurant ?</a></dt>
        <dd class="accordion_content">
            <p>Lorsque vous déjeunez régulièrement au  restaurant, prenez un plat unique plus une boisson TIME Protein qui vous  permettra un apport en protéines suffisant. Ne prenez ni entrée, ni dessert, et  finissez par un petit thé ou café non sucré.</p>
        </dd>
        <dt class="accordion_toggle"><a href="">Je vais déjeuner dans un restaurant chinois. Que puis-je prendre ?</a></dt>
        <dd class="accordion_content">
            <p>Vous pouvez prendre par exemple&nbsp;:<br />
                En entrée : omelette ou crevettes ou calamars... <br />
                En deuxième plat : bœuf ou canard ou poulet...  avec un petit bol de riz. <br />
                En boisson&nbsp;: eau ou thé (sans sucre).<br />
                Plus une boisson TIME Protein qui vous permettra un  apport en protéines suffisant.</p>
        </dd>
        <dt class="accordion_toggle"><a href="">Je vais déjeuner dans un restaurant italien. Que puis-je prendre ?</a></dt>
        <dd class="accordion_content">
            <p>Vous pouvez prendre par exemple&nbsp;:<br />
                En entrée une Tomates mozarella ou de la  charcuterie (mortadelle, coppa, jambon...).<br />
                Puis une viande accompagnée d’un peu de pâtes. <br />
                Et pour finir, pourquoi pas, un expresso (sans  sucre).<br />
                Plus une boisson TIME Protein qui vous permettra un  apport en protéines suffisant.</p>
        </dd>
        <dt class="accordion_toggle"><a href="">Je vais déjeuner dans un restaurant français traditionnel. Que puis-je prendre ? </a></dt>
        <dd class="accordion_content">
            <p>Vous pouvez prendre par exemple&nbsp;:<br />
                Une entrée du jour : charcuterie, saucisson,  pâté... (sans pain). <br />
                Puis un plat traditionnel (bœuf bourguignon +  pommes de terre, steak + frites, entrecôte + pommes au four,  saucisses-lentilles...) sans dévorer tous les féculents. <br />
                Et terminer par un café (sans sucre) et une  boisson TIME Protein qui vous permettra un apport en protéines suffisant.</p>
        </dd>
        <dt class="accordion_toggle"><a href="">Quelle boisson choisir pour le déjeuner ? Puis-je prendre un verre de vin ?</a></dt>
        <dd class="accordion_content">
            <p>Tout au long de la journée, il faut boire de  l’eau pour combattre les effets de l’évaporation naturelle de l’eau du corps.  Mais là encore, pas d’excès. S’il est utile de boire lorsqu’on a soif, il n’est  pas utile de boire plus que de raison. Un litre et demi par jour&nbsp;: eau, cafés  et thés compris, cela suffit.</p>
            <p>Il faut prendre de l’eau pendant, mais aussi en  dehors des repas, en petites quantités,  régulièrement au cours de la journée et sans  excès, sinon cela entraîne une hypervolémie (augmentation anormale du volume  sanguin) que l’on réduit aussitôt en allant faire pipi ! L’eau absorbée en  quantité n’hydrate pas et ne sert à rien !</p>
            <p>Le vin&nbsp;: oui, mais seulement lorsqu’on a  éliminé les kilos en trop et que la silhouette est stabilisée.</p>
        </dd>
        <dt class="accordion_toggle"><a href="">Est-ce que je peux diminuer mon déjeuner lorsque je n'ai pas très faim à midi?</a></dt>
        <dd class="accordion_content">
            <p>Vous pouvez exceptionnellement diminuez votre  déjeuner si vous n’avez pas très faim. Cependant prenez soin de boire en  complément une boisson TIME Protein qui vous assurera un apport en protéines  suffisant.</p>
        </dd>

        <h2 class="accordion_toggle_categorie">Goûter TIME Nutrition</h2>
        <dt class="accordion_toggle"><a href="">A quelle heure faut-il prendre le goûter ?</a></dt>
        <dd class="accordion_content">
            <p>Si vous avez un rythme régulier, le goûter doit  être pris avant 18 heures.</p>
            <p>Notez que si vous avez très faim à l’heure du  goûter, c’est que votre repas du matin ou celui de midi, ou les deux ont été mal  équilibrés. Vérifiez si vous avez bien suivi les recommandations de TIME  Nutrition.</p>
        </dd>
        <dt class="accordion_toggle"><a href="">Je n’ai pas le temps ni la possibilité de goûter. Est-ce je peux sauter ce repas ?</a></dt>
        <dd class="accordion_content">
            <p>Non, ne le négligez surtout pas. On a quatre pics  de cortisol, donc quatre repas par jour et le goûter ne doit pas être oublié. </p>
        </dd>
        <dt class="accordion_toggle"><a href="">Quel est le rôle du goûter ?</a></dt>
        <dd class="accordion_content">
            <p>Le goûter est très important&nbsp;! En même temps  qu’un repas « plaisir » énergétique, cette collation constitue un excellent  coupe-faim destiné à vous éviter de faire un repas trop abondant le soir.</p>
            <p>C’est au cours de cette collation de 17-18 heures  que vous devez apporter une quantité suffisante de tryptophane pour favoriser la  synthèse de sérotonine limitant le grignotage et la synthèse nocturne de  mélatonine assurant un bon sommeil. </p>
            <p>Et si vous n’avez pas encore stabilisé votre  silhouette, n’hésitez pas à prendre 1 SLIM Gum à la fin du goûter.</p>
        </dd>
        <dt class="accordion_toggle"><a href="">Que faut-il manger au goûter ?</a></dt>
        <dd class="accordion_content">
            <p>L’aliment de choix à cette heure doit contenir  des protéines (il en faut à tous les repas), un peu de gras insaturé, des  vitamines, des minéraux et éventuellement un peu de sucre.</p>
            <p>Les graines oléagineuses (amandes, noix, etc.)  correspondent à ce profil et conviennent à merveille. Le carré de chocolat noir  aussi car il est fabriqué à partir d’une graine oléagineuse, la fève de cacao.</p>
            <p>Vous pourrez même ajouter, si vous le souhaitez,  un fruit ou, vous permettre pourquoi pas une petite « gâterie » sucrée : un  gâteau ! En effet, dans les gâteaux, le sucre est intimement mêlé au gras, ce  qui le ralentit (comme le matin avec le beurre qui ralentit les sucres du  pain).</p>
        </dd>
        <dt class="accordion_toggle"><a href="">En prenant ce goûter au quotidien, est-ce que je ne risque pas de grossir ?</a></dt>
        <dd class="accordion_content">
            <p>Non. À l’heure du goûter (vers 17-18 heures), les  récepteurs à insuline deviennent progressivement résistants. </p>
            <p>Le début de cette insulinorésistance  physiologique associé au gras des graines évitera tout problème de stockage et  donnera même un coup de fouet agréable en fin de journée.</p>
        </dd>
        <dt class="accordion_toggle"><a href="">Quel chocolat choisir pour le goûter ?</a></dt>
        <dd class="accordion_content">
            <p>Choisissez de préférence du chocolat noir pour  éviter les sucres du lait (lactose) présents dans le chocolat au lait.</p>
        </dd>
        <dt class="accordion_toggle"><a href="">Je n’aime pas le chocolat. Par quoi puis-je le remplacer ?</a></dt>
        <dd class="accordion_content">
            <p>Si vous n’aimez pas le chocolat vous pouvez le  remplacer par des gâteaux, avocats, noix, amandes ou toutes graines non salées.</p>
        </dd>
        <dt class="accordion_toggle"><a href="">Puis-je manger des gâteaux, des crêpes ou de la pâte à tartiner au goûter ?</a></dt>
        <dd class="accordion_content">
            <p>Un gâteau ou une crêpe oui, mais évitez les pâtes  à tartiner trop grasse qui contiennent du gras saturé, inadapté pour notre  organisme à cette heure là. </p>
        </dd>
        <dt class="accordion_toggle"><a href="">Quels fruits choisir pour le goûter ?</a></dt>
        <dd class="accordion_content">
            <p>N’importe quel fruit frais convient sauf la  banane qui est trop riche en sucre.</p>
            <p>Petite remarque sur les fruits : consommez-les si  possibles entiers et pas en jus ou alors tout frais pressés. Si on laisse le  jus «&nbsp;traîner&nbsp;» (ou si l’on achète un jus en bouteille), les chaînes  de fructose qui sont dans le fruit vont rapidement se « casser », libérant du  fructose pur qui gênera l’utilisation du glucose dans l’organisme. <br />
                Attention aussi aux boissons sucrées ou gâteaux  industriels contenant du « glucose-fructose » ou du « sirop de maïs hydrolysé »  : ils sont trop riches en fructose pur et présentent les mêmes effets néfastes  pour la santé.</p>
        </dd>
        <dt class="accordion_toggle"><a href="">Un enfant prendra-t-il la même quantité de goûter qu’un ado ou un adulte ?</a></dt>
        <dd class="accordion_content">
            <p>Oui. Le goûter sera le même pour tous, quel que  soit l’âge, le poids ou la taille.</p>
        </dd>
        <dt class="accordion_toggle"><a href="">J'ai très faim au goûter, est-ce que je peux augmenter les quantités conseillées ?</a></dt>
        <dd class="accordion_content">
            <p>Non. Si vous avez très faim, c’est que votre  repas du matin ou celui de midi, ou les deux ont été  mal équilibrés. Vérifiez si vous avez bien  suivi les recommandations TIME Nutrition.</p>
        </dd>
        <dt class="accordion_toggle"><a href="">Je n’ai pas très faim le soir au dîner, est-ce que je peux réduire mon goûter ?</a></dt>
        <dd class="accordion_content">
            <p>Non, il vaudra mieux diminuer le repas du soir  (mais ne pas le sauter).</p>
        </dd>
        <dt class="accordion_toggle"><a href="">Je prends mon goûter très tard. Suis-je obligé de prendre un dîner ?</a></dt>
        <dd class="accordion_content">
            <p>Même si le repas du soir est très léger il vaut  mieux le prendre.</p>
        </dd>
        <dt class="accordion_toggle"><a href="">Je fais du sport en fin d’après-midi. Que dois-je manger à mon goûter ? </a></dt>
        <dd class="accordion_content">
            <p>Si vous faites du sport en fin de journée, prenez  votre goûter avant d’y aller. </p>
            <p>Si vous avez très faim en revenant du sport, la  prochaine fois rajoutez un gâteau ou une figue ou une banane en plus à votre  goûter. </p>
            <p>Il faut revenir du sport en ayant ni faim ni pas  d’appétit pour le dîner. Et surtout n’oubliez pas de boire&nbsp;!</p>
        </dd>

        <h2 class="accordion_toggle_categorie">Dîner TIME Nutrition</h2>
        <dt class="accordion_toggle"><a href="">A quelle heure faut-il dîner ?</a></dt>
        <dd class="accordion_content">
            <p>Le soir, dînez au moins une heure avant de vous  coucher.</p>
        </dd>
        <dt class="accordion_toggle"><a href="">Quels sont les aliments que l’on doit prendre au dîner ?</a></dt>
        <dd class="accordion_content">Encore une fois, il s’agit de respecter les  sécrétions physiologiques et ne pas relancer la machine à un moment où elle  doit faire autre chose.
            <p>Pour cela, premièrement, pas d’apport de  sucres&nbsp;; deuxièmement, pas de graisses en excès.<br />
                En revanche, il convient de continuer l’apport en  protéines, mais de petit poids moléculaire, faciles à digérer et de bien  choisir ses graisses&nbsp;: les produits de la mer (poissons, crustacés...)  conviennent parfaitement à ce profil. Dans les viandes, ce seront  essentiellement les viandes jeunes et non grasses (poulet, dinde, volailles,  lapin, veau, agneau, porcelet...) qui pourront aller. Mais attention à leur  qualité et leur richesse en acides gras essentiels.</p>
            <p>Ajoutez à cela une petite quantité de fibres, nécessaire  au bon fonctionnement du colon et de ses germes. Attention, consommer trop de  fibres entraîne des gonflements et un malaise digestif. Il faudra donc n’en  prendre que de façon limitée sinon vous allez gonfler&nbsp;! Pour que les  fibres soient bien digestes, il faudrait faire du sport et ainsi « masser » les  fibres dans l’intestin, ce qui n’est pas évident le soir.<br />
                Vous pouvez assaisonner ces fibres avec une  petite quantité d’huile riche en oméga-3 : colza par exemple, ou colza/ olive. </p>
            <p>Il sera nécessaire de prendre un complément  alimentaire en oméga-3 pour bénéficier d’une action sur la souplesse des  membranes cellulaires et un complément alimentaire en magnésium qui, comme pour  le matin, facilitera le travail des enzymes réparateurs. Enfin, un peu de  tryptophane pour permettre la synthèse de mélatonine qui sera favorable à un  bon sommeil.</p>
        </dd>
        <dt class="accordion_toggle"><a href="">Je n’ai pas faim le soir, est-ce que je peux sauter le dîner ?</a></dt>
        <dd class="accordion_content">
            <p>Non&nbsp;! Le soir vous pouvez considérablement alléger  le repas en fonction de votre appétit cependant il faut veillez à ne pas le  supprimer pour autant. Votre physiologie a besoin des nutriments apportés au  dîner.</p>
        </dd>
        <dt class="accordion_toggle"><a href="">Je n’aime pas le poisson. Par quoi le remplacer au dîner ?</a></dt>
        <dd class="accordion_content">
            <p>Si vous n’en aimez aucun, la solution consiste à  le remplacer par de la viande issue d’animaux « jeunes », facile à digérer (poulet,  dinde, volaille, lapin, veau, agneau, porcelet...). Mais attention à leur  qualité et leur richesse en acides gras essentiels. </p>
        </dd>
        <dt class="accordion_toggle"><a href="">Quels sont les poissons gras ?</a></dt>
        <dd class="accordion_content">
            <p>En voici quelques-uns : espadon, haddock, hareng, lotte, maquereau, morue, sardine, saumon, thon, truite...</p>
        </dd>
        <dt class="accordion_toggle"><a href="">Quels sont les poissons maigres ?</a></dt>
        <dd class="accordion_content">
            <p>En voici quelques-uns : brochet, cabillaud,  colin, lieu, limande, merlan, raie, rouget, sole, turbot...</p>
        </dd>
        <dt class="accordion_toggle"><a href="">Pourquoi manger du poisson ou de la viande « jeune » le soir ? Est-ce que je ne peux pas me contenter de légumes ?</a></dt>
        <dd class="accordion_content">
            <p>Non, il faut apporter à l’organisme des  nutriments pour qu’il puisse se reconstruire pendant la nuit&nbsp;: protéines,  acides gras insaturés... Or, ces nutriments indispensables sont absents des  légumes verts.</p>
        </dd>
        <dt class="accordion_toggle"><a href="">Quels légumes peut-on prendre le soir ?</a></dt>
        <dd class="accordion_content">
            <p>Au dîner, il faut prendre des légumes «&nbsp;feuilles&nbsp;»,  «&nbsp;racine&nbsp;», «&nbsp;tige&nbsp;», «&nbsp;fleurs&nbsp;»,  fruits&nbsp;»... dits verts, c’est-à-dire non farineux, non féculents. Tout  légume susceptible de faire de la farine se mange le midi.</p>
            <p>Exemples de légumes pour le soir&nbsp;:</p>
            <ul>
                <li>Légumes «&nbsp;racines&nbsp;» : les navets,  betteraves, salsifis...</li>
                <li>Légumes «&nbsp;feuilles&nbsp;» : les choux,  épinards, salades, oseille...</li>
                <li>Légumes «&nbsp;tiges&nbsp;» : les poireaux,  céleris, asperges...</li>
                <li>Légumes «&nbsp; fleurs&nbsp;» : les artichauts...</li>
                <li>Légumes «&nbsp;fruits&nbsp;» : les courgettes,  concombres, poivrons...</li>
            </ul>
        </dd>
        <dt class="accordion_toggle"><a href="">Quels aliments sont à éviter le soir ?</a></dt>
        <dd class="accordion_content">
            <p>Le soir, il faut éviter les œufs, la charcuterie,  les abats, les féculents, les laitages, le pain, les potages...</p>
        </dd>
        <dt class="accordion_toggle"><a href="">Pourquoi faut-il éviter les potages le soir ?</a></dt>
        <dd class="accordion_content">
            <p>La soupe correspond à un mélange eau salée en  grande quantité et légumes.</p>
            <p>La soupe présente donc deux inconvénients : d’une  part elle est riche en sucres rapides (la cuisson des légumes transforme  l’amidon en glucose et d’autre part elle est riche en sel. On se retrouve en  face de nos deux ennemis : trop de glucose et trop de sel !</p>
            <p>Cependant elle apporte tous les bons minéraux  comme le potassium et le magnésium. Alors la soupe oui, mais sans féculents ni  farineux, et sans sel ! Le pire des potages le soir pour le tour de taille,  c’est celui qui contient des pommes de terre ou du vermicelle&nbsp;!</p>
        </dd>
        <dt class="accordion_toggle"><a href="">Je ne peux pas me passer de dessert le soir. Comment faire ?</a></dt>
        <dd class="accordion_content">
            <p>Si vous ne pouvez vraiment pas vous passez de  dessert et qu’à la fin du repas vous avez encore envie de manger quelque chose  (un gâteau, une glace, un yaourt, du  fromage...), ne vous inquiétez pas, c’est très fréquent lorsqu’on a pris de  mauvaises habitudes alimentaires.</p>
            <p>Dans ces cas, prenez une infusion parfumée mais  non sucrée ou mieux&nbsp;: un SLIM Gum&nbsp;qui vous évitera une erreur qui  vous coûterait un redoutable bourrelet autour de la taille&nbsp;!  </p>
        </dd>
        <dt class="accordion_toggle"><a href="">Je n'ai pas le temps de manger à midi. Puis-je me rattraper le soir ?</a></dt>
        <dd class="accordion_content">
            <p>Non, le dîner doit être un repas léger sinon il  devient le meilleur moyen de grossir !</p>
        </dd>
        <dt class="accordion_toggle"><a href="">Je termine mes journées avec une faim de loup ! Est-ce que je peux manger plus au dîner ?</a></dt>
        <dd class="accordion_content">
            <p>Si vous terminez la journée avec une faim de loup  c’est que vous n’avez pas eu des apports suffisants aux autres repas. Avant de  manger plus au dîner il faut donc revoir le petit-déjeuner, le déjeuner et le  goûter&nbsp;et ajouter si besoin des boissons TIME Protein qui vous permettront  un apport en protéines suffisant. </p>
            <p>Vérifiez donc si vous avez bien suivi les  recommandations de TIME Nutrition et en attendant, prenez un SLIM Gum.</p>
        </dd>
        <dt class="accordion_toggle"><a href="">Comment faire quand je rentre très tard et que j'ai un petit creux ?</a></dt>
        <dd class="accordion_content">
            <p>Si vraiment vous avez un creux très tard, après  le dîner, prenez un grand verre d’eau ou une tisane aromatisée ou mieux&nbsp;:  un SLIM Gum.</p>
        </dd>

        <h2 class="accordion_toggle_categorie">Repas TIME Free</h2>
        <dt class="accordion_toggle"><a href="">Puis-je faire des écarts au cours de la semaine ?</a></dt>
        <dd class="accordion_content">
            <p>Deux repas TIME Free sont prévus chaque semaine,  le jour que vous voulez et au repas de votre choix (petit-déjeuner, déjeuner,  goûter ou dîner). </p>
            <p>Les repas TIME Free sont les repas au cours  desquels tout est permis y compris entrée, dessert, apéritif et vin à table ! </p>
            <p>Attention même si vous dînez TIME Free, n’oubliez  pas le goûter. Et dans tous les cas, prenez 1 SLIM Gum avant chaque TIME Free. </p>
        </dd>
        <dt class="accordion_toggle"><a href="">Comment faire si j’ai fait un repas TIME Free de trop ?</a></dt>
        <dd class="accordion_content">
            <p>Pas d’inquiétude : il suffira de prendre un SLIM Gum en plus du goûter pendant les 4 jours suivants.</p>
        </dd>

        <br/><h1>CAS PARTICULIERS</h1><br/>
        <h2 class="accordion_toggle_categorie">TIME Nutrition et le végétarisme</h2>
        <dt class="accordion_toggle"><a href="">Le programme TIME Nutrition peut-il être adapté au régime végétarien ?</a></dt>
        <dd class="accordion_content">
            <p>Oui. Il faudra cependant adapter les synchroniseurs  pour éviter les carences (en protéines, vit B12, fer, etc.) et surveiller les  associations de féculents et de céréales de façon à éviter la surconsommation  de glucides. Un synchroniseur spécialement adapté aux végétariens est à l’étude.  En attendant, pour compléter vos apports en protéines, n’hésitez pas à prendre  une boisson TIME Protein aux protéines végétales aux repas de midi et du soir.</p>
        </dd>

        <h2 class="accordion_toggle_categorie">TIME Nutrition et le sport</h2>
        <dt class="accordion_toggle"><a href="">Le programme TIME Nutrition peut-il convenir aux sportifs de haut niveau ?</a></dt>
        <dd class="accordion_content">
            <p>Oui. Cependant dans le cas d’un sportif de haut  niveau, un suivi particulier est indispensable, en particulier pour le ratio  protéines/glucides et le suivi de sa perméabilité intestinale.<strong></strong></p>
        </dd>
        <dt class="accordion_toggle"><a href="">Je fais beaucoup de sport. Dois-je adapter mon alimentation ?</a></dt>
        <dd class="accordion_content">
            <p>Oui, cela nécessite un apport d’énergie  complémentaire. Les efforts physiques intenses doivent être précédés et  accompagnés par un complément nutritionnel essentiellement végétal et le plus  riche possible en protéines et en lipides : banane fraîche ou séchée, châtaignes  grillées, crème de marron, figue ou cake non industriel conviendront  parfaitement. </p>
            <p>Ce complément énergétique devra être pris dans  l’heure qui précède l’activité sportive. Si l’effort est très intense vous  pourrez renouveler la prise pendant l’activité, et prendre une boisson TIME  Protein si l’effort se prolonge au-delà d’une heure. </p>
            <p>Petit conseil&nbsp;: Buvez  suffisamment&nbsp;tout au long de l’effort et  évitez le sport à midi. Le meilleur moment est la fin d’après-midi.</p>
        </dd>

        <h2 class="accordion_toggle_categorie">TIME Nutrition et la vie sociale</h2>
        <dt class="accordion_toggle"><a href="">Je suis invitée à une réception, qu’est ce que je peux boire en guise d’apéritif ?</a></dt>
        <dd class="accordion_content">
            <p>Le mieux sera de l’eau gazeuse, aromatisée ou  non. Si vous êtes contraint de boire une boisson alcoolisée, essayez de  l’accompagner avec des fruits et d’éviter les gras (chips, snacks...). Et  pensez à emmener vos SLIM Gum pour éviter de grignoter sans arrêt. </p>
        </dd>
        <dt class="accordion_toggle"><a href="">J’ai un repas entre amis ou de famille. Comment éviter les erreurs alimentaires sans fâcher mes hôtes ?</a></dt>
        <dd class="accordion_content">
            <p>Prenez un SLIM Gum avant le repas et considérez  ce repas comme TIME Free. Laissez alors parler la convivialité&nbsp;!</p>
        </dd>
        <dt class="accordion_toggle"><a href="">J’ai un pique-nique entre amis. Que manger ?</a></dt>
        <dd class="accordion_content">Prenez un SLIM Gum avant le repas puis une boisson TIME Protein au début et profitez du pique-nique</dd>

        <h2 class="accordion_toggle_categorie">TIME Nutrition et le cholestérol</h2>
        <dt class="accordion_toggle"><a href="">J’ai du cholestérol. Puis-je quand même suivre le programme TIME Nutrition ?</a></dt>
        <dd class="accordion_content">
            <p>Oui. </p>
            <p>S’il est traité par un médicament, informez votre  médecin pour qu’il ne soit pas surpris par une amélioration de vos analyses.</p>
            <p>Si vous n’êtes pas traité, n’hésitez pas à faire  le petit-déjeuner TIME Nutrition avec pain, beurre et fromage en remplaçant un  jour sur deux 20 g de fromage par un œuf coque ou sur le plat. Et évitez  absolument œuf et fromage aux autres repas ainsi que tout féculent, pain et  viande grasse le soir.</p>
        </dd>

        <h2 class="accordion_toggle_categorie">TIME Nutrition et le diabète</h2>
        <dt class="accordion_toggle"><a href="">J'ai du diabète. Puis-je quand même suivre le programme TIME Nutrition ?</a></dt>
        <dd class="accordion_content">
            <p>Si votre diabète est traité par un médicament par  voie orale, vous pouvez suivre le programme TIME Nutrition. Informez cependant  absolument votre médecin avant de commencer pour éviter tout risque  d’hypoglycémie (vos médicaments deviendraient trop actif en raison de  l’amélioration de votre santé).</p>
            <p>Si c’est un diabète soigné par des injections  d’insuline, ne faites rien sans l’accord de votre médecin pour éviter tout  accident&nbsp;(risque d’hypoglycémie la nuit si vous avez une injection  d’insuline le soir par exemple).</p>
            <p>Si vous n’êtes pas traité, n’hésitez pas à faire  le petit-déjeuner TIME Nutrition avec pain, beurre et fromage et évitez  absolument œuf et fromage aux autres repas ainsi que tout féculent, pain et  viande grasse le soir.</p>
            <p>TIME Nutrition vous propose un nouveau style de  vie parfaitement sain et sans restriction alimentaire, à condition de le  respecter définitivement. </p>
        </dd>

        <h2 class="accordion_toggle_categorie">TIME Nutrition et l’arrêt du tabac</h2>
        <dt class="accordion_toggle"><a href="">Je souhaite arrêter de fumer. Comment éviter les pulsions alimentaires compensatoires et la fameuse la prise poids consécutive à l’arrêt de la cigarette ?</a></dt>
        <dd class="accordion_content">
            <p>La crainte de prendre du poids fait souvent  abdiquer les fumeurs qui tentent de se libérer de la nicotine. En fait, il n’y  a vraiment pas de quoi s’empêcher de prendre une décision aussi louable : la  solution existe&nbsp;!</p>
            <p>A l'arrêt du tabac, la prise de poids constatée  est en moyenne de 3 à 5 kg chez les hommes et de 4 à 6 kg chez les femmes. Elle  n’est pas obligatoire et on peut la prévenir.</p>
            <p>La prise de poids à l’arrêt du tabac peut avoir  plusieurs origines :</p>
            <ul>
                <li>soit une compensation de la frustration générée  par le manque de nicotine, frustration compensée en grignotant toute la  journée. Il est fréquent que le  fumeur privé de cigarettes compense par la nourriture avec pour préférence des  produits sucrés tels que chocolat, gâteaux ou plus souvent des féculents, du  pain, des pizzas... </li>
            </ul>
            <ul>
                <li>soit à cause de la reprise du fonctionnement  normal des cellules. En effet, il faut savoir que lorsque l’on fume, l’oxyde de  carbone empoisonne le sang. Du coup les échanges sont altérés, les métabolismes  diminués et malgré un apport supplémentaire de nourriture le poids n’est pas  modifié. A l’arrêt du tabac, tous les globules rouges redeviennent  fonctionnels, les échanges redeviennent normaux et l’apport alimentaire  supplémentaire au temps du tabac provoque une prise de poids d’environ 10% ! </li>
            </ul>
            <p>En résumé, ce qu’il faut comprendre c’est que le  tabac est, par la nicotine qu’il contient, un excitant de l’intestin. Cela est  dû aux stimulations que la nicotine provoque sur les récepteurs nicotiniques situés  un peu partout sur nos organes et particulièrement nombreux au niveau  intestinal. La nicotine accélère donc le fonctionnement de l’intestin. A  l’arrêt du tabac et donc de la nicotine, il y a ralentissement du métabolisme  de l’intestin et si l’on surconsomme certains aliments, l’intestin qui  fonctionne plus lentement ne pourra pas les transformer. Ils seront ainsi  assimilés et entraineront inéluctablement une prise de poids !</p>
            <p>Pour éviter cette prise de poids, il  faut&nbsp;donc dès l’arrêt du tabac (et même avant&nbsp;!), manger «  normalement », c’est-à-dire physiologiquement. Cela veut dire qu’il faut manger  en respectant son fonctionnement biologique, en apportant ce qu’il lui faut  pour bien tourner mais pas plus, et surtout cet apport doit se faire dans des  conditions correctes, c’est-à-dire au moment où le corps en a besoin. </p>
            <p>En un mot il faut manger TIME Nutrition,  c’est-à-dire chronobiologiquement&nbsp;! </p>
            <p>Les règles diététiques sont bien connues (Plan  National Nutrition Santé). Il faut les appliquer en fonction de sa morphologie  et en fonction du moment où notre organisme peut métaboliser les nutriments,  sans perte ni stockage (chronobiologie). C’est dans le respect de cette  harmonie biologique que réside le contrôle du poids. </p>
            <p>TIME Nutrition et son adaptation personnalisée va  donc vous aider à ne pas prendre de poids à l’arrêt du tabac. </p>
        </dd>
        <dt class="accordion_toggle"><a href="">J’ai arrêté de fumer il y a plusieurs mois. Comment me débarrasser des quelques kilos superflus accumulés ?</a></dt>
        <dd class="accordion_content">
            <p>Tout d’abord félicitations&nbsp;! Vous avez fait  le plus difficile&nbsp;! La perte des quelques kilos superflus sera bien plus  facile que ce que vous venez d’endurer pour arrêter de fumer&nbsp;!</p>
            <p>Il faut savoir la nicotine est un excitant de  l’intestin, elle accélère son fonctionnement. Sans nicotine il y a donc  ralentissement et si l’on consomme trop de céréales (pain, pâtes...), trop de  féculents (pomme de terre...), trop de sucres (lents ou rapides), ce  ralentissement favorisera l’assimilation et... une prise de poids inévitable. C’est  certainement ce qui a du vous arrivez&nbsp;!</p>
            <p>Pour vous débarrassez de ces quelques kilos de  trop, TIME Nutrition vous recommande donc de ne pas manger de pain en dehors du  petit-déjeuner, et pas de pommes de terre, de féculents ou de légumes secs au  delà des quantités inscrites dans votre programme. </p>
            <p>De plus, pour accélérer la perte du bourrelet  récalcitrant, n’oubliez pas de prendre TIME Fat Burner tous les matins. Il vous  aidera à brûler les graisses superflues.</p>
            <p>Enfin, n’hésitez pas à mâcher un SLIM Gum après le  repas si nécessaire. Cela évitera les grignotages intempestifs catastrophiques  pour la silhouette.</p>
            <p>Dernière remarque&nbsp;: si une constipation  apparaît à l’arrêt de tabac, une épuration du foie s’impose avec un complément  alimentaire adapté. Un synchroniseur spécialement conçu pour vous accompagner  dans l’arrêt du tabac est à l’étude.</p>
        </dd>

        <h2 class="accordion_toggle_categorie">TIME Nutrition et la grossesse</h2>
        <dt class="accordion_toggle"><a href="">Peut-on suivre TIME Nutrition pendant la grossesse et l'allaitement ?</a></dt>
        <dd class="accordion_content">
            <p>Oui. C’est même physiologiquement conseillé.  Cependant la grossesse et l’allaitement sont des états particuliers&nbsp;qui nécessitent  obligatoirement un suivi médical.  </p>
        </dd>
        <dt class="accordion_toggle"><a href="">Comment faire pour perdre les kilos résistants suite à ma grossesse ?</a></dt>
        <dd class="accordion_content">
            <p>Simplement suivre le programme TIME Nutrition&nbsp;!</p>
        </dd>

        <h2 class="accordion_toggle_categorie">TIME Nutrition et la ménopause</h2>
        <dt class="accordion_toggle"><a href="">Le programme TIME Nutrition peut-il être suivi par des femmes en pré-ménopause ou en ménopause ?</a> </dt>
        <dd class="accordion_content">
            <p>Oui, TIME Nutrition s'applique à tout le monde,  pré-ménopause et ménopause comprises. Dans ces deux cas les erreurs  alimentaires sont moins pardonnées&nbsp;: il faudra donc suivre régulièrement  des cures de synchroniseurs alimentaires.</p>
        </dd>

        <h2 class="accordion_toggle_categorie">TIME Nutrition et les horaires</h2>
        <dt class="accordion_toggle"><a href="">Comment faire en cas de journée décalée ?</a></dt>
        <dd class="accordion_content">
            <p>Si vous avez une journée avec des horaires  décalés, décalez tous les repas en fonction de l’heure de lever. Des  adaptations plus fines peuvent être nécessaires selon chaque cas et suivant la  fréquence des décalages.</p>
        </dd>
        <dt class="accordion_toggle"><a href="">Je n’ai pas des horaires fixes. Est-ce un problème de ne pas prendre les repas toujours à la même heure ?</a> </dt>
        <dd class="accordion_content">
            <p>Non, ce n’est pas un problème cependant il faut trouver  son rythme et réussir le démarrage de la journée avec un bon petit-déjeuner.</p>
        </dd>

        <h2 class="accordion_toggle_categorie">Les synchroniseurs TIME Nutrition</h2>
        <dt class="accordion_toggle"><a href="">Quel est le rôle des synchroniseurs ?</a> </dt>
        <dd class="accordion_content">
            <p>Les synchroniseurs sont des compléments alimentaires  qui doivent aider et accompagner la mise en place du programme alimentaire TIME  Nutrition. Ces compléments alimentaires sont indispensables à la santé et font  partie intégrante et continuelle de TIME Nutrition. </p>
            <p>Certains servent à rétablir ou améliorer le  fonctionnement physiologique (TIME Magnesium, TIME Omega), d’autres à  entretenir ou remettre en état l’assimilation intestinale (TIME Probiotic).  D’autres encore complètent ces actions   indispensables pour retrouver une belle silhouette en synchronisant,  équilibrant et surtout recalant les différents mécanismes physiologiques de la  gestion de l’appétit et de la faim (TIME Tyrosine et TIME Tryptophan).</p>
        </dd>
        <dt class="accordion_toggle"><a href="">Qu’est ce que la tyrosine ?</a></dt>
        <dd class="accordion_content">
            <p>La tyrosine est le précurseur de plusieurs neuromédiateurs  :</p>
            <ul>
                <li>la  dopamine, neuromédiateur de l’action et de la motivation</li>
                <li>la  noradrénaline, neuromédiateur de l’éveil et coupe-faim</li>
                <li>l’adrénaline,  médiateur du stress </li>
            </ul>
            <p>Les déficits ou carences en tyrosine sont  essentiellement liés à une hyper-utilisation due au stress. </p>
        </dd>
        <dt class="accordion_toggle"><a href="">Quel est le rôle de TIME Tyrosine ?</a></dt>
        <dd class="accordion_content">
            <p>TIME Tyrosine   agit sur deux fronts : la gestion de l’appétit et la gestion de  l’activité.<br />
                La carence en tyrosine ou sa mauvaise absorption  entraîne des troubles du rythme alimentaire et une chute du dynamisme. </p>
            <p>La propension à se jeter compulsivement sur la  nourriture en cas de déprime ou de tension nerveuse sera moins pressante avec  l’utilisation de ce synchroniseur, qui contient également des vitamines B qui  régularisent l’influx nerveux, et du ginseng qui donne un coup de fouet  anti-fatigue bien utile pour commencer la journée du bon pied. Il contient  aussi un acide aminé, la L-glutamine, carburant des cellules de l’intestin, qui  préparera la muqueuse intestinale à une bonne absorption des aliments de la  journée.</p>
            <p>En apportant de la tyrosine en complément  alimentaire le matin, TIME Tyrosine permet l’augmentation du dynamisme et la suppression  des phénomènes de boulimie. </p>
        </dd>
        <dt class="accordion_toggle"><a href="">Qu’est ce que les probiotiques ? </a></dt>
        <dd class="accordion_content">
            <p>Les probiotiques sont des  germes vivants qui ont un rôle primordial sur la flore intestinale. Les  probiotiques contribuent à la réparation d’un intestin devenu trop perméable et  assurent son entretien. Ils évitent ainsi l’afflux de substances toxiques dans  le sang et inhibent le développement de flores pathogènes, ils permettent  l’assimilation des bons nutriments et corrigent les déséquilibres qui ont pu  induire des prises de poids anormales. Les probiotiques ont un rôle essentiel  dans l’immunité. </p>
            <p>En un mot, ils sont  indispensables pour entretenir ou remettre en état l’assimilation intestinale,  passage incontournable pour un résultat silhouette, minceur et santé.</p>
        </dd>
        <dt class="accordion_toggle"><a href="">Qu’est ce que l’hyperperméabilité intestinale ?</a></dt>
        <dd class="accordion_content">
            <p>L’intestin est&nbsp;une interface fragile. Le  stress, les aliments préparés, les consommations excessives, la carence en  fibres… agressent l’intestin et le rendent poreux. C’est ce que l‘on appelle l’hyperperméabilité  intestinale. </p>
            <p>Cette situation favorise le passage des  substances toxiques dans le sang. Ce qui provoque allergies, intolérances alimentaires  et font le lit de maladies pouvant être très graves.</p>
            <p>L’hyperperméabilité intestinale est&nbsp; très  fréquente. Elle est souvent annoncée par des signes caractéristiques : douleurs  intestinales, diarrhées ou constipation, ballonnements... La correction de  l’hyperperméabilité est indispensable. </p>
            <p>Les levures pathogènes (Candida) profitent de la  perméabilité intestinale et des déséquilibres de la flore pour se développer  et  aggraver symptômes et troubles.</p>
        </dd>
        <dt class="accordion_toggle"><a href="">Quel est le rôle de TIME Probiotic ?</a> </dt>
        <dd class="accordion_content">
            <p>Le synchroniseur TIME  Probiotic agit sur la flore intestinale et la muqueuse intestinale&nbsp;: il  favorise la bonne assimilation des aliments. </p>
            <p>Quand la muqueuse  intestinale a été rendue perméable par une alimentation anarchique,  surabondante, mal appropriée, ou par une consommation trop fréquente d’aliments  transformés, l’organisme s’intoxique. Les déchets traversent la barrière de  l’intestin, entraînant la plupart du temps des réactions allergiques, voire des  maladies graves. Dans ces conditions, les prises de poids et gonflements  abdominaux sont fréquents. </p>
            <p>TIME Probiotic permet donc  de rétablir l’équilibre immunitaire au niveau de l’intestin, diminuant les  phénomènes allergiques et permettant la réparation de la muqueuse intestinale. Pour  avoir des résultats « minceur et santé », il faut remettre en état et  entretenir l’écosystème intestinal dès le début de toute intervention à visée  nutritionnelle. </p>
            <p>En apportant des probiotiques  le matin, TIME Probiotic réduit la perméabilité intestinale et améliore la  tolérance alimentaire tout en régulant le transit, assurant ainsi le meilleur  résultat possible santé, minceur et silhouette.</p>
        </dd>
        <dt class="accordion_toggle"><a href="">J’entends souvent dans les publicités que les yaourts sont sources de probiotiques. TIME Nutrition déconseille la consommation de yaourts industriels brassés, est-ce pour cela qu'il faut compléter son alimentation avec TIME Probiotic ?</a></dt>
        <dd class="accordion_content">
            <p>Non, cela n’a rien à voir&nbsp;! S'il existe des  probiotiques dans les yaourts, leur efficacité pour notre physiologie est  faible car<strong> </strong>ce sont des probiotiques utiles pour faire des yaourts,  mais inutiles pour notre intestin&nbsp;!</p>
        </dd>
        <dt class="accordion_toggle"><a href="">Qu’est ce que le magnésium ?</a></dt>
        <dd class="accordion_content">
            <p>Le magnésium est un sel minéral. Il est l’un des  principaux cofacteurs enzymatiques, c’est-à-dire l’un des facteurs  indispensables au bon fonctionnement des enzymes donc à une bonne digestion. Il  participe au métabolisme des glucides et des lipides et à la synthèse des  protéines.</p>
            <p>Aussi, le magnésium est obligatoire à la  transmission de l’influx nerveux et permet de stabiliser l’activité de  l’ensemble des cellules et de diminuer leur hyperexcitabilité. Lors d’un  stress, l’organisme consomme de très grosses quantités de magnésium, d’où  l’importance d’augmenter son apport.</p>
            <p>Son déficit voire sa carence sont très fréquents.  Toute amélioration nutritionnelle visant la santé et la minceur passe par un  apport complémentaire de magnésium.</p>
        </dd>
        <dt class="accordion_toggle"><a href="">Quel est le rôle de TIME Magnesium ?</a></dt>
        <dd class="accordion_content">
            <p>L’alimentation moderne est très fortement  carencée en magnésium. </p>
            <p>Pour apporter la quantité de magnésium  quotidienne nécessaire à la nutrition des cellules et garantir le bon équilibre  neuromusculaire et nerveux, le Synchroniseur TIME Magnesium joint à une dose de  magnésium d’origine marine correspondant aux besoins physiologiques, une série  de composés : L-lysine, taurine, L-méthionine, cystine. Leur rôle est de  potentialiser par des mécanismes divers les effets du magnésium. TIME Magnesium  contient également un cocktail de cacao qui possède des propriétés  antioxydantes, relaxantes, et qui contribue à favoriser le déstockage des  graisses, du pollen qui contribue à augmenter le tonus et la résistance de  l’organisme ainsi qu’un extrait de feuilles de cassis aux vertus  anti-oxydantes. </p>
            <p>Il faut noter que l’origine marine du magnésium lui  permet d’être mieux assimilé et mieux toléré par l’organisme. En effet le  magnésium marin est extrait de l’eau de mer dans laquelle il se trouve  naturellement présent (1,25 g / litre), c’est donc un produit naturel, il n’a  pas les effets secondaires laxatifs du magnésium de synthèse. </p>
            <p>En apportant du magnésium matin et soir, TIME  Magnesium contribue tant à soutenir l’activité diurne que le travail cellulaire  de la nuit. </p>
        </dd>
        <dt class="accordion_toggle"><a href="">Qu’est ce que les oméga-3 ?</a></dt>
        <dd class="accordion_content">
            <p>Les  oméga-3 sont des nutriments que l’organisme ne sait pas fabriquer lui-même. Il  doit les trouver dans les aliments. Ces nutriments sont indispensables pour  aider à une meilleure qualité de construction et d’échange cellulaires. </p>
            <p>Or avec  l’alimentation actuelle, la carence en oméga-3 est fréquente. Et sans un  échange cellulaire correct, pas de bons résultats santé et minceur possibles. </p>
        </dd>
        <dt class="accordion_toggle"><a href="">Quel est le rôle de TIME Omega ?</a></dt>
        <dd class="accordion_content">
            <p>Le Synchroniseur TIME Omega,&nbsp;riche en  oméga-3 longue chaîne, va permettre d’apporter aux cellules le fameux DHA  (acide docosahexaénoïque). Le DHA est l’acide gras le plus difficile à  synthétiser par notre organisme. Il est pourtant vital pour assurer un bon  fonctionnement cérébral et rétinien. </p>
            <p>TIME Nutrition a choisi comme source d’oméga-3  les algues de l’espèce Ulkenia. Cette source permet d’éviter les contaminations  par des métaux lourds ou des toxiques qui peuvent résider dans les autres produits  marins (poissons gras ou extraits de crevettes). En effet l’algue Ulkenia,  algue élevée en incubateur, est exempte de ce risque. </p>
            <p>En apportant des oméga-3 de qualité le soir, TIME  Omega permet leur incorporation optimale au niveau des membranes cellulaires et  favorise ainsi leur renouvellement au bon moment, c’est-à-dire durant la nuit.</p>
        </dd>
        <dt class="accordion_toggle"><a href="">Qu’est ce que le tryptophane ?</a></dt>
        <dd class="accordion_content">
            <p>Le tryptophane&nbsp;est un acide aminé apporté  par les protéines et qui joue un rôle central sur la régulation de la satiété. En  effet le tryptophane préside à la formation de la sérotonine, qui induit la  satiété et combat les envies de sucre. Dans un deuxième temps, en tant que  précurseur de la mélatonine, la sérotonine favorise un sommeil nocturne de  qualité. </p>
            <p>Le problème est que cet acide aminé ne se stocke  pas et est très peu présent dans l’alimentation, car vite détruit par la  cuisson et les préparations industrielles. Il est donc important de l’apporter  par des compléments alimentaires.</p>
        </dd>
        <dt class="accordion_toggle"><a href="">Quel est le rôle de TIME Tryptophan ?</a></dt>
        <dd class="accordion_content">
            <p>Le Synchroniseur TIME Tryptophan&nbsp;a une action  satiétogène, entraîne la suppression des déprimes et favorise un bon sommeil  réparateur.  </p>
            <p>À ces actions anti-grignotage et pro-sommeil, le Synchroniseur  TIME Tryptophan&nbsp; ajoute l’action de la L-glutamine, de la L-lysine, de la  chlorophylle, du curcuma et de l’extrait de propolis, qui favorisent la santé  de la muqueuse intestinale, préviennent l’oxydation et le développement de  phénomènes inflammatoires de l’intestin, et diminuent l’hyperperméabilité  intestinale. Autrement dit, tous les ingrédients qui peuvent, la nuit, réparer  l’intégrité du système digestif et le rendre disponible aux nutriments qu’on  lui proposera d’assimiler le lendemain.</p>
            <p>En apportant du tryptophane le soir, TIME  Tryptophan permet  de réguler la faim, d’éviter  boulimies et fringales mais également de favoriser un bon sommeil et une  réparation de l’intestin durant la nuit. </p>
        </dd>
        <dt class="accordion_toggle"><a href="">Quel est le rôle du SLIM Gum ?</a></dt>
        <dd class="accordion_content">
            <p>Le SLIM Gum aide à lutter contre les tentations  ponctuelles de grignotage, c’est un régulateur immédiat d’appétit. </p>
            <p>C’est une première dans le monde des produits à  visée amincissante, le SLIM Gum permet de « casser » vos brutales fringales. Son  action naturelle anti-grignotage est immédiate et percutante. En effet, SLIM  Gum est riche en tryptophane, cet acide aminé, si difficile à trouver en  quantité suffisante dans l’alimentation courante et qui sert de précurseur à la  sécrétion de sérotonine qui régule notre satiété et nos pulsions alimentaires.</p>
        </dd>
        <dt class="accordion_toggle"><a href="">Quel est le rôle du Synchroniseur TIME Silhouette T ?</a></dt>
        <dd class="accordion_content">
            <p>Le Synchroniseur TIME Silhouette T&nbsp;permet de  drainer et de booster l’amincissement spécifique des zones rebelles de la TIME  Silhouette T (Taille et ventre).</p>
            <p>En réunissant des actifs ciblés&nbsp;tels que artichaut,  cresson, mûrier, germe de blé, extraits de ginseng et chrome il met l’accent  sur le foie et l’insulino-résistance, deux problèmes métaboliques typiques de  la TIME Silhouette T.</p>
        </dd>
        <dt class="accordion_toggle"><a href="">Quel est le rôle du Synchroniseur TIME Silhouette I ?</a></dt>
        <dd class="accordion_content">
            <p>Le Synchroniseur TIME Silhouette I permet de  drainer et de booster l’amincissement spécifique des zones rebelles de la TIME  Silhouette I (parties Inférieures du corps&nbsp;: fesses, cuisses et hanches).</p>
            <p>En réunissant des actifs ciblés&nbsp;tels que de  chiendent, radis noir, cresson, chicorée, Ulvaline® et pépins de raisin, il possède une action douce,  à la fois diurétique et laxative, et agit prioritairement sur le foie, organe  sensible des personnes ayant une TIME Silhouette I.</p>
        </dd>
        <dt class="accordion_toggle"><a href="">Quel est le rôle du Synchroniseur TIME Silhouette M ?</a></dt>
        <dd class="accordion_content">
            <p>Le Synchroniseur TIME Silhouette M permet de  drainer et de booster l’amincissement spécifique des zones rebelles de la TIME  Silhouette M (silhouette Massive&nbsp;: ventre, taille, fesses, cuisses et  hanches).</p>
            <p>En réunissant dans sa composition des extraits de  reine des prés, artichaut, olivier, frêne, Ulvaline® et chrome, il agit sur la rétention d’eau et  l’assimilation des sucres, deux problèmes métaboliques majeurs de la TIME  Silhouette M.</p>
        </dd>
        <dt class="accordion_toggle"><a href="">Quel est le rôle du Synchroniseur TIME Silhouette E ?</a></dt>
        <dd class="accordion_content">
            <p>Le Synchroniseur TIME Silhouette E permet d’entretenir  et de prolonger  l’acquis d’une silhouette idéale.</p>
            <p>En réunissant dans sa formule des extraits de thé  vert, bardane, ortie, bouleau, cynorrhodon et gelée royale, le synchroniseur  TIME Silhouette E possède une exceptionnelle richesse en vitamines et  antioxydants.</p>
        </dd>
        <dt class="accordion_toggle"><a href="">Quel est le rôle du TIME Fat Burner ?</a></dt>
        <dd class="accordion_content">
            <p>Le TIME Fat Burner&nbsp;est un brûleur de  graisses qui aide à l’amincissement généralisé.  </p>
            <p>Sa formule associe&nbsp;:<br />
            <blockquote>
                <p>
                - l’Ulvaline® qui  favorise la fonte des graisses et l’élimination de l’eau en réduisant capitons  et peau d’orange, <br />
                - des extraits de guarana et de thé vert qui  stimulent l’élimination des graisses et le ralentissement de leur stockage, <br />
                - du vinaigre de cidre dont les pectines sont des  brûle-graisses <br />
                - des Fructo-Oligo-Sacharides (FOS) qui  complètent l’action prébiotique.</p>
            </blockquote>
        </dd>
        <dt class="accordion_toggle"><a href="">Quel est le rôle des TIME Protein ?</a></dt>
        <dd class="accordion_content">
            <p>Les boissons TIME Protein permettent de compléter  un apport insuffisant en protéines.</p>
            <p>Ces boissons seront particulièrement utiles pour  aider ceux ou celles qui, soit n’aiment pas les aliments carnés, soit déjeunent  « sur le pouce » ou en collectivités et n’ont pas un apport protéique  suffisant. </p>
            <p>De plus, ces boissons seront très utiles pour  retrouver un équilibre lorsque l’on sort d’une alimentation anarchique.</p>
            <p>À noter que certaines de ces boissons sont à base  de protéines végétales&nbsp;: idéales pour les végétariens&nbsp;!</p>
        </dd>

    </dl>
    <br/>
    <p><strong><em>Si vous  souhaitez poser une question directement à l'un de nos experts, vous pouvez le faire en envoyant un email à : experts@time-nutrition.com</em></strong></p>
    <div class="clearfix"></div>

    <script>

        require(['jquery'], function ($) {
            var allPanels = $('.container-selector > dd').hide();
            $('.container-selector > dt > a').click(function(){
               allPanels.slideUp();
                $(this).parent().next().slideDown();
                return false;
            });

        });
    </script>