<div class="col-md-12 text-center" style="letter-spacing:2px;">


    <div class="logo-time">
        <img src="<?php echo $this->getViewFileUrl('images/programme_minceur/logo-time-fond-blanc-01.png'); ?>" width="250">
    </div>

    <div class="privation">
        <h3 class="amastic-titre">...Sans aucune privation...</h3>
        <hr class="hr-rose"></hr>
    </div>

    <div class="upper-text">
        <span class="upper-rose">Atteignez vos <strong>objectifs</strong> grâce à la <strong>chronobiologie alimentaire</strong></span>
        <div style="margin-top:10px;margin-bottom:50px;">
            Concept basé sur le respect de l'horloge biologique du corps et<br>
            sur la prise d'une alimentation adaptée. Alliez silhouette,<br>
            bien être, beauté et santé avec le concept global<br>
            TIME Nutrition.
        </div>
    </div>

    <div class="bloc-offert-container row">
        <div class="col-xs-12 col-sm-4 col-md-4 fleche-gauche bloc-offert">
            <div class="arrow_box">
                <div class="arrow_box_text">Un <span style="text-transform:uppercase;">rééquilibrage<br> alimentaire</span></div>
            </div>
            <div class="arrow_box">
                <div class="arrow_box_text">Un <span style="text-transform:uppercase;">programme<br> minceur</span></div>
            </div>
        </div>
        <div class="col-xs-12 col-sm-4 col-md-4 bloc-offert-center">
            <a href="http://bilanoffert.programmeminceur.info/" style="text-decoration:none;">
                <div class="carre-rose">
                    mon bilan<br> personnalisé<br> <span class="carre-rose-gras">offert</span>
                </div>
            </a>
        </div>
        <div class="col-xs-12 col-sm-4 col-md-4 fleche-droite bloc-offert">
            <div class="arrow_box-1">
                <div class="arrow_box1_text">Un <span style="text-transform:uppercase;">diagnostic<br> personnalisé</span></div>
            </div>
            <div class="arrow_box-1">
                <div class="arrow_box1_text">Un <span style="text-transform:uppercase;">coaching</span> par<br> un spécialiste</div>
            </div>
        </div>
    </div>


    <div class="anti-stress row">
        <div class="anti-stress-content col-md-6 no-padding">
            <a href="http://decouvrez.guide-stress.programmeminceur.info/" target="blank">
                <div class="anti-stress-img">
                    <img src="<?php echo $this->getViewFileUrl('images/programme_minceur/Programme-minceur-landing_03.jpg'); ?>">

                    <div class="anti-stress-title">
                        mon guide anti-stress offert ici
                    </div>
                </div>
            </a>
        </div>
        <div class="anti-stress-content col-md-6 no-padding">
            <div class="anti-stress-content-text">
                Quand le stress vient perturber votre alimentation, TIME Nutrition vous apporte une solution<br><br>
                Les 3 causes principales du stress :<br>
                - la vie professionnelle<br>
                - les relations extraprofessionnelles<br>
                - les grandes occasions
            </div>
        </div>
    </div>

    <div class="guide-minceur row">
        <div class="guide-minceur-content col-md-6 no-padding">
            <a href="http://decouvrez.guide-minceur.programmeminceur.info/" target="blank">
                <div class="guide-minceur-img">
                    <img src="<?php echo $this->getViewFileUrl('images/programme_minceur/Programme-minceur-landing_06.jpg'); ?>">
                    <div class="guide-minceur-title">
                        mon guide minceur offert ici
                    </div>
                </div>
            </a>
        </div>
        <div class="guide-minceur-content col-md-6 no-padding">
            <div class="guide-minceur-content-text">
                Mauvaise habitudes alimentaires ?<br>
                Grignotages à répétition ?<br>
                TIME Nutrition vous offre les clés pour allier plaisir et équilibre !
            </div>
        </div>
    </div>

    <div class="mon-diagnostic row">
        <div class="mon-diagnostic-content col-md-6 no-padding">
            <a href="http://bilanoffert.programmeminceur.info/">
                <div class="mon-diagnostic-img">
                    <img src="<?php echo $this->getViewFileUrl('images/programme_minceur/Programme-minceur-landing_08.jpg'); ?>">
                    <div class="mon-diagnostic-title">
                        Je commence mon diagnostic
                    </div>
                </div>
            </a>
        </div>
        <div class="mon-diagnostic-content col-md-6 no-padding">
            <div class="mon-diagnostic-content-text">
                A chaque problème sa solution TIME<br> Nutrition pour préserver votre capital santé
            </div>
        </div>
    </div>

    <div class="row">
        <h3 class="title-divider"><span>Suivez Nous</span></h3><br>
        <div class="social-network">
            <div class="social-links">
                <a><img src="<?php echo $this->getViewFileUrl('images/programme_minceur/Programme-minceur-landing_11.jpg'); ?>"></a>
            </div>
            <div class="social-links">
                <a href="https://fr-fr.facebook.com/TIME.Nutrition"><img src="<?php echo $this->getViewFileUrl('images/programme_minceur/Programme-minceur-landing_13.jpg'); ?>"></a>
            </div>
            <div class="social-links">
                <a href="https://twitter.com/timenutrition"><img src="<?php echo $this->getViewFileUrl('images/programme_minceur/Programme-minceur-landing_15.jpg'); ?>"></a>
            </div>
            <div class="social-links">
                <a href="https://www.youtube.com/user/TIMENutrition"><img src="<?php echo $this->getViewFileUrl('images/programme_minceur/Programme-minceur-landing_17.jpg'); ?>"></a>
            </div>
        </div>
    </div>

</div>