<?php
$attributes = $block->getAttribute('lexel_');
/*var_dump($attributes);
exit;*/
;?>
<div class="row">
    <form class="form-horizontal" method="post" action="<?php echo $block->getUrl('common/additionalinfo/save', ['_secure' => true]);?>">
        <?php foreach($attributes as $value):?>
            <?php $name = explode('lexel_', $value['name']);?>
            <div class="form-group">
                <label class="col-lg-4 control-label required"><?php echo $name[1]; ?></label>
                <div class="col-lg-8">
                    <?php switch ($value['type']){
                        case 'textarea':?>
                            <textarea id="<?php echo $name[1]; ?>" name="name[<?php echo $value['name']; ?>]" class="form-control input-lg required"></textarea>
                        <?php break;
                        case 'radio':
                            ?>
                            <table>
                                <tr>
                            <td>
                            <?php
                            $option = explode('|',$value['opt']);
                            foreach ($option as $valueOption){?>
                                <input id="<?php echo $name[1]; ?>" name="name[<?php echo $value['name']; ?>]" type="<?php echo $value['type'] ?>" class="form-control"><?php echo $valueOption?>


                        <?php }?></td>
                                </tr>
                            </table>
                        <?php break;
                        case 'checkbox':?>
                            <input id="<?php echo $name[1]; ?>" name="name[<?php echo $value['name']; ?>]" type="<?php echo $value['type'] ?>" class="form-control input-lg required">
                        <?php break;
                        default:?>
                            <input id="<?php echo $name[1]; ?>" name="name[<?php echo $value['name']; ?>]" type="<?php echo $value['type'] ?>" class="form-control input-lg required">
                        <?php break;

                    }?>
                    <?php if($value['type']!='textarea'): ?>

                    <?php else: ?>

                    <?php endif; ?>
                    <input type="hidden" name="id[<?php echo $value['name']; ?>]" value="<?php echo $value['id']; ?>">
                </div>
            </div>
        <?php endforeach;?>
        <h1>Connaissance</h1>
        <h2>Visage</h2>
        <div class="form-group">
            <label class="col-lg-4 control-label required"><?php /* @escapeNotVerified */ echo __('Height') ?></label>
            <div class="col-lg-8">
                <select id="contact_prefix" name="prefix" class="form-control input-lg">
                    <option value="oui">Mlle</option>
                    <option value="non">Mme</option>
                </select>
            </div>
        </div>
        <div class="form-group">
            <label class="col-lg-4 control-label required"><?php /* @escapeNotVerified */ echo __('Height') ?></label>
            <div class="col-lg-8">
                <input id="height" name="height" type="number" class="form-control input-lg">
            </div>
        </div>
        <div class="form-group">
            <label class="col-lg-4 control-label required"><?php /* @escapeNotVerified */ echo __('Height') ?></label>
            <div class="col-lg-8">
                <input id="height" name="height" type="number" class="form-control input-lg">
            </div>
        </div>
        <div class="form-group">
            <label class="col-lg-4 control-label required"><?php /* @escapeNotVerified */ echo __('Height') ?></label>
            <div class="col-lg-8">
                <select id="contact_prefix" name="prefix" class="form-control input-lg">
                    <option value="oui">Mlle</option>
                    <option value="non">Mme</option>
                </select>
            </div>
        </div>
        <h5>Démaquillant</h5>

        <h4>Sérums spécifiques</h4>
        <h4>Crèmes</h4>
        <h2>Corps</h2>
        <h1>Type de peau</h1>


        <div class="form-group text-center">
            <div class="col-lg-6">
                <div class="primary">
                    <button type="submit" class="action submit primary" title="<?php /* @escapeNotVerified */ echo __('Create an Account') ?>"><span><?php /* @escapeNotVerified */ echo __('Create an Account') ?></span></button>
                </div>
            </div>
        </div>
    </form>
</div>